### ISSUE TITLE
any problem to use activiti 5.16 with spring 3.2.7

### ISSUE THREAD

**Issue by AdoHe** [Activiti/Activiti#1008]
FYI. Since activiti 5.16, activiti starts use spring 4, but for some reason I have to use spring 3.2.* in my project, I did a simple test using activiti 5.16 and spring 3.2.7, it seems ok, but I am not hundred percent sure about this. And from the git commit history, it seems spring version was upgraded in the last commits of 5.16. Can some activiti project make sure about this? It is really important for me, thanks very much. @jbarrez @tijsrademakers

**Comment by tijsrademakers** [comment]
Hi, we are using Spring 4 in the web applications and as Spring dependency version just because we have to choose a version to include in our web applications. But we didn't include Spring 4.x specific logic, so it should still work fine with Spring 3.x as well.

**Comment by AdoHe** [comment]
@tijsrademakers in the web applications? you mean activiti explorer? Actually I am planning using activiti engine in my spring 3 based web application, is this ok?

**Comment by tijsrademakers** [comment]
Yes Activiti Explorer and Activiti REST apps. You can use the Activiti Engine in a Spring 3 based web application, that's fine.

**Comment by AdoHe** [comment]
@tijsrademakers Thanks very much, you really save my life.

**Comment by AdoHe** [comment]
@tijsrademakers sorry to bother you again, just the same question. I want to know until which version I can't use spring 3? can I use activiti 5.19.* with spring 3? or can you tell me whether activiti engine depends on spring? Also there is a module named activiti-spring, does this depends on any specific spring version? Thanks very much.

**Comment by tijsrademakers** [comment]
All versions of Activiti should work with Spring 3. The Activiti Engine is only dependent on the spring-beans module and this works with Spring 3 and 4. The activiti-spring module provides easy integration with the Spring framework to use Spring transaction management and Spring beans in service tasks for example. This also works with Spring 3 and 4.

**Comment by AdoHe** [comment]
@tijsrademakers Thanks very much :)
