### ISSUE TITLE
upgrading activiti engine schema from 6.0.0.beta2 to 6.0.0.beta3 fails on oracle

### ISSUE THREAD

**Issue by PascalSchumacher** [Activiti/Activiti#1009]
>org.activiti.engine.impl.db.DbSqlSession - upgrading activiti engine schema from 6.0.0.1 to 6.0.0.2
>org.activiti.engine.impl.db.DbSqlSession - Upgrade needed: 6001 -> 6002. Looking for schema update resource for component 'engine'
>org.activiti.engine.impl.db.DbSqlSession - performing upgrade on engine with resource org/activiti/db/upgrade/activiti.oracle.upgradestep.6001.to.6002.engine.sql
>org.activiti.engine.impl.db.DbSqlSession - problem during schema upgrade, statement alter table ACT_RU_EXECUTION add column IS_COUNT_ENABLED_ NUMBER(1,0) CHECK (IS_COUNT_ENABLED_ IN (1,0))
>java.sql.SQLSyntaxErrorException: ORA-00904: : invalid identifier
>
>	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447) ~[ojdbc6-11.2.0.4.jar:11.2.0.3.0]
>	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396) ~[ojdbc6-11.2.0.4.jar:11.2.0.3.0]
>	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951) ~[ojdbc6-11.2.0.4.jar:11.2.0.3.0]
>	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513) ~[ojdbc6-11.2.0.4.jar:11.2.0.3.0]
>	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227) ~[ojdbc6-11.2.0.4.jar:11.2.0.3.0]
>	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531) ~[ojdbc6-11.2.0.4.jar:11.2.0.3.0]
>	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:195) ~[ojdbc6-11.2.0.4.jar:11.2.0.3.0]
>	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:1036) ~[ojdbc6-11.2.0.4.jar:11.2.0.3.0]
>	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1336) ~[ojdbc6-11.2.0.4.jar:11.2.0.3.0]
>	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1916) ~[ojdbc6-11.2.0.4.jar:11.2.0.3.0]
>	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1878) ~[ojdbc6-11.2.0.4.jar:11.2.0.3.0]
>	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:318) ~[ojdbc6-11.2.0.4.jar:11.2.0.3.0]
>	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95) ~[HikariCP-2.4.7.jar:?]
>	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-2.4.7.jar:?]
>	at org.activiti.engine.impl.db.DbSqlSession.executeSchemaResource(DbSqlSession.java:1213) [activiti-engine-6.0.0.Beta3.jar:6.0.0.Beta3]
>	at org.activiti.engine.impl.db.DbSqlSession.executeSchemaResource(DbSqlSession.java:1135) [activiti-engine-6.0.0.Beta3.jar:6.0.0.Beta3]
>	at org.activiti.engine.impl.db.DbSqlSession.dbSchemaUpgrade(DbSqlSession.java:1114) [activiti-engine-6.0.0.Beta3.jar:6.0.0.Beta3]
>	at org.activiti.engine.impl.db.DbSqlSession.dbSchemaUpdate(DbSqlSession.java:944) [activiti-engine-6.0.0.Beta3.jar:6.0.0.Beta3]
>	at org.activiti.engine.impl.db.DbSqlSession.performSchemaOperationsProcessEngineBuild(DbSqlSession.java:1315) [activiti-engine-6.0.0.Beta3.jar:6.0.0.Beta3]
>	at org.activiti.engine.impl.SchemaOperationsProcessEngineBuild.execute(SchemaOperationsProcessEngineBuild.java:28) [activiti-engine-6.0.0.Beta3.jar:6.0.0.Beta3]
>	at org.activiti.engine.impl.interceptor.CommandInvoker$1.run(CommandInvoker.java:38) [activiti-engine-6.0.0.Beta3.jar:6.0.0.Beta3]
>	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:79) [activiti-engine-6.0.0.Beta3.jar:6.0.0.Beta3]
>	at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:58) [activiti-engine-6.0.0.Beta3.jar:6.0.0.Beta3]
>	at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:43) [activiti-engine-6.0.0.Beta3.jar:6.0.0.Beta3]
>	at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:48) [activiti-engine-6.0.0.Beta3.jar:6.0.0.Beta3]
>	at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:63) [activiti-engine-6.0.0.Beta3.jar:6.0.0.Beta3]

**Comment by jbarrez** [comment]
Thanks for reporting. Our upgrade QA seems to be running green, but I'll dive into it and see if I can reproduce.

What version of Oracle are you running?

**Comment by PascalSchumacher** [comment]
Thanks.

We are still using 11g (11.2.0.4.0 to be exact). Maybe that is the problem.

Dropping the user and recreating it works fine by the way.

**Comment by jbarrez** [comment]
Ok, great to hear, so it must be something in the upgrade scripts.
11g should be fine normally.

**Comment by jbarrez** [comment]
Update after looking into it: there is a wrong update script for oracle and sql server (see fix here https://github.com/Activiti/Activiti/commit/c1da54817900a467d354c2cb63bde3b2d5c543d2)

**Comment by PascalSchumacher** [comment]
Thanks!
