### ISSUE TITLE
activiti will delete database records in backend?

### ISSUE THREAD

**Issue by AdoHe** [Activiti/Activiti#1010]
FYI. I am running an activiti performance test: 15 threads, each process definition contains almost 5000 nodes. And I have run test for two days, got almost 70g data in backend mysql. But when I check the mysql capacity usage record, I found sometimes the capacity usage will decline, e.g from 70g to 60g. This is strange, as the test will not delete any database records, and the mysql instance in used only by the test. I did understand the runtime data will be removed after process instances executed, but the capacity should not be that large. I have checked the user guide and can't find any help. So I am wondering whether activiti will do database archive or will it drop some database records? If so what's the frequency and how I can control this. @tijsrademakers @jbarrez Thanks very much.

**Comment by jbarrez** [comment]
No, Activiti won't delete any historical data at all. 
The only thing that gets removed is the runtime data (process instances, tasks and variables). If you're using a lot of process variable, this could very well explain the results. Or maybe mysql reserves space for future use or cleans it ...
