### ISSUE TITLE
end event should only have one incoming sequence flow

### ISSUE THREAD

**Issue by AdoHe** [Activiti/Activiti#1016]
FYI. I build a process definition xml file and when I open it with BPMN2 diagram editor, I get this error:
```
EndEvent should only have one incoming sequence flow
```
and my process diagram is:
<img width="1212" alt="2016-09-08 7 30 13" src="https://cloud.githubusercontent.com/assets/1555564/18347874/bba5c9d6-75fa-11e6-83a3-3eeb34ae56e3.png">

Since after every task I want to enable kind of decision, so I used exclusive gateway and message, so there are two sequence flow ended with the end event, but definitely only one path will get executed. I have rechecked the Activiti User Guide, and I can't find anything about this, does end event not allow multiple incoming sequence flows? Besides I want to know how to do decision in Activiti workflow, now I use a intermediate catch message to get user action and then use a exclusive gateway to chose different path based on the user action, is there any best practice in Activiti to do this kind of work? @tijsrademakers @jbarrez Thanks very much.

**Comment by jbarrez** [comment]
Having multiple incoming sequence flow to an end event should not be a problem. Where do you get that error?

Decisions are indeed done with an exclusive gateway and exressions on the sequence flow conditions.

**Comment by AdoHe** [comment]
@jbarrez I got this error when I use Eclipse BPMN Plugin, as you can see from the diagram.

**Comment by jbarrez** [comment]
Afaik, an end event can have multiple incoming sequence flow (Activiti supports this). Seems to me like a limitation by the BPMN plugin, not by Activiti.
