### ISSUE TITLE
NPE while using ExecutorPerTenantAsyncExecutor

### ISSUE THREAD

**Issue by egov-systems** [Activiti/Activiti#1017]
getting null pointer exception while using ExecutorPerTenantAsyncExecutor, hope unit test not covering to check this condition as well, issue occurring in 6 beta4 version

**Comment by jbarrez** [comment]
@egov-systems : can you describe how you get this nullpointer?

**Comment by egov-systems** [comment]
@jbarrez i'm getting the NPE when i set ExecutorPerTenantAsyncExecutor for asynExecutor, you can see my code at https://github.com/egovernments/egov-playground/blob/master/egov-process/src/main/java/org/egov/process/config/ApplicationConfig.java#L144

**Comment by jbarrez** [comment]
Ok, thanks for the clarification, it does make sense now. I'll fix the code and add a unit test for this.

**Comment by egov-systems** [comment]
Thanks @jbarrez :+1:

**Comment by jbarrez** [comment]
Fixed. Thanks for reporting!

**Comment by egov-systems** [comment]
Always welcome :) , happy to contribute to such a wonderful framework :+1:
