### ISSUE TITLE
taskCandidate cause Referential integrity constraint violation for task with skipExpression

### ISSUE THREAD

**Issue by faizal-manan** [Activiti/Activiti#1019]
Test Script Scenario
ActivitiVersion: 5.20.0

Step 1. define _activiti:candidateUsers_ or _activiti:candidateGroups_ for _userTask1_ in **SkipExpressionUserTaskTest.test.bpmn20.xml**
Step 2. run **org.activiti.examples.bpmn.usertask.SkipExpressionUserTaskTest.test()**

Issue details
Since transaction is not committed yet, _IdentityLinkEntityManager_  can't find identityLink for the userTask. The identityLink to delete is only can be retrieve via _task.getIdentityLinks()_

Proposed Solution
1. Skip _UserTaskActivityBehavior.handleAssignments_ for task with skipExpression
or
2. add in-memory indentityLink finder in TaskEntityManager.deleteTask(TaskEntity task, String deleteReason, boolean cascade). DbSqlSession.flush will take care the rest

**Comment by jbarrez** [comment]
@faizal-manan : thanks, that's indeed a bug. Fixed it with your proposed solution (1)
