### ISSUE TITLE
Seems like just one @RequestMapping worked

### ISSUE THREAD

**Issue by AlaricLiu** [Activiti/Activiti#1022]
Dear all:
    I am using activiti with spring boot. I config my application follow the activiti user guide. 

   and i defined my requestmapping like this.

   @RequestMapping(value="/hello", method= RequestMethod.POST)
    public String Greeting() {
        return "hello";
    }
    
    @RequestMapping(value="/process", method= RequestMethod.POST)
    public void startProcessInstance(@RequestBody StartProcessRepresentation startProcessRepresentation) {
        myService.startProcess(startProcessRepresentation.getAssignee());
    }
    
    @RequestMapping(value="/tasks", method= RequestMethod.POST)

  but only /process worked. 
 How can I fix this?

**Comment by jbarrez** [comment]
This is more a Spring MVC question than an Activiti question. 
There should be no problem having multiple @RequestMapping annotations in the same class. Can you put your project somewhere on github so we can have a look?

**Comment by AlaricLiu** [comment]
Thx @jbarrez , I have figured out why. I added @ReponseBody before every function and it worked.
