### ISSUE TITLE
ResetExpiredJobsRunnable is not tenant aware

### ISSUE THREAD

**Issue by egov-systems** [Activiti/Activiti#1023]
ResetExpiredJobsRunnable is not setting tenant id while running, is this the way activiti works in multitenant mode or is there any way we can make it tenant aware ?

**Comment by egov-systems** [comment]
I've done a patch for the same to work in multitenant, please review and include in activiti if its good enough. https://github.com/egovernments/egov-playground/blob/5ec32e84f0df32974de8703e1bececa1f964c02f/egov-process/src/main/java/org/egov/process/config/multitenant/activiti/TenantAwareResetExpiredJobRunnable.java

**Comment by jbarrez** [comment]
Patch applied, many thanks!

**Comment by egov-systems** [comment]
Thanks @jbarrez, may i expect these changes in any upcoming version 6.0.0 release ?

**Comment by jbarrez** [comment]
Yes, they are on master, so they'll be part of the next release (most likely a release candidate version).

**Comment by egov-systems** [comment]
many thanks @jbarrez, i'm bit confused between 5.x and 6.x hope these will be available in both.

**Comment by jbarrez** [comment]
No, this class is not in v5 (as there was no need for resetting jobs there).

V6 has a rewritten Async Executor (see https://github.com/Activiti/Activiti/blob/activiti6/userguide/src/en/ch15-Advanced.adoc#async-executor for more information), that's superior in throughput. But one of the extra's needed was resetting jobs (it was part of the query in v5, but this also led to slowness). Read more about it here: http://www.jorambarrez.be/blog/2016/07/20/message-queue-async-executor-benchmark/

**Comment by egov-systems** [comment]
great... thanks @jbarrez, will go through those articles as well.
