### ISSUE TITLE
Auto start a process instance

### ISSUE THREAD

**Issue by skbelalmd** [Activiti/Activiti#1025]
Hello,
I have deployed several business processes in activiti.
All the business processes are started manually.

Is there any way so that a particular business process gets started at a specific date (say every 1 st date of the month) without any user intervention.

**Comment by jbarrez** [comment]
Yes, use a timer start event, see http://activiti.org/userguide/index.html#bpmnTimerStartEvent

**Comment by skbelalmd** [comment]
Thanks,
 I got it.

**Comment by skbelalmd** [comment]
I have a question, that the date we provide, is it in UTC format or my local .

**Comment by jbarrez** [comment]
No, it needs to be an ISO 6601 string (check the docs)
