### ISSUE TITLE
Auto start a process instance

### ISSUE THREAD

**Issue by skbelalmd** [Activiti/Activiti#1026]
As per the documentation in your answer in [ my previous issue](https://github.com/Activiti/Activiti/issues/1025) , we have 2 options to auto start a process.

1- We can start a process for a specified no of times in specified time intervals.
2- Or we can start a process once on selected data.

Can we extend this a little bit, like as I asked before "to start a process on specified date of each month".

**Comment by jbarrez** [comment]
Yes, you'd have to use a cron expression for that, that allows to define repeating things like that.

Also, this is not really an issue, but rather a question. Please us http://stackoverflow.com/questions/tagged/activiti for questions.
