### ISSUE TITLE
The non-interrupting boundary event(cancelActivity="false") incorrectyly completed the original activity.

### ISSUE THREAD

**Issue by daisuke-yoshimoto** [Activiti/Activiti#1030]
The non-interrupting boundary event(cancelActivity="false") incorrectyly completed the original activity.

When time boundary event(cancelActivity="false") is triggered, the original activity was incorrectyly completed.
We checked the activity history's endTime(act_hi_actinst) of the original activity was recorded.
### Test case

https://github.com/daisuke-yoshimoto/Activiti/tree/cancel_activity_incorrect_completion

diff
https://github.com/Activiti/Activiti/compare/master...daisuke-yoshimoto:cancel_activity_incorrect_completion?expand=1

**Comment by daisuke-yoshimoto** [comment]
@balsarori @vasiledirla
If possible , please feedback.

**Comment by daisuke-yoshimoto** [comment]
I created the issue in JIRA.
https://activiti.atlassian.net/browse/ACT-4247

**Comment by Salaboy** [comment]
@daisuke-yoshimoto is this still an open issue?

**Comment by Salaboy** [comment]
@balsarori please advise and check with Daisuke if we want to include a fix about this.

**Comment by daisuke-yoshimoto** [comment]
This issue can be closed by merging the pull request https://github.com/Activiti/Activiti/pull/1831.
