### ISSUE TITLE
when will startProcessInstanceBy*** return?

### ISSUE THREAD

**Issue by AdoHe** [Activiti/Activiti#1033]
FYI. I am using activiti to do some workflow execution, everytime I will first construct a BPMN model, and then deploy that BPMN model, then I will call the `runtimeService.startProcessInstanceBy***` method to start a process instance. And I just noticed a truth this method will not return immediately, sometimes it will block quite a long time, and from the Java doc I cannot find any good reference, so I want to when this method will return exactly. @jbarrez @tijsrademakers ptal. Thanks very much

**Comment by tijsrademakers** [comment]
By default the Activiti Engine will run the process instance in the starting thread and block it until a wait state or end state has been reached. This can be changed by adding a async service task or other task type at the start of the process definition. Then the process instance is started and an asynchronous job is created, but before that job is executed the blocking thread is returned.

**Comment by AdoHe** [comment]
@tijsrademakers thanks very much, I will give it a try.
