### ISSUE TITLE
does activiti support resume process instance?

### ISSUE THREAD

**Issue by AdoHe** [Activiti/Activiti#1034]
FYI. I have create a simple process definition like this:
<img width="511" alt="2016-09-22 11 38 48" src="https://cloud.githubusercontent.com/assets/1555564/18755215/de3152a8-811d-11e6-83d7-69c03e04fa53.png">

And then I start a process instance of this process definition, but for some reason the upper service tasked failed and cause the entire JVM process exit, I want to know how I can resume this process instance execution when I restart the program, is there any API for me to do this? Also if I can resume this process instance execution, where this process instance will start execute? from the failed activity? @jbarrez @tijsrademakers really hope to get your help, thanks very much :)

**Comment by tijsrademakers** [comment]
The entire JVM process exiting is quite uncommon. Can you provide a bit more details with a stacktrace etc?

**Comment by AdoHe** [comment]
@tijsrademakers Actually I am doing a test, for the upper service task in the diagram above I will sleep a while, and during the sleep process, I will kill the Java process. I want to know how I can resume the process instance execution under such condition. Since in our use case, there is possibility that the process will exit during process instances execution, as some process instances will run quite a long time. I want to know how I can handle this. :)

**Comment by jbarrez** [comment]
In the case you're describing, the JVM is killed, the database transaction won't be committed and the database will roll back to the last stable state. Which is in this case rolling back the whole process instance, as there is no wait state before the service task.

**Comment by AdoHe** [comment]
@jbarrez in my test case, both of the two service tasks are `async`, IIUC there will be two executions in the database, and the process instance will store into database. The problem is I manually killed the process, and the two service tasks have not finish execution, so if you check the database now, you will see the process instance is not end. The question is how I can restart the process instance, and let it execute from the failed activity? For example in the test case if I can restart the process instance, both of two service tasks should execute and the process instance will run to the end. I want to know how I can do this. Really appreciate your help.

**Comment by jbarrez** [comment]
In this case, the transaction rollback should have happened during job execution. The jobs should still be in the database and be picked up later by the job executor. 

Did you enable the async executor in your test? It can take a certain amount of time until the executor polls again.

If you can put your unit test somewhere online, that would surely help in giving more concrete information.

**Comment by AdoHe** [comment]
@jbarrez I have create a new repo to include my test case, https://github.com/AdoHe/activiti-test/blob/master/src/test/java/com/westudio/activiti/ResumeTest.java ptal.

**Comment by AdoHe** [comment]
@jbarrez Also in the `activiti-context.xml` I have configured async executor. According to what you have comment, if I kill the process during job execution, the transaction will rollback, just wonder will rollback to which state? In the test case, I will kill the JVM process during job execution, then I will restart the JVM process, how I can restart the process instance and let the process instance run to the end state? I want to know how to implement this. Thanks

**Comment by jbarrez** [comment]
Killing the JVM in a unit test and then resuming is pretty hard :p

If you're running on a server and the JVM is killed, the state will be that there are two jobs in the database. You could picture them as being 'just before' the service task, but not yet executing it. After restart, the job executor will find these jobs and continue further, executing these service tasks.

**Comment by AdoHe** [comment]
@jbarrez 
```
the job executor will find these jobs and continue further, executing these service tasks.
```
will this run the process instance to the end state?

**Comment by jbarrez** [comment]
In this simple example above, yes, as there is no other 'wait state' after the service tasks.

**Comment by AdoHe** [comment]
<img width="671" alt="2016-09-23 5 42 17" src="https://cloud.githubusercontent.com/assets/1555564/18781608/1ec44964-81b5-11e6-9f3c-a8be93ac8910.png">

If I change the process definition to this, and the process exit during the parallel tasks execution. After I restart the process, will the last task get executed?

**Comment by jbarrez** [comment]
Yes, correct.

**Comment by AdoHe** [comment]
Of course, I will do a test. What makes me quite confusing is in my own view, I think async executor will just run async activity(service task, subprocess), but according to what you have comment, seems the async executor will also run the process instance? am I right?

**Comment by jbarrez** [comment]
The async executor picks up jobs and continues the process instance. In a way it 'runs' part of the process instance. But technically, it simply delegates to the core engine operations once it has picked up a job.

**Comment by AdoHe** [comment]
I noticed there is a method in management service `executeJob`, if I call this method manually, will it has the same effect as async executor picks up the job? I am worried the job will still fail after retry.

**Comment by AdoHe** [comment]
@jbarrez also what if the process exit when the process instance holds on a waitstate, for example a receive task, how I can restart the process instance and let the process instance starts from the receive task activity?

**Comment by jbarrez** [comment]
>  if I call this method manually, will it has the same effect as async executor picks up the job

Yes, that is manually executing the job. Make sure you have the async executor disabled, or it might interfere of course.

> how I can restart the process instance and let the process instance starts from the receive task activity

If it's in a wait state, it's in the database. There is no need for a restart of the process instance. You can trigger continuation from that step using the runtimeService.signal (.trigger in v6) method.

**Comment by AdoHe** [comment]
@jbarrez Thanks very much of your kind help, I think I have a more deep understanding now.
