### ISSUE TITLE
Activiti 5.22.0 release date.

### ISSUE THREAD

**Issue by daisuke-yoshimoto** [Activiti/Activiti#1044]
If possible, please provide information on Activiti 5.22.0 release date.

When will Activiti 5.22.0 be released?
https://activiti.atlassian.net/projects/ACT/versions/10600/tab/release-report-all-issues

If the last ticket(ACT-4210) is doned, will Activiti 5.22.0 be released?
https://activiti.atlassian.net/browse/ACT-4210

Or,is there a plan to release Activiti 5.21.1(minor version upgrade)?

**Comment by daisuke-yoshimoto** [comment]
> If the last ticket(ACT-4210) is doned, will Activiti 5.22.0 be released?
> https://activiti.atlassian.net/browse/ACT-4210

All tickets of Activiti 5.22.0 seem to be completed.
ACT-4210 was fixed by this pull request and merged to master by tijsrademakers.
https://github.com/Activiti/Activiti/pull/1014 https://github.com/Activiti/Activiti/pull/1015

**Comment by daisuke-yoshimoto** [comment]
oh...

Flowable and Activiti: What the Fork?!
http://www.flowable.org/blog/2016/10/12/flowable-and-activiti.html

Flowable 5.22.0 release
http://www.flowable.org/blog/2016/10/13/flowable-5.22.0-release.html

**Comment by daisuke-yoshimoto** [comment]
@balsarori

If possible,please inform us of the current situation.
Activiti 5.22.0 that all issues was doned isn't released and pull requests aren't merged recently.

Activiti core developers(Joram Barrez, Tijs Rademakers) leaved Alfresco and forked Activiti.
https://github.com/flowable/flowable-engine

Alfresco is recruiting new developers.
Until new developers are hired, does development of Activiti stop?
https://www.linkedin.com/jobs2/view/197691876

**Comment by jsotiro** [comment]
Hi @daisuke-yoshimoto We are doing some tests and we will update you shortly. Apologies for a period of silence. A lot has happened but you will see much faster progress and turnaround

**Comment by jsotiro** [comment]
@daisuke-yoshimoto on your questions around flowable. See john newton's blog https://www.alfresco.com/blogs/alfresco-activiti/   We are plannig to have very soon a community hangout with all the commiters to reboot Activiti. Activiti lives on and you will see investment and innovation in this project outpacing the market

**Comment by daisuke-yoshimoto** [comment]
@jsotiro 
Thank you for your reply.
We see the situation of Activiti.

We hope that the Activiti 5.22.0 will be early released.

**Comment by daisuke-yoshimoto** [comment]
@balsarori @jsotiro 
What's the status now?

We confirmed that the release branch was created.
https://github.com/Activiti/Activiti/tree/5.22.0-release

Would it be released soon?

**Comment by jsotiro** [comment]
Hi @daisuke-yoshimoto 5.22 is out

**Comment by daisuke-yoshimoto** [comment]
@jsotiro

Thank you very mach for releasing Activiti 5.22.0.

We were able to include Activiti 5.22.0 to our next release.
