### ISSUE TITLE
any possibility to modify process even when process is running

### ISSUE THREAD

**Issue by adohe** [Activiti/Activiti#1046]
FYI. I am using Activiti to do some complicated workflow executing, for some reason I would hope that I can modify the process even when I started it. For example I defined a process definition which contains three sequential subprocess, I deployed this definition, and started a process instance. I want to know whether it is possible to delete the third subprocess, when the process instance is still executing the first subprocess. If not possible, how to hack this? @tijsrademakers @jbarrez Thanks very much

**Comment by gro-mar** [comment]
Hi,
try this one:
https://gromar01.wordpress.com/2016/06/16/design-by-doing-with-activiti6/
(adding nodes to the flow)

**Comment by AdoHe** [comment]
@gro-mar thanks very much, I will take a deep look.
