### ISSUE TITLE
service tasks within async subProcess needs to be async?

### ISSUE THREAD

**Issue by adohe** [Activiti/Activiti#1055]
FYI. I have two async parallel subProcess in my process definition, and each subProcess has three java service tasks. I have configured each subProcess to be async(with async attribute in xml), the question is whether I also need to configure every java service tasks to be async? If I just set the subProcess to async, will the inner service tasks be executed by the async executor? @tijsrademakers @jbarrez ptal, thanks.

**Comment by martin-grofcik** [comment]
Hi,
I do not know what is the goal.
If you make subprocess asynchronous -> all service tasks are executed in one transaction
If you make each service task async -> each service task will be executed in separate transaction.
Martin

**Comment by AdoHe** [comment]
@martin-grofcik as what you said, if I make subprocess asynchronous, all service tasks within this subprocess will get executed in one transaction, what if the service tasks take a long time to return, the transaction will last a quite long time, also under such case, does it mean that the service tasks state will updated to db only when the whole subprocess finished? Also I want to know whether these service tasks will be converted to async job and executed by the async executor?

**Comment by Salaboy** [comment]
@adohe I'm closing this issue because it sounds more like questions that can be asked and answered in the community forums or stackOverflow than in a github issue. If there is a problem in the behaviour of the engine please open a new issue.
