### ISSUE TITLE
Why substring(8) for name of FieldExtend ?

### ISSUE THREAD

**Issue by henryyan** [Activiti/Activiti#1069]
```java
FieldExtension field = new FieldExtension();
field.setFieldName(name.substring(8));
String value = getPropertyValueAsString(name, elementNode);
```

I don't know why fixed intercept 8 characters before？

[codes](https://github.com/Activiti/Activiti/blob/ddf9b515550c26bc6f884b91e4563e035497f0c2/modules/activiti-json-converter/src/main/java/org/activiti/editor/language/json/converter/BaseBpmnJsonConverter.java#L641)

**Comment by Salaboy** [comment]
@henryyan this is a very good question. Did you got an answer? Did you have an issue with this? if so please create a reproducer and we will try to find out why that was limited to 8 characters. For now I'm closing this issue to make sure that we keep track of what is being done.
