### ISSUE TITLE
Support for SpEL nested variables

### ISSUE THREAD

**Issue by openwms** [Activiti/Activiti#1070]
Is there support for SpEL variables nested in expressions? [Reference](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/expressions.html#expressions-ref-variables)

Example 1:
`activiti:expression="#{transportUnitApi.updateActualLocation(#in.msg.barcode, #in.msg.actualLocation)}"`

Example 2:
`activiti:expression="#{transportUnitApi.updateActualLocation(#{in.msg.barcode}, #{in.msg.actualLocation})}"`

where `transportUnitApi` is a managed Spring Bean (actually a Feign stub) and `in` could be either a property or a Spring Bean. The example 1 above should work with variables (resp. Spring Reference manual), but it doesn't

What do you propose as a solution?

**Comment by gro-mar** [comment]
Did you try
`activiti:expression="#{transportUnitApi.updateActualLocation(in.msg.barcode, in.msg.actualLocation)}"`

see:
org.activiti.engine.test.el.ExpressionManagerTest#testExecutionAvailable
(the test references execution - but it should be the same for variables)

**Comment by openwms** [comment]
Indeed, that actually works as expected. I tried this before without luck, because I referenced a bean that did not exist in the same `ApplicationContext` where Activiti is bootstrapped. For that I need to dig into how `Feign` clients work with Activiti. But with _plain_ Spring beans it works the way you proposed. Thanks!
