### ISSUE TITLE
Is that a bug when import bpmn xml.（6.0.0.Beta4）

### ISSUE THREAD

**Issue by linkaiyi** [Activiti/Activiti#1072]
I had created a simple process with activiti-app,and export to BPMN 2.0:
`<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:activiti="http://activiti.org/bpmn" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" typeLanguage="http://www.w3.org/2001/XMLSchema" expressionLanguage="http://www.w3.org/1999/XPath" targetNamespace="http://www.activiti.org/processdef">
  <process id="aaa" name="aaa" isExecutable="true">
    <startEvent id="startEvent1"></startEvent>
    <userTask id="myTask" activiti:assignee="zs">
      <extensionElements>
        <modeler:activiti-idm-assignee xmlns:modeler="http://activiti.com/modeler"><![CDATA[true]]></modeler:activiti-idm-assignee>
        <modeler:assignee-info-email xmlns:modeler="http://activiti.com/modeler"><![CDATA[zs]]></modeler:assignee-info-email>
        <modeler:assignee-info-firstname xmlns:modeler="http://activiti.com/modeler"><![CDATA[SAN]]></modeler:assignee-info-firstname>
        <modeler:assignee-info-lastname xmlns:modeler="http://activiti.com/modeler"><![CDATA[ZHANG]]></modeler:assignee-info-lastname>
        <modeler:initiator-can-complete xmlns:modeler="http://activiti.com/modeler"><![CDATA[false]]></modeler:initiator-can-complete>
      </extensionElements>
    </userTask>
    <endEvent id="sid-E08FE3AB-D434-438A-920B-8FED20860266"></endEvent>
    <sequenceFlow id="sid-0A638B2F-274F-455A-8DFD-52AD7D61B7D1" sourceRef="myTask" targetRef="sid-E08FE3AB-D434-438A-920B-8FED20860266"></sequenceFlow>
    <sequenceFlow id="sid-F6A5C057-87AF-4CDB-9C6C-6E6EB89C76E2" sourceRef="startEvent1" targetRef="myTask"></sequenceFlow>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_aaa">
    <bpmndi:BPMNPlane bpmnElement="aaa" id="BPMNPlane_aaa">
      <bpmndi:BPMNShape bpmnElement="startEvent1" id="BPMNShape_startEvent1">
        <omgdc:Bounds height="30.0" width="30.0" x="100.0" y="163.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="myTask" id="BPMNShape_myTask">
        <omgdc:Bounds height="80.0" width="100.0" x="191.0" y="138.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="sid-E08FE3AB-D434-438A-920B-8FED20860266" id="BPMNShape_sid-E08FE3AB-D434-438A-920B-8FED20860266">
        <omgdc:Bounds height="28.0" width="28.0" x="336.0" y="164.0"></omgdc:Bounds>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="sid-0A638B2F-274F-455A-8DFD-52AD7D61B7D1" id="BPMNEdge_sid-0A638B2F-274F-455A-8DFD-52AD7D61B7D1">
        <omgdi:waypoint x="291.0" y="178.0"></omgdi:waypoint>
        <omgdi:waypoint x="336.0" y="178.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge bpmnElement="sid-F6A5C057-87AF-4CDB-9C6C-6E6EB89C76E2" id="BPMNEdge_sid-F6A5C057-87AF-4CDB-9C6C-6E6EB89C76E2">
        <omgdi:waypoint x="130.0" y="178.0"></omgdi:waypoint>
        <omgdi:waypoint x="191.0" y="178.0"></omgdi:waypoint>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>`

and import it again with the "Import Process" button. then, the logger report ERROR:
`11:15:43,454 [http-nio-8081-exec-46] ERROR org.activiti.editor.language.json.converter.BpmnJsonConverter  - Error converting org.activiti.bpmn.model.UserTask@6cdb8f38
java.lang.NumberFormatException: For input string: "zs"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.valueOf(Long.java:803)
	at org.activiti.editor.language.json.converter.UserTaskJsonConverter.convertElementToJson(UserTaskJsonConverter.java:94)`

"UserTaskJsonConverter.convertElementToJson" source code line 94:
assigneeNode.put("id", **Long.valueOf(userTask.getAssignee())**);
why convert the assignee value to Long?

**Comment by balsarori** [comment]
Yes indeed that's a bug. We are working on fixing this and will allow string values instead.

**Comment by balsarori** [comment]
Created a Jira issue here https://activiti.atlassian.net/browse/ACT-4271

**Comment by balsarori** [comment]
fixed
