### ISSUE TITLE
SpringBoot: Feign clients not visible in ApplicationContext

### ISSUE THREAD

**Issue by openwms** [Activiti/Activiti#1076]
I've developed an application using SpringBoot, Activiti and Feign. The SpringBoot application starts up, Activiti is on the classpath (org.activiti:activiti-spring-boot-starter-basic:5.21.0). Beans of the SpringBoot ApplicationContext are visible to Activiti and can be used in the workflow (with SpEL expressions). So far so good.

But Feign client stubs cannot be referenced from Activiti. The Feign implementations are not found by Activiti even they do exist. I test this by trying to get a bean reference to one of the Feign beans inside my SpringBoot application - that works.

One possible reason: The Activiti starter setup is incorrect
-> That's why I ask here.

Second reason: Feign seems to be instantiated in its own ApplicationContext per client (so called Ensembles). I am not sure if this leads to the situation that Feign beans are only visible to beans of the SpringBoot application and not for Activiti, although Activiti shares the same context like the main application does, right?
-> Will ask that in the SpringBoot community, too

**Comment by Salaboy** [comment]
@openwms  Did you get any answers to this problem?
I'm closing the issue because our new integration with spring boot is going to handle this specific use case. But we are not looking into providing that feature for activiti 6 on activiti 7 and activiti cloud.

**Comment by openwms** [comment]
Nobody answered. You can close it and I'll try again with the lastest versions
