### ISSUE TITLE
Activity Eclipse plugin update site is not valid

### ISSUE THREAD

**Issue by limansky** [Activiti/Activiti#1090]
It seems like Eclipse Update site link  http://activiti.org/designer/update/ is not valid anymore. If the link was changed, it should be updated in user guide.

**Comment by alexandrepkill** [comment]
Happed with me as well.

**Comment by edgarberlinck** [comment]
Happened with me too.

**Comment by jnuc093** [comment]
Yes the update url can't access. i have packaged one you can download here:
https://pan.baidu.com/s/1nuRCP9f 
password: e29t

**Comment by doug4j** [comment]
http://activiti.org/designer/update/ has been corrected. This ticket can be closed.
