### ISSUE TITLE
Mark Beta-releases as prereleases

### ISSUE THREAD

**Issue by konstin** [Activiti/Activiti#1091]
A bot of mine just stumbled and fell across a detail in your github page: On the release page, the [Beta2 of version 6](https://github.com/Activiti/Activiti/releases/tag/activiti-6.0.0.Beta2), the [Beta3 of version 6](https://github.com/Activiti/Activiti/releases/tag/activiti-6.0.0.Beta3) and the [Beta4 of version 6](https://github.com/Activiti/Activiti/releases/tag/activiti-6.0.0.Beta4) are not marked as prereleases. I agree that this is a neither a problem for humans nor a severe bug, but please be so kind and check the "prerelease box". This will make life for people using the github api much easier.

**Comment by magemello** [comment]
Hi @konstin done. Just for curiosity what does your bot?

**Comment by konstin** [comment]
Thanks! My bot does import metadata from github into wikidata, so that e.g. the "stable release" and the "website" entry on wikipedia can be automatically updated.
