### ISSUE TITLE
Activiti BPMN 2.0 designer Not available at  http://activiti.org/designer/update/

### ISSUE THREAD

**Issue by girish989** [Activiti/Activiti#1094]
Activiti BPMN 2.0 designer Not available at  http://activiti.org/designer/update/

Also, archived page is down as well - 

https://www.activiti.org/designer/archived/

**Comment by Salaboy** [comment]
@girish989 the eclipse plugin is not being maintained anymore at least not by the team working in Activiti 7 & Activiti Cloud.
