### ISSUE TITLE
Does Activity support queues and time spent on each task.

### ISSUE THREAD

**Issue by Padmahas** [Activiti/Activiti#1096]
I need couple of clarifications.
1. Does Activiti supports queuing a task and/or reassigning a task to others?
2. Does Activiti logs time spent, on each process steps and provides "cycle time"?

**Comment by Salaboy** [comment]
@Padmahas yes to both questions. You just need to configure some listeners to get that information. I'm closing this issue, because it is not an issue. For questions please use stackoverflow or the community forums.
