### ISSUE TITLE
CamelBehavior is coupled with SpringProcessEngineConfiguration

### ISSUE THREAD

**Issue by woczkowski** [Activiti/Activiti#1104]
[CamelBehavior](https://github.com/Activiti/Activiti/blob/master/modules/activiti-camel/src/main/java/org/activiti/camel/CamelBehavior.java) directly uses SpringProcessEngineConfiguration instead of ProcessEngineConfiguration interface. It tights it's use strictly to Spring environment. That makes it unuseable in servicemix environment for example. Servicemix is using JtaProcessEngineConfiguration witch cannot be cast to SpringProcessEngineConfiguration. 

It seems like [CamelBehavior](https://github.com/Activiti/Activiti/blob/master/modules/activiti-camel/src/main/java/org/activiti/camel/CamelBehavior.java) is using spring for default camelContext resolution. Shuldn't it use ContextProvider's like in old [CamelBehaviour](https://github.com/Activiti/Activiti/blob/master/modules/activiti-camel/src/main/java/org/activiti/camel/CamelBehaviour.java) class?

**Comment by lukawoznicki** [comment]
Also, there is a problem when you want to use Activiti in osgi model with StandaloneProcessEngineConfiguration.

**Comment by Salaboy** [comment]
@woczkowski @lukawoznicki totally agree with your points, we are cleaning up the spring integration for activiti 7 and activiti cloud.
