### ISSUE TITLE
Set the editor source for a model API not respecting RFC

### ISSUE THREAD

**Issue by quirinobrizi** [Activiti/Activiti#1105]
The Set the editor source for a model API respond to PUT method and accept a multipart/form-data request, this is against RFC specification (http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.6) in the specific:

> The URI in a POST request identifies the resource that will handle the enclosed entity. That resource might be a data-accepting process, a gateway to some other protocol, or a separate entity that accepts annotations. In contrast, the URI in a PUT request identifies the entity enclosed with the request -- the user agent knows what URI is intended and the server MUST NOT attempt to apply the request to some other resource.

Which means that PUT method represent a single resource while a mutipart request may contain multiple resources.

This is in some ways acknowledged on the API implementation which uses a single resource if multiple are provided and by the documentation (https://www.activiti.org/userguide/#_set_the_editor_source_for_a_model)

**Comment by Salaboy** [comment]
@quirinobrizi totally agree. we are refactoring our REST APIs to follow more standard practices. Take a look at Activiti 7 and Activiti Cloud and get involved as a community member if you are interested in helping us with this new approach.
