### ISSUE TITLE
Activiti REST mising process instance attachments

### ISSUE THREAD

**Issue by bkmeneguello** [Activiti/Activiti#1110]
Activiti REST does not expose process instance attachment endpoint. Since Activiti Explorer task UI attaches files to process instance, instead to Task itself (I prefer this way), this functionality is missing from REST.
I'm building an alternative, lite, frontend, using only REST calls. This should be fundamental.

**Comment by 1289100276** [comment]
can I join to code

**Comment by 1289100276** [comment]
好像activiti自动根据mysql创建表里面有张表创建出来的时间转换会报错

**Comment by Salaboy** [comment]
@bkmeneguello totally agree, we are refactoring our REST endpoints and services to expose all those functionalities for Activiti Cloud. Please feel free to help us moving forward. We will appreciate your views and experience building your REST endpoints.
