### ISSUE TITLE
Two-worded REST API resource names are inconsistent in convention

### ISSUE THREAD

**Issue by archerjon89** [Activiti/Activiti#1127]
This isn't an _enormous_ issue, but it has caused my dev team some confusion that the resource names "identitylinks" and "resourcedata" are not consistent with the other resources in the REST API (e.g. "exception-stacktrace", "form-data", "process-definitions", etc).
Is there a reason for this difference? Would it cause serious problems if these were fixed to be more in-line with the others (e.g. "identity-links")?

**Comment by balsarori** [comment]
I agree it would have been more consistent to use identity-links instead of identitylinks but fixing it now will break existing users code that already work with identitylinks.
