### ISSUE TITLE
StackOverflow on simple looping process

### ISSUE THREAD

**Issue by SergioModulusData** [Activiti/Activiti#1128]
Hi,

I have a simple process that loops using a gateway instead of using a regular multi instance tab. My simple process is a copy of an internal business process that calls a event gateway to retrieve any message (HTTP method), if there is a message than the second process will delete it and call the get once again. Using this structure the application will always stop before the required number of execution of the task, around 40 in my test and maybe more when changing Java memory flags.

I have created a repo that showcase the same error I had with only Groovy scripting. 

![simpleloop](https://cloud.githubusercontent.com/assets/15251865/23617690/e52c751e-025b-11e7-9e8b-57bc794d04c6.png)

https://github.com/ModulusData/LoopActivitiTest

I'm looking for either guidelines to accomplish the desired loop controls, 

Thanks
Sergio

**Comment by balsarori** [comment]
Hi Sergio,

Seems the execution exceeds the default stack size. I ran your code with ```-Xss4m``` and worked.

**Comment by SergioModulusData** [comment]
Hi Bassam,

Thanks for your swift reply, seems I need to refresh my knowledge of Java memory flags. It's working with the Xss flags.

Sergio
