### ISSUE TITLE
Error reading bpmn xml file containing CDATA in JBoss EAP 6.4

### ISSUE THREAD

**Issue by thetasp** [Activiti/Activiti#1141]
JBoss EAP 6.4 tested is using Woodstox for javax.xml.stream.XMLInputFactory.
When the xml reader read the CData, it does not read all the content in one read, causing missing content. This behaviour is random and cannot always reproduce.
This error is caused by how activiti read the XML in the class org/activiti/bpmn/converter/util/BpmnXMLUtil.java line 166
and the value read keep being overriden by new value in the loop.

    while (readyWithExtensionElement == false && xtr.hasNext()) {
      xtr.next();
      if (xtr.isCharacters() || XMLStreamReader.CDATA == xtr.getEventType()) {
        if (StringUtils.isNotEmpty(xtr.getText().trim())) {
          extensionElement.setElementText(xtr.getText().trim());
        }

suggest to change the code to buffer the read before setting to element as below

		// temporary storage of the content to build the full 
		String content = null;
		while (readyWithExtensionElement == false && xtr.hasNext()) {
		      xtr.next();
		      if (xtr.isCharacters() || XMLStreamReader.CDATA == xtr.getEventType()) {
		        if (StringUtils.isNotEmpty(xtr.getText().trim())) {
		          if(content != null) {
		        	  content =xtr.getText().trim();
		          } else {
		        	  //append the content
		        	  content += xtr.getText().trim();
		          }
		          extensionElement.setElementText(content);
		        }

**Comment by Salaboy** [comment]
@thetasp this is a great suggestion. Can you please create a PR to the appropriate branch with the fix and a test case? Fixes in github issues get really difficult to track. For that reason I'm closing this issue to wait for the PR.
