### ISSUE TITLE
Activiti 6 Beta Radio button with multiple options in Form Task

### ISSUE THREAD

**Issue by muraliveligeti** [Activiti/Activiti#1142]
In Activiti 6 Beta 4 version not able to create Radio button with multiple options in Form Task. Getting bad request error

**Comment by lucianoprea** [comment]
Hi @muraliveligeti! I tried to reproduce your issue on the latest version of activiti6 and all seems to work fine. Can you please check it and provide more details if can be reproduced?
Thanks
