### ISSUE TITLE
the activiti After the call to the complete method to complete the first task, the process directly ended

### ISSUE THREAD

**Issue by dunmengjun** [Activiti/Activiti#1143]
Such as title 
I created a process with six nodes, and then once I completed the first task, the process directly ended

![qq 20170321071300](https://cloud.githubusercontent.com/assets/14136848/24125881/e522a4de-0e05-11e7-97d9-3f603dcfc9e7.png)

This is a screenshot of the events at that time
I do not know what happened and now ask for help

**Comment by gotemkr** [comment]
Can you please attach a test case for us to understand this better ?

**Comment by Salaboy** [comment]
@dunmengjun if your tasks are all synchronous that is the expected behaviour. Please ask questions in the forums or stackoverflow not here. That's why I'm closing this issue.
