### ISSUE TITLE
setup complecated

### ISSUE THREAD

**Issue by dipenpatel235** [Activiti/Activiti#1149]
hello,...
is there any simple documents help available to sertup activiti BPM and Rest API server ?
i have read all thing and to much confuse not able to understand which steps need to do.

i have test one api Activiti explorer and it is working.
But Activiti rest api is not working. not able to understand what need to do for that.
Please provide some help.

Thanks

**Comment by balsarori** [comment]
did you deploy the activiti-rest.war file?
