### ISSUE TITLE
activiti HistoricTaskInstanceQuery  or() function in SQL is and

### ISSUE THREAD

**Issue by dunmengjun** [Activiti/Activiti#1150]
as this title
I wrote the following code
`List<HistoricTaskInstance> list = historyService.createHistoricTaskInstanceQuery().taskAssignee("10003_14").or().taskAssignee("10003_13").list();`
debug
the sql is
`select distinct RES.* from ACT_HI_TASKINST RES WHERE RES.ASSIGNEE_ = ? and ( RES.ASSIGNEE_ = ? ) order by RES.ID_ asc LIMIT ? OFFSET ? `
I would like to ask is this normal?
I am confused
Because the semantics of or and and is not a semantic

**Comment by balsarori** [comment]
For your specific use case, you can use ```taskAssigneeIds()``` method (available in upcoming version 6) which checks if the assignee id value is amongst a list of id values
```historyService.createHistoricTaskInstanceQuery().taskAssigneeIds(...)```

The current use of ```or``` is to check two different attributes/clauses and should start with ```or()``` and end with ```endOr()``` calls. For example, the following get tasks where kermit is either an owner or an assignee
```
historyService.createHistoricTaskInstanceQuery()
.or()
.taskAssignee("kermit")
.taskOwner("kermit")
.endOr()
.list();
```

SQL will look like
```select distinct RES.* from ACT_HI_TASKINST RES WHERE ( RES.OWNER_ = ? or RES.ASSIGNEE_ = ? ) order by RES.ID_ asc LIMIT ? OFFSET ? ```

I hope this clarifies the usage of ```or()```
