### ISSUE TITLE
Permissions Error with Parallel Gateway Question

### ISSUE THREAD

**Issue by dhrobbins** [Activiti/Activiti#1170]
I have a complex work flow where I have added a Parallel Gateway. Prior to adding the gateway it has functioned as expected. Now that I have added the Parallel Gateway, the initiator cannot view the workflow details and receives this message when clicking the task link from "Workflows I've Started:

User originator does not have permission to access this task.

The odd thing is the workflow still allows assigned users access to their tasks. Older versions of the workflow allow the originator to view the Workflow details and advance tasks. I have rolled back to the previous version of the workflow and the error does not occur.

Really puzzled about this one, and any insight would be great.
What type of symptoms should I look for? As I said, without the Parallel Gateway the workflow functions normally.  I have also created workflows smaller in scale where the Parallel Gateway functions as expected.

We are using Alfresco Community Edition 5.2, the workflow engine is the embedded Activity engine and this runs as a Share application.

I have attached the source files and can also supply logs but so far I do not see any thing related.  Being new to Alfresco & Spring I certainly can take direction / feedback.  

[lec-context.zip](https://github.com/Activiti/Activiti/files/920671/lec-context.zip)

**Comment by balsarori** [comment]
@dhrobbins this seems to be an issue related to Alfresco Community Edition setup. Please report the issue to Alfresco Community.
