### ISSUE TITLE
Completed tasks no longer have DELETE_REASON_='completed'

### ISSUE THREAD

**Issue by mpolajnar** [Activiti/Activiti#1188]
In @jbarrez's commit @19b3ff8 on activiti6 branch, AbstractCompleteTaskCmd no longer sets task's delete reason to "completed", instead setting it to null. This is an, as far as I figured out, undocumented change in behaviour. There is also no database upgrade step to migrate the old data, which I would consider to be inappropriate anyway, because null was a valid delete reason before as well.

I am not sure if this change was intentional or not, but I consider it a bad idea, at least for backward compatibility reasons.

**Comment by whyicantusemyemailasusername** [comment]
It would be nice to be able to set custom delete reason for complete.

**Comment by Salaboy** [comment]
@mpolajnar @whyicantusemyemailasusername totally agree with you guys. Are you interested in contributing that for Activiti 7 & activiti Cloud? get in touch via gitter and we can plan how to do that. I'm closing this issue for now so we can have a discussion about how to proceed.
