### ISSUE TITLE
No zip release for RC1 on activiti.org?

### ISSUE THREAD

**Issue by PascalSchumacher** [Activiti/Activiti#1189]
I can not find a zip release for RC1, https://www.activiti.org/download-links still links to activiti-6.0.0.Beta4.zip

Edit: Found it on github: https://github.com/Activiti/Activiti/releases/download/activiti-6.0.0.RC1/activiti-6.0.0.RC1.zip, but having on the website would still be nice.

**Comment by balsarori** [comment]
Thanks for reporting this. The zip file has been included in the activiti.org site.

**Comment by PascalSchumacher** [comment]
Thanks!
