### ISSUE TITLE
backslash character is not escaped when searching for tables with prefix act_

### ISSUE THREAD

**Issue by martinhanes** [Activiti/Activiti#1191]
It caused tables named "activiti" or "actual" or anything with prefix act to be found with query instead. Correct approach is to escape '_' character with backslash.

### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: relation "active_user" does not exist

**Comment by balsarori** [comment]
reported here https://activiti.atlassian.net/browse/ACT-4287

**Comment by balsarori** [comment]
fixed
