### ISSUE TITLE
Problems with cancelling boundary events (Version 6.0.0.RC1)

### ISSUE THREAD

**Issue by explorer566** [Activiti/Activiti#1194]
In our application we have a sub process with a signal boundary event using cancelActivity="true".
Within this sub process we create a sub process instance using a service task with a Java delegate (_entityManager.createSubprocessInstance_).
During execution of this sub process the signal for the signal boundary event is thrown.

This leads to a database error because the sub process with the signal boundary event is deleted in method _deleteChildExecutions_ of class _org.activiti.engine.impl.bpmn.behavior.BoundaryEventActivityBehavior_ but not the created sub process that references the deleted one as super execution.

If the statement
`if (parentExecution.getCurrentFlowElement() instanceof CallActivity)`
would be ommited in method _deleteChildExecutions_ all would be fine, because then the created sub process (that was not created by a call activity) would be deleted too.

Thanx in advance
Ralf

**Comment by Amaravadishk** [comment]
Hi Ralf, 

Can you provide a unit test case to reproduce the scenario ? 

Thanks, 
Srihari.

**Comment by explorer566** [comment]
Hi Srihari,

 

here is an eclipse project containing the test case.

 

Thanx

Ralf

**Comment by Amaravadishk** [comment]
Hi Ralf, 

Thats ok. 

Thanks. 
Srihari.

**Comment by explorer566** [comment]
Finally, here is the test-case

Cheers
Ralf

[activiti-test.zip](https://github.com/Activiti/Activiti/files/1019586/activiti-test.zip)

**Comment by Amaravadishk** [comment]
Thanks Ralf. We will be fixing this soon. 

Regards,
Srihari.

**Comment by lourdupranay** [comment]
Fixed with this PR #1206

**Comment by balsarori** [comment]
fixed
