### ISSUE TITLE
Problems with error propagation (Version 6.0.0.RC1)

### ISSUE THREAD

**Issue by explorer566** [Activiti/Activiti#1195]
When a sub process element has two error boundary events, one with a specific error code and one without, the first one should be chosen, when the error codes match.

In my case during execution of the sub process an error end event is executed calling method _propagateError_ of class _org.flowable.engine.impl.bpmn.helper.ErrorPropagation_. In method _findCatchingEventsForProcess_ both error boundary events of the parent process are correctly found and returned in the same list as value of the returned event map but in method _executeCatch_ (line 143) simply the first error boundary event in the list (in my case the one without error code) is chosen and propagated without checking the other error boundary event in the list for a matching error code.

I attached a small example to demonstrate the error.
[example.zip](https://github.com/Activiti/Activiti/files/989643/example.zip)

I also found out that the complete error propagation fails, when in method _propagateError_ the first call of method _findCatchingEventsForProcess_ returns an eventMap with irrelevant error boundary events and then method _executeCatch_ is called. In case of a call activity you get a "No matching parent execution for error code" exception because the search for catching events only includes parent executions but not super executions.

I attached a small example for this type of error too.
[error_example.zip](https://github.com/Activiti/Activiti/files/989649/error_example.zip)

If you add the following code before line 152 it works for me.

     `} else if (StringUtils.isNotEmpty(parentExecution.getSuperExecutionId())) {
              parentExecution = parentExecution.getSuperExecution();
              eventMap = findCatchingEventsForProcess(parentExecution.getProcessDefinitionId(),
                                   errorId);`

**Comment by purvendra-k** [comment]
Hi Ralf,
The class "org.flowable.engine.impl.bpmn.helper.ErrorPropagation" does not exist in Activiti. It should be in flowable.

**Comment by explorer566** [comment]
Sorry I mean class org.activiti.engine.impl.bpmn.helper.ErrorPropagation

**Comment by purvendra-k** [comment]
Okay

**Comment by explorer566** [comment]
Here are two unit tests to demonstrate the errors

[activiti-test.zip](https://github.com/Activiti/Activiti/files/1022729/activiti-test.zip)

**Comment by Amaravadishk** [comment]
We had this in our to do list. Thanks for reporting and for the unit test case. We will investigate and fix it. 

Regards,
Srihari.

**Comment by lourdupranay** [comment]
@ #1214

**Comment by lourdupranay** [comment]
#1214

**Comment by Salaboy** [comment]
Closing the issue due it is marked as fixed by @lourdupranay
