### ISSUE TITLE
upload file via Form not include taskId

### ISSUE THREAD

**Issue by vlancer123** [Activiti/Activiti#1199]
When I try use upload module (drag and drop when create a form). The Form only upload file and add a new record to act_wo_related_content table with task_id and process_id is null and after I submit that form then data of "uploaded" properties in RESOURCE_BYTES_ column still null.

![capture](https://cloud.githubusercontent.com/assets/24229179/26045530/e5ec0802-3974-11e7-81f1-efee6a8cb070.PNG)
![capture1](https://cloud.githubusercontent.com/assets/24229179/26045529/e5ebd792-3974-11e7-9444-99c04980b663.PNG)

**Comment by purvendra-k** [comment]
This is a bug. We are fixing it.

**Comment by purvendra-k** [comment]
Fixed and created the pull request.
#1212

**Comment by purvendra-k** [comment]
This issue is fixed. It can be closed now.

**Comment by itamarribeirosilva** [comment]
@purvendra-k 
Sorry my basic question, 
This correction not aplied in general release (Activiti 6.0.0) avaliable for deploy.
I  think shoud I build my own release.
Can you help me with the steps for build from sources ?
I tried "mvn install" but can't found Activit-app.war, Activit-admin.war and and Activit-rest.war.

Also i tried to build (Make Activit-app.war, Activit-admin.war and and Activit-rest.war) using  sources (https://github.com/Activiti/Activiti/releases/tag/7.0.0.Beta1) and importing by  IntelliJ and Building (Crt +F9), but i’m not sure I’m doing by correct way.

Can you help me with steps for build and deploy Activiti Community (6.0 and 7.0) from sources?
Thank you!
