### ISSUE TITLE
BUG: not working runtime/tasks?withoutDueDate=true

### ISSUE THREAD

**Issue by vvp83** [Activiti/Activiti#1220]
## **when execute query runtime/tasks?withoutDueDate=true - return all tasks**

Version Activiti - 6.0

**Comment by SudhaBalabhadra** [comment]
#1222

**Comment by vvp83** [comment]
Thanks! Where i can download beta version release with fix?

**Comment by balsarori** [comment]
fix merged into 6.x branch
