### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by mxassis** [Activiti/Activiti#1224]
Hi all! what do you think about portuguese version of Activiti. I can colaborate with this.

**Comment by Salaboy** [comment]
@mxassis We will love it, what about starting with our new gitbook for activiti 7. We will appreciate your collaboration in the new version. Feel free to join us in gitter so we can have a chat about it: https://gitter.im/Activiti/Activiti7?utm_source=share-link&utm_medium=link&utm_campaign=share-link
