### ISSUE TITLE
Variable scope issue with task with multiple listeners [Activiti 6]

### ISSUE THREAD

**Issue by whyicantusemyemailasusername** [Activiti/Activiti#1236]
We've found some issues with var visibility - it seems that listeners implementation is buggy.
Here the test case (see attached bpmn & kotlin file):
- set process variable v1
- in task1, set local variable with same name (v1) (task.setVariableLocal()) in task listener
- complete task1
- in task2, check that process' v1 var has initial value (task.getVariable()/task.getExecution().getVariable())
If task1 has single listener, everything works as intended.
However, if it has more than one listener, task.getVariable('v1') in task2 returns wrong value.

[ActivitiScopesTest.kt.txt](https://github.com/Activiti/Activiti/files/1139634/ActivitiScopesTest.kt.txt)
[test_bpmn.txt](https://github.com/Activiti/Activiti/files/1139635/test_bpmn.txt)

**Comment by whyicantusemyemailasusername** [comment]
Here the fix from my colleague
`
public class MybatisVariableInstanceDataManagerFixed extends MybatisVariableInstanceDataManager {

    private final CachedEntityMatcher<VariableInstanceEntity> variableInstanceMatcher =
            new VariableByExecutionIdMatcherFixed();

    public MybatisVariableInstanceDataManagerFixed(
            final ProcessEngineConfigurationImpl processEngineConfiguration
    ) {
        super(processEngineConfiguration);
    }

    @Override
    public List<VariableInstanceEntity> findVariableInstancesByExecutionId(final String executionId) {
        return getList("selectVariablesByExecutionId", executionId, variableInstanceMatcher, true);
    }

    private static class VariableByExecutionIdMatcherFixed extends VariableByExecutionIdMatcher {
        @Override
        public boolean isRetained(
                final VariableInstanceEntity variableInstanceEntity,
                final Object parameter
        ) {
            return variableInstanceEntity.getTaskId() == null &&
                    super.isRetained(variableInstanceEntity, parameter);
        }
    }
}
`

**Comment by Salaboy** [comment]
@whyicantusemyemailasusername Thanks for the suggestions and proposed fix. Can you please provide a pull request to the appropriate branch where this is fixed? if not this becomes really difficult to track.
