### ISSUE TITLE
Run external depedency (e.g. keycloak) for tests inside docker

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1245]
Starting point - https://docs.travis-ci.com/user/docker/

Next step after proving it is to provide a reference a docker image with the keycloak json files applied (the json files here - https://github.com/Activiti/Activiti/tree/9308ca29fb2c7033a945f03ba961165bb9f6f62a/activiti-spring-boot/spring-boot-samples/spring-boot-sample-hal-rest-api)... See https://github.com/dfranssen/docker-keycloak-import-realm and https://github.com/keycloak/keycloak-test-docker-images/tree/master/keycloak-sssd-integration-tests for info on how to do this.

**Comment by ryandawsonuk** [comment]
Enzo found this - https://github.com/spotify/dockerfile-maven

**Comment by ryandawsonuk** [comment]
We now do have a reference docker file that has the json configuration applied to it and which the tests pass against - https://github.com/Activiti/Activiti/tree/tasks-specific-to-user/activiti-spring-boot/spring-boot-samples/spring-boot-sample-hal-rest-api  (note this isn't in master branch at time of writing). 

So the outstanding bit is this bit to initiate it from maven and invoke the tests against it from maven (currently maven set to exclude any tests with 'Keycloak' in the name).

**Comment by Salaboy** [comment]
@ryandawsonuk there are 3 options for maven plugins the one provided by spotify, the one provided by fabric8 and another one provided by an individual. There is also a matrix provided by fabric8 comparing the 3 options. I should go with the one provided by spotify unless the fabric8 one provides too many extra advantages.
