### ISSUE TITLE
ExecutionEntityImpl declares multiple JSON fields named isDeleted

### ISSUE THREAD

**Issue by zqr95518** [Activiti/Activiti#1262]
Request processing failed; nested exception is java.lang.IllegalArgumentException: class org.activiti.engine.impl.persistence.entity.ExecutionEntityImpl declares multiple JSON fields named isDeleted
Appear when use gson.toJson(obj).

**Comment by daisuke-yoshimoto** [comment]
@zqr95518 
You can ask questions on the forum site.
https://community.alfresco.com/community/bpm

Or, if it is a defect report, JIRA is appropriate.
https://activiti.atlassian.net
