### ISSUE TITLE
Update Activiti 6.0.x to 7.0.0 manual

### ISSUE THREAD

**Issue by vvp83** [Activiti/Activiti#1264]
## Hello! Im build activiti from git and as result only JAR files not WAR
./activiti-process-validation/target/activiti-process-validation-7.0.0-SNAPSHOT.jar
./activiti-json-converter/target/activiti-json-converter-7.0.0-SNAPSHOT.jar
./activiti-spring/target/activiti-spring-7.0.0-SNAPSHOT.jar
./activiti-bpmn-layout/target/activiti-bpmn-layout-7.0.0-SNAPSHOT.jar
./activiti-engine/target/activiti-engine-7.0.0-SNAPSHOT.jar
./activiti-bpmn-model/target/activiti-bpmn-model-7.0.0-SNAPSHOT.jar
./activiti-bpmn-converter/target/activiti-bpmn-converter-7.0.0-SNAPSHOT.jar
./activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter-hal-rest-api/target/activiti-spring-boot-starter-hal-rest-api-7.0.0-SNAPSHOT.jar
./activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter-basic/target/activiti-spring-boot-starter-basic-7.0.0-SNAPSHOT.jar
./activiti-spring-boot/spring-boot-samples/spring-boot-sample-hal-rest-api/target/spring-boot-sample-hal-rest-api-7.0.0-SNAPSHOT.jar'

I m to try change files in lib directory 6.0.x to 7.0.0 but got error. 
How update 6.0.0 to 7.0.0 version??

**Comment by ryandawsonuk** [comment]
If you're interested in Activiti7 the best place to discuss it right now is the gitter chat https://gitter.im/Activiti/Activiti7 Please do feel free to join!

**Comment by Salaboy** [comment]
@vvp83 Hi, there is no upgrade path defined yet. we are just starting with Activiti 7 and we are changing the distribution mode. Meaning that we are moving to a more microservice oriented approach, where there are no monolith WAR files containing everything. We are following the roadmap described here: https://salaboy.com/2017/07/05/activiti-7-kick-off-roadmap/ . A migration path will be provided at some point toward the end of the year, but I strongly recommend you to check the roadmap, understand the changes that we are making and join if you are interested in shaping the future of the project. It will be very valuable for the community to know your thoughts about the new plans and how you were using Activiti before.
