### ISSUE TITLE
[Activiti 6.0] activiti-admin console looks bad in browser

### ISSUE THREAD

**Issue by chicco0386** [Activiti/Activiti#1265]
Hi all,
I'm try to install and work with Activiti.
I'm looking to a BPMN that has a good admin console for monitoring the flows and their tasks, and for activiti I think that the activiti-admin.war is for that.
But when I deploy the WAR into a Tomcat the application looks like in the image attached.
I'm doing something wrong?

Thank you

![schermata del 2017-07-21 09-44-10](https://user-images.githubusercontent.com/15104165/28453976-c0d60f22-6df9-11e7-8b0c-30468cfcc69d.png)

**Comment by daisuke-yoshimoto** [comment]
@chicco0386 
You can ask questions on the forum site.
https://community.alfresco.com/community/bpm

Or, if it is a defect report, JIRA is appropriate.
https://activiti.atlassian.net

**Comment by chicco0386** [comment]
https://community.alfresco.com/thread/232489-activiti-60-activiti-admin-console-looks-bad-in-browser
