### ISSUE TITLE
Build Notification Service using WebSockets

### ISSUE THREAD

**Issue by Salaboy** [Activiti/Activiti#1267]
Use https://github.com/spring-projects/spring-boot/tree/master/spring-boot-starters/spring-boot-starter-websocket to create a web socket enabled service that pushes notifications to websocket clients. 

This service will consume events from the engine, transform those events and push them to interested clients via WebSockets. This service should consider the logged-in user to make sure that we only send relevant notifications to the right user. 

You can follow something like this tutorial to get the basics working: https://spring.io/guides/gs/messaging-stomp-websocket/

**Comment by erdemedeiros** [comment]
@igdianov  is working on GraphQL notifications (https://github.com/Activiti/Activiti/issues/1507)
