### ISSUE TITLE
Provide Eclipse Code Convention Files

### ISSUE THREAD

**Issue by Salaboy** [Activiti/Activiti#1277]

**Comment by daisuke-yoshimoto** [comment]
@Salaboy @gmalanga 

Sorry, apparently the format results seem different.
The left is Intellij and the right is Eclipse.
![difference](https://user-images.githubusercontent.com/16251291/28644176-75471bb6-7293-11e7-9264-fcabf711b627.png)

**Comment by Salaboy** [comment]
Yes true, 
@gmalanga already fixed some of those, but I'm not sure if he push that already. @gmalanga can you export the new settings after your changes so we can share the new version?

**Comment by Salaboy** [comment]
updated configs
