### ISSUE TITLE
Runtime Query Service

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#1287]
Create a Runtime Query Service that consumes Process Engine Events and keeps state about Process Instances and tasks. This component will aggregate events generated by different apps and process engines. 

Different implementations using different technologies can be provided but the API should be shared. 

This component should work independently from the rest of the infrastructure and it must be security enabled. 

This component must be a spring boot 2 app. 

This component should expose a REST API that enables the user to query for his/her tasks and process instances and applying complex filters, sorting and pagination.

**Comment by mteodori** [comment]
implemented in JPA, other implementations haven't been continued
