### ISSUE TITLE
Query API Elastic integration

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1288]
Can we use same query API endpoints and approach to run on relational DB using spring data and also on elastic by plugging in different repository?

**Comment by Salaboy** [comment]
@willkzhou hi William, what is the status of this? Is it realistic to say that we can have the intial version for the 15th Dec?

**Comment by Salaboy** [comment]
@willkzhou still there?

**Comment by Salaboy** [comment]
@willkzhou @gmalanga please let us know what is the plan for this one.

**Comment by mteodori** [comment]
closing as obsolete, no feedback
