### ISSUE TITLE
some question about using function of suspendProcessInstanceById

### ISSUE THREAD

**Issue by onealcenter** [Activiti/Activiti#1296]
import org.activiti.engine.RuntimeService;
import org.activiti.engine.delegate.DelegateExecution;
import org.activiti.engine.delegate.Expression;
import org.activiti.engine.delegate.JavaDelegate;

public class Cjst1 implements JavaDelegate {
	private Expression rs;

	@Override
	public void execute(DelegateExecution arg0) {
		RuntimeService rrr = ((RuntimeService) rs.getValue(arg0));
		rrr.suspendProcessInstanceById(arg0.getProcessInstanceId());
		System.out.println("1 " + arg0.getProcessInstanceId());
	}

}

hello, this is my code. i wanna to use suspendProcessInstanceById function to suspend current process in JavaDelegate, however the process is not suspended as expected and it continues to next step. in code, object rrr is a instance of RuntimeService from field inject, and in fact rrr is the RuntimeService of spring boot. i am so confused about this condition. please help, thanks

**Comment by Salaboy** [comment]
@onealcenter first of all this is not the best place to ask questions. I would suggest you to go to the activiti forums for that. I will close this issue now.
