### ISSUE TITLE
Remove H2 Dependency from Activiti Spring Boot Starter

### ISSUE THREAD

**Issue by Salaboy** [Activiti/Activiti#1303]
We should remove the dependency from the starter and document that DB configuration properties are needed in the final application that includes the starter as a dependency.

**Comment by ryandawsonuk** [comment]
It is already only a test dependency - https://github.com/Activiti/Activiti/blob/master/activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter/pom.xml#L144

It's the sample that has been adding it as dependency:
https://github.com/Activiti/activiti-examples/commit/ca3ad9392c4eebf8f1f296b2801977131ba07fee#diff-5879dee49b904b7072e5888d2dde25e4R46
