### ISSUE TITLE
Remove all System.outs -> replace by logging

### ISSUE THREAD

**Issue by Salaboy** [Activiti/Activiti#1307]
in all the services project at least this should be a common practice and System.outs shouldn't go to master anymore.

**Comment by Salaboy** [comment]
@erdemedeiros @ryandawsonuk Three key pieces on the logging side. 
1) We shouldn't allow System.outs to go into master, so pay attention to the PRs review
2) We use generic APIs as dependencies to our project, so people can hook in their own logging frameworks, by this I mean: 
<dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
3) for tests we add: 
 <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <scope>test</scope>
    </dependency> and
logback-test.xml with the correct configuration such as: 
<?xml version="1.0" encoding="UTF-8"?>
<configuration>

  <appender name="consoleAppender" class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
      
      
      <pattern>%d [%t|%C] %-5p %m%n</pattern>
    </encoder>
  </appender>

  <root level="info">
    <appender-ref ref="consoleAppender" />
  </root>

</configuration>

We need to make sure that we don't include any logging framework in our starter or apps, the user should choose which implementation to use.

**Comment by daisuke-yoshimoto** [comment]
@Salaboy 

> We shouldn't allow System.outs to go into master, so pay attention to the PRs review

Like the following sample, Can we check that automatic with Codacy?
https://www.codacy.com/app/mziccard/gcloud-java/issues?step=80&filters=W3siaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJDb2RlIFN0eWxlIl19XQ%3D%3D

**Comment by erdemedeiros** [comment]
Good idea @daisuke-yoshimoto. I enabled this check on codacy. It should track that now.
