### ISSUE TITLE
How to disable JpaProcessEngineAutoConfiguration bean auto configure when integrated with spring boot?

### ISSUE THREAD

**Issue by autumind** [Activiti/Activiti#1331]
Activiti version is 6.0.0.

I've tried `@EnableAutoConfiguration(exclude = JpaProcessEngineAutoConfiguration.class)`.

When I start application with `java -jar`, this annotation seems not work.

**Comment by Salaboy** [comment]
@autumind hi there, can you elaborate on what are you trying to achieve? Have you look at our new work in Activiti Cloud and the new starters under our activiti-cloud-runtime-bundle-service repository?

**Comment by autumind** [comment]
@Salaboy I've solved this issue in my pr [#1416](https://github.com/Activiti/Activiti/pull/1416).
