### ISSUE TITLE
Docker containers are started/stopped even if the tests are not running/ignored.

### ISSUE THREAD

**Issue by Salaboy** [Activiti/Activiti#1353]
Docker images should be built always, even if tests are not running, but containers shouldn't be started/stopped if the tests are not executed.

**Comment by ryandawsonuk** [comment]
I think we want to use this configuration on the plugin:

        <executions>
          <execution>
            <id>build</id>
            <phase>package</phase>
            <goals>
              <goal>build</goal>
            </goals>
          </execution>
          <execution>
            <id>start</id>
            <configuration>
              <skip>${skipTests}</skip>
            </configuration>
            <phase>pre-integration-test</phase>
            <goals>
              <goal>start</goal>
            </goals>
          </execution>
          <execution>
            <id>stop</id>
            <configuration>
              <skip>${skipTests}</skip>
            </configuration>
            <phase>post-integration-test</phase>
            <goals>
              <goal>stop</goal>
            </goals>
          </execution>
        </executions>

**Comment by Salaboy** [comment]
@ryandawsonuk can you add that, to where is applicable please

**Comment by ryandawsonuk** [comment]
Have included in https://github.com/Activiti/activiti-spring-boot-starters/pull/1
