### ISSUE TITLE
Define "possible actions" endpoint for runtime bundles

### ISSUE THREAD

**Issue by Salaboy** [Activiti/Activiti#1356]
The Possible Actions (find a better name) Endpoint should list which actions can be executed for a given Runtime Bundle (Spring boot app + process defs + activiti starter)

For example:
- start all these process defs
- suspend all these process instances
- activate all these process instances
- complete all these tasks

This endpoint should expose data in a resource way so it can be navigated. This endpoint also should take into account the currently logged in user and the businessAdmin Role

**Comment by Salaboy** [comment]
@daisuke-yoshimoto what do you think about this issue? I was thinking to assign it to you after you finish the TaskVariables ones. This also involves some endpoints and you already know that code.

**Comment by daisuke-yoshimoto** [comment]
@Salaboy 
I see. Thank you.
Next, I will try this issue.

**Comment by Salaboy** [comment]
I will close this issue to not confuse people. We might think more carefully about how to approach this in the future.
