### ISSUE TITLE
Add Mongo support to Audit Service

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1380]
Currently using h2. Mongo would be better suited to the large volumes expected. See https://www.mkyong.com/spring-boot/spring-boot-spring-data-mongodb-example/

Copy the existing JPA implementation under https://github.com/Activiti/Activiti/tree/master/activiti-services/activiti-services-audit and put in an additional implementation based on mongo

**Comment by Salaboy** [comment]
@ryandawsonuk @daisuke-yoshimoto just to be clear, we are not planning to change the JPA implementation with Mongo DB, just have an alternative (additional) implementation. I just want to be clear because the title of the issue is confusing.

**Comment by daisuke-yoshimoto** [comment]
@Salaboy I chanaged the title of this issue for not confusing.
