### ISSUE TITLE
Audit service to use Predicates

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1381]
The Query service uses @QuerydslPredicate to enable filtering on endpoints by attributes. See https://github.com/Activiti/Activiti/pull/1312 . (For an official spring example see https://github.com/spring-projects/spring-data-examples/tree/master/web/querydsl or some of the other tutorials online.) But Audit currently does not do this. Need to implement the same functionality on audit.

**Comment by Salaboy** [comment]
@ryandawsonuk @erdemedeiros is this something that we can guide @mteodori to do in December?

**Comment by erdemedeiros** [comment]
Actually this was already implemented in the milestone [7-201710-EA](https://github.com/Activiti/activiti-cloud-audit-service/blob/7-201710-EA/activiti-cloud-services-audit/activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/EventsRepository.java#L36)

**Comment by Salaboy** [comment]
:) great!
