### ISSUE TITLE
Actuator in activiti basic starter to be moved out into service

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1395]
Or remove it maybe... do we have services doing what it did?

**Comment by Salaboy** [comment]
@ffazzini can you also take this one?

**Comment by ryandawsonuk** [comment]
In this case there isn't a service to move it out into. See https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-starter-configure/pom.xml#L78 . I suggest we just close this ticket.
