### ISSUE TITLE
Feature request: Cannot set variables when complete task

### ISSUE THREAD

**Issue by vvp83** [Activiti/Activiti#1398]
POST runtime/tasks/{taskId}
{
  "action" : "complete",
  "variables" : [{"name" : "result_doc","value" : "TEST_URL_DOC","type":"string"}]
}

**Comment by huicaier** [comment]
can you paste error log for more details

**Comment by vvp83** [comment]
**GET IFO ABOUT TASK:**
GET /runtime/tasks?includeProcessVariables=TRUE&size=10000&assignee=testuser

DATA:
----------------------------------
        {
            "id": "79123",
            "url": "https://activiti.dev-alex.org/activiti-rest/service/runtime/tasks/79123",
            "owner": null,
            "assignee": "testuser",
            "delegationState": null,
            "name": "Execute form",
            "description": null,
            "createTime": "2017-09-30T00:49:02.166+03:00",
            "dueDate": null,
            "priority": 50,
            "suspended": false,
            "taskDefinitionKey": "sid-46138B1D-ED22-4EE8-86CD-456EA0E05E61",
            "tenantId": "",
            "category": null,
            "formKey": null,
            "parentTaskId": null,
            "parentTaskUrl": null,
            "executionId": "79116",
            "executionUrl": "https://activiti.dev-alex.org/activiti-rest/service/runtime/executions/79116",
            "processInstanceId": "79078",
            "processInstanceUrl": "https://activiti.dev-alex.org/activiti-rest/service/runtime/process-instances/79078",
            "processDefinitionId": "tasks_manager_multiuser:4:5012",
            "processDefinitionUrl": "https://activiti.dev-alex.org/activiti-rest/service/repository/process-definitions/tasks_manager_multiuser:4:5012",
            "variables": [
                {
                    "name": "cycle_period",
                    "value": null,
                    "scope": "global"
                },
                {
                    "name": "DocumentFolderUUID",
                    "type": "string",
                    "value": "815b9a46-46c1-4a4c-8950-0d1baedfb234",
                    "scope": "global"
                },
                {
                    "name": "start_datetime",
                    "value": null,
                    "scope": "global"
                },
                {
                    "name": "form_executor_string",
                    "type": "string",
                    "value": "testuser",
                    "scope": "global"
                },
                {
                    "name": "AssignmentName",
                    "type": "string",
                    "value": "Назначение 1",
                    "scope": "global"
                },
                {
                    "name": "DocumentSiteId",
                    "type": "string",
                    "value": "d95bd0150e8502d5a04b07a1ce2fad702d4f821b",
                    "scope": "global"
                },
                {
                    "name": "initiator",
                    "type": "string",
                    "value": "testuser",
                    "scope": "global"
                },
                {
                    "name": "TemplateName",
                    "type": "string",
                    "value": "ыфвафыва",
                    "scope": "global"
                },
                {
                    "name": "form_executor",
                    "type": "serializable",
                    "value": null,
                    "valueUrl": "https://activiti.dev-alex.org/activiti-rest/service/runtime/tasks/79123/variables/form_executor/data",
                    "scope": "global"
                },
                {
                    "name": "TemplateId",
                    "type": "string",
                    "value": "754b0d67-2480-497b-bed9-0a44418869cf",
                    "scope": "global"
                }
            ]
        }
-------------------------
-------------------------

**UPDATE & COMPLETE TASK**

POST /runtime/tasks/79123
{
"action" : "complete",
"variables" : [{"name" : "result_doc","value" : "TEST_URL_DOC","type":"string"}]
}


**CHECK TASK VARIABLES**
GET /history/historic-task-instances/79123?includeTaskLocalVariables
{
    "id": "79123",
    "processDefinitionId": "tasks_manager_multiuser:4:5012",
    "processDefinitionUrl": "https://activiti.dev-alex.org/activiti-rest/service/repository/process-definitions/tasks_manager_multiuser:4:5012",
    "processInstanceId": "79078",
    "processInstanceUrl": "https://activiti.dev-alex.org/activiti-rest/service/history/historic-process-instances/79078",
    "executionId": "79116",
    "name": "Execute form",
    "description": null,
    "deleteReason": null,
    "owner": null,
    "assignee": "xandr",
    "startTime": "2017-09-30T00:49:02.166+03:00",
    "endTime": "2017-09-30T01:07:10.345+03:00",
    "durationInMillis": 1088179,
    "workTimeInMillis": null,
    "claimTime": null,
    "taskDefinitionKey": "sid-46138B1D-ED22-4EE8-86CD-456EA0E05E61",
    "formKey": null,
    "priority": 50,
    "dueDate": null,
    "parentTaskId": null,
    "url": "https://activiti.dev-alex.org/activiti-rest/service/history/historic-task-instances/79123",
    "variables": [],
    "tenantId": "",
    "category": null
}


LOCAL VARIABLES IS EMPTY.

**Comment by balsarori** [comment]
Complete task will call the complete method in TaskService which saves variables in the process level scope not local task scope.

**Comment by vvp83** [comment]
Yes. This is Feature request not bug!

**Comment by Salaboy** [comment]
@vvp83 I'm closing this issue due inactivity, please feel free to reach us in the gitter channel to discuss how this is going to work in Activiti 7 & Activiti Cloud: https://gitter.im/Activiti/Activiti7?utm_source=share-link&utm_medium=link&utm_campaign=share-link
