### ISSUE TITLE
rename activiti-cloud-keycloak to activiti-cloud-sso-idm

### ISSUE THREAD

**Issue by Salaboy** [Activiti/Activiti#1402]
in github repo and docker hub

**Comment by ryandawsonuk** [comment]
PRs:
https://github.com/Activiti/activiti-cloud-examples/pull/13
https://github.com/Activiti/activiti-cloud-audit/pull/6
https://github.com/Activiti/activiti-cloud-query/pull/4
https://github.com/Activiti/activiti-cloud-gateway/pull/5
https://github.com/Activiti/activiti-cloud-runtime-bundle/pull/6

**Comment by Salaboy** [comment]
@ryandawsonuk can you confirm that after merging everything works? 
so I can close this issue.

**Comment by ryandawsonuk** [comment]
Also removed activiti/activiti-cloud-keycloak from dockerhub. There's no starter for this as it's all docker-based so can now close.
