### ISSUE TITLE
Improvement of sending event to Audit Service

### ISSUE THREAD

**Issue by daisuke-yoshimoto** [Activiti/Activiti#1407]
Changing sending method as follows.
* Before: sending events each time an event is generated(ActivitiEventListener)
* After : sending events when the command is closed(CommandContextCloseListener).

https://github.com/Activiti/Activiti/blob/master/activiti-services/activiti-services-events/src/main/java/org/activiti/services/events/MessageProducerActivitiEventListener.java

### Improvement of network communication frequency

* If sending events each time an event is generated, the number of times of network communication will very increase.
  * For example, when 100 variables are updated, at least 100 network communications occur.

### Transaction consistency 

* The data of Audit Service is committed for each event.
* However, if an error occurs during the command, Process Engine data is rolled back and Audit Service data is not rolled back.

**Comment by Salaboy** [comment]
@daisuke-yoshimoto ok I want to understand more about this. I do understand that events will be sent even if the state of the process engine is rolled back in the case of an issue. So basically, you are sending all the events when the transaction is committed, am I right? In principle, I do agree with that idea, but we need to be careful on how we implement this. In my opinion, we can solve this by making all the process interactions with external entities async by default. Meaning that we will assume that BPMN events and Sequence Flows will not fail so transactions will be small and will not cause big rollbacks. In the example of (start event) -> (service task) - > (user task) -> (end event) we will force the engine to deal with the first service task in an async way always, so the first transaction will only include the start event + scheduling the service task. 

Does this make sense?
