### ISSUE TITLE
eureka refresh period

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1411]
We first found this when we were trying to use a random port for runtime bundle and saw it getting a 204 wait status from eureka. Don't necessarily want random port now but takes a long time to register runtime bundle. Presumably there's a eureka setting for this.

**Comment by Salaboy** [comment]
@ryandawsonuk did we find an answer for this? I think that for now everything is working quite ok. If you can close or refine this I will appreciate it.

**Comment by ryandawsonuk** [comment]
Yeah it doesn't seem to be causing us any problems at the moment. Let's close as we can always open a new issue if we need one.
