### ISSUE TITLE
expose a debug port in the java start command and also in docker

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1412]

**Comment by ryandawsonuk** [comment]
Think we can follow this example -
https://stackoverflow.com/questions/31070671/debug-spring-boot-in-docker

**Comment by ryandawsonuk** [comment]
I had read online that there would be no performance impact - perhaps there's not on most running but setting this on query definitely caused it to take longer to register with eureka. I opened a PR and then closed it when I realised there was this impact - https://github.com/Activiti/activiti-cloud-query/pull/6 .

I suggest we either make this conditional on a variable or document it as something that can be done for debugging purposes.

**Comment by ryandawsonuk** [comment]
Now needs to be done for the other docker images - activiti-cloud-runtime-bundle, activiti-cloud-audit, activiti-cloud-audit-mongodb, activiti-cloud-gateway, activiti-cloud-registry and activiti-cloud-sso-idm

**Comment by Salaboy** [comment]
@ryandawsonuk please work on this so we can close it.

**Comment by Salaboy** [comment]
:)
