### ISSUE TITLE
Refactor Activiti Cloud Example to have a maven runtime bundle and a Docker Compose based runtime bundle

### ISSUE THREAD

**Issue by Salaboy** [Activiti/Activiti#1420]
The Cloud Example repository should have the following structure:
1) /infrastructure/ with a docker-compose.yml inside to bootstrap all the infrastructural services
2) docker-runtime-bundle/ with a Dockerfile  inside to create runtime bundles based on extending the generic Docker Image
3) maven-runtime-bundle/ project that uses the starter to define how the runtime bundle docker image will look like. 
4) runtime-bundle-docker-compose.yml which will use one of the generated images from maven or docker runtime bundle projects.

**Comment by Salaboy** [comment]
@ryandawsonuk @erdemedeiros I've merged this PR already in activiti-cloud-examples so I can write the blog post that I've share the other day. Please check that the example still works. I would recommend: 
1) rm -rf ~/.m2/repository/org/activiti
2) docker rmi $(docker images -a -q)
3) follow the README file. Notice that there are 2 options: 1) Docker based 2) Maven based If you can try them both that will be great.

**Comment by ryandawsonuk** [comment]
Have had a look and proposed small documentation changes https://github.com/Activiti/activiti-cloud-examples/pull/6
