### ISSUE TITLE
Create Dockerfile for -cloud projects

### ISSUE THREAD

**Issue by Salaboy** [Activiti/Activiti#1423]
1) activit-cloud-query
2) activiti-cloud-audit
3) activiti-cloud-gateway
4) activiti-cloud-registry
5) activiti-cloud-runtime-bundle: here make sure that the postgresql dependency is not in the maven project but it is added as part of the docker build, so the project doesn't carry the postgresql driver in it.

**Comment by ryandawsonuk** [comment]
PRs to switch to dockerfile builds:
https://github.com/Activiti/activiti-cloud-registry/pull/2
https://github.com/Activiti/activiti-cloud-query/pull/2
https://github.com/Activiti/activiti-cloud-runtime-bundle/pull/3
https://github.com/Activiti/activiti-cloud-gateway/pull/2
https://github.com/Activiti/activiti-cloud-audit/pull/3

Will need to create dockerhub builds and remove bamboo builds.

**Comment by ryandawsonuk** [comment]
To exclude the postgres dependency and add in to child image have submitted these PRs:
https://github.com/Activiti/activiti-cloud-runtime-bundle/pull/4
https://github.com/Activiti/activiti-cloud-examples/pull/8
