### ISSUE TITLE
avoid escaping expression though preceded by \

### ISSUE THREAD

**Issue by amitport** [Activiti/Activiti#1425]
I'm trying to write code that includes $ in the context of a windows file path. For example:

``` xml
<activiti:field name="X">
    <activiti:expression>c:\folder\${contextVar}</activiti:expression>
</activiti:field>
```

This is evaluated to literal `c:\folder\${contextVar}` since `\${` escapes the expression.

Is there any way I can keep the preceding `\` _and_ evaluate the expression?
 
(this issue is re-added following https://github.com/Activiti/Activiti/issues/648#issuecomment-323572317. Previous issue should not have been closed IMO. As far as I can tell, it was inactive because no one worked on it, not because of low importance or lack of information)

**Comment by purvendra-k** [comment]
@amitport 
Which activiti version are you using? Can you attach your sample project here?

**Comment by amitport** [comment]
I use I use 5.17, but this is easily reproducible in any project that uses expressions, and also, IMHO, reproduction is irrelevant

This is not a bug. This is a design/specification issue/question. Is there a way to evaluate inline expressions with `\` before them (e.g., `"c:\folder\${contextVar"`). If there is one, what is it? if there isn't, one should probably be defined, developed and documented.

**Comment by Salaboy** [comment]
@amitport I'm closing this issue, because as you stated this is a question. Which is related to how expression are evaluated. Please refer to the forums if the question is still open.

**Comment by amitport** [comment]
@Salaboy, I looked for answers in various forums. As far as I can tell, this is a bug in the specification of the expression language.

**Comment by Salaboy** [comment]
@amitport it sounds more like a feature, you need a way to escape parsing expressions. So I would recommend how to avoid escaping those characters. My gut feeling is that if you add double \\  before the $ should do the trick.

**Comment by amitport** [comment]
@Salaboy My gut feeling was to try `\\` also. It didn't work. I don't know if it's a bug/feature/documentation issue. Just that it is an issue.
