### ISSUE TITLE
javascript client for infrastructure in activiti-cloud-examples

### ISSUE THREAD

**Issue by Salaboy** [Activiti/Activiti#1426]

**Comment by ryandawsonuk** [comment]
Seems to make sense to try to use the keycloak angular2 demo - https://github.com/ebondu/angular2-keycloak/tree/master/example/angular2-webpack-product-app

I think we'll want to give consideration to https://medium.com/@SumanthShankar/integrate-keycloak-with-angular-2-on-demand-login-10a16c9f8e2e

**Comment by ryandawsonuk** [comment]
PR to enable CORS in gateway - https://github.com/Activiti/activiti-cloud-gateway/pull/4
