### ISSUE TITLE
Move Audit events handling outside of JpaAuditApplication

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#1433]
Currently the audit events handling is performed directly inside the [JpaAuditApplication](https://github.com/Activiti/activiti-cloud-audit/blob/master/src/main/java/org/actviti/cloud/audit/JpaAuditApplication.java#L55). Instead, it should be moved to a dedicated component inside the [activiti-services-audit-jpa](https://github.com/Activiti/Activiti/tree/master/activiti-services/activiti-services-audit/activiti-services-audit-jpa) module. Similar to [QueryConsumerChannelHandler](https://github.com/Activiti/Activiti/blob/master/activiti-services/activiti-services-query/activiti-services-query-rest/src/main/java/org/activiti/services/query/app/QueryConsumerChannelHandler.java).

The `JpaAuditApplication` inside the [starters tests](https://github.com/Activiti/activiti-cloud-starters/blob/master/activiti-cloud-starter-audit/src/test/java/org/activiti/cloud/starter/audit/tests/JpaAuditApplication.java#L58) should be updated as well.

The annotation `@EnableBinding` should moved from [EnableActivitiAudit](https://github.com/Activiti/activiti-cloud-starters/blob/master/activiti-cloud-starter-audit/src/main/java/org/activiti/cloud/starter/configuration/EnableActivitiAudit.java#L19) to new created component.

**Comment by erdemedeiros** [comment]
PRs:
https://github.com/Activiti/Activiti/pull/1448
https://github.com/Activiti/activiti-cloud-starters/pull/13
https://github.com/Activiti/activiti-cloud-audit/pull/7

**Comment by daisuke-yoshimoto** [comment]
@erdemedeiros 
Thank you for your changes.
I will take this change and proceed with the following issue.
https://github.com/Activiti/Activiti/issues/1380
