### ISSUE TITLE
HAL links are broken for my-runtime-bundle endpoints

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#1435]
HAL links (i.e `self` link) are parameterised instead of having the actual entity id:
Actual:
``` json
{
                "id": "16",
                "processDefinitionId": "SimpleProcess:1:4",
                "initiator": "hruser",
                "startDate": 1503410455670,
                "status": "RUNNING",
                "_links": {
                    "self": {
                        "href": "http://localhost:8080/my-runtime-bundle/v1/process-instances/{processInstanceId}",
                        "templated": true
                    },
                    "variables": {
                        "href": "http://localhost:8080/my-runtime-bundle/v1/process-instances/{processInstanceId}/variables",
                        "templated": true
                    },
                    "processInstances": {
                        "href": "http://localhost:8080/my-runtime-bundle/v1/process-instances"
                    },
                    "home": {
                        "href": "http://localhost:8080/my-runtime-bundle/v1"
                    }
                }
            }
```
Expected: 
``` json
{
                "id": "16",
                "processDefinitionId": "SimpleProcess:1:4",
                "initiator": "hruser",
                "startDate": 1503410455670,
                "status": "RUNNING",
                "_links": {
                    "self": {
                        "href": "http://localhost:8080/my-runtime-bundle/v1/process-instances/16"
                    },
                    "variables": {
                        "href": "http://localhost:8080/my-runtime-bundle/v1/process-instances/16/variables"
                    },
                    "processInstances": {
                        "href": "http://localhost:8080/my-runtime-bundle/v1/process-instances"
                    },
                    "home": {
                        "href": "http://localhost:8080/my-runtime-bundle/v1"
                    }
                }
            }
```

**Comment by erdemedeiros** [comment]
This might be related to the use of interface instead of a class in the `*ResourceAssembler`s.

**Comment by Salaboy** [comment]
@erdemedeiros can you guide @mteodori to take a look at this? He is looking at other REST endpoint related issue.

**Comment by mteodori** [comment]
I can confirm, it works only with concrete classes, not interfaces

**Comment by erdemedeiros** [comment]
In this case I think we can remove the interfaces and keep only the implementation for controllers. @Salaboy do you have any strong felling to keep interfaces for controllers?

**Comment by Salaboy** [comment]
@erdemedeiros @mteodori as I mention in Gitter, I wanted to use those interfaces and provide different implementations. @mteodori mention that there are some compromises, but I would rather do that to make sure that our controllers implement those interfaces, no matter if they are or not annotated. Having a separate module for -apis will allow us to not drag the whole implementation if we want to reuse that module somewhere else. It also pushes us to think about dependencies and to avoid duplication of code. @mteodori if you can briefly mention what compromises did you found?

**Comment by mteodori** [comment]
@Salaboy the assemblers are technically part of the api as they define the shape of the links section so they should definitely stay in the API package, but the spring-hateoas methodOn works only with classes not interfaces, honestly I don't see a use case for the api/impl split of controllers

**Comment by Salaboy** [comment]
@mteodori the split needs to remain. Those controllers interfaces (the interfaces themselves) are not tied to be controllers and that's why we can use them for other purposes. We need to make those interfaces as agnostic as possible from the implementation and the fact that they are serving as controllers.
