### ISSUE TITLE
How to run activiti v6 BPMN editing UI in spring-boot

### ISSUE THREAD

**Issue by wplin007** [Activiti/Activiti#1437]
I'm interested in running either the explorer from activiti 6 kickstart app from activiti 6 within my spring project, so that I can utilize the BPMN editing UI to modify/create processes that the activiti engine will leverage in my application. I'm confused as to how to do this. I've only be successful in running the kickstart app by running the activiti-app.war file with tomcat.

**Comment by Salaboy** [comment]
@wplin007 hi there, this is a very good requirement. We are planning something like this for Activiti 7 & Activiti Cloud, but it is not possible with v6 without doing some work on your side. I'm closing this issue to be able to keep track of the work that we are doing right now for version 7.

**Comment by stonesingsong** [comment]
@wplin007 看你的主页，应该也是中国人，请问你解决了这个问题吗？我也想把activiti-ui改成springboot项目，并改一些页面和汉化。盼复，谢谢！

**Comment by Salaboy** [comment]
@wplin007 @stonesingsong are you guys working on this? 
It will be great if we can coordinate this moving forward. Can you please share the URL for your repos?

**Comment by stonesingsong** [comment]
@Salaboy 
I am a Chinese Java developer. My company use Activiti to develop workflow. It help we a lot.
I haven't create the repo yet, and I plan to do it after our Spring Festival.
I'm not sure I'm up to it. I would be very happy to be able to do something for Activiti.

**Comment by Salaboy** [comment]
@stonesingsong that sounds great.. let's collaborate. We are also doing some tests for a new modeller but we still don't have anything. Let me know when you start with that and we can sync again to see if we have someone else working on something similar.

**Comment by rohanpatkar** [comment]
Guys, do we have any updates on this requirement? I have a case where I am planning to do same stuff that  wplin007 had mentioned.

**Comment by salaboy** [comment]
@roberthafner there are some updates about this, and the new modeler is coming out with beta2. 
We currently have the front end in Angular 6 and the backend are spring boot 2 services. 
But the setup also includes SSO(Keycloak)  which is something that we can avoid in the future for simple use cases: 
https://github.com/Activiti/activiti-modeling-app -> Front end

https://github.com/Activiti/activiti-cloud-modeling -> Back end

**Comment by johnzhang521** [comment]
@stonesingsong  我打算 spring boot + activiti 6.0 集成流程设计器到自己的项目中, 并支持汉化, 请问你这边有在做或者做好了的项目吗?
