### ISSUE TITLE
Fix randomly failing test case

### ISSUE THREAD

**Issue by daisuke-yoshimoto** [Activiti/Activiti#1443]
Activiti - Engine

[ERROR]   BoundaryTimerNonInterruptingEventTest>AbstractActivitiTestCase.runBare:97->AbstractTestCase.runTest:60->testMultipleTimersOnUserTask:77 expected:<0> but was:<1>

**Comment by Salaboy** [comment]
@daisuke-yoshimoto when you have time, it will be great if you can take a look at this issue.

**Comment by Salaboy** [comment]
@daisuke-yoshimoto did you manage to check this one? I'm moving it to next month milestone anyway.

**Comment by erdemedeiros** [comment]
@daisuke-yoshimoto we are closing it as this test does not seem to be failing anymore. Feel free to re-open it if it occurs again.

**Comment by daisuke-yoshimoto** [comment]
@Salaboy @erdemedeiros 
I see.
If this test fail again, I will reopen this issue.
