### ISSUE TITLE
keycloak/idm hostname in etc/hosts file bit awkward

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1449]
can we tell keycloak to treat token as not host-specific? increasingly thinking keycloak want us to use hosts file in this scenario because the host machine is not part of the docker network (search 'keycloak etc/hosts' or see https://issues.jboss.org/browse/KEYCLOAK-2067 )

Doesn't seem to be any neat docker solution either - https://forums.docker.com/t/question-docker-host-know-container-ip-and-hostname/19339

Maybe we just close this one?

**Comment by Salaboy** [comment]
I'm closing this one now. Not sure if we need to fix this.. as it seems the norm for everyone.
