### ISSUE TITLE
historyService could not use createHistoricVariableInstanceQuery to find variable name

### ISSUE THREAD

**Issue by huicaier** [Activiti/Activiti#1451]
historyService could not use createHistoricVariableInstanceQuery to find variable name 
which is variableNameLike.
just like :
historyService.createHistoricVariableInstanceQuery().processInstanceId(processId).variableNameLike("approve").list()
the result have no "approvePass" variable etc
my activiti version is 5.22.0 with spring boot

**Comment by Salaboy** [comment]
@huicaier did you manage to solve this problem? That API wasn't exposed for 5.22.0 version.

**Comment by Salaboy** [comment]
@balsarori are you tracking this one?

**Comment by daisuke-yoshimoto** [comment]
@huicaier @Salaboy @balsarori 
I think that this is not an issue but a usage problem about like method.
When we use methods like Like, we need to specify a wildcard.

`historyService.createHistoricVariableInstanceQuery().processInstanceId(processId).variableNameLike("approve%").list()`

https://github.com/Activiti/Activiti/blob/master/activiti-engine/src/test/java/org/activiti/standalone/escapeclause/HistoricVariableInstanceEscapeClauseTest.java#L79
https://www.activiti.org/userguide/#historyQueryTaskInstance

**Comment by Salaboy** [comment]
@daisuke-yoshimoto thanks for the clarification, I'm closing this issue then.
