### ISSUE TITLE
why deleted ACT_RU_EVENT_SUBSCR when deploy a bpmn20.xml??

### ISSUE THREAD

**Issue by whan0216** [Activiti/Activiti#1457]
I found that when deploying a new process , activiti will delete all message or signal record in the table ACT_RU_EVENT_SUBSCR of lastest version process.
WHY????
The version i use is 5.19.0.2

**Comment by daisuke-yoshimoto** [comment]
@whan0216 
Your problem was fixed as the following issue at Activiti 5.20.0
https://activiti.atlassian.net/browse/ACT-4117
