### ISSUE TITLE
ProcessDefinitionCacheEntry can't be serialized

### ISSUE THREAD

**Issue by veryyoung** [Activiti/Activiti#1465]
Hi, I'm trying to store  ProcessDefinitionCache to redis, however, I found some issue to get this done.

The spring-data-redis use JdkSerializationRedisSerializer as default to serialize the ProcessDefinitionCache, but every class that ProcessDefinitionCache needs should  implements Serializable, and the BpmnModel is not.

I alse tried some other ways to solve this, but   jackson、fastjson、kryo,   missing no-arg constructor, gson the cyclic dependency problem occurs

**Comment by Salaboy** [comment]
@veryyoung this is a very good requirement, do you want to help us to get this done? It sounds like a great community contribution. We are willing to mentor and help you to get this done for version 7 and Activiti Cloud. I'm closing this issue now, to make sure that we can keep track of this work, feel free to contact us via gitter to have a conversation about how we can get this done: https://gitter.im/Activiti/Activiti7?utm_source=share-link&utm_medium=link&utm_campaign=share-link
