### ISSUE TITLE
can not find the activiti-parent

### ISSUE THREAD

**Issue by QiquWong** [Activiti/Activiti#1472]
I just want to build the project source code, but it can not find the activiti-parent pom, so the build was fail. Where is it? Can anyone give me some suggestion?

The build info is below:
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.activiti:activiti-root:7-201709-EA-SNA
in the local repository, resolution will not be reattempted until the update int

**Comment by Salaboy** [comment]
@QiquWong hi there, are you still facing this issue? 
Now all artifacts has been published to maven central. If you still want to build from source you can. We work and build the source code almost everyday, so please feel free to reach us via gitter if you have problems with it or if you want to contribute: https://gitter.im/Activiti/Activiti7?utm_source=share-link&utm_medium=link&utm_campaign=share-link
