### ISSUE TITLE
Create Helm Chart following: https://github.com/kubernetes/helm

### ISSUE THREAD

**Issue by Salaboy** [Activiti/Activiti#1473]
https://github.com/kubernetes/helm/blob/master/docs/quickstart.md

**Comment by ryandawsonuk** [comment]
Am using https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/getting_started.md

**Comment by ryandawsonuk** [comment]
PR - https://github.com/Activiti/activiti-cloud-examples/pull/18

**Comment by Salaboy** [comment]
We should close this one right?
