### ISSUE TITLE
SSO/IDM using UAA integration 

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1485]
- like keycloak but base on http://www.java-allandsundry.com/2017/02/using-uaa-oauth2-authorization-server.html and https://github.com/spring-cloud-samples/sso

See https://activiti.gitbooks.io/activiti-7-developers-guide/content/sso-and-idm/integrating-with-an-idm.html

**Comment by Salaboy** [comment]
@ryandawsonuk I will close this one, until we find out what is the PKS strategy for security. I bet it will be UAA, but let's plan and add support for it only if it is needed for PKS or if the JHispter community is using it for the microservices approach
