### ISSUE TITLE
Be able to choose which IDM adapter through properties

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1494]
We want ConditionalOnProperty set on all of the classses in https://github.com/Activiti/Activiti/tree/master/activiti-services/activiti-services-identity-keycloak . There is a KeycloakAutoConfiguration which we should be able to switch off by setting keycloak.enabled but to do that I think we need to be able to disable the others too. We should also do this for https://github.com/Activiti/Activiti/tree/master/activiti-services/activiti-services-identity-basic and any future IDM adapters and that will let us choose which IDM to interface to using properties.

**Comment by Salaboy** [comment]
@daisuke-yoshimoto I can see that you pick this one. Let us know if you are planning or if you are working on one.

**Comment by ryandawsonuk** [comment]
I'm no longer sure this is the best route. Seems nobody is working on it so best to close and think further in this area.
