### ISSUE TITLE
Slice Starters tests. Stream Listener is being loaded for all tests and it is throwing a lot of exceptions.

### ISSUE THREAD

**Issue by Salaboy** [Activiti/Activiti#1501]
This might be related with the latest spring boot upgrade. 
Or our @ComponentScans. We need to split the tests into MockMVC tests that doesn't load the whole app, integration tests and Stream tests. 

This applies to 
- runtime-bundle starter
- audit-starter
- query-starter

**Comment by erdemedeiros** [comment]
Related PR: https://github.com/Activiti/activiti-cloud-runtime-bundle-service/pull/3
