### ISSUE TITLE
Duplicate two if blocks in AbstractProcessEngineAutoConfiguration@L102

### ISSUE THREAD

**Issue by pdilipkumar** [Activiti/Activiti#1516]
https://github.com/Activiti/Activiti/blob/b6aba7e29ce1e1c613176c551c04427c9111e942/modules/activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter-basic/src/main/java/org/activiti/spring/boot/AbstractProcessEngineAutoConfiguration.java#L102

Below mentioned if blocks are duplicated in AbstractProcessEngineAutoConfiguration@L102. I assume this to be a mistake. Please ignore if it is intentional.

if (activitiProperties.getCustomMybatisMappers() != null) {
 conf.setCustomMybatisMappers(getCustomMybatisMapperClasses(activitiProperties.getCustomMybatisMappers()));
    }
    if (activitiProperties.getCustomMybatisXMLMappers() != null) {
      conf.setCustomMybatisXMLMappers(new HashSet<String>(activitiProperties.getCustomMybatisXMLMappers()));
    }

**Comment by Salaboy** [comment]
@pdilipkumar we will fix this for our activiti 7 release, which now was moved from activiti/activiti to activiti/activiti-cloud-runtime-bundle-service where our spring boot starter is.

**Comment by Salaboy** [comment]
https://github.com/Activiti/activiti-cloud-runtime-bundle-service/pull/15
