### ISSUE TITLE
Models converted by BpmnJsonConverter have validation errors in activiti 6+, if they contain subprocess

### ISSUE THREAD

**Issue by alirezamirian** [Activiti/Activiti#1518]
# Problem:
If you convert a `BpmnModel` to json, and it contains subprocesses, validation errors will be reported for links inside subProcesses:

# Root of the problem:
In activiti 6, `Process#getFlowElement` doesn't recursively search for element. Instead, it looks up `flowElementMap` field, which is obviously added in 6.x for performance optimizations and is meant to serve as an **id to element** map in *flow element containers* (Process and SubProcess).

In `addFlowElement` of `SubProcess`, it checks if it's inside another container and adds the currently adding element to `flowElementMap` of that parent container:

[SubProcess.java#L50]:(https://github.com/Activiti/Activiti/blob/b6aba7e29ce1e1c613176c551c04427c9111e942/modules/activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/SubProcess.java#L50)
```java
if (getParentContainer() != null) {
    getParentContainer().addFlowElementToMap(element);
}
```
There is a problem though. If elements are added to some subprocess, before subprocess is added to its parent, the added elements will be missed in parent flowElementMap. Interestingly, this is the case for BpmnJsonConverter. It actually first adds all child flow elements of the subProcess to it, and then adds subprocess itself to its parent.

I think the `addFlowElement` of containers, should also check if the added element is a container itself, and add all entries of it's `flowElementMap` to its own `flowElementMap`.

I can craft a PR to fix this if you want.

**Comment by Salaboy** [comment]
@alirezamirian we will appreciate a PR so we can fix this problem. Make sure that you target the develop branch which is our main stream of work. We are keeping track of all the opened issues now, so please free to get in touch via gitter if you have questions on how to proceed: https://gitter.im/Activiti/Activiti7?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by alirezamirian** [comment]
I will submit two separate PRs targeting `develop` and `6.x` branches, if you don't mind.
