### ISSUE TITLE
Activiti properties not used anywhere

### ISSUE THREAD

**Issue by pdilipkumar** [Activiti/Activiti#1520]
Below mentioned properties are not being used anywhere in activiti-spring-boot-starter-basic. Is there a planned work regarding this? Basically I was looking for a way to disable default rest end points provided and found the property restApiEnabled but this was not working when I set to false and found out that the properties are not used anywhere. Please help me in excluding particular or all restend points registration at startup.

https://github.com/Activiti/Activiti/blob/b6aba7e29ce1e1c613176c551c04427c9111e942/modules/activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter-basic/src/main/java/org/activiti/spring/boot/ActivitiProperties.java#L30
https://github.com/Activiti/Activiti/blob/b6aba7e29ce1e1c613176c551c04427c9111e942/modules/activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter-basic/src/main/java/org/activiti/spring/boot/ActivitiProperties.java#L46
https://github.com/Activiti/Activiti/blob/b6aba7e29ce1e1c613176c551c04427c9111e942/modules/activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter-basic/src/main/java/org/activiti/spring/boot/ActivitiProperties.java#L47

**Comment by Salaboy** [comment]
@pdilipkumar we are working on this, now that we move our starters to our Activiti Cloud namespace you can expect a lot of changes around this space. If you are interested to contribute with this initiative please get in touch via Gitter: https://gitter.im/Activiti/Activiti7?utm_source=share-link&utm_medium=link&utm_campaign=share-link
