### ISSUE TITLE
Create process model REST API

### ISSUE THREAD

**Issue by constantin-ciobotaru** [Activiti/Activiti#1521]

**Comment by Salaboy** [comment]
@constantin-ciobotaru initial version should be added to our December Release. For that reason I'm adding it to the December milestone.

**Comment by Salaboy** [comment]
@constantin-ciobotaru we should close this one right? can we create another issue to follow the progress?

**Comment by constantin-ciobotaru** [comment]
@Salaboy yes, we can close it.
