### ISSUE TITLE
[Critical Bug]Data inconsistency will occur when java.lang.Error is throwen.

### ISSUE THREAD

**Issue by daisuke-yoshimoto** [Activiti/Activiti#1525]
### Bug

* When  java.lang.Error like StackOverflow  is throwen, database operation until error occurrence is committed.

### Cause

* CommandContextInterceptor.class catches all exceptions and stores the caught exception in its own field.
* And when closing CommandContext in the finally clause, if an exception is saved in its own field, CommandContextInterceptor.class will rollback transaction.
* If it is not saved, CommandContextInterceptor.class will commit transaction.
* If java.lang.Error or more exceptions are thrown, there are no exceptions in their fields, so CommandContextInterceptor.class will commit transaction.

### Problem point

* https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/impl/interceptor/CommandContextInterceptor.java#L65

**Comment by daisuke-yoshimoto** [comment]
https://github.com/Activiti/Activiti/pull/1526

**Comment by Salaboy** [comment]
@daisuke-yoshimoto ok.. I think that I understand what was the problem. 
It all comes down to: 
-    } catch (Exception e) {
+    } catch (Throwable e) {

I tend to agree that even rare and obscure Errors might happen and we want to catch them to make sure that the transaction gets rollbacked. 
I do approve this PR and it should be merged on monday. 
I will delegate this review to @erdemedeiros who probably have some extra experience on this matter.

**Comment by daisuke-yoshimoto** [comment]
Thanks for merging the pull request. So, I close this issue.
https://github.com/Activiti/Activiti/pull/1526
