### ISSUE TITLE
Bug IntegrationEvents: Foreign Key is used by IntegrationEvents pointing to executions

### ISSUE THREAD

**Issue by Salaboy** [Activiti/Activiti#1531]
When trying to complete a process instance that participated in an integration sequence FK are being violated when the execution is deleted and the reference to the IntegrationEvent is still there which causes the following exception:
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: update or delete on table "act_ru_execution" violates foreign key constraint "act_fk_int_execution" on table "act_ru_integration"
  Detail: Key (id_)=(12020) is still referenced from table "act_ru_integration".
### Cause: org.postgresql.util.PSQLException: ERROR: update or delete on table "act_ru_execution" violates foreign key constraint "act_fk_int_execution" on table "act_ru_integration"
  Detail: Key (id_)=(12020) is still referenced from table "act_ru_integration".

**Comment by Salaboy** [comment]
@erdemedeiros this is a serious problem that we need to fix. I think that you might be able to cascade the deletion of integration events related to execution Ids when process instances (or the execution ends) In this way, the integration events table will be automatically cleaned up when process instances are finished. Please take a look at these as soon as possible because this blocks all the connectors work.

**Comment by erdemedeiros** [comment]
@Salaboy Indeed, not deleting the integration event entries are bigger problem than we though initially (not only a problem related to the number of entries on that table). We could automatically delete the entries using the delete cascade approach, but then putting a [state on in the integration context](https://github.com/Activiti/Activiti/issues/1515) does not make a lot of sense. It's probably better use the same approach that we are using for audit and query to track the changes.
I'll update the algorithm to delete the entries once the integration result has arrived.

**Comment by Salaboy** [comment]
@erdemedeiros totally the state doesn't matter if they are going to be deleted. The next step for this task is to expose the pending ones via a rest endpoint for admins to check the pending ones details.
