### ISSUE TITLE
Get bamboo to check for refs to feature versions in develop branch

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1535]
To use a match and check dependencies as well as pom version. Maybe a regex search like the one we already have in the release process could do it.

**Comment by ryandawsonuk** [comment]
A regex that would match to a feature version such as 7-201711-EA-daisuke_1534_process_def_key-SNAPSHOT would be:

7-[0-9]{6}-EA-.*-SNAPSHOT

This would only match feature versions.

**Comment by ryandawsonuk** [comment]
Would be good to do a general search for that string above in pom files but for the meantime I've updated the jobs for non-example repos to do a check on the top-level POM version in develop branch and if it detects that the version is not of the develop format then the job fails and outputs "POM version in develop branch does not match expected format of 7-[0-9]{6}-EA-SNAPSHOT".

**Comment by Salaboy** [comment]
@ryandawsonuk @erdemedeiros can we close this now?

**Comment by ryandawsonuk** [comment]
I would like to be able to search all poms - currently it just checks the root pom.

**Comment by Salaboy** [comment]
@ryandawsonuk ok.. moving to the next milestone.

**Comment by ryandawsonuk** [comment]
Have got it to do it now with this block

    if [ ! -z `grep -lr '<version>7-.*-EA-.*-SNAPSHOT</version>' pom.xml **/*pom.xml` ]; 
    then
        echo "Feature version reference found in develop"
        echo `grep -lr '<version>7-.*-EA-.*-SNAPSHOT</version>' pom.xml **/*pom.xml`
        exit 1
    else
        echo "building develop version"
    fi
