### ISSUE TITLE
value too long error in audit when using UUIDs

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1538]
This was the bugfix that switched to UUIDs:

https://github.com/Activiti/activiti-cloud-runtime-bundle-service/commit/0fb5d6b004dabdf6f343d71b07169281f36b1f14

With this UUIDs have to be turned off explicitly using spring.activiti.useStrongUuids=false

Error we then see in the JPA Audit serivce is 

Caused by: org.h2.jdbc.JdbcSQLException: Value too long for column "TASK VARCHAR(255)": "'{""id"":""a320e46b-be37-11e7-9a7a-0a586460015a"",""name"":""Perform action"",""createdDate"":1509453182721,""priority"":50,""processDefiniti... (266)"; SQL statement:
insert into process_engine_event_entity (application_name, event_type, execution_id, process_definition_id, process_instance_id, timestamp, task, type, id) values (?, ?, ?, ?, ?, ?, ?, 'TaskCreatedEvent', ?) [22001-193]

the whole json description of a task is recorded in the task column of the process_engine_event_entity table but it only has 255 chars for all that json - the UUID change may have exposed this but we were probably always going to hit it eventually. Solution probably something like https://github.com/jpmorganchase/cakeshop/blob/master/cakeshop-api/src/main/java/com/jpmorgan/cakeshop/model/Event.java#L39
Need to recreate it in a test

**Comment by ffazzini** [comment]
Tested the change on minikube, no errors from api and in audit logs

**Comment by ryandawsonuk** [comment]
Still getting this error in docker-compose

**Comment by erdemedeiros** [comment]
The last fix missed [TaskAssignedEventEntity](https://github.com/Activiti/activiti-cloud-audit-service/blob/develop/activiti-cloud-services-audit/activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/events/TaskAssignedEventEntity.java#L33).

**Comment by Salaboy** [comment]
this is high priority for December release.

**Comment by ffazzini** [comment]
Added the fix using @Lob also to TaskAssignedEventEntity.
The error now disappeared from logs testing with docker-compose.

I followed the testing steps indicated by @erdemedeiros : 

1. get process definitions
2. start process
3. get tasks
4. claim task
4. get events
