### ISSUE TITLE
foreign key constraint failure in query service

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1539]
Run any full setup from activiti-cloud-examples. Start a process instance. The query module receives the event but does not create a record as it hits the error:

 Referential integrity constraint violation: "FK8OVY657S7TUS1IDVJOLXQB2SJ: PUBLIC.VARIABLE FOREIGN KEY(PROCESS_INSTANCE_ID) REFERENCES PUBLIC.PROCESS_INSTANCE(PROCESS_INSTANCE_ID) ('a31c5085-be37-11e7-9a7a-0a586460015a')"; SQL statement:
insert into variable (id, create_time, execution_id, last_updated_time, name, process_instance_id, task_id, type, value) values (null, ?, ?, ?, ?, ?, ?, ?, ?) [23506-193]

Seems the VariableCreatedEvents are consistently coming before the ProcessStartedEvent as it's always this foreign key and that's also the order we see in the audit log.

**Comment by ryandawsonuk** [comment]
I found I can turn off the foreign keys but only by using a deprecated hibernate annotation (seems hibernate want us to use a jpa annotation but they've not fixed a bug that necessitates the hibernate-specific annotation for a bidirectional association - https://stackoverflow.com/questions/41729709/how-do-i-disable-hibernate-foreign-key-constraint-on-a-bidirectional-association)

**Comment by erdemedeiros** [comment]
Hi @igdianov, did you manage to make some progress on that? We are going to release next week, just wanted to know if this can be included in the release or not.

Thanks

**Comment by Salaboy** [comment]
@igdianov any progress on that?

**Comment by ryandawsonuk** [comment]
We are still with the stopgap measure - the deprecated hibernate annotation is still in the code https://github.com/Activiti/activiti-cloud-query-service/blob/develop/activiti-cloud-services-query/activiti-cloud-services-query-model/src/main/java/org/activiti/cloud/services/query/model/ProcessInstance.java#L53

**Comment by Salaboy** [comment]
@ryandawsonuk @igdianov @erdemedeiros we need to fix this for beta1, any suggestions? can someone take the lead?

**Comment by Salaboy** [comment]
It didn't make beta1, so we need to review for beta2

**Comment by ryandawsonuk** [comment]
This is no longer using the hibernate annotation https://github.com/Activiti/activiti-cloud-query-service/blob/develop/activiti-cloud-services-query/activiti-cloud-services-query-model/src/main/java/org/activiti/cloud/services/query/model/ProcessInstanceEntity.java#L81
and from checking postman we are getting the variables on the process instance in query without error. We've a pending PR that will add an acceptance test that covers variables set when starting an instance
