### ISSUE TITLE
move to very latest keycloak version

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1540]
We're on 3.3.0.CR2 in our client libraries. We've not yet updated the docker image but it should work with 3.3.0.CR2 as we've used our client libraries against jhipster which is using 3.3.0.CR2. Keycloak have since released 3.3.0.Final which is probably the same as 3.3.0.CR2. We should update our keycloak.version in root pom of activiti-cloud-build and in  activiti-cloud-sso-idm docker image and test all works in cloud-examples (esp getTasks endpoint).

**Comment by Salaboy** [comment]
@ryandawsonuk what is the status of this ?

**Comment by ryandawsonuk** [comment]
Open. We did an update to get things working for jhipster when working with Antonio but there was then a keycloak release just after that so we're not on the very latest.

**Comment by ryandawsonuk** [comment]
Currently have it working through postman but get the invalid parameter redirect_uri issue through browser. Probably means I need to build adapter again.

**Comment by Salaboy** [comment]
moved to December then.

**Comment by ryandawsonuk** [comment]
Actually seems the issue I hit is not related to the adapter. I'm now seeing this problem on the latest images and this PR is not incorporated in them. Something else must have changes to break this. Strange as it was working about a week ago as @mteodori was hitting endpoints through the browser.

**Comment by ryandawsonuk** [comment]
Actually demo UI hits a cors problem with keycloak versions above 3.2.0 - https://github.com/Activiti/Activiti/issues/1595. I would expect it to at least work with 3.3.0 as our adapter was built against 3.4.0.CR1-SNAPSHOT

**Comment by ryandawsonuk** [comment]
Actually demo UI hits a cors problem with keycloak versions above 3.2.0 - #1595. I would expect it to at least work with 3.3.0 as our adapter was built against 3.4.0.CR1-SNAPSHOT. For the meantime I've reverted the keycloak version in the docker image back to 3.2.0.Final
