### ISSUE TITLE
Zipkin + Sleuth research and integration for tracing and logging

### ISSUE THREAD

**Issue by Salaboy** [Activiti/Activiti#1546]
https://cloud.spring.io/spring-cloud-sleuth/

https://piotrminkowski.wordpress.com/2017/04/05/part-2-creating-microservices-monitoring-with-spring-cloud-sleuth-elk-and-zipkin/

**Comment by ffazzini** [comment]
We managed to get a zipkin server running on minikube and all application services communicate with zipkin via sleuth(no discovery eureka as recommended).

To build the zipkin image we are using fabric8 deployment descriptor, we had to change the file a bit to include minikube nodeport for zipkin service, and fix something on the mysql-data persistent volume that was giving unmount errors.

**Comment by ryandawsonuk** [comment]
We should keep a note that the persistent volume config we have now works on minikube and doesn't seem to work on AWS

**Comment by Salaboy** [comment]
@ffazzini what is the status of this issue? should we close it as this was included for our main services?

**Comment by ffazzini** [comment]
Yes sure
