### ISSUE TITLE
Automatically activate sign profile during the release

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#1548]
Update the profile `sign` to be automatically activated when a release is performed:
```
<profile>
      <id>sign</id>
      <activation>
         <property>
            <name>performRelease</name>
            <value>true</value>
        </property>
      </activation>
...
</profile>
```
*Note:* the property `performRealese` will be automatically set to `true` by calling `mvn jgitflow:release-finish`.

**Comment by erdemedeiros** [comment]
Related PRs:
https://github.com/Activiti/activiti-build/pull/12
https://github.com/Activiti/Activiti/pull/1579
https://github.com/Activiti/activiti-cloud-build/pull/10
https://github.com/Activiti/activiti-cloud-query-service/pull/6
https://github.com/Activiti/activiti-cloud-audit-service/pull/12
https://github.com/Activiti/activiti-cloud-runtime-bundle-service/pull/16
https://github.com/Activiti/activiti-cloud-service-common/pull/9
https://github.com/Activiti/activiti-cloud-process-model-service/pull/3
https://github.com/Activiti/activiti-cloud-connectors/pull/4

**Comment by Salaboy** [comment]
@erdemedeiros can we close this one now?
