### ISSUE TITLE
Update release Job to use Maven 3.x task instead of Script task

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#1549]
Using the `Script` Bamboo task instead of `Maven 3.x`one seems to make the signature  of artefacts fails.

In addition, the release job **must use static agents** as `GPG` is not installed in the elastic agents.

**Comment by ryandawsonuk** [comment]
@erdemedeiros discovered that we don't seem to need this if we set  -Dgpg.homedir=${HOME}/.gnupg - but there is currently a problem with the gpg secret in bamboo so not able to fully test right now.

**Comment by ryandawsonuk** [comment]
gpg key issue resolved and released successfully using script tasks so don't need to do this.
