### ISSUE TITLE
Review dependency management properties

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#1550]
We need to review the value of the properties used inside the dependency management section to be sure that the development  process is not painful when the changes implies only one repository.
A possible solution would be having one property by repository.

**Comment by Salaboy** [comment]
@erdemedeiros what is the status of this issue? We did a great deal of this for this release. Can we open a more specific one?

**Comment by erdemedeiros** [comment]
This seems to be no longer necessary after the pom refactoring done by @mteodori.
