### ISSUE TITLE
Spring Rest Docs for our Audit services

### ISSUE THREAD

**Issue by lucianoprea** [Activiti/Activiti#1551]

**Comment by Salaboy** [comment]
@lucianoprea @erdemedeiros what is the status of this issue?

**Comment by Salaboy** [comment]
@lucianoprea @erdemedeiros please close or move to 12-2017 depending on the current state of this issue.

**Comment by lucianoprea** [comment]
@Salaboy the problem here was with the authorization. I tried to write tests in order to add spring rest docs but I couldn't solve the problem of injecting an auth token for my user and I was being redirected to the login in tests.

**Comment by Salaboy** [comment]
@erdemedeiros it will be great if you can spend some time looking at how to fix @lucianoprea problem to enable him to move forward

**Comment by Salaboy** [comment]
@lucianoprea what is the status of this one?

**Comment by lucianoprea** [comment]
I'll start working on it.
