### ISSUE TITLE
Read auth config from property file

### ISSUE THREAD

**Issue by ffazzini** [Activiti/Activiti#1552]
At the moment the our SecurityConfig class in the common service sets the policies for the authentication. 

We would like to set this behaviour via property file in each individual service, for instance
we already have this auth config here:
https://github.com/Activiti/activiti-cloud-audit/blob/master/src/main/resources/application.properties
but these configs are either overriden(by SecurityConfig) or not taken in account.

Ideally we would like to specify auth policy configs only via property files.

**Comment by ryandawsonuk** [comment]
We also want to move actuator dependency into a new monitoring dependency.
