### ISSUE TITLE
Deploy via Rest-API always fails with "Multipart request is required"

### ISSUE THREAD

**Issue by hoax** [Activiti/Activiti#1553]
I have trouble to deploy a process definition using the REST API. First I thought it is because of my Javascript code but even with curl it won't work:

```
$ curl -v --basic --user admin:admin -F file=@assignTaskToUser.bpmn20.xml http://localhost:8080/activiti-app/api/repository/deployments`
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
* Server auth using Basic with user 'admin'
> POST /activiti-app/api/repository/deployments HTTP/1.1
> Host: localhost:8080
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.52.1
> Accept: */*
> Content-Length: 3357
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------3a84c849f7353c4d
> 
< HTTP/1.1 100 Continue
< HTTP/1.1 400 Bad Request
< Server: Apache-Coyote/1.1
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Thu, 09 Nov 2017 10:23:35 GMT
< Connection: close
< 
* Curl_http_done: called premature == 0
* Closing connection 0
{"message":"Bad request","exception":"Multipart request is required"}
```

What I found out is, that the exception gets thrown in _activiti-rest/src/main/java/org/activiti/rest/service/api/repository/DeploymentCollectionResource.java#uploadDeployment_. Here the request is expected to be of MultipartHttpServletRequest but actually is of type org.springframework.security.web.servletapi.HttpServlet3RequestFactory$Servlet3SecurityContextHolderAwareRequestWrapper.

I'm using Activiti 6.0.0 with tomcat 7.075.

Does anyone know this problem and/or how to resolve it?

**Comment by hoax** [comment]
Found the bug. Fix: copy method _multipartResolver()_ from _org.activiti.app.servlet.AppDispatcherServletConfiguration_ to _org.activiti.app.servlet.ApiDispatcherServletConfiguration_.

**Comment by hoax** [comment]
Found the bug. Fix: copy method _multipartResolver()_ from _org.activiti.app.servlet.AppDispatcherServletConfiguration_ to _org.activiti.app.servlet.ApiDispatcherServletConfiguration_.

**Comment by Salaboy** [comment]
@hoax can you send a PR with the fix?

**Comment by Salaboy** [comment]
@hoax you there?

**Comment by hoax** [comment]
sorry, I was assigned to another project ... I just pushed a fix for the missing file upload property

**Comment by Salaboy** [comment]
@hoax can you paste the link to where the fix is?

**Comment by hoax** [comment]
https://github.com/Activiti/Activiti/pull/1562/commits/64473230884ae36ee261950268ec3ea0787b1649

**Comment by Salaboy** [comment]
@hoax thanks a lot. @balsarori is going to merge it.

**Comment by Salaboy** [comment]
PR merged, closing this issue.
