### ISSUE TITLE
Fix swagger for audit and query services

### ISSUE THREAD

**Issue by ffazzini** [Activiti/Activiti#1555]
At the moment we have only this exposed via the api-docs, it should have all info instead:
```json
{
    "swagger": "2.0",
    "info": {
        "description": "Api Documentation",
        "version": "1.0",
        "title": "Api Documentation",
        "termsOfService": "urn:tos",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0"
        }
    },
    "host": "activiti-cloud-sso-idm-kub:30080",
    "basePath": "/audit/"
}
```
Below there are the changes to fix the problem on our side, but
unfortunately we will need this to be fixed first in springfox, I am watching the issue:
https://github.com/springfox/springfox/issues/1957

#### Maven dependency in activiti-cloud-build
```xml
<dependency>
     <groupId>io.springfox</groupId>
     <artifactId>springfox-data-rest</artifactId>
     <version>${springfox.version}</version>
</dependency>
```
#### Maven dependency in both audit and mongo starters:
```xml
<dependency>
     <groupId>io.springfox</groupId>
     <artifactId>springfox-data-rest</artifactId>
</dependency>
```
#### Add the following annotation above the SwaggerConfig class in the audit-service:
```java
@Import({springfox.documentation.spring.data.rest.configuration.SpringDataRestConfiguration.class})
```

**Comment by ffazzini** [comment]
https://github.com/spring-cloud/spring-cloud-netflix/issues/856

**Comment by Salaboy** [comment]
moving to Jan to recheck with latest spring updates.

**Comment by ryandawsonuk** [comment]
Now putting controllers back so that we get swagger - https://github.com/Activiti/activiti-cloud-audit-service/pull/17

Suggest we take controllers out again when springfox update

**Comment by erdemedeiros** [comment]
Solved using controllers.
