### ISSUE TITLE
activiti-cloud-service-common is dragging activiti-engine plus all transitive dependencies to query, audit and connectors

### ISSUE THREAD

**Issue by Salaboy** [Activiti/Activiti#1557]
The lack of APIs is hurting us really bad here. 
Query, Audit and Connectors depends on Service Common that implements one Engine interface. 
We need to extract this interfaces in a separate module (ie. activiti-process-api) to make sure that we don't drag all the modules as transitive dependencies to services that will not use the engine at all.

**Comment by ryandawsonuk** [comment]
Didn't we resolve this one already?

**Comment by Salaboy** [comment]
Did we? we need to check to confirm

**Comment by ryandawsonuk** [comment]
Seems the engine dependency is still there in query-service:

[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ activiti-cloud-services-query-rest ---
[INFO] org.activiti.cloud:activiti-cloud-services-query-rest:jar:7-201801-EA-SNAPSHOT
[INFO] +- org.activiti.cloud:activiti-cloud-services-api:jar:7-201801-EA-SNAPSHOT:compile
[INFO] |  +- org.activiti:activiti-engine:jar:7-201801-EA-SNAPSHOT:compile

**Comment by Salaboy** [comment]
this must be done in march before beta

**Comment by Salaboy** [comment]
New Runtime APIs should break all these dependency nightmares

**Comment by Salaboy** [comment]
@ryandawsonuk @erdemedeiros closing this because it was fixed by the new API in Beta1
