### ISSUE TITLE
Update release job to set activiti.version and version.activit.cloud to the next snapshot

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#1561]
Currently those properties are being set to ${project.version}, they need to be set to the next SNAPSHOT instead.

**Comment by ryandawsonuk** [comment]
sed -i -E "s|<version.activiti>\${project.version}<\/version.activiti>|<version.activiti>$NEXT_SNAPSHOT<\/version.activiti>|" pom.xml
sed -i -E "s|<version.activiti.cloud>\${project.version}<\/version.activiti.cloud>|<version.activiti.cloud>$NEXT_SNAPSHOT<\/version.activiti.cloud>|" pom.xml

**Comment by ryandawsonuk** [comment]
These sed commands work locally but they don't do the replace in the bamboo job.

**Comment by Salaboy** [comment]
@ryandawsonuk is this done now? or should we move it to December milestone?

**Comment by ryandawsonuk** [comment]
Bamboo does seem to be happy with this form:

sed -i -E "s|<version.activiti>.*project.version.*<\/version.activiti>|<version.activiti>$NEXT_SNAPSHOT<\/version.activiti>|" pom.xml
sed -i -E "s|<version.activiti.cloud>.*project.version.*<\/version.activiti.cloud>|<version.activiti.cloud>$NEXT_SNAPSHOT<\/version.activiti.cloud>|" pom.xml

So have switched jobs to use that.
