### ISSUE TITLE
How run In Eclipse?

### ISSUE THREAD

**Issue by sandipJava** [Activiti/Activiti#1564]
Hello Members,
   I totally new in Activiti, I dont know how run in eclipse this example, pls show me right way to run this example in Eclipse or Intellij

**Comment by Salaboy** [comment]
hi @sandipJava Activiti is a framework so yo usually create applications and embed it inside. You don't run it. If you refer to the web application then you need to deploy that in tomcat. In any case, this is no place to ask questions about how to use the project. Please use the forums and the check the documentation in our website.
