### ISSUE TITLE
"Could not upload file" Error in Activit Admin 6.x

### ISSUE THREAD

**Issue by gjackson12** [Activiti/Activiti#1565]
I am using Activiti 6. I am attempting to upload a .bpmn20.xml file for a deployment however each time I attempt to I receive an error that says, "Could not upload this file." 

Any thoughts on what the problem could be? (I created the xml file via the Activiti-app itself, so the format should be fine)

**Comment by Salaboy** [comment]
@gjackson12 hi there.. that is a really interesting assumption :) 
You need to take a look at the server logs to see what the issue is. Is there anyway that you can share your process definition so we can check for correctness?
