### ISSUE TITLE
Audit HAL REST API self link is broken

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#1570]
In the example bellow the `self` link is pointing to `http://localhost:8080/audit/v1/processStartedEventEntity/27`, but it should be `http://localhost:8080/audit/v1/events/27`
``` instead.
{
    "id": 27,
    "timestamp": 1511431447981,
    "eventType": "ProcessStartedEvent",
    "executionId": "28",
    "processDefinitionId": "MQServiceTaskProcess:1:7",
    "processInstanceId": "23",
    "applicationName": "rb-my-app",
    "_links": {
        "self": {
            "href": "http://localhost:8080/audit/v1/processStartedEventEntity/27"
        },
        "processStartedEventEntity": {
            "href": "http://localhost:8080/audit/v1/processStartedEventEntity/27"
        }
    }
}
```

When fixing this bug, make sure that there is test covering this link.

**Comment by erdemedeiros** [comment]
The fix might be related to the class `EventsRelProvider`.

**Comment by Salaboy** [comment]
@mteodori can we check the status of this? Was this fixed or is it still an issue with the config that we are using?

**Comment by ffazzini** [comment]
@Salaboy i have recently done a temp change to the audit api : from spring-data-rest to controllers to fix swagger.

**Comment by ryandawsonuk** [comment]
@mteodori can we check the status of this? Was this fixed or is it still an issue with the config that we are using?

**Comment by erdemedeiros** [comment]
I guess that is fixed now that we switched back to controllers, but it's probably better to add some test on that. Maybe do a deeper check on  tests of [EventsRepositoryIT](https://github.com/Activiti/activiti-cloud-audit-service/blob/develop/activiti-cloud-services-audit/activiti-cloud-services-audit-jpa/src/test/java/org/activiti/cloud/services/audit/repository/EventsRepositoryIT.java).

**Comment by ffazzini** [comment]
true @erdemedeiros 
Let's see if we can do anything on query service as well?

**Comment by Salaboy** [comment]
@erdemedeiros should we close this one? and report a new one for query?

**Comment by Salaboy** [comment]
@erdemedeiros @ffazzini what is the status of this one?

**Comment by ffazzini** [comment]
In query we put controllers back to fix swagger, hal format is equivalent to RB so I believe query service is fine. Closing this.
