### ISSUE TITLE
rename properties used for keycloak access

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1572]
e.g. keycloakadminclientapp
should be keycloak-admin-client-app

Will mean updating all of the repos - activiti-cloud-query, activiti-cloud-audit etc.

Would also be good if we could update KeycloakInstanceWrapper in activiti-cloud-service-common to use a configurationproperties class

**Comment by ryandawsonuk** [comment]
To test this I built all the above projects, including running their tests, and checked from activiti-cloud-examples using the images that had been built.

**Comment by Salaboy** [comment]
@ryandawsonuk is this done already? Which one is missing? let's start closing things :)

**Comment by ryandawsonuk** [comment]
The PR on activiti-cloud-process-model-service is still open. Waiting for the version of that service to be upgraded to current.

**Comment by Salaboy** [comment]
Ok I think that you can close this issue then. I will review with @constantin and include those changes in develop
