### ISSUE TITLE
I give implemention to runtime process clone, just code split.

### ISSUE THREAD

**Issue by xiaohelong** [Activiti/Activiti#1573]
I give implemention to runtime process clone, just code split.
requirement:
in manufacture, order need to split, so need to clone process and suspend parent process instance ,but I don't want lose info(before this,I just start a new process instance,then jump ,but a lot of problem and information lose)
So I spend sometime to implement a solution to Process Clone,and done it .
paste here ,I hope official implement and give a api.
https://github.com/xiaohelong/ActivitiOrFlowableProcessInstanceCloneSolution
thanks a lot ,there has a detail documentation about it.

**Comment by Salaboy** [comment]
@xiaohelong hi there. This looks cool. We can definitely look into adding this to our source code. It will be interesting if you can translate the documentation to english and then help us with the new infrastructure that we are building. This code might live inside the activiti/activiti repo, but this feature should be exposed in our Runtime Bundles as well. Please get in touch with us via gitter so we can discuss how to move this contribution forward: https://gitter.im/Activiti/Activiti7?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by xiaohelong** [comment]
ok,I got and will translate quickly. then paste here,thanks
