### ISSUE TITLE
List of deployments does not accept sort option "deploytime"

### ISSUE THREAD

**Issue by verheyenkoen** [Activiti/Activiti#1574]
The [docs](https://www.activiti.org/userguide/#_list_of_deployments) state that you can sort the list of deployments (`GET repository/deployments`) by "deploytime".

However when I try this (in Activiti 5.18) I get the following response:
```
{"message":"Bad request","exception":"Value for param 'sort' is not valid, 'deploytime' is not a valid property"}
```

**Comment by daisuke-yoshimoto** [comment]
You must specify the sort key by camelcase.
deployTime

**Comment by verheyenkoen** [comment]
I see. Then the docs need an update I guess. 

Also the field in the results is "deploymentTime" which may be confusing.
