### ISSUE TITLE
Versions of images used in activiti-cloud-examples - how should they be set?

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1575]
Seems like we set them manually in master -

https://github.com/Activiti/activiti-cloud-examples/commit/4e568c6925d1051381e3c09936830abc617753a9

Should we have that automated upon release?

Also, what about runtime bundle? Do we want to point to a specific image for that and if so what image pull policy do we want? We should discuss.

**Comment by Salaboy** [comment]
master examples should point to latest release, 
develop examples should point to snapshots. 
For now we do it manually while testing the released artefacts. Not sure how we can automate this. but at least the repositories should reflect this policy.

**Comment by ryandawsonuk** [comment]
Yeah I had thought about automating this as part of the release process. But it's not so straightforward as the images won't be published until after the release. Maybe we just close this issue?
