### ISSUE TITLE
Re add compatibility mode for activiti 5 inside activiti 7 develop branch

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#1578]
We need to re-add removed functionality and schemas for supporting activiti 5 backwards compatibility

**Comment by Salaboy** [comment]
@balsarori we need a section in our gitbook that explains how to hook up a runtime bundle into an activiti 5 db and what is the expected result. I saw that there is an issue that is also recommending an improvement for that compatibility for customTypes during the migration process. Can you please keep track of that: https://github.com/Activiti/Activiti/issues/1346

**Comment by Salaboy** [comment]
@balsarori any chance that you can work on this on December? I'm moving this to Jan due the fact that there is not much time left. But please update the status on this issue when you have time to look at this. It is becoming high priority for us.

**Comment by salaboy** [comment]
@balsarori I am closing this because we already solved this
