### ISSUE TITLE
Upgrade to Spring Boot 2.0.0.M6

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#1585]
- Spring Boot -> 2.0.0.M6
- Spring Cloud version -> Finchley.M4

**Comment by erdemedeiros** [comment]
Related PRs:
             https://github.com/Activiti/activiti-build/pull/13
             https://github.com/Activiti/activiti-cloud-build/pull/13
             https://github.com/Activiti/activiti-cloud-runtime-bundle-service/pull/17
             https://github.com/Activiti/activiti-cloud-query-service/pull/7
             https://github.com/Activiti/activiti-cloud-audit/pull/15
             https://github.com/Activiti/activiti-cloud-audit-mongodb/pull/4
             https://github.com/Activiti/activiti-cloud-examples/pull/30
             https://github.com/Activiti/activiti-cloud-gateway/pull/13
             https://github.com/Activiti/activiti-cloud-runtime-bundle/pull/12/files
             https://github.com/Activiti/activiti-cloud-query/pull/13

**Comment by Salaboy** [comment]
@erdemedeiros can this be closed?

**Comment by erdemedeiros** [comment]
All the PRs are merged now.
