### ISSUE TITLE
Update Spring versions

### ISSUE THREAD

**Issue by Salaboy** [Activiti/Activiti#1593]
Spring (5.0.2.Release), Spring Boot  (2.0.0.M7) and Spring Cloud (Finchley M5) and Spring Cloud Stream (Elmhurst.M3)

**Comment by Salaboy** [comment]
https://github.com/Activiti/activiti-build/pull/14

**Comment by Salaboy** [comment]
https://github.com/Activiti/activiti-cloud-build/pull/14

**Comment by erdemedeiros** [comment]
The plugin version should be updated as well accros the docker image repositories.

**Comment by Salaboy** [comment]
Is the plugin version M7 as well?

**Comment by erdemedeiros** [comment]
Yes, it's aligned to the spring boot version.

**Comment by Salaboy** [comment]
@erdemedeiros can you take care of creating the PRs for this? and probably directly merge the change to those repositories, we are not releasing those anyway.

**Comment by erdemedeiros** [comment]
PRs to upgrade the version of Spring Boot Maven Plugin:
https://github.com/Activiti/activiti-cloud-audit/pull/18
https://github.com/Activiti/activiti-cloud-query/pull/15
https://github.com/Activiti/activiti-cloud-audit-mongodb/pull/6
https://github.com/Activiti/activiti-cloud-examples/pull/55
https://github.com/Activiti/example-runtime-bundle/pull/5
