### ISSUE TITLE
Demo UI gives CORS issue if keycloak version increased above 3.2.0

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1595]
Affecting the demo JS app in activiti-cloud-examples. Error in browser is:

Failed to load http://activiti-cloud-sso-idm:8180/auth/realms/springboot/protocol/openid-connect/token: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:3000' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

If you use 7-201711-EA version of activiti-cloud-sso-idm then all works fine. Only with the new keycloak version do we get the error. We are using the 3.4.0 libraries in our code but if we update the keycloak version above 3.2.0 in the keycloak docker image (without changing anything else) then we get hit this CORS problem.

As it happens we do have a wildcard set in the gateway (https://github.com/Activiti/activiti-cloud-gateway/blob/develop/src/main/java/org/activiti/cloud/gateway/GatewayApplication.java#L37) but this goes wrong before that point - the demo client hasn't made any calls to gateway when it fails. Here the problem seems to be entirely between the keycloak server and demo JS client.

**Comment by ryandawsonuk** [comment]
The JS client implementation is based on that from http://slackspace.de/articles/authentication-with-spring-boot-angularjs-and-keycloak/

Looking back at that, I wonder if the * referred to in the error is coming from https://github.com/Activiti/activiti-cloud-sso-idm/blob/master/springboot-realm.json#L385

**Comment by ryandawsonuk** [comment]
If I change the * to 'http://localhost:*' then the error becomes:

Failed to load http://activiti-cloud-sso-idm:8180/auth/realms/springboot/protocol/openid-connect/token: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

**Comment by vrrenga123** [comment]
this issue still reproducible in keycloak-4.3.0.Final version
