### ISSUE TITLE
json converter doesn't convert localization information

### ISSUE THREAD

**Issue by alirezamirian** [Activiti/Activiti#1596]
Localized **name** and **description** (documentation) can be saved [for user tasks and subprocesses][1] in specific extension elements. Currently BpmnJsonConverter doesn't convert these extension element to/from json.

[1]: https://github.com/Activiti/Activiti/blob/e30e7058ab3ead70133692e0f91c22dc7613e10b/modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/deployer/BpmnDeployer.java#L315

**Comment by Salaboy** [comment]
@balsarori can you please review and see if we can merge this?

**Comment by Salaboy** [comment]
@balsarori any chance that you can review this before the end of this week?

**Comment by Salaboy** [comment]
@alirezamirian I will close this, but if you can send a PR to develop that will be great.

**Comment by alirezamirian** [comment]
@salaboy Sorry, but I've already submitted a PR. Maybe they are not correctly linked together: #1597

**Comment by Salaboy** [comment]
@alirezamirian that's targeting 6.x not develop. Do you mind creating one targeting the develop branch as well? So we make sure that your fix is included in our Jan Early Access release for activiti 7?

**Comment by alirezamirian** [comment]
You're right. Soon I will submit another PR targeting `develop` branch.

**Comment by Salaboy** [comment]
@alirezamirian thanks a lot!

**Comment by alirezamirian** [comment]
I just submitted [the PR](#1736).
