### ISSUE TITLE
Do we still need the maven example within activiti-cloud-examples? Why not say to clone instead?

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1599]
In activiti-cloud-examples we have an entry in application-docker-compose that says:

      image: rb-my-app

This is to fit with the maven example. But we could change it to:

       image: activiti/example-runtime-bundle

And then we could update the instructions to say that if you want to build with maven then clone that repo first and build from there.

**Comment by Salaboy** [comment]
@ryandawsonuk yes totally agree.. let's change that. We need to remove the docker and maven runtime bundle templates from our examples repo.

**Comment by Salaboy** [comment]
done, no need for this templated projects anymore.
