### ISSUE TITLE
Add dependencies vulnerability check for Activiti engine

### ISSUE THREAD

**Issue by mteodori** [Activiti/Activiti#1601]
Integrate a maven plugin to check for dependencies with vulnerabilities and eventually fail the build limited to the Activiti engine.

The following options are available:
- https://github.com/victims/maven-security-versions
- https://jeremylong.github.io/DependencyCheck/

**Comment by Salaboy** [comment]
@mteodori does this found anything that we might consider a vulnerability or old dependency? I can see the update to batik groupId, but besides that, is there something else that we need to be aware?
