### ISSUE TITLE
Task query with variable  restricting data at 20000 causing incomplete task data

### ISSUE THREAD

**Issue by vgaur** [Activiti/Activiti#1606]
Hi,
In `_TaskEntityManager.findTasksAndVariablesByQueryCriteria()_` we are restricting data size by setting taskQuery.setMaxResults(). This causes the last task to be extracted without full process variables.
Even if we use pagination, this issue remains.

We should remove the last task just to make sure we send out the complete task data.

**Comment by Salaboy** [comment]
@vgaur can you please specify the version that you are using? 
I think that this problem was fixed already.

**Comment by vgaur** [comment]
@Salaboy I am using 5.19.0. I checked the latest repo code and found that instead of 20K now we can set the limit in process config.
The issue will still remain, because we are not using database pagination. 
Am I missing something ?

**Comment by Salaboy** [comment]
@vgaur Have you tried 5.22? I think that issue was fixed there already. Which branch did you checked?
@balsarori is that correct? or it is in 5.x but not released?

**Comment by balsarori** [comment]
@vgaur can try latest release (5.22). Also, if you could provide a unit test that we can use to reproduce the issue it will be great.

**Comment by smrobinson** [comment]
I also ran into this limit while paginating. I tried 5.22 but that did not change the behavior (I'm not sure we can go up to 6.0 but will try that next if needed.)

**Comment by Salaboy** [comment]
@smrobinson we appreciate that.

**Comment by daisuke-yoshimoto** [comment]
@vgaur @Salaboy @balsarori 

This issue is not fixed in 5.22.

But, I added the alternative solution in 5.22. Please check this url.
https://github.com/Activiti/Activiti/pull/891

**Comment by smrobinson** [comment]
Thanks for the reference to #891.

I looked at the code modifications we would need to migrate to 6.x and it is too much for the sake of an experiment - so FYI I won't be trying 6.x.

**Comment by vgaur** [comment]
I tried 6.x and the issue seems to be fixed now. Thanks a lot !!!
