### ISSUE TITLE
Possible bug in editor-controller.js - Canvas resizers getting positioned incorrectly

### ISSUE THREAD

**Issue by piyushshri** [Activiti/Activiti#1610]
# HOW TO REPRODUCE
1. Open a new model
2. Click on the default Start Event and end an End Event by clicking in the quick menu icon (Do not click anywhere else, keep the new quick menu of the End Event visible)
3. Click on the left or right canvas resizers (canvas_resize_indicator)

The canvas resize indicators get repositioned to the center of the canvas.

# THE CAUSE
This is happening because in editor-controller.js at line [225](https://github.com/piyushshri/Activiti/blob/de8e347b012829bfc811cfbee47b5b700799797c/modules/activiti-ui/activiti-app/src/main/webapp/editor/editor-app/editor-controller.js#L225) , `canvas[0].children[1]` is not giving the full canvas, instead it is giving the delete button from the quick menu of the End Event. Therefore, `actualWidth` is getting incorrectly calculated which leads to incorrect value of `canvasLeft`. This pushes the resize indicators to the center.

The actual canvas is at `canvas[0].children[11]` . 

Please confirm if this is a bug.

**Comment by Salaboy** [comment]
It seems that this was merged and the PR closed as well. So I will close the issue, please write a comment if this is not correct.

**Comment by piyushshri** [comment]
@Salaboy No, I closed the pull request as my solution didn't completely solve the problem. I can work on the issue once a master/owner confirms that this is an actual bug.

**Comment by Salaboy** [comment]
@balsarori can you confirm that? if this is reproducible we will be happy to receive a fix from @piyushshri
