### ISSUE TITLE
Add known vulnerabilities Snyx badge to README

### ISSUE THREAD

**Issue by mteodori** [Activiti/Activiti#1615]
Add badge to README as documented in https://snyk.io/docs/badges/ on the following repos:
- [x] [Activiti](https://github.com/Activiti/Activiti)
- [x] [activiti-build](https://github.com/Activiti/activiti-build)
- [x] [activiti-cloud-audit](https://github.com/Activiti/activiti-cloud-audit)
- [x] [activiti-cloud-audit-mongodb](https://github.com/Activiti/activiti-cloud-audit-mongodb)
- [x] [activiti-cloud-audit-service](https://github.com/Activiti/activiti-cloud-audit-service)
- [x] [activiti-cloud-build](https://github.com/Activiti/activiti-cloud-build)
- [x] [activiti-cloud-connectors](https://github.com/Activiti/activiti-cloud-connectors)
- [x] [activiti-cloud-modeling-backend](https://github.com/Activiti/activiti-cloud-modeling-backend)
- [x] [activiti-cloud-org-service](https://github.com/Activiti/activiti-cloud-org-service)
- [x] [activiti-cloud-process-model-service](https://github.com/Activiti/activiti-cloud-process-model-service)
- [x] [activiti-cloud-query](https://github.com/Activiti/activiti-cloud-query)
- [x] [activiti-cloud-query-service](https://github.com/Activiti/activiti-cloud-query-service)
- [x] [activiti-cloud-registry](https://github.com/Activiti/activiti-cloud-registry)
- [x] [activiti-cloud-runtime-bundle](https://github.com/Activiti/activiti-cloud-runtime-bundle)
- [x] [activiti-cloud-runtime-bundle-service](https://github.com/Activiti/activiti-cloud-runtime-bundle-service)
- [x] [activiti-cloud-service-common](https://github.com/Activiti/activiti-cloud-service-common)

**Comment by Salaboy** [comment]
@mteodori can you take care of this? It shouldn't take that much time.

**Comment by mteodori** [comment]
@Salaboy ok for me, which repositories should I add it to besides engine?

**Comment by ryandawsonuk** [comment]
activiti-build
activiti-cloud-audit-mongodb
example-runtime-bundle
activiti-cloud-registry
activiti-cloud-runtime-bundle
activiti-cloud-app-service
activiti-cloud-audit
activiti-cloud-audit-service
activiti-cloud-build
activiti-cloud-connectors
activiti-cloud-org-service
activiti-cloud-modeling-backend
activiti-cloud-process-model-service
activiti-cloud-runtime-bundle-service
activiti-cloud-service-common
Activiti
activiti-cloud-query
activiti-cloud-query-service

**Comment by Salaboy** [comment]
just don't add it in activiti-cloud-app-service
all the others should have it.

**Comment by Salaboy** [comment]
@mteodori can you please close this asap?

**Comment by mteodori** [comment]
completed on all referenced repos
