### ISSUE TITLE
Fix actuator endpoint breaking change on M7

### ISSUE THREAD

**Issue by ffazzini** [Activiti/Activiti#1619]
In the M6 version of the Boot we were using /application/status

The status endpoint has been removed, so we will now use the /actuator/health as stated in the doc:
https://docs.spring.io/spring-boot/docs/2.0.0.M7/reference/html/production-ready-endpoints.html

It should be fine only updating those values in the kubernetes deployment descriptors

**Comment by ryandawsonuk** [comment]
Have merged https://github.com/Activiti/activiti-cloud-examples/pull/44
