### ISSUE TITLE
Create an env for docker images via terraform

### ISSUE THREAD

**Issue by ffazzini** [Activiti/Activiti#1620]
Following our discussion with Hussain, we want to try to deploy activiti 7 docker images on rancher via terraform. The objective is to have an environment up.
https://github.com/Alfresco/terraform-template-library

cc: @Salaboy

**Comment by Salaboy** [comment]
@ffazzini I would close this and open a new one for January to work on the AWS environments with KOPS

**Comment by ffazzini** [comment]
Ok
