### ISSUE TITLE
Activiti Cloud Example - Runtime Bundle App missing postgres driver

### ISSUE THREAD

**Issue by lucianoprea** [Activiti/Activiti#1636]
Trying to build locally the runtime bundle with `docker build -t rb-my-app .` from **docker-runtime-bundle** folder in **activiti-cloud-examples** repo will end up with an image that is missing the postgres driver and would not start.

The problem could be in the _download_assets.sh_ where the driver is downloaded.

**Comment by Salaboy** [comment]
@ryandawsonuk @erdemedeiros should we remove these maven and docker runtime bundle templates? I'm tempted to just create a yeoman generator for our projects.

**Comment by Salaboy** [comment]
@ryandawsonuk @erdemedeiros we might want to do this clean up right after releasing in Feb.

**Comment by Salaboy** [comment]
@lucianoprea @ryandawsonuk @erdemedeiros should we close this one? I think that we removed the project already.

**Comment by lucianoprea** [comment]
yes, this is no longer available in examples
