### ISSUE TITLE
Look at editorconfig to set up a config across IDEs

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1640]
http://editorconfig.org/

**Comment by daisuke-yoshimoto** [comment]
@ryandawsonuk 

It is better to check the code format with the status check at the pull request, not only formatting in the local development environment of each development member.

For example, can we use the following functions of Codacy?
https://blog.codacy.com/codacy-integrates-with-checkstyle-5780f95145a2

**Comment by mteodori** [comment]
@daisuke-yoshimoto I think we can have both, editorconfig checks basic editor stuff not the java syntax, still is very helpful as most of the editors do support it natively now
