### ISSUE TITLE
how to set TENATN_ID_ and CATEGORY_ info in activiti-app editor based on activiti 6.0.0

### ISSUE THREAD

**Issue by kingbacks** [Activiti/Activiti#1656]
Hi,
    thanks for activiti team, It is a great team, and activiti-app online editor is useful to me.
    but now, I got a question:how to set TENATN_ID_ and CATEGORY_ info when I publish the workflow? 
I don't see any location to set the value to TENANT_ID_ and CATEGORY_, help me, tks!

**Comment by balsarori** [comment]
Hi @kingbacks 
Thats not currently possible. Feel free to contribute this feature

**Comment by kingbacks** [comment]
thanks very much, I will try it. @balsarori
