### ISSUE TITLE
make mongo the default audit implementation

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1661]
We continue to find cases where the JPA implementation has columns which are too short. Elias has been using mongo for testing the trending topics twitter example and it seems to work. Seems to make sense that we make mongo the default.

We would just need to update the activiti-cloud-examples deployment descriptors and maybe the gitbook. I think it would also need to be added to the config server example.

**Comment by Salaboy** [comment]
@erdemedeiros @ryandawsonuk 
It sounds weird to me that the JPA impl doesn't work. Did you manage to find out when it breaks? 
Which kind of content is not being supported and when?

**Comment by ryandawsonuk** [comment]
Essentially we're getting permutations on https://github.com/Activiti/Activiti/issues/1538

Elias hit the problems again when hooking audit into trending-topics. We could try doing that again to get the specific errors.

**Comment by Salaboy** [comment]
We should do that as part of keep improving the example

**Comment by ryandawsonuk** [comment]
I think the current position is that JPA should remain the default implementation. So closing this and can reopen if this changes or anyone has information otherwise.
