### ISSUE TITLE
disable config server with a property so that we don't get warning and don't have to exclude in pom

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1662]
Ideally pass in property value as environment variable in deployment descriptor. See https://stackoverflow.com/questions/27569168/cannot-disable-spring-cloud-config-via-spring-cloud-config-enabledfalse

**Comment by constantin-ciobotaru** [comment]
PRs:
https://github.com/Activiti/activiti-cloud-examples/pull/58
https://github.com/Activiti/activiti-cloud-examples/pull/61
https://github.com/Activiti/activiti-cloud-audit/pull/19
https://github.com/Activiti/activiti-cloud-query/pull/16
https://github.com/Activiti/activiti-cloud-process-model-service/pull/6
https://github.com/Activiti/activiti-cloud-org-service/pull/4
https://github.com/Activiti/activiti-cloud-modeling-backend/pull/2
https://github.com/Activiti/activiti-cloud-runtime-bundle/pull/15
https://github.com/Activiti/activiti-cloud-registry/pull/7
