### ISSUE TITLE
add spring cloud contract tests back into process modeling

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1663]
We've tried using the stub runner (https://github.com/spring-cloud/spring-cloud-contract/tree/master/spring-cloud-contract-stub-runner) but found that travis wasn't able to find the producer just from the maven dependency and we would have to actually build the producer's project in our local maven. This is no good for travis as travis set up to just build one project and it would be complicated to change this and have travis find the correct version to build. But we believe this has been fixed in https://github.com/spring-cloud/spring-cloud-contract/commit/748e512f4d92d67dd6d40e994163788592e7b612 We need to find out when the fix will be released in a milestone. 

We'll also need to write a short script for the release. Since the consumer needs to have a pom reference to the producer, that dependency will have to be set during the release process before and after the release and this needs to be automated. So we want a script to run before release that replaces the -SNAPSHOT version with the next release version. But note that it must only do this for the version in dependency that the consumer has to the producer. The existing release script does something like this when it does:

sed -i -E "s|<version.activiti>.*-SNAPSHOT.*<\/version.activiti>|<version.activiti>\${project.version}<\/version.activiti>|" pom.xml

But we can't simply add another line with <version> instead of <version.activiti> as that would also put the project on a release version and jgitflow will only release a snapshot version. Our best bet is probably to use the maven versions plugin's use-releases goal with the includes parameter set to just find the producer project. The producer should be fed to the script as a command-line argument and we should only run this goal if the parameter is set so that it can also be run against other projects. Our pattern at the moment is to use the same release script for each project. See any of the PerformRelease tasks under https://bamboo.alfresco.com/bamboo/chain/admin/config/defaultStages.action?buildKey=ACT-AJ We'll need a small script initially that just does this part so that we can test it locally. Note you can locally set a project to a 'release' version and do mvn clean install to get the 'release' version into your local maven. This is actually the same situation as the release script faces as nothing enters maven central until the staging repository is manually promoted after the release (see https://docs.google.com/document/d/1RAWxqGJd2BEH6XB338utD1lk9F0G7xXhWklpGXUNiIY/edit#)

The version will also need to be set back to snapshot after the release but I think the script as it is will do that already.

**Comment by lucianoprea** [comment]
there is some work around this that requires some minor changes to have this working with new release of Spring Cloud [PR](https://github.com/Activiti/activiti-cloud-org-service/pull/5)

**Comment by Salaboy** [comment]
@lucianoprea @constantin-ciobotaru what is the status of this one?

**Comment by constantin-ciobotaru** [comment]
It should work with the new spring cloud release. I'll check this and close if it's ok.

**Comment by Salaboy** [comment]
@constantin-ciobotaru please close if it is done.,. if not move to the next milestone.

**Comment by constantin-ciobotaru** [comment]
There are still problems when using the maven plugin to download the stubs jar, but it's working when it just uses the stubs jar as maven dependency and AutoConfigureStubRunner is looking in the classpath, not in the local maven repository.

The stubs jar dependency is to the version corresponding to the consumer ${project.version}, so no need of the script for release and if the contract is changed, the same jgitflow feature should be started in both consumer and producer repositories to ensure the consumer tests run against the correct producer stubs.

PR: https://github.com/Activiti/activiti-cloud-org-service/pull/5

**Comment by Salaboy** [comment]
@constantin-ciobotaru question added to the PR, please get back to me in gitter.

**Comment by Salaboy** [comment]
Merged in develop
