### ISSUE TITLE
use spring session close listener for sending messages to audit and query

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1665]
We found that the activiti session close listener mechanism isn't guaranteed to fire when the spring session closes and might fire before the spring transaction has ended. We found and fixed this under https://github.com/Activiti/Activiti/issues/1660 by moving to a native spring listener. This is not so serious for audit and query feeds as it was for connectors as audit and query are one-way. But we should switch it anyway as otherwise there's a risk (though we've not actually observed it) of sending a message for a transaction that actually gets rolled back. Arguably we should change the engine's mechanism but that wouldn't be easy.

**Comment by erdemedeiros** [comment]
This depends on the [changes](https://github.com/Activiti/activiti-cloud-runtime-bundle-service/pull/27/files#diff-4d3ed153efda1fa500c39d3e8c25a63fR68) done in the PR https://github.com/Activiti/activiti-cloud-runtime-bundle-service/pull/27.

**Comment by ryandawsonuk** [comment]
That's merged now so I think we can close this.
