### ISSUE TITLE
connector integration results go to all runtime bundles if there are multiple

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1666]
If two runtime bundles are using the same connector (e.g. when two campaigns used in trending topics example - note I mean separate campaigns and not replicas) then the response goes to both RBs. This is ok (at least when using UUIDs) as only the RB that has that execution will process it (see https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/activiti/services/connectors/channel/ServiceTaskIntegrationResultEventHandler.java#L60). You could avoid this happening by using different destinations for the channels but then you'd need two connectors for two RBs - it wouldn't be a sharing scenario. Perhaps the sharing scenario will prove unusual but it would be better if in a sharing scenario we could at least check in the ServiceTaskIntegrationResultEventHandler whether the connector was processing a message that came from this particular RB using a field and not just the execution id lookup. Presumably we could do this by adding a field to capture RB app name and a filter in the StreamListener by that name.

**Comment by Salaboy** [comment]
@erdemedeiros @ryandawsonuk what is the status of this one? Can you please close or move to the next milestone depending on the current state of this issue.

**Comment by ryandawsonuk** [comment]
I think the PRs under https://github.com/Activiti/Activiti/issues/1681 cover it as each RB has its own channel and response goes to the RB that sent - I checked that I could run with multiple RBs when I checked that PR and seemed fine.
