### ISSUE TITLE
Could we use Spring AOP interceptors to reduce code in connectors?

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1669]
The @streamlistener methods in our connectors currently feature a fair bit of plumbing code to get process variables and send back. Could we do this code automatically using http://www.baeldung.com/spring-aop-annotation ?

**Comment by Salaboy** [comment]
Maybe extending the @StreamListeners annotations. The question if we are going to do this or this fall low in our priority list?

**Comment by ryandawsonuk** [comment]
I don't think it's so important now that a builder class is there as that makes it more intuitive.

**Comment by Salaboy** [comment]
I'm closing this, because it looks more like a question. 
We need to look more into kubeless or lambdas and make sure that we make connectors as thin as possible.
