### ISSUE TITLE
Are we going to use kub configmap?

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1670]
It's kind of a competitor to the spring cloud config server. Feels to me like we'd want to use config maps in kub (https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/) but config server if running outside of kub. (There is an interesting article on these overlaps between kub and spring cloud in general at https://developers.redhat.com/blog/2016/12/09/spring-cloud-for-microservices-compared-to-kubernetes/)

**Comment by Salaboy** [comment]
totally.. spring cloud kubernetes configmaps :)
