### ISSUE TITLE
Review column mappings for Audit JPA entities

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1673]
If you plug the JPA audit implementation into the twitter example you actually get errors about columns not being big enough. Presumably that example generates larger JSON than the RB-query-audit example.

**Comment by Salaboy** [comment]
this is also referenced from here: https://github.com/Activiti/Activiti/issues/1661
I think that this is important, and JPA is prepared to handle large content, so we should solve it

**Comment by Salaboy** [comment]
@ryandawsonuk I think that this was solved already. We should check with the blueprint, but Beta1 included the fix already. Let's create a new issue if this is not the case.
