### ISSUE TITLE
demo with rate-limiting

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1674]
We could demo calling out to an external service hosted by somebody else and using rate-limiting in the calls so that the external service doesn't fall over or reject. We could use a connector to do this. Mauricio originally did this in the twitter example using an online service called 'Shout' but we removed it from there as it wasn't related to twitter (https://github.com/Activiti/activiti-cloud-examples/tree/b8147a044d0bd9042f4e337a0dcd4d746f42d35a/trending-topic-campaigns/activiti-cloud-connectors-3rd-party/src/main/java/org/activiti/cloud/connectors/external). But we could create a new example based upon the code in that commit and just a simple process with one connector service task

**Comment by Salaboy** [comment]
@ryandawsonuk I would like to close this one, mostly because we have the dummy feed that can be controlled, for me that's fine. Then we will have the real life twitter feed which I wouldn't care much about rate limiting. Does that make sense?

**Comment by ryandawsonuk** [comment]
Ok, let's close.
