### ISSUE TITLE
POM files cleanup

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1675]
It was released only a few days after M7, which we're already on, so don't expect the differences to be very much. https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0.0-RC1-Release-Notes

**Comment by ryandawsonuk** [comment]
Actually we're best to park this until there is a new release of spring cloud above M5 https://github.com/spring-projects/spring-cloud/wiki/Spring-Cloud-Finchley-Release-Notes - there's no reason for us to do a boot upgrade without a cloud upgrade.

**Comment by Salaboy** [comment]
I'm pretty sure that we will need to upgrade before closing this milestone.

**Comment by Salaboy** [comment]
We need to do this before releasing. Now we have Spring Cloud M7 which should include SB 2 RC1

**Comment by mteodori** [comment]
removing the change on Spring Cloud M7 as it's not released yet, see: https://spring.io/blog/category/releases

**Comment by Salaboy** [comment]
Please see here: https://github.com/spring-projects/spring-cloud/wiki/Spring-Cloud-Finchley-Release-Notes
We need to upgrade to M6 not M7

**Comment by mteodori** [comment]
Moved Spring Cloud upgrade to a separate issue: https://github.com/Activiti/Activiti/issues/1790
We need to skip M6 and wait for M7 due to outstanding issue: spring-cloud/spring-cloud-sleuth#856

**Comment by mteodori** [comment]
pom files have been cleaned up on this branch to avoid copy paste as less as possible, maven publishing requirements as in https://maven.apache.org/guides/mini/guide-central-repository-upload.html have been verified to be present as inherited in the effective pom

**Comment by mteodori** [comment]
removed the changes in spring boot and just doing a POM cleanup in preparation for https://github.com/Activiti/Activiti/issues/1790

**Comment by Salaboy** [comment]
@mteodori how are we doing with this one? Can we close this already?
