### ISSUE TITLE
Improve response error body message

### ISSUE THREAD

**Issue by ffazzini** [Activiti/Activiti#1679]
Expected 'u' instead of 'o'

The error message above is returned by startProcess endpoint when the processDefinitionId does not exist.

Let's maybe also think to a standard error message payload we can use across different components.

**Comment by Salaboy** [comment]
@ffazzini are you getting this in Postman? that might be because you are looking at JSON content instead of Text/Plain?

**Comment by ffazzini** [comment]
No it happens when my processDefinitionId does not exist in the body, for example:
```javascript
{
  "processDefinitionId": "ProcessWithVariables:1:d2b96724-00fa-11e8-8cda-0a586460022e",
  "variables": {
    "firstName": "Paulo",
    "lastName": "Silva",
    "aget": 25
  },
  "commandType":"StartProcessInstanceCmd"
}

**Comment by Salaboy** [comment]
@ffazzini sounds like a change in the json files and also it means that we are not validating the process variables.. which we should.

**Comment by Salaboy** [comment]
@erdemedeiros we need to add some checks for the exceptions that we are throwing and data validation in our endpoints.

**Comment by salaboy** [comment]
@erdemedeiros @ryandawsonuk I am closing this one because now we have variables definition checks when we have variables defined.
