### ISSUE TITLE
Programmatically create producer stream bindings in RB

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1680]
Currently one channel is used for all connectors (https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/activiti/services/connectors/IntegrationRequestSender.java#L45). This is effectively a broadcast model where each has to filter. (Each really is checking as zipkin for Twitter example shows it is happening.) It would be better if we could have dedicated channels. Then each connector only has to listen for its messages. Actually on this model we wouldn't need the condition in the StreamListener on the connector implementation.

Would make sense for the RB to scan the XML and dynamically create streams for each connector. Perhaps use the flownode id as the destination or the value of the implementation attribute without spaces. Could optionally prefix with RB name to make RB-specific. 

The dedicated streams would only need to be dynamically generated in the RB->connector direction. The connector's consumer end can bind via property-file. Likewise the connector->RB responses can all go via the integration channel for the RB so the RB consumer end doesn't need to be dynamic. We should be able to do destination binding dynamically like https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#dynamicdestination

I did wonder if maybe we should support a broadcast mode as well as a direct mode but am not sure if anybody would want a broadcast mode. Would you want multiple connectors to consume the same event? If direct mode were the default that would do the trick.

**Comment by erdemedeiros** [comment]
After some investigation this approach presents a downside: it complexifies the amount of work necessary at the connector side. This extra step may be justified if it improves the application scalability.

## Single channel with filtering
**Actions per connector**
- Define a condition for the stream listener:

```
@StreamListener(value = CloudConnectorChannels.INTEGRATION_EVENT_CONSUMER, condition = "headers['connectorType']=='Process English Tweet'")
```

**Actions per Spring boot Application**
 - Configure consumer:

```
spring.cloud.stream.bindings.integrationEventsConsumer.destination=integration
spring.cloud.stream.bindings.integrationEventsConsumer.contentType=application/json
spring.cloud.stream.bindings.integrationEventsConsumer.group=integration
```

## Dedicated channels:
**Actions per connector**
-  Define consumer channels (`@Input`)

```
public interface ProcessingConnectorChannels {

    String TWITTER_ANALYZER_CONSUMER = "twitterAnalyzerConsumer";
    String TWITTER_PROCESSING_CONSUMER = "twitterProcessingConsumer";

    @Input(TWITTER_ANALYZER_CONSUMER)
    SubscribableChannel twitterAnalyzerConsumer();

    @Input(TWITTER_PROCESSING_CONSUMER)
    SubscribableChannel twitterProcessingConsumer();

}
```
- Configure consumer channel

```
spring.cloud.stream.bindings.twitterAnalyzerConsumer.destination=Analyze English Tweet
spring.cloud.stream.bindings.twitterAnalyzerConsumer.contentType=application/json
spring.cloud.stream.bindings.twitterAnalyzerConsumer.group=integration

spring.cloud.stream.bindings.twitterProcessingConsumer.destination=Process English Tweet
spring.cloud.stream.bindings.twitterProcessingConsumer.contentType=application/json
spring.cloud.stream.bindings.twitterProcessingConsumer.group=integration
```

**Actions per Spring Boot Application**
- None

**Comment by ryandawsonuk** [comment]
If it were possible to dynamically bind a consumer channel then we could maybe do it with a properties-based format like activiti.cloud.delegate.BEANNAME=Analyze English Tweet. It doesn't look like spring cloud streams have any official examples of dynamically binding consumers and it doesn't appear to be in their reference guide. The only suggestion I can find that it might be possible is https://stackoverflow.com/a/41726817 - he's using camel spring cloud stream but the classes he's using look like they're present in spring cloud streams. We should talk about whether we're comfortable attempting to go down that path.

**Comment by Salaboy** [comment]
@erdemedeiros this is definitely interesting... we should catch up with @ryandawsonuk about this as well. I know that you guys have been talking, but the complexity added in the connector side might be something that we can work on. 

From the connector point of view, the developer only need to define which logical inputs he/she wants to consume from -> ProcessingConnectorChannels -> SubscribableChannel twitterAnalyzerConsumer(); and  SubscribableChannel twitterProcessingConsumer();, once that is done, the properties can be configure lated at the time when you want to really start the connector. Meaning that the properties are not needed at definition time, are only needed at runtime before booting app the service (and this can be done with my current research). 
From my point of view, if we can expose from the runtime bundle definition (not at runtime) what are the channels that are going to be created (based on the services tasks defined in the processes) we should be able to help developers on the creation of their connectors, by making sure that they know which stream they can subscribe to from their connectors. 

Does this make sense?

**Comment by erdemedeiros** [comment]
@Salaboy yes, it makes sense. We can probably do some improvements to leverage the amount of work to be done during the connector implementation. We have the information in the process definition, we just need to figure out the best way to extract and expose this information.
