### ISSUE TITLE
Messages between runtime bundles in cloud

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1691]
Like https://github.com/Activiti/Activiti/issues/1687 but for messsages. It does not matter whether we tackle this issue first or if #1687 is done first.

**Comment by Salaboy** [comment]
@daisuke-yoshimoto can we have a chat about this issue? We might want to do timers first.

**Comment by erdemedeiros** [comment]
Release notes: mention new starter.
