### ISSUE TITLE
Separate notifications and query components

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1693]
Currently you can only see notifications through the graphiql interface or by creating a subscription against the query module.
You can only do that in docker and not kubernetes right now as it requires exposing the port directly. If you try to go through the gateway then the gateway effectively blocks the websockets request.

How do we hope to extract notifications away from query? What do we expect a ‘notifications’ server to do?

We want a query server that exposes the /graphql/ endpoint and which queries to a query database. Preferably it should be accessed through the gateway.
Presumably we want a separate notifications server which listens to events on rabbitmq and provides a /ws/graphql endpoint.
Both notifications and query presumably need to build a schema from a model (i.e. JPA entities) but one would expect them to be different models since the notifications schema is really listening for events. Presumably it persists those events (which might call into question the need for a separate audit component?).
Where should the igraphql endpoint go? Presumably it will need both subscriptions and queries.

We have this diagram reflecting the intended structure:
![image](https://user-images.githubusercontent.com/22754674/35276024-bb83654c-0039-11e8-8ab0-75c0fc0b1ac7.png)

It's not clear where igraphql could go.

Some of these questions might be easier to answer if we could list what each of the submodules under https://github.com/Activiti/activiti-cloud-query-service/tree/develop/activiti-cloud-services-query does and how they are intended to be used:

graphiql - just a javascript client that provides UI for both queries and subscriptions. Would we have to provide this separately on the new query and notification servers if we wanted it?

ws - adds a websockets dependency and creates unused EnableActivitiGraphQLNotifications annotation. Seems annotation is intended just to make available some configuration classes. One of these creates the websocket configuration. The other builds the schema for queries. It seems it takes the event schema (https://github.com/Activiti/activiti-cloud-query-service/blob/develop/activiti-cloud-services-query/activiti-cloud-services-query-graphql-ws/src/main/java/org/activiti/cloud/services/query/qraphql/ws/config/GraphQLSubscriptionsSchemaConfiguration.java#L51) and merges it with the standard query schema (https://github.com/Activiti/activiti-cloud-query-service/blob/develop/activiti-cloud-services-query/activiti-cloud-services-query-graphql-ws/src/main/java/org/activiti/cloud/services/query/qraphql/ws/config/GraphQLSubscriptionsSchemaConfiguration.java#L51). In doing so it creates a dependency to query as it uses the EnableActivitiGraphQLQueryService annotation.

graphql - This makes the graphql endpoint available - it has a dependency to model.

model - Just the basic JPA entity model.

notifications - Seems to enable transformations on inbound events? For what purpose though? Does it handle persistence?

repo - Enables persistence for the core model.

rest - Implementation for consuming event stream from runtime bundle and also provides REST endpoints (but not related to graphql). Uses spring data.

stomp - Adds websocket dependency and /ws/stomp endpoint - presumably that endpoint is only used in the background?

We can attempt to break this into:

Query: -graphql,-model,-repo,-rest
Notifications: -ws,-notifications,-stomp

-graphiql is unclear. It may be on neither or both. Could we split it into the part that does queries and the part that does subscriptions (see https://github.com/Activiti/activiti-cloud-query-service/blob/develop/activiti-cloud-services-query/activiti-cloud-services-query-graphiql/src/main/resources/static/graphiql.html)?

Unfortunately it looks like Notifications will need a dependency on some Query modules because of the schema-merging in the -ws module.

Ultimately we think we want to build two spring boot apps. We'll want to build those from two starters and annotations following our usual pattern. Perhaps a notification starter would need both the EnableActivitiGraphQLNotifications annotation from the -ws module and the EnableActivitiNotificationsGateway annotation from the -notifications module?

I think that both the notificationsGateway and notificationsConsumer properties (https://github.com/Activiti/activiti-cloud-query/blob/develop/src/main/resources/application.properties) would be set on the notifications app and not the query app.

**Comment by ryandawsonuk** [comment]
After discussion with @igdianov now thinking that we might leave the websocket and graphql endpoints in the same container. This way they can both be hit at the same place (I understand a websocket request to /graphql will be automatically routed to /ws/graphql) and the graphiql can naturally be used in that container. We might separate the notifications gateway component out of the container - need to review that and assess how great of a scalability benefit it would give. @Salaboy has suggested looking at having the option to turn off websockets in the query component.

**Comment by Salaboy** [comment]
@ryandawsonuk if ws cannot be turned off maybe just exclude all graphql functionality? that shouldn't be that hard.

**Comment by ryandawsonuk** [comment]
Yes will look into it. If we do decide against separation we should remember to remove/archive the -notifications and -notifications-service repos.

**Comment by ryandawsonuk** [comment]
We do have the properties spring.activiti.cloud.services.query.graphql.enabled and spring.activiti.cloud.services.notifications.gateway.enabled. I'll check that these give us the flexibility to disable event listening and graphql from docker environment variables.

**Comment by ryandawsonuk** [comment]
It seems spring.activiti.cloud.services.notifications.gateway.enabled unused within the code. I'm thinking the main things that we would want it to do are 1) turn on/off the listening to a stream of events and 2) control whether the server accepts requests for subscriptions.

**Comment by ryandawsonuk** [comment]
Another point is we'll need to decide about whether to publish a rabbitmq image with the stomp plugin added for use on kub in AWS. There doesn't seem to be an official image with this option set but there are unofficial ones. Alternatively, the rabbitmq-ha helm chart seems like it has it enabled by default (https://github.com/kubernetes/charts/blob/master/stable/rabbitmq-ha/templates/configmap.yaml#L13).

**Comment by ryandawsonuk** [comment]
These three PRs (https://github.com/Activiti/activiti-cloud-query-service/pull/15, https://github.com/Activiti/activiti-cloud-query/pull/18, https://github.com/Activiti/activiti-cloud-examples/pull/70) give the ability to use properties to turn graphql or notifications off (though notifications won't work without graphql). To get a rabbit with stomp enabled they use a docker image from https://github.com/Byteflair/docker-rabbitmq-stomp/blob/master/Dockerfile . We could certainly host our own image that enables this plugin. Extending the image is rabbit's suggested approach (https://github.com/docker-library/rabbitmq/issues/5). This possibly isn't a big issue if we're going to move towards helm and rabbitmq-ha anyway as that helm chart has the plugin enabled. 

The tests for the query-service repo are taking a while to build now and sometimes fail to run within Travis's time restrictions. 

I'm also thinking we should remove the -notifications-service and -notifications repos that we created as we've changed tack and are not using them.

**Comment by Salaboy** [comment]
@ryandawsonuk I will remove those two repos. but I do believe that we need a relaying mechanism as the notification gateway, it just feel right for some reason. If we probe that we don't need it we need to document why not in the gitbook.

**Comment by ryandawsonuk** [comment]
Yeah I want to look at it more. I am sure we want to be able to scale to be able to run multiple query components. That means we need to not use embedded database. It also means if the notification consumer is built in then it has to use a group so that the replicas don't also consume at once (I think this is the case already). Scaling the notification processing independently of the query module is also desirable but not essential - perhaps it would be best to put the notification gateway code in a separate repo and still build it into the query module but document so that it would be easy to run independently later. There is more I want to do. Just thinking a new ticket/s might be better as there are quite a few strands to this.
