### ISSUE TITLE
How to custom identity management in activiti6 with Spring Boot?

### ISSUE THREAD

**Issue by grath10** [Activiti/Activiti#1695]
It seems that the user guide has been out-of-date as the api seemed to change.
According to [https://www.activiti.org/userguide/#advanced.custom.session.manager](url), part 16.8 , guide was provided to show an example but not complicant with activiti 6.
Any advice similar to the example in the guide is helpful, 3x

**Comment by daisuke-yoshimoto** [comment]
Probably, I think that you can use custom identity management with Activiti 6.0 with the following procedure.

1. Implement the GroupDataManager interface. Or, extend MybatisGroupDataManager.class

2. ProcessEngineConfigurationImpl.setGroupDataManager(GroupDataManager groupDataManager)
https://github.com/Activiti/Activiti/blob/6.x/modules/activiti-engine/src/main/java/org/activiti/engine/impl/cfg/ProcessEngineConfigurationImpl.java#L3051

Certainly, Activiti user guide is wrong.
https://www.activiti.org/userguide/#advanced.custom.session.manager

Reference
https://community.alfresco.com/community/bpm/blog/2017/06/01/activiti-6-is-here

**Comment by grath10** [comment]
@daisuke-yoshimoto 3x for your prompt reply. The problem has been settled according to your suggestion, thx again!

**Comment by daisuke-yoshimoto** [comment]
@balsarori 
I would like to modify Activiti 6's User Guide, but is it possible to have it published to the public repository? Previously, you said that Activiti 6's User Guide is managed in the Private repository.
