### ISSUE TITLE
Update Demo UI with Angular/ADF

### ISSUE THREAD

**Issue by mteodori** [Activiti/Activiti#1696]
The current demo-ui app is built from an old Keycloak example with AngularJS.

It needs to be upgraded to Angular leveraging [ADF](https://github.com/Alfresco/alfresco-ng2-components) in order to have an example closer to a good starting point for a modern process application.

**Comment by Salaboy** [comment]
@mteodori let';s try to add more context, so if a community user read this they know what we are doing and if they want to help the have some links to look at what we are doing.

**Comment by Salaboy** [comment]
@mteodori can we add Maurizio Vitale here as well? I've created this repo (https://github.com/Activiti/activiti-cloud-demo-ui) that generates a docker image , but we need to get the new angular stuff in.

**Comment by mteodori** [comment]
@Salaboy updated desc, I don't have rights on the Activiti org to do that, moving the branch to the new repo now

**Comment by Salaboy** [comment]
@mteodori can we close this when maurizio moves the stuff that he has to the new repo?

**Comment by mteodori** [comment]
I thought he would have been working on this ticket, or are you guys creating others with more detail?

**Comment by Salaboy** [comment]
initial version done.. now we need to refactor it and make sure that the docker image is working as expected.
