### ISSUE TITLE
6.x version

### ISSUE THREAD

**Issue by starryskydog** [Activiti/Activiti#1697]
source code of version cannot running in eclipse

**Comment by Salaboy** [comment]
@starryskydog can you please provide more details about what you cannot do? 
The projects are maven modules, so you need to know how to import maven modules in eclipse. If you can please clarify what exactly are the problems that will be great. There is not much that we can do if Eclipse has a problem with maven modules.

**Comment by Salaboy** [comment]
closing due feedback not provided.
