### ISSUE TITLE
startProcess payload contains field 'aget'

### ISSUE THREAD

**Issue by ffazzini** [Activiti/Activiti#1698]
Either is wrong domain model code or the postman collection.

**Comment by Salaboy** [comment]
@ffazzini where is that? can you add more context? a screenshot or the json that you are referring to.

**Comment by ffazzini** [comment]
Endpoint: startProcess
Request payload in my postman collection below:

```javascript
{
  "processDefinitionId": "ProcessWithVariables:1:067f24c4-02b2-11e8-8ac0-0a5864600118",
  "variables": {
    "firstName": "Paulo",
    "lastName": "Silva",
    "aget": 25
  },
  "commandType":"StartProcessInstanceCmd"
}
```
It should be age, no aget.
