### ISSUE TITLE
evaluate best http method based on rest principles

### ISSUE THREAD

**Issue by ffazzini** [Activiti/Activiti#1703]
/rb-my-app/v1/tasks/9b0c1ebd-04e3-11e8-8ac0-0a5864600118/complete

probably PATCH is better solution than POST as we are updating a singe field of an entity and we are not adding a new entity.

By using PATCH or PUT you probably won't event need 'complete' or 'claim' at the end

**Comment by ffazzini** [comment]
Before proceeding let's investigate if this is a state machine use case and we should leave it like it is or there is a better solution on that sense.

**Comment by ryandawsonuk** [comment]
There might also be bigger questions to be aware of than the best HTTP method. Here is the relevant APS REST API section:

http://docs.alfresco.com/process-services1.7/topics/task_actions.html

And here is the section from the v6 community REST API:

https://www.activiti.org/userguide/#_task_actions

In v7 we have a complete task action that calls the engine's java API:

https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/TaskControllerImpl.java#L96

But we don't seem to have delegate or involve or remove-involved. We also don't have options for adding or removing forms from a task, at least not currently. That's just task actions - presumably there will be more gaps. We should aim to either identify and close the gaps (I think we'd anticipated this would happen in conjunction with UI development) or at least take account of whether or how future actions will be handled in making decisions about http method. Perhaps these are questions we should be reviewing first.

**Comment by Salaboy** [comment]
@ffazzini @ryandawsonuk @erdemedeiros it will be good to see how the Alfresco Guidelines are suggesting to deal with this. Not sure how much can we change for Beta1

**Comment by Salaboy** [comment]
Closing because beta1 already adopted a way of dealing with command type endpoints.
