### ISSUE TITLE
org.activiti.engine.impl.pvm was not found in Activiti 6.x

### ISSUE THREAD

**Issue by stonesingsong** [Activiti/Activiti#1706]
I want to change the current activity  of an ongoing process instance. For example , the current activity is the third activity, I want to back the first activity, and I don't want to delete the process instance.
Before Activiti 6.0.0, I can import org.activiti.engine.impl.pvm to achieve it, but now the package was not found.
Thank you very much!

**Comment by ryandawsonuk** [comment]
Please see https://www.activiti.org/migration.html#_pvm_classes
and also the V5 compatibility section beneath it.

If you need to get to these classes in v6 it should be possible - there are tests in the v6 codebase which use these classes - see https://github.com/Activiti/Activiti/tree/6.x/modules/activiti5-test 

You could try adding the activiti5-compatibility dependency like that pom.xml does.

**Comment by Salaboy** [comment]
@stonesingsong I'm closing this issue, because this is a question and questions are better answered in the alfresco bpm forum: https://community.alfresco.com/community/bpm/content
