### ISSUE TITLE
logstash dependency should be under activiti-cloud-build

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1718]
shouldn't be setting version at https://github.com/Activiti/activiti-cloud-service-common/blob/develop/activiti-cloud-services-logging/pom.xml#L16

should be feeding through from https://github.com/Activiti/activiti-cloud-build/blob/develop/pom.xml

**Comment by Salaboy** [comment]
@mteodori can you help us with this one before the release? is this solved by your other refactorings?

**Comment by Salaboy** [comment]
@mteodori is this done? if so, please close, if not please move to the next milestone

**Comment by mteodori** [comment]
no, it's not a library we use across projects, do we want to put it in the parent? I believe that there are other libraries specific to projects we don't bring up in the same why
