### ISSUE TITLE
access pivotal env and deployment

### ISSUE THREAD

**Issue by ffazzini** [Activiti/Activiti#1722]

**Comment by ffazzini** [comment]
We are able to deploy activiti7 in the pivotal environment following this procedure:
https://github.com/Activiti/activiti-cloud-examples/tree/master/kubernetes/aws-deployment

The only difference from amazon is that pivotal works with ip addresses so the ```kubectl get service.. ``` command should change to this:
```export AUTH_ADDRESS=$(kubectl get  service activiti-cloud-sso-idm-kub -o jsonpath={.status.loadBalancer.ingress[0].ip})```

**Comment by ryandawsonuk** [comment]
I see the README has been updated so I'd say we close this and move on to next step. Have we given feedback to pivotal?

**Comment by ffazzini** [comment]
@ryandawsonuk as discussed earlier we can close this task.

Pivotal people are investigating on their side the ip vs hostname when you do ```kubectl get service... ```
and also this issue that we have already experienced on minikube:
https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
