### ISSUE TITLE
Deployment descriptors for Modeling service

### ISSUE THREAD

**Issue by lucianoprea** [Activiti/Activiti#1727]
- create a file descriptor for Modeling backend service to deploy it inside docker or kubernetes

Note: modeling-backend-service is the one that aggregates/consumes organization-service and process-model-service

**Comment by Salaboy** [comment]
@lucianoprea @constantin-ciobotaru did you manage to create that? I think that we have the docker-compose but not the kubernetes descriptors.. can you please report back the status of this?

**Comment by constantin-ciobotaru** [comment]
PR: https://github.com/Activiti/activiti-cloud-examples/pull/73

**Comment by Salaboy** [comment]
merged
