### ISSUE TITLE
Spike - Reduce billing costs

### ISSUE THREAD

**Issue by ffazzini** [Activiti/Activiti#1728]
At the moment to keep the environment up and healthy we create EC2 m4.xlarge, try to create a new cluster with minor EC2 size and less nodes and see what happens.

Also get in touch with DBP to make sure that java-opts is passed into infrastructure dockerfile components.

**Comment by Salaboy** [comment]
This should be done by the platform team or APS team, but this is not priority for the Activiti community at this point. I will move it to the future, even though I recognise that we will get some value out of this research.

**Comment by ffazzini** [comment]
yes agree, actually you won't need it outside DBP as we have already seen that actual costs is low, you can actually close this.
