### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by ffazzini** [Activiti/Activiti#1735]
After building environments and acceptance tests, we can now measure the performances of activiti7.

Investigate about the best tool to use and the best scenarios to test.

**Comment by ffazzini** [comment]
https://github.com/Activiti/activiti-cloud-performance-tests

It is based on gatling, so it is written with Scala, but i decided to use maven so we can include this project in our release process.

**Comment by Salaboy** [comment]
now we have the initial version, I will close this and create more specific issues to track progress on this front!
