### ISSUE TITLE
Remove backend suffix from activiti-cloud-modeling-backend

### ISSUE THREAD

**Issue by mteodori** [Activiti/Activiti#1741]
Rename to activiti-cloud-modeling for consistency
Check Travis/Bamboo and badges are changed as well

**Comment by ryandawsonuk** [comment]
Need to be careful about the linked dockerhub automatic build repo. That can't be renamed as dockerhub doesn't support. If we delete it will we lose the published images under that repo?

**Comment by Salaboy** [comment]
@mteodori @ryandawsonuk do we want to do this or not?

**Comment by mteodori** [comment]
looks like the issue @ryandawsonuk had about it can be solved like this, https://github.com/docker/hub-feedback/issues/313#issuecomment-265843090

**Comment by mteodori** [comment]
@Salaboy @ryandawsonuk I don't have the rights to make the change in the comment above as I don't see the repo in Docker Cloud I can change, if any of you guys can easily do it then please proceed otherwise we can take this issue off the backlog

**Comment by ryandawsonuk** [comment]
We should make sure the whole team has rights on those configurations. Can you check https://hub.docker.com/r/activiti/activiti-cloud-modeling-backend/ again as I've just made changes?

**Comment by mteodori** [comment]
I cannot select the activiti org and another repository to build in: https://cloud.docker.com/app/activiti/repository/docker/activiti/activiti-cloud-modeling-backend/builds/edit

**Comment by mteodori** [comment]
assigning to @Salaboy as it requires github admin rights on activiti org

**Comment by mteodori** [comment]
PR:
- https://github.com/Activiti/activiti-scripts/pull/5
- https://github.com/Activiti/activiti-cloud-modeling/pull/7
- https://github.com/Activiti/activiti-cloud-examples/pull/81

**Comment by Salaboy** [comment]
@mteodori all PRs merged.. so I asume that this is done
