### ISSUE TITLE
access control for REST part of query

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1744]
To be as close as possible to RB - see Security section of https://activiti.gitbooks.io/activiti-7-developers-guide/content/components/activiti-cloud-app/RuntimeBundle.html and https://github.com/Activiti/Activiti/issues/1493

RFC doc for this at https://docs.google.com/document/d/1p3PLBVdjB_s6gBr4dAKjYRNlaiYSDCtO_54GOp80s08/edit#heading=h.5fwzajweqlpw

**Comment by Salaboy** [comment]
PRs merged for ProcessInstance lists.

**Comment by Salaboy** [comment]
Tasks filters still remaining.. should we create a different issue to track that progress?

**Comment by ryandawsonuk** [comment]
I'm happy to track tasks under this one.

**Comment by ryandawsonuk** [comment]
Current status is can send and handle events to determine if user/group is a candidate and use this to restrict access to tasks in query service. Adding /admin/ endpoint for tasks just so admin user knows the difference between tasks they are candidate for and tasks they see just because they're an admin. Need to apply restrictions to variables and decide on cases like /process-instances/7/tasks

**Comment by Salaboy** [comment]
@ryandawsonuk can we just use the same approach than the RB for admin endpoints? which is: we use the same endpoints but we check for the role of the user in keycloak?

**Comment by ryandawsonuk** [comment]
RB admin endpoints were missing so have included /admin/v1/tasks in these PRs
