### ISSUE TITLE
Name for process instance id not the same in query and RB responses

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1746]
API query 
"processInstanceId": "459ab950-04f0-11e8-9f7c-0a5864600307", 
"processDefinitionId": "ProcessWithVariables:1:d44693ef-04ef-11e8-9f7c-0a5864600307", 
"status": "RUNNING", 
"lastModified": "2018-01-29T12:31:04.128+0000", 

API runtime bundle 
"id": "459ab950-04f0-11e8-9f7c-0a5864600307", 
"processDefinitionId": "ProcessWithVariables:1:d44693ef-04ef-11e8-9f7c-0a5864600307", 
"processDefinitionKey": "ProcessWithVariables", 
"initiator": "hruser", 
"startDate": "2018-01-29T12:31:04.123+0000", 
"status": "RUNNING",

Process Definition Key is also missing but that has a separate issue https://github.com/Activiti/Activiti/issues/1752

**Comment by ryandawsonuk** [comment]
I added the Activated and Suspended events into the query model in  https://github.com/Activiti/activiti-cloud-query-service/pull/22/commits/360ab813e7db10a1342b31f5393a7c69269fbf98 with the aim of getting access to this data through those events. But it seems the activated events actually are not fired when a process is started and only if explicitly activated by an action. The null fields are then being omitted from the json body. It looks like we're going to need more data to be fed to query in the ProcessStartedEvent.

**Comment by ryandawsonuk** [comment]
Implemented under https://github.com/Activiti/Activiti/issues/1761

**Comment by ryandawsonuk** [comment]
Reopened as fix hasn't been deployed to the relevant test environment.

**Comment by Salaboy** [comment]
we do not track if fixes are deployed.. only if the fix is in the source code.
