### ISSUE TITLE
Runtime bundle REST responses should contain lastModified if it's available on the engine-level entity

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1747]
It is present in query so would be good to have in RB. I suspect it is there on the engine entity.

**Comment by constantin-ciobotaru** [comment]
There is no lastModified in org.activiti.engine.runtime.ProcessInstance engine-level entity.  Indeed, there is a lastModified field in org.activiti.cloud.services.query.model.ProcessInstance, but this is set based on the event date by the eventHandler on query service side.

I didn't find it neither in Activiti 6: there is no lastModified field in the response for "/rest/query/process-instances". The existing sorting functionality does order by "startedDate".

@ryandawsonuk Are you sure about this lastModified field? Is it really needed?

**Comment by ryandawsonuk** [comment]
Not sure, no. I think it came out of a conversation with @mauriziovitale . I had assumed it was on the engine entity but perhaps it's only available through the historyService and I doubt we want to do that in RB.

@mauriziovitale is it ok if we don't show lastModified in the runtime bundle and only show it in query?

**Comment by mauriziovitale** [comment]
@ryandawsonuk @constantin-ciobotaru
it sounds good to me.

**Comment by constantin-ciobotaru** [comment]
Thanks @mauriziovitale
