### ISSUE TITLE
Deploy multiple runtime bundles to AWS

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1748]
The AWS deployment currently has a single runtime bundle baked into the chart.

I think we could take this out of the chart and deploy the RBs separately using the rbapchart and rbdbchart from https://github.com/Activiti/activiti-cloud-examples/tree/develop/kubernetes/helm

We should need to change things a little though as those charts expect the infra services to be prefixed with a release name (https://github.com/Activiti/activiti-cloud-examples/blob/develop/kubernetes/helm/activitirbapchart/templates/runtime-bundle-ap.yml#L27). I don't think we should do that. We should default the names and expose them as configurable values. (See for example https://github.com/kubernetes/charts/blob/master/stable/rabbitmq/templates/svc.yaml#L4 defaulted at https://github.com/kubernetes/charts/blob/a96337bc2ca97482f46ecd5c76b185a2fb1e8e9d/stable/rabbitmq/templates/_helpers.tpl but we could just use values.yaml initially - DBP guys also seem to be doing this now https://github.com/Alfresco/alfresco-dbp-deployment )

That would allow us to deploy multiple runtime bundles via a script. They need to have different names so that they get different gateway routes. 

I think they could share a database even with the same process definition xml (this will work if they use separate schemas - see https://github.com/Activiti/Activiti/issues/1723). If it's simpler for now we could use different databases.

This was requested so we can have a more realistic test scenario on AWS for the UI guys to work against

![image](https://user-images.githubusercontent.com/22754674/36026682-108f0be6-0d90-11e8-86bf-171809c9d3f0.png)

**Comment by Salaboy** [comment]
@ffazzini can you help us with this? it should be just another RB definition in yaml with a different spring boot app name.

**Comment by Salaboy** [comment]
I'm closing this now that we are looking into pipelines.
