### ISSUE TITLE
use websockets in DBP deployment

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1750]
Have had to disable for now:

https://github.com/Activiti/activiti-cloud-examples/commit/4715bbbf0f4264a3210ee5f8e0084fffa5b96047

DBP deployment uses rabbit-ha:

https://github.com/Alfresco/alfresco-dbp-deployment/blob/master/charts/incubator/alfresco-dbp-infrastructure/values.yaml#L1

but rabbit chart presently doesn't seem to support that:

https://github.com/kubernetes/charts/issues/3653

**Comment by Salaboy** [comment]
@ryandawsonuk how is this different in our infrastructure? If it is DBP specific we should tell them to track that.

**Comment by ryandawsonuk** [comment]
Yes it is different. Our stuff is different because we're not using an official rabbit chart and are instead are including the activiti/rabbitmq-stomp image through our own charts. I kinda think the DBP approach is the better way but we're blocked on it. I did discuss with the DBP guys before opening kubernetes/charts#3653 and gave them that link afterwards but you're right we should follow up.

**Comment by Salaboy** [comment]
closing here, this needs to be tracked in DBP
