### ISSUE TITLE
processDefinitionKey missing from query

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1752]
Should be included in the model and the REST endpoints

**Comment by ryandawsonuk** [comment]
Need this to be in the model so that we can apply security restrictions by process definition key. But events fed to query and audit aren't at process definition level. I think we want to add it into the events at:

https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-services-runtime-bundle/activiti-cloud-services-api/src/main/java/org/activiti/cloud/services/api/events/ProcessEngineEvent.java

**Comment by ryandawsonuk** [comment]
ProcessDefinitionKey added but only to ProcessInstance under https://github.com/Activiti/Activiti/issues/1761

**Comment by ryandawsonuk** [comment]
Reopened as fix hasn't been deployed to the relevant test environment.

**Comment by Salaboy** [comment]
I'm closing this issue because we do not track deployed changes.
