### ISSUE TITLE
Make Demo UI app Docker image configurable

### ISSUE THREAD

**Issue by mteodori** [Activiti/Activiti#1753]
Add configuration options for the Docker image from https://github.com/Activiti/activiti-cloud-demo-ui to specify Keycloak and environment to launch the webapp against.

Update the README to document how to run and configure the docker image

**Comment by Salaboy** [comment]
@mteodori can you help us with this one? I mean if you are working with @mauriziovitale can you keep track of this work?

**Comment by mteodori** [comment]
completed and documented in the https://github.com/Activiti/activiti-cloud-examples/blob/develop/kubernetes/kubectl/README.md
