### ISSUE TITLE
Suspend and activate endpoints in RB return empty json responses

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1754]
Return the updated entity instead

**Comment by Salaboy** [comment]
@erdemedeiros I want your view on this.. We should avoid doing an extra query for getting the entity but when we have them we should return it, or at least the pieces that we have available. 
The UI can use this to update a list item for example, which will be a big improvement compared with the old APIs -> which leads us to consider adding this change now.

**Comment by mauriziovitale** [comment]
From my point of view, the API should at least return: 
id and new status.
@mteodori what do you think?

**Comment by Salaboy** [comment]
this is done for beta1
