### ISSUE TITLE
RB sorting for process instance only works on certain fields

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1758]
?sort=id,desc and ?sort=id,asc work
but sort=initiator,desc  gives
 `ActivitiIllegalArgumentException: The property 'initiator' cannot be used to sort the result.`
Same for status

**Comment by mauriziovitale** [comment]
Same for startDate, processDefinitionKey, status
i.e.
    "message": "org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.activiti.engine.ActivitiIllegalArgumentException: The property 'startDate' cannot be used to sort the result.",

**Comment by ryandawsonuk** [comment]
Apparently the equivalent fields are sortable in the query REST API

**Comment by Salaboy** [comment]
@ryandawsonuk @mauriziovitale no sorting, filtering capability will be provided by the RB, we should throw an error if people is trying to do that. All sorting and filtering should be Query Service's responsibility.
