### ISSUE TITLE
Add a subprocess example to example-runtime-bundle

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1765]
We want to put MyMainProcess-10.bpmn20.xml from attached into example-runtime-bundle

[AppSubProcWithVariables.zip](https://github.com/Activiti/Activiti/files/1727558/AppSubProcWithVariables.zip)

**Comment by mauriziovitale** [comment]
I have created a simple process definition that contains a subprocess. 
The parent process contains a start event, subprocess, end event
The subprocess contains a start event, user task, end event

[SubProcessDefinition.zip](https://github.com/Activiti/Activiti/files/1736681/SubProcessDefinition.zip)

**Comment by Salaboy** [comment]
@mauriziovitale did you manage to get this working in our example-runtime-bundle?

**Comment by Salaboy** [comment]
@mauriziovitale I can see that it was included so I'm closing this issue.

**Comment by mauriziovitale** [comment]
@Salaboy Now I'm able to see a process definition with a subprocess
http://{{domain}}/rb-my-app/v1/process-definitions
```
{
                "id": "SubprocessParent:1:c6fe677a-2615-11e8-a752-0a5864600113",
                "name": "Subprocess Parent",
                "version": 1,
                "_links": {
                    "self": {
                        "href": "http://a8ec9df8a163911e8ae310a512638dd5-140056902.us-east-1.elb.amazonaws.com/rb-my-app/v1/process-definitions/SubprocessParent:1:c6fe677a-2615-11e8-a752-0a5864600113"
                    },
                    "startProcess": {
                        "href": "http://a8ec9df8a163911e8ae310a512638dd5-140056902.us-east-1.elb.amazonaws.com/rb-my-app/v1/process-instances"
                    },
                    "home": {
                        "href": "http://a8ec9df8a163911e8ae310a512638dd5-140056902.us-east-1.elb.amazonaws.com/rb-my-app/v1"
                    }
                }
            }
```
but when I try to start a new process with that processDefinition I'getting the error:
```
{
    "timestamp": "2018-03-12T17:05:04.869+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.activiti.engine.ActivitiException: Unknown property used in expression: ${activiti_subProcessVariablesMappingListener}",
    "path": "/v1/process-instances"
}
```
