### ISSUE TITLE
variables controllers in RB should support update, add and delete

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1770]
engine supports set and remove

we should support in https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/ProcessInstanceVariableControllerImpl.java

**Comment by Salaboy** [comment]
@ryandawsonuk I am not entirely sure that we should. Maybe only in the Admin API
