### ISSUE TITLE
format error in the api response

### ISSUE THREAD

**Issue by ffazzini** [Activiti/Activiti#1772]
Api should return an error section in the response which displays informations such as
response code, message, a key. 
Please see the API guidelines for the details. @mteodori 

We have already had a quick technical discussion with @erdemedeiros and @ryandawsonuk about how to achieve this, for example exception handlers and controller advices.

**Comment by Salaboy** [comment]
This is about Error and Exception handling at the API level, so this should be done for Beta1

**Comment by Salaboy** [comment]
@ffazzini can you take the lead on this?

**Comment by Salaboy** [comment]
@ffazzini @erdemedeiros @ryandawsonuk we already have Exception handling in our REST controllers, do we need more? where? I will close this broad issue , Please create new issues for the specific cases.

**Comment by erdemedeiros** [comment]
@Salaboy we have exception handlers in our controllers, but they are returning plein String. It should probably return a json instead. In addition, I think @ffazzini is referencing the Alfresco media-type (currently not covered for errors).
