### ISSUE TITLE
Add Swagger to BluePrint Services to use Feign for acceptance tests

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#1775]
Add swagger to blueprint services:
1) Dummy Twitter feed
2) Rewards
3) Rankings
4) Runtime Bundle Campaign

To create acceptance tests using JBehave. 
A simple scenario should show: 
1) How to send a tweet related to an active campaign
2) how the tweet is processed by the campaign
3) how the user is ranked
4) how the reward is submitted to the top users for that campaign.

**Comment by mteodori** [comment]
obsolete, blueprints have been dismissed
