### ISSUE TITLE
Add support for MongoDB 4.2(multi-document transactions)

### ISSUE THREAD

**Issue by daisuke-yoshimoto** [Activiti/Activiti#1777]
It seems that MongoDB 4.0(in Summer 2018) will add support for multi-document transactions.
So, we may be able to manage transactions for writing audit events by upgrading to MongoDB 4.0 and Spring Data Mongo 2.0.x.
* https://www.mongodb.com/blog/post/multi-document-transactions-in-mongodb
* https://www.mongodb.com/transactions
* https://github.com/Activiti/activiti-cloud-audit-service/blob/develop/activiti-cloud-services-audit/activiti-cloud-services-audit-mongo/src/main/java/org/activiti/cloud/services/audit/mongo/channel/AuditConsumerChannelHandler.java#L42

> In MongoDB 4.0, which will be released this summer*, transactions will work across a single replica set, and MongoDB 4.2* will support transactions across a sharded deployment.

It seems that MongoDB 4.2 including supporting transactions across a sharded deployment will be more future.

**Comment by Salaboy** [comment]
👍 Let's schedule this for after Beta1
