### ISSUE TITLE
review differences between APS and Activiti7 tasks endpoint response

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1795]
From ADF guys.

APS output.

{  
   "data":[  
      {  
         "id":"5390770",
         "processDefinitionId":"Test1900:3:5355724",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/Test1900:3:5355724",
         "processInstanceId":"5390762",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/5390762",
         "executionId":"5390762",
         "name":null,
         "description":null,
         "deleteReason":null,
         "owner":null,
         "assignee":"5006",
         "startTime":"2018-02-02T19:13:15.969+05:30",
         "endTime":null,
         "durationInMillis":null,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-403915F2-6375-4B87-8FD1-8313405F5DED",
         "formKey":"106106",
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/5390770",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      },
      {  
         "id":"4793117",
         "processDefinitionId":"Stencil:27:4793110",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/Stencil:27:4793110",
         "processInstanceId":"4793112",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/4793112",
         "executionId":"4793112",
         "name":null,
         "description":null,
         "deleteReason":"Cancelled by 5006",
         "owner":null,
         "assignee":"26026",
         "startTime":"2017-10-09T12:48:52.090+05:30",
         "endTime":"2017-10-09T14:39:41.885+05:30",
         "durationInMillis":6649795,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-64D93AC5-0A8E-4160-8128-EEDF823CB072",
         "formKey":"55095",
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/4793117",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      },
      {  
         "id":"4786016",
         "processDefinitionId":"StencilExample:8:4786010",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/StencilExample:8:4786010",
         "processInstanceId":"4786011",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/4786011",
         "executionId":"4786011",
         "name":null,
         "description":null,
         "deleteReason":"Cancelled by 5006",
         "owner":null,
         "assignee":"5006",
         "startTime":"2017-10-04T18:47:54.762+05:30",
         "endTime":"2017-10-04T18:57:23.106+05:30",
         "durationInMillis":568344,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-BF5B493B-1CB4-4151-AD74-7C0C95C26E69",
         "formKey":"54091",
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/4786016",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      },
      {  
         "id":"5360312",
         "processDefinitionId":"test_upload:2:5360304",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/test_upload:2:5360304",
         "processInstanceId":"5360305",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/5360305",
         "executionId":"5360305",
         "name":null,
         "description":null,
         "deleteReason":"completed",
         "owner":null,
         "assignee":"29029",
         "startTime":"2018-01-29T17:13:08.214+05:30",
         "endTime":"2018-01-30T10:52:50.994+05:30",
         "durationInMillis":63582780,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-32933371-5839-4399-8373-2D44E383B7B2",
         "formKey":"108109",
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/5360312",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      },
      {  
         "id":"4301294",
         "processDefinitionId":"sample-leave:1:4301114",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/sample-leave:1:4301114",
         "processInstanceId":"4301200",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/4301200",
         "executionId":"4301200",
         "name":null,
         "description":null,
         "deleteReason":"completed",
         "owner":null,
         "assignee":"8009",
         "startTime":"2017-09-28T15:33:26.537+05:30",
         "endTime":"2017-09-28T15:34:07.366+05:30",
         "durationInMillis":40829,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-A99718AC-D3F1-4037-8BB6-10CFECE15799",
         "formKey":"52064",
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/4301294",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      },
      {  
         "id":"5092136",
         "processDefinitionId":"OutComeProcess:10:5092127",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/OutComeProcess:10:5092127",
         "processInstanceId":"5092131",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/5092131",
         "executionId":"5092131",
         "name":null,
         "description":null,
         "deleteReason":"completed",
         "owner":null,
         "assignee":"26026",
         "startTime":"2017-11-08T13:17:10.766+05:30",
         "endTime":"2017-11-08T14:29:18.601+05:30",
         "durationInMillis":4327835,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-E51B886D-E498-49DA-BF31-BF7334025B44",
         "formKey":"70134",
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/5092136",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      },
      {  
         "id":"58064",
         "processDefinitionId":"SampleStudent:1:58041",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/SampleStudent:1:58041",
         "processInstanceId":"58056",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/58056",
         "executionId":"58056",
         "name":null,
         "description":null,
         "deleteReason":"completed",
         "owner":null,
         "assignee":"5005",
         "startTime":"2017-03-27T18:18:50.644+05:30",
         "endTime":"2017-03-27T18:18:58.194+05:30",
         "durationInMillis":7550,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-1737B64C-9206-490D-A766-9C027FC96ECA",
         "formKey":"11067",
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/58064",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      },
      {  
         "id":"5091979",
         "processDefinitionId":"OutComeProcess:3:5091956",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/OutComeProcess:3:5091956",
         "processInstanceId":"5091974",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/5091974",
         "executionId":"5091974",
         "name":null,
         "description":null,
         "deleteReason":"Cancelled by 26026",
         "owner":null,
         "assignee":"26026",
         "startTime":"2017-11-08T12:28:37.270+05:30",
         "endTime":"2017-11-08T12:31:55.417+05:30",
         "durationInMillis":198147,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-E51B886D-E498-49DA-BF31-BF7334025B44",
         "formKey":"70127",
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/5091979",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      },
      {  
         "id":"5325043",
         "processDefinitionId":"testinitiator:1:5322825",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/testinitiator:1:5322825",
         "processInstanceId":"5325038",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/5325038",
         "executionId":"5325038",
         "name":null,
         "description":null,
         "deleteReason":"completed",
         "owner":null,
         "assignee":"33034",
         "startTime":"2018-01-10T13:11:18.348+05:30",
         "endTime":"2018-01-10T13:11:29.190+05:30",
         "durationInMillis":10842,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-E66C8C4D-07A5-4BD7-AD3E-6544DF35E57E",
         "formKey":"101101",
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/5325043",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      },
      {  
         "id":"5360047",
         "processDefinitionId":"leaveprocess:8:5357520",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/leaveprocess:8:5357520",
         "processInstanceId":"5360042",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/5360042",
         "executionId":"5360042",
         "name":null,
         "description":null,
         "deleteReason":"completed",
         "owner":null,
         "assignee":"1",
         "startTime":"2018-01-29T15:50:51.722+05:30",
         "endTime":"2018-01-29T15:52:00.625+05:30",
         "durationInMillis":68903,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-EBB06739-0DF9-4EB7-A240-DF74AA5B2DAE",
         "formKey":"107108",
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/5360047",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      },
      {  
         "id":"4582357",
         "processDefinitionId":"sample-leave:2:4582114",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/sample-leave:2:4582114",
         "processInstanceId":"4582352",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/4582352",
         "executionId":"4582352",
         "name":null,
         "description":null,
         "deleteReason":"completed",
         "owner":null,
         "assignee":"25025",
         "startTime":"2017-10-03T12:11:10.149+05:30",
         "endTime":"2017-10-03T12:11:22.239+05:30",
         "durationInMillis":12090,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-5ABA04D3-FAA2-43D2-9A3F-4F7C5D30F85A",
         "formKey":"53059",
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/4582357",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      },
      {  
         "id":"662399",
         "processDefinitionId":"RegProcess:1:662331",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/RegProcess:1:662331",
         "processInstanceId":"662387",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/662387",
         "executionId":"662387",
         "name":null,
         "description":null,
         "deleteReason":"completed",
         "owner":null,
         "assignee":"11011",
         "startTime":"2017-05-04T12:51:19.365+05:30",
         "endTime":"2017-05-04T12:51:31.348+05:30",
         "durationInMillis":11983,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-1111C8DB-4D0E-49E5-B1E8-BED8EB6A2783",
         "formKey":"16165",
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/662399",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      },
      {  
         "id":"5129232",
         "processDefinitionId":"Colortest:10:5129224",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/Colortest:10:5129224",
         "processInstanceId":"5129227",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/5129227",
         "executionId":"5129227",
         "name":null,
         "description":null,
         "deleteReason":"completed",
         "owner":null,
         "assignee":"5006",
         "startTime":"2017-11-16T17:39:41.261+05:30",
         "endTime":"2017-11-16T17:42:17.192+05:30",
         "durationInMillis":155931,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-104747B2-AF24-479E-82F4-2DB0C76C76DF",
         "formKey":"76129",
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/5129232",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      },
      {  
         "id":"5089393",
         "processDefinitionId":"TestLoop:12:5089361",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/TestLoop:12:5089361",
         "processInstanceId":"5089362",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/5089362",
         "executionId":"5089379",
         "name":null,
         "description":null,
         "deleteReason":"Cancelled by 5006",
         "owner":null,
         "assignee":"1234",
         "startTime":"2017-11-03T15:20:24.651+05:30",
         "endTime":"2017-11-03T15:25:14.189+05:30",
         "durationInMillis":289538,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-6E112C5D-E7B1-4092-8B28-1989C43EB0BB",
         "formKey":"69161",
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/5089393",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      },
      {  
         "id":"2202995",
         "processDefinitionId":"MessageThrowProcess3:7:2192837",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/MessageThrowProcess3:7:2192837",
         "processInstanceId":"2202988",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/2202988",
         "executionId":"2202988",
         "name":null,
         "description":null,
         "deleteReason":"completed",
         "owner":null,
         "assignee":"5006",
         "startTime":"2017-07-26T11:25:13.823+05:30",
         "endTime":"2017-07-26T16:57:19.242+05:30",
         "durationInMillis":19925419,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-36B4C4C4-C458-4378-84E9-6FDE7CB4AA0D",
         "formKey":"27028",
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/2202995",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      },
      {  
         "id":"5322845",
         "processDefinitionId":"testinitiator:1:5322825",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/testinitiator:1:5322825",
         "processInstanceId":"5322836",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/5322836",
         "executionId":"5322836",
         "name":null,
         "description":null,
         "deleteReason":null,
         "owner":null,
         "assignee":"33033",
         "startTime":"2018-01-10T11:36:56.067+05:30",
         "endTime":null,
         "durationInMillis":null,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-490E172B-7372-4A5E-97AE-932A117F097F",
         "formKey":"101102",
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/5322845",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      },
      {  
         "id":"4301157",
         "processDefinitionId":"sample-leave:1:4301114",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/sample-leave:1:4301114",
         "processInstanceId":"4301152",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/4301152",
         "executionId":"4301152",
         "name":null,
         "description":null,
         "deleteReason":"completed",
         "owner":null,
         "assignee":"25025",
         "startTime":"2017-09-28T15:32:27.731+05:30",
         "endTime":"2017-09-28T15:33:37.833+05:30",
         "durationInMillis":70102,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-5ABA04D3-FAA2-43D2-9A3F-4F7C5D30F85A",
         "formKey":"52064",
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/4301157",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      },
      {  
         "id":"3818487",
         "processDefinitionId":"claimsprocess:8:22508",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/claimsprocess:8:22508",
         "processInstanceId":"3818482",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/3818482",
         "executionId":"3818482",
         "name":null,
         "description":null,
         "deleteReason":"completed",
         "owner":null,
         "assignee":"1",
         "startTime":"2017-09-19T11:44:33.938+05:30",
         "endTime":"2017-11-20T11:42:19.585+05:30",
         "durationInMillis":5356665647,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-C8E6EA92-8DBE-443D-9E4B-1515ECBE1211",
         "formKey":null,
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/3818487",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      },
      {  
         "id":"5134312",
         "processDefinitionId":"claimsprocess:8:22508",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/claimsprocess:8:22508",
         "processInstanceId":"5134307",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/5134307",
         "executionId":"5134307",
         "name":null,
         "description":null,
         "deleteReason":null,
         "owner":null,
         "assignee":"1",
         "startTime":"2017-11-24T12:30:54.420+05:30",
         "endTime":null,
         "durationInMillis":null,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-C8E6EA92-8DBE-443D-9E4B-1515ECBE1211",
         "formKey":null,
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/5134312",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      },
      {  
         "id":"4582512",
         "processDefinitionId":"sample-leave:2:4582114",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/sample-leave:2:4582114",
         "processInstanceId":"4582408",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/4582408",
         "executionId":"4582408",
         "name":null,
         "description":null,
         "deleteReason":"completed",
         "owner":null,
         "assignee":"25025",
         "startTime":"2017-10-03T12:12:12.974+05:30",
         "endTime":"2017-10-03T12:12:17.498+05:30",
         "durationInMillis":4524,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-5ABA04D3-FAA2-43D2-9A3F-4F7C5D30F85A",
         "formKey":"53059",
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/4582512",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      },
      {  
         "id":"5367518",
         "processDefinitionId":"test_upload:3:5360316",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/test_upload:3:5360316",
         "processInstanceId":"5367513",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/5367513",
         "executionId":"5367513",
         "name":null,
         "description":null,
         "deleteReason":null,
         "owner":null,
         "assignee":"29029",
         "startTime":"2018-01-31T14:45:18.711+05:30",
         "endTime":null,
         "durationInMillis":null,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-32933371-5839-4399-8373-2D44E383B7B2",
         "formKey":"108110",
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/5367518",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      },
      {  
         "id":"4785793",
         "processDefinitionId":"StencilExample:3:4785781",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/StencilExample:3:4785781",
         "processInstanceId":"4785788",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/4785788",
         "executionId":"4785788",
         "name":null,
         "description":null,
         "deleteReason":"Cancelled by 5006",
         "owner":null,
         "assignee":"5006",
         "startTime":"2017-10-04T18:02:08.705+05:30",
         "endTime":"2017-10-04T18:05:37.658+05:30",
         "durationInMillis":208953,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-BF5B493B-1CB4-4151-AD74-7C0C95C26E69",
         "formKey":"54081",
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/4785793",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      },
      {  
         "id":"5097935",
         "processDefinitionId":"TestLoop:43:5097863",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/TestLoop:43:5097863",
         "processInstanceId":"5097905",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/5097905",
         "executionId":"5097921",
         "name":null,
         "description":null,
         "deleteReason":"completed",
         "owner":null,
         "assignee":"8009",
         "startTime":"2017-11-09T17:42:32.619+05:30",
         "endTime":"2017-11-09T17:42:39.247+05:30",
         "durationInMillis":6628,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-6E112C5D-E7B1-4092-8B28-1989C43EB0BB",
         "formKey":"72120",
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/5097935",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      },
      {  
         "id":"5128450",
         "processDefinitionId":"Colortest:7:5128442",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/Colortest:7:5128442",
         "processInstanceId":"5128445",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/5128445",
         "executionId":"5128445",
         "name":null,
         "description":null,
         "deleteReason":"completed",
         "owner":null,
         "assignee":"5006",
         "startTime":"2017-11-16T16:16:49.198+05:30",
         "endTime":"2017-11-16T17:18:11.032+05:30",
         "durationInMillis":3681834,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-104747B2-AF24-479E-82F4-2DB0C76C76DF",
         "formKey":"76126",
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/5128450",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      },
      {  
         "id":"4785958",
         "processDefinitionId":"StencilExample:6:4785948",
         "processDefinitionUrl":"http://192.168.0.172:8089/activiti-app/api/repository/process-definitions/StencilExample:6:4785948",
         "processInstanceId":"4785953",
         "processInstanceUrl":"http://192.168.0.172:8089/activiti-app/api/history/historic-process-instances/4785953",
         "executionId":"4785953",
         "name":null,
         "description":null,
         "deleteReason":"Cancelled by 5006",
         "owner":null,
         "assignee":"5006",
         "startTime":"2017-10-04T18:19:42.587+05:30",
         "endTime":"2017-10-04T18:47:48.444+05:30",
         "durationInMillis":1685857,
         "workTimeInMillis":null,
         "claimTime":null,
         "taskDefinitionKey":"sid-BF5B493B-1CB4-4151-AD74-7C0C95C26E69",
         "formKey":"54088",
         "priority":50,
         "dueDate":null,
         "parentTaskId":null,
         "url":"http://192.168.0.172:8089/activiti-app/api/history/historic-task-instances/4785958",
         "variables":[  

         ],
         "tenantId":"tenant_1",
         "category":null
      }
   ],
   "total":6161,
   "start":0,
   "sort":"name",
   "order":"asc",
   "size":25
}

Activiti7 output

{
  "_embedded" : {
    "tasks" : [ {
      "id" : "15568100-1652-11e8-aeb9-0a586460020b",
      "name" : "Perform action",
      "priority" : "50",
      "processDefinitionId" : "ProcessWithVariables:1:a47800c9-1651-11e8-aeb9-0a586460020b",
      "processInstanceId" : "155102ba-1652-11e8-aeb9-0a586460020b",
      "applicationName" : "rb-my-app",
      "status" : "CREATED",
      "lastModified" : "2018-02-22T10:38:12.153+0000",
      "_links" : {
        "self" : {
          "href" : "http://fakeurl/query/v1/tasks/15568100-1652-11e8-aeb9-0a586460020b"
        }
      }
    } ]
  },
  "_links" : {
    "first" : {
      "href" : "http://fakeurl/query/v1/tasks?page=0&size=1"
    },
    "self" : {
      "href" : "http://fakeurl/query/v1/tasks?page=0&size=1"
    },
    "next" : {
      "href" : "http://fakeurl/query/v1/tasks?page=1&size=1"
    },
    "last" : {
      "href" : "http://fakeurl/query/v1/tasks?page=1&size=1"
    }
  },
  "page" : {
    "size" : 1,
    "totalElements" : 2,
    "totalPages" : 2,
    "number" : 0
  }
}

I've faked the url

**Comment by Salaboy** [comment]
@mauriziovitale is there any action to be performed here? can we create more concrete issues if there are fields missing?
