### ISSUE TITLE
Add REST APIs to create standalone task

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#1803]

**Comment by lucianoprea** [comment]
List of the PRs

- https://github.com/Activiti/activiti-cloud-runtime-bundle-service/pull/48
- https://github.com/Activiti/activiti-cloud-query-service/pull/35
- https://github.com/Activiti/activiti-cloud-acceptance-tests/pull/9

**Comment by Salaboy** [comment]
merged in develop
