### ISSUE TITLE
TaskList REST API response is different from the query and Runtimebundle end point

### ISSUE THREAD

**Issue by mauriziovitale** [Activiti/Activiti#1804]
The query endpoint 
http://{{domain}}/query/v1/tasks
returns

```json
{
    "id": "5727b473-1d4c-11e8-bfd1-0a5864600111",
    "assignee": "hruser",
    "name": "Perform action",
    "priority": "50",
    "processDefinitionId": "ProcessWithVariables:1:01b7e8b4-1d4c-11e8-bfd1-0a5864600111",
    "processInstanceId": "5727664d-1d4c-11e8-bfd1-0a5864600111",
    "applicationName": "rb-my-app",
    "status": "ASSIGNED",
    "lastModified": "2018-03-02T11:57:05.511+0000"
    }
}
```
- <del>The createdDate is missing</del>
- The createdAt is missing
- The owners is missing

The runtimebundle instead 
http://{{domain}}/rb-my-app/v1/tasks
```json
{
    "id": "5727b473-1d4c-11e8-bfd1-0a5864600111",
    "assignee": "hruser",
    "name": "Perform action",
    "createdDate": "2018-03-01T12:30:35.173+0000",
    "claimedDate": "2018-03-02T11:57:05.510+0000",
    "priority": 50,
    "processDefinitionId": "ProcessWithVariables:1:01b7e8b4-1d4c-11e8-bfd1-0a5864600111",
    "processInstanceId": "5727664d-1d4c-11e8-bfd1-0a5864600111",
    "status": "ASSIGNED",
}
```
- the applicationName is missing
- the lastModified is missing
- the owners is missing

**Comment by erdemedeiros** [comment]
The one implementing this please make sure that rest docs tests are updated in consequence.

**Comment by mauriziovitale** [comment]
As discussed with @erdemedeiros the createdDate is the lastModified when the status is COMPLETED

**Comment by erdemedeiros** [comment]
@mauriziovitale you probably meant `completedDate`, not `createdDate ` :)

**Comment by Salaboy** [comment]
@erdemedeiros @mauriziovitale what is the status of this one?

**Comment by mauriziovitale** [comment]
http://{{domain}}/rb-my-app/v1/tasks
```json
"entry": {
                    "id": "be956780-2d3c-11e8-966f-0a586460030f",
                    "name": "Investigate hardware",
                    "createdDate": 1521659955355,
                    "priority": 50,
                    "processDefinitionId": "fixSystemFailure:1:f9c78164-2d38-11e8-966f-0a586460030f",
                    "processInstanceId": "be8ed7c5-2d3c-11e8-966f-0a586460030f",
                    "status": "CREATED"
                }
```
Missing field:
**lastModified**

http://{{domain}}/query/v1/tasks
```json
 "entry": {
                    "id": "be956780-2d3c-11e8-966f-0a586460030f",
                    "name": "Investigate hardware",
                    "priority": "50",
                    "processDefinitionId": "fixSystemFailure:1:f9c78164-2d38-11e8-966f-0a586460030f",
                    "processInstanceId": "be8ed7c5-2d3c-11e8-966f-0a586460030f",
                    "applicationName": "rb-my-app",
                    "status": "CREATED",
                    "lastModified": 1521659955358
                }
```
Missing field:
**createdDate**
**Priority** is a string and not a number

**Comment by Salaboy** [comment]
we need to review this for Beta2 with @erdemedeiros and @mauriziovitale

**Comment by salaboy** [comment]
@erdemedeiros ok.. lastModified difference is ok in my opinion, as well as metadata from the application. 
As a general guideline Query is ok to have a superset of information contained in the RB. 

This two differences needs to be fixed
- createdDate
- priority (type)

**Comment by erdemedeiros** [comment]
@mauriziovitale @salaboy I've check against Beta4 and contents are now the same, except for lastModifiedDate that is present in query, but not in runtime bundle.

**Comment by salaboy** [comment]
@erdemedeiros and that is correct, because lastModified is something that is generated only on the query side. so it is ok to close this issue.
