### ISSUE TITLE
activiti-cloud-examples: Postman collection does not set the kcAccessToken into the getKeycloakToken

### ISSUE THREAD

**Issue by fcorti** [Activiti/Activiti#1807]
I'm working with a vanilla Ubuntu OS with the Activiti 7 installed as described from the Developer Guide (quickstart guide).
I'm using Postman version 6.0.8 as Desktop app (and the problem should be related to the new major version of Postman).

Once executed the `getKeycloakToken` service, the JSON response is positive and complete, but no tests are executed. This causes all the following request to be unauthorised because no valid token is available in the environment.

The issue is related to a different change of syntax in developing the tests on the newest versions of postman.

Replacing the source code starting at:

https://github.com/Activiti/activiti-cloud-examples/blob/7e9b40b5ad04eddfe777a30509d9d9c53a38456c/Activiti%20v7%20REST%20API.postman_collection.json#L156

With:

```
pm.test("Setting the kcAccessToken.", function () {
  var tokens = JSON.parse(responseBody);
  pm.globals.set("kcAccessToken", tokens.access_token);
});
```

Everything is running fine and the `kcAccessToken` is correctly set up.

**Comment by ryandawsonuk** [comment]
Suggest we change it to:

var tokens=JSON.parse(responseBody); 
postman.setGlobalVariable("kcAccessToken", tokens.access_token); 
pm.test("Setting the kcAccessToken.", function () {
  var tokens = JSON.parse(responseBody);
  pm.globals.set("kcAccessToken", tokens.access_token);
});

I've checked this in v5 and Francesco Corti has checked it in v6 of postman
