### ISSUE TITLE
The Process Instance Model REST API doesn't work

### ISSUE THREAD

**Issue by mauriziovitale** [Activiti/Activiti#1808]
When I try to call the endpoint 
http://{{domain}}/rb-my-app/v1/process-instances/{processId}/model
with content type image/svg+xml.
I'm getting this error:
<body>
        <h2>HTTP ERROR 406</h2>
        <p>Problem accessing /error. Reason:

            <pre>    Not Acceptable</pre>
        </p>
        <h3>Caused by:</h3>
        <pre>org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:986)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:870)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:855)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

<img width="821" alt="screen shot 2018-03-05 at 14 15 23" src="https://user-images.githubusercontent.com/14923305/36979699-2cc0a042-2080-11e8-8267-ef16b66f6069.png">

**Comment by constantin-ciobotaru** [comment]
PRs: https://github.com/Activiti/example-runtime-bundle/pull/11 and https://github.com/Activiti/activiti-cloud-acceptance-tests/pull/8

**Comment by Salaboy** [comment]
@constantin-ciobotaru can we close this right? if this is still not solved open a new one to fix it, but both PRs are merged now

**Comment by mteodori** [comment]
still not working on the deployed env, reopening

**Comment by mauriziovitale** [comment]
the model API works fine for the process definition of a type "ProcessWithVariables" but it doesn’t work if the instance is of type fixSystemFailure.

The latest one is a process that contains a subprocess.
https://github.com/Activiti/example-runtime-bundle/blob/develop/src/main/resources/processes/SubProcessTest.fixSystemFailureProcess.bpmn20.xml

**Comment by constantin-ciobotaru** [comment]
The second issue found for the "fixSystemFailure" process is different than the first one and appears because the the process doesn't have graphic info stored in xml file. Accordingly with discussions with @Salaboy and @mteodori, I've fixed it by returning a default SVG image when there is no graphic info available for the process.

**Comment by constantin-ciobotaru** [comment]
PR for the second issue: https://github.com/Activiti/activiti-cloud-runtime-bundle-service/pull/51

**Comment by constantin-ciobotaru** [comment]
more PRs: https://github.com/Activiti/Activiti/pull/1868 and https://github.com/Activiti/activiti-cloud-acceptance-tests/pull/11

**Comment by Salaboy** [comment]
same here.. all the PRs are merged. I'm closing it, if this is still not working please reopen @constantin-ciobotaru @mauriziovitale
