### ISSUE TITLE
The Runtimebundle REST API should have a fixed root

### ISSUE THREAD

**Issue by mauriziovitale** [Activiti/Activiti#1811]
At the moment there is no fixed root for the API under the runtime bundle. 
For instance, if we have two runtime bundles "_rb-my-app-1_" and "_rb-my-app-2_"  the tasks API should be like:
**to do**
/runtime/rb-my-app-1/v1/tasks
/runtime/rb-my-app-2/v1/tasks
**as is**
/rb-my-app-1/v1/tasks
/rb-my-app-2/v1/tasks

**Comment by Salaboy** [comment]
This is related with the application service.. so we might move this one to beta2

**Comment by salaboy** [comment]
@mauriziovitale can you please report that to the APS team, this is not even defined in the community side. That is part of the gateway component in community which is not being used by APS, so I am closing this because there is not much that we can do in community.
