### ISSUE TITLE
Activiti-spring-boot-starter-basic fails to coincide with Spring boot 2.0

### ISSUE THREAD

**Issue by grath10** [Activiti/Activiti#1826]
When working with Spring Boot 2.0, org.activiti:activiti-spring-boot-starter-basic :6.0.0 starters seems to give out errors in that SecurityAutoConfiguration depends on SecurityAutoConfiguration class.
But the package has been renamed in Spring Boot 2.0, so class can not be found.
Please fix the bug, thx!

**Comment by ryandawsonuk** [comment]
v6 wasn't written to support spring boot 2.0 but v7 is. The equivalent of the starter-basic is starter-configure if you're looking for the same behaviour you had with the v6 boot starter. Or if you're interested in going cloud-native then have a look at https://community.alfresco.com/community/bpm/blog/2018/02/27/activiti-cloud-overview-blueprint and join the conversation on https://gitter.im/Activiti/Activiti7

**Comment by grath10** [comment]
Thx for your reply. According to your reply, I'd like to switch to Activiti v7. Thx again!
