### ISSUE TITLE
Show how to use Activiti Cloud Query with custom data

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1839]
Let’s say you have an Account Opening use-case. Imagine that only premium customers are allowed more than one account and the customer system owns that data. Then you might have BPMN like:

[accountOpening.bpmn20.xml.zip](https://github.com/Activiti/Activiti/files/1841528/accountOpening.bpmn20.xml.zip)

![image](https://user-images.githubusercontent.com/22754674/37829761-46d6517c-2e98-11e8-9a03-99e44f1c74ab.png)

The service tasks can be implemented as microservices using connectors. 

The customer system has its own database. Here the customer system decides whether a new account is allowed to be opened.

How can I search for customers in e.g. Australia that had new account requests rejected? Or which member of staff recently entered most account opening requests for premium customers?

To do that I need customer data and process data in the same place or sufficiently linked to query on.

There are lots of scenarios for this but a powerful example would be to have Customer create/update page and have the customer system send events that are consumed by a common query component that also consumes Activiti events. This could be done by implementing the query project as a spring boot project that consumes customer events as streams and also has the EnableActivitiQuery annotation. Then the spring entities will automatically be added to the GraphQL schema by [GraphQL JPA](https://github.com/introproventures/graphql-jpa-query). The customer system could be a simple spring boot app, perhaps with a simple embedded UI (maybe a JHipster app).

Alternatively we could add to the trending topics example and have a ‘Rewarded Users’ database that tracks who got rewards and perhaps their locations and number of followers (or the handles of their followers?). Or maybe do both. I personally think it would be easier to grasp as part of its own example.

**Comment by salaboy** [comment]
@ryandawsonuk this is what we tried to do in TTC right -> "I personally think it would be easier to grasp as part of its own example."

**Comment by ryandawsonuk** [comment]
TTC is now illustrating some [custom querying](https://github.com/Activiti/ttc-query-campaign/blob/master/src/main/java/org/activiti/cloud/query/repository/ExtendedProcessInstanceRepository.java#L16) in the query module but the queries are still only on process instances and variables. The idea would be to also include custom domain objects in the queries.

**Comment by ryandawsonuk** [comment]
I suggest we close this for now as not a priority as it seems community members are doing custom querying (e.g. https://github.com/Activiti/Activiti/issues/2571) and there hasn't yet been any specific demand for custom domain objects to be handled in their own table structure (as opposed to as variables)

**Comment by ryandawsonuk** [comment]
Very relevant in this space is investigations that @igdianov has been doing to add extra data sources to the graphql module
