### ISSUE TITLE
REST API should not use commands as body content

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#1842]
When calling a REST endpoint the user shouldn't need to worry that's ca command. For instance, to start a process instance `v1/process-instances` the field `commandType` should not be necessary.
Change request body from
```json
{
  "processDefinitionId": "myProcess:1:de119197-2c4c-11e8-8ed7-0242ac120005",
  "variables": {
    "firstName": "John",
    "lastName": "Doe",
  },
  "commandType":"StartProcessInstanceCmd"
}
```
to 
```json
{
  "processDefinitionId": "myProcess:1:de119197-2c4c-11e8-8ed7-0242ac120005",
  "variables": {
    "firstName": "John",
    "lastName": "Doe",
  }
}
```

**Comment by Salaboy** [comment]
@erdemedeiros do we know how to fix this? it sounds like a marshalling/jackson specific problem.. not sure how to deal with this now.

**Comment by erdemedeiros** [comment]
@Salaboy I would change the [controller interface](https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-api/src/main/java/org/activiti/cloud/services/rest/api/ProcessInstanceController.java#L26) to don't use commands, but payloads:

```java
Resource<ProcessInstance> startProcess(@RequestBody StartProcessInstanceCmd cmd);
```
becomes:

```java
Resource<ProcessInstance> startProcess(@RequestBody ProcessInstancePayload payload);
```

Then in the [controller implementation](https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/ProcessInstanceControllerImpl.java#L110)   create the command from the given payload:

```java
return resourceAssembler.toResource(processEngine.startProcess(new StartProcessInstanceCmd(payload)));```

What do you think?

**Comment by Salaboy** [comment]
@erdemedeiros what about StartProcessInstancePayload? because each action will have it's own payload type (It is not just a ProcessInstance entity). Remember that these are the same that we use in the messaging endpoints.. so we need to make sure that we unify those.

**Comment by lijing666** [comment]
Maybe this is a jackson bug or jackson use problem, I found that bug too, like this problem: https://stackoverflow.com/questions/49071166/jackson-java-util-optional-serialization-does-not-include-type-id

**Comment by Salaboy** [comment]
@lijing666 thanks for the suggestion, but I don't see if this can be fixed in our side for now. 
If you have a suggestion/fix that allows us to remove the subclass type from the json body, that will be a great community contribution. 

I'm closing this because there is not much that we can do on our side.
