### ISSUE TITLE
a cloud 'task listener' example

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1846]
It's 'task listener' and not task listener because I'm thinking there would be no need to use the extension in the BPMN.

Listeners are quite common in Activiti examples and in implementations. Especially using a task listener to set the assignee of a user task. It probably won't be obvious how to do this in a cloud-native way i.e. without the listener logic being on the same classpath as the engine. But we can do it by consuming an event and calling out to the runtime bundle to tell it to change the assignee (either by http or messaging - http seems better here so as to get an acknowledgement).

We should be aware of this note from Activiti in Action:

"The order of events for a user task is maybe not what you would expect. The first event that’s thrown is the assignment event. After the assignment is handled, the user task create event is fired. When the user task assignment is changed in the task listener, a new assignment event will be thrown. Only change the assignment of the user task in a create event. When it’s done inside an assignment event, a StackOverflowError exception is thrown in the Activiti Engine, because the assignment event is then called in a loop"

Not a problem, just means we need to listen for the create event

**Comment by salaboy** [comment]
this is done in the new API, so closing
