### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1847]
Many of our controllers handle errors like:

    @ExceptionHandler(ActivitiObjectNotFoundException.class)
    @ResponseStatus(HttpStatus.NOT_FOUND)
    public String handleAppException(ActivitiObjectNotFoundException ex) {
        return ex.getMessage();
    }

The disadvantage of this is that it returns a content type of hal or json but it's neither. It's just plain text. We should really return an error object through Resource<Error>. We should have an Error class at common level that has at least a message and status code. The alfresco guidelines define more but this would get us started.

**Comment by ryandawsonuk** [comment]
To reproduce this issue try submitting a GET request to one of the endpoints in runtime bundle, query or audit for which there is no record corresponding to the submitted id. The response body should be formatted according to the content type rather than returning plain text.

**Comment by ryandawsonuk** [comment]
To reproduce this issue try submitting a GET request to one of the endpoints in runtime bundle, query or audit for which there is no record corresponding to the submitted id. The response body should be formatted according to the content type rather than returning plain text.

In fixing this we could add tests to or alter existing tests in runtime-bundle-service, query-service and audit-service.

**Comment by salaboy** [comment]
@erdemedeiros @ryandawsonuk is there something that we can do for this for M1? can you describe which controllers can be improved and maybe help @miguelruizdev to take a look at this?

**Comment by miguelruizdev** [comment]
Done
