### ISSUE TITLE
use autoconfiguration in spring boot starters

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1850]
We would be better not to use annotations like @EnableActivitiQueryService and similar for RB and Audit. Instead we should use Autoconfiguration. 

Using @EnableActivitiQueryService (https://github.com/Activiti/activiti-cloud-query/blob/develop/src/main/java/org/actviti/cloud/query/QueryApplication.java#L30 ) ends up breaking the autoconfiguration

Because it imports configuration classes

https://github.com/Activiti/activiti-cloud-query-service/blob/d2687bedaeacb7aabd0c5bc5bf84f8b7fbececf4/activiti-cloud-services-query/activiti-cloud-services-query-graphql/src/main/java/org/activiti/cloud/services/query/graphql/autoconfigure/EnableActivitiGraphQLQueryService.java#L35

But you want to only conditionally load that configuration if the relevant property is set https://github.com/Activiti/activiti-cloud-query-service/blob/develop/activiti-cloud-services-query/activiti-cloud-services-query-graphql/src/main/java/org/activiti/cloud/services/query/graphql/autoconfigure/ActivitiGraphQLAutoConfiguration.java#L46 as per the autoconfiguration. We can follow this example in Query and also refer to https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-auto-configuration.html

If we switched to this model across the services then it would be easier to turn on/off these behaviours by properties and for autoconfiguration order to be controlled. I think we could also get rid of the [@ComponentScans](https://github.com/Activiti/Activiti/issues/1399)

**Comment by Salaboy** [comment]
Ok this sounds really good. 
We just want to make sure that there is a way to enable this.. that was the main reason for the annotations.

**Comment by Salaboy** [comment]
Be careful, why other starters in spring are using the @enable.. approach then?

**Comment by ryandawsonuk** [comment]
Interesting question. To make an application a Spring Cloud Config Server you add [@EnableConfigServer](https://github.com/spring-cloud/spring-cloud-config/blob/465bc949534d1ad48bfa20ae5ba947803796a5e9/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/EnableConfigServer.java). But to make an application a client of the config server you don't add any annotation, just the starter and the [autoconfiguration](https://github.com/spring-cloud/spring-cloud-config/blob/123011d7d55ad93aba4dfe044380683e719bd7ef/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigClientAutoConfiguration.java) takes care of it. There is [autoconfiguration](https://github.com/spring-cloud/spring-cloud-config/blob/master/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/config/ConfigServerAutoConfiguration.java) for the config server too but it doesn't seem to come into effect without the enableconfigserver

**Comment by Salaboy** [comment]
Exactly.. we are using the @Enable annotations because we are like the @EnableConfigServer. Exactly the same.. we are not a client of the server.. 
We should have the AutoConfigurations in the back for sure. 
So we all understand what the approach is? I think that what causes confusion is that Autoconfigurations are just broken because our @Enable annotations are not correctly implement just yet.

**Comment by ryandawsonuk** [comment]
For query in particular (which is where this convo with Igor started) it makes sense if the @enablequery turns on event consumption and REST and the GraphQL stuff is autoconfig that you can turn off by property. It seems when you want to turn off a whole piece by property then you don't use @Enable. (To get around it I had been putting conditionalonprperty in lots of places but that should be unnecessary.)
