### ISSUE TITLE
On the source of the war package program in activiti-6.0.0.zip

### ISSUE THREAD

**Issue by yanwencheng** [Activiti/Activiti#1861]
I downloaded activiti resources in official website, including activiti-admin war package. I want to know if there is an open source project of war package in GitHub.

**Comment by daisuke-yoshimoto** [comment]
@yanwencheng 
Probably, this url.
https://github.com/Activiti/Activiti/tree/activiti-6.0.0/modules/activiti-admin

**Comment by yanwencheng** [comment]
@daisuke-yoshimoto What development tools should I use to modify and build?

**Comment by Salaboy** [comment]
@yanwencheng just maven and the ant scripts. 
This is not an issue so I will close it to avoid conflicts
