### ISSUE TITLE
make audit read permission error consistent with query and RB

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1862]
If I try to do a read on a record in RB or query and I don't have permission to read it I get a 404.  But not in audit.

There's a point in the audit code where it throws a RuntimeException - https://github.com/Activiti/activiti-cloud-audit-service/blob/develop/activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/controllers/AuditEventsControllerImpl.java#L89

It should handle it like https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/ProcessInstanceControllerImpl.java#L68 and those exception types should be moved to common

**Comment by salaboy** [comment]
merged in develop
