### ISSUE TITLE
SecurityPoliciesApplicationService to be moved to common

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1863]
In RB it uses a SecurityPoliciesProcessDefinitionRestrictionApplier interface to implement restrictions:

https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-services-runtime-bundle/activiti-cloud-services-core/src/main/java/org/activiti/cloud/services/core/SecurityPoliciesApplicationService.java

The one in query implements this differently but seems like it could do so using a common interface:

https://github.com/Activiti/activiti-cloud-query-service/blob/develop/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/security/SecurityPoliciesApplicationService.java

Likewise for the two implementations (JPA and Mongo) in audit:

https://github.com/Activiti/activiti-cloud-audit-service/blob/develop/activiti-cloud-services-audit/activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/security/SecurityPoliciesApplicationService.java

https://github.com/Activiti/activiti-cloud-audit-service/blob/develop/activiti-cloud-services-audit/activiti-cloud-services-audit-mongo/src/main/java/org/activiti/cloud/services/security/SecurityPoliciesApplicationService.java

It might be we also want a common abstract parent and specific implementations

**Comment by Salaboy** [comment]
merged in develop
