### ISSUE TITLE
MybatisHistoricActivityInstanceDataManager

### ISSUE THREAD

**Issue by SashaAV** [Activiti/Activiti#1864]
Hi!
A have found mistake in class MybatisHistoricActivityInstanceDataManager
You have two methods with same statement:

`public List<HistoricActivityInstanceEntity> findUnfinishedHistoricActivityInstancesByExecutionAndActivityId(final String executionId, final String activityId)`

and 

```
public List<HistoricActivityInstanceEntity> findUnfinishedHistoricActivityInstancesByProcessInstanceId(final String processInstanceId)
have statement selectUnfinishedHistoricActivityInstanceExecutionIdAndActivityId

```

 but in HistoricActivityInstance.xml they are different:

`selectUnfinishedHistoricActivityInstanceExecutionIdAndActivityId`

and 

`selectUnfinishedHistoricActivityInstanceByProcessInstanceId`

I'm using: name: 'activiti-engine', version:'6.0.0'

**Comment by Salaboy** [comment]
@balsarori can you check this issue? has this been fixed?

**Comment by balsarori** [comment]
@SashaAV thanks for reporting the issue. Indeed it seems to be a typo. Unit tests run green in both cases. Was there a specific issue that lead you to find this?

**Comment by SashaAV** [comment]
I have found this during implement aerospike data modules.
So in my implementation I have found this duplicate statement

**Comment by salaboy** [comment]
@SashaAV @balsarori can we close this then?

**Comment by SashaAV** [comment]
I suppose yes, if you don't have an error
