### ISSUE TITLE
how to use activiti 6 together with spring boot 2

### ISSUE THREAD

**Issue by bjstcm** [Activiti/Activiti#1869]
does activiti 6 compatible with Spring boot 2

**Comment by Salaboy** [comment]
@bjstcm hi there, we are working on activiti 7 to be fully compatible with spring boot 2 and spring cloud. Activiti 6 spring boot starter works with spring boot 1.5. I will close this issue because you asked a question. usually it is recommened to ask questions in the forums. 
Cheers
