### ISSUE TITLE
'Fully qualified' component names using application name, version and component name

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1870]
1) Component names

It should be possible to mark each service as part of an application and for the application name to be part of what identifies the service. So for example a runtime bundle 'rb1' might need to be identified as 'app1-v1-rb1' - this is the 'fully qualified' name (or possibly 'app1-v1-rb1-v1'). For query and audit the app name should be optional as we may want to use those components as shared across apps and/or versions. For RBs we can assume there will always be an app name and version.

This can in part be handled by passing in a fully qualified name into the SPRING_APPLICATION_NAME. But we should also have properties that identify the app name, version and rb name separately.

Suggested properties:

activiti.cloud.component.type      (can be 'activiti-runtime-bundle','activiti-query','activiti-audit' - just for tracking and will correspond to kub serviceType label in deploy https://github.com/Activiti/activiti-cloud-examples/blob/master/kubernetes/kubectl/application.yml#L7)
activiti.cloud.component.name   (can be e.g. 'rb1' or 'query' - should not be fully qualified)
activiti.cloud.application.name
activiti.cloud.application.version
activiti.cloud.component.version
spring.application.name                (expected to be fully qualified)

Note all of these will be set by environment variables so that their values can be determined by the deployment descriptor

2) Message Channels

Message channel names should be able to be set via environment variables so that they can also be fully qualified. The specific name used for a channel should be decided in the deployment descriptor.

3) Events

Event data emitted by RBs should contain app name and version as well as RB name

4) Config

Components should find the right config corresponding to their name and version.

**Comment by Salaboy** [comment]
I would suggest the following properties based on my spike on the app service:
- spring.application.name -> which is the service name
- activiti.cloud.service.version -> which indicates the version of the service
- activiti.cloud.service.type (audit, query, connector, domain/custom)
- activiti.cloud.application.name 
- activiti.cloud.application.version

**Comment by Salaboy** [comment]
With those properties as metadata in the service registry we can do a lot of stuff.
Now the question is if we want to include the version in the service name, and that might be a yes to support multiple versions of the same service to be up and running.

**Comment by ryandawsonuk** [comment]
So basically use 'service' instead of 'component' and just start with these

**Comment by ryandawsonuk** [comment]
Re 3 above, the event stream names are already externalised and would just need to be set from the deployment descriptors 
https://github.com/Activiti/example-runtime-bundle/blob/develop/src/main/resources/application.properties#L5
https://github.com/Activiti/activiti-cloud-audit/blob/master/src/main/resources/application.properties#L4
https://github.com/Activiti/activiti-cloud-query/blob/master/src/main/resources/application.properties#L6

**Comment by ryandawsonuk** [comment]
Query is proving more complex than anticipated. I've started changes there to handle the event metadata. What it is turning up is that 'applicationName' as it is used in query is ambiguous.

For the purposes of the notification routing, I think it needs to be the fully qualified service name. I am not sure if that imposes any restrictions on what format and separators we could use for FQNs.

For security policies applicationName is being used to mean short service name. But this actually won't work going forward. An example policy is:

ACTIVITI_CLOUD_SECURITY_GROUP_HR_RB1_POLICY_READ=SimpleProcess

but there could be two Applications that both contain a service called RB1. The 'RB1' could be replaced with the FQN but then we have to find an FQN format that can work when injected with environment variables like this - I think meaning that the obvious choices for separators would be ruled out. Simply using applicationName would work. Application name would be mandatory if you want to use security policies but presumably users wanting to use security policies would be happy to set an application name.

**Comment by ryandawsonuk** [comment]
From query/v1/process-instances
![image](https://user-images.githubusercontent.com/22754674/39133067-35c746bc-470b-11e8-8b1a-e500d37dc11f.png)
From audit/v1/events
![image](https://user-images.githubusercontent.com/22754674/39133097-4b37df8e-470b-11e8-8817-7967541b3960.png)
I didn't specify version. The type is blank because that's set in a different pull request (the metadata ones also referenced here). For these attributes the blanks are being inserted even when there's no value. To change that we'd need to either change RuntimeBundleProperties, the converters in RB service or (more likely) both.

**Comment by ryandawsonuk** [comment]
Doing a [remote debug](https://github.com/Activiti/activiti-cloud-query/pull/6#issuecomment-383859262) suggests that the transformer is the problem:
![image](https://user-images.githubusercontent.com/22754674/39180421-be23c69a-47ae-11e8-8bf3-f48f88763dbc.png)

**Comment by ryandawsonuk** [comment]
It does work when all of the service and app attributes are in the routing key. And using '.' in the version doesn't appear to cause any problems, even though that's a separator in the routing key code.

![image](https://user-images.githubusercontent.com/22754674/39184981-6c4d2500-47bd-11e8-8260-57eb811eed3b.png)

**Comment by ryandawsonuk** [comment]
Actually there does seem to be a problem when specifying restrictions on the subscription. I should be able to get result for the below (or on variations with some of the items removed) but I'm not getting matches:
`subscription {
  ProcessEngineNotification(
	     serviceName: "rb-my-app",
       serviceFullName: "rb-my-app",
       serviceVersion: "0.2",
       appName: "app",
       appVersion: "0.1",
       processDefinitionId: "SimpleProcess:1:0dd1ea9a-47ba-11e8-9c2f-0242ac120009"
   ) {
    processInstanceId,   
    serviceName, 
    processDefinitionId    
    TaskCreatedEvent {
      executionId, timestamp
      task { name }
    }
    TaskAssignedEvent {
      executionId, timestamp
      task { name, assignee }
    }
}
}`

**Comment by ryandawsonuk** [comment]
I've now gone back to taking the versions out of the routing key.

I am able to see that data in an unrestricted subscription:
![image](https://user-images.githubusercontent.com/22754674/39190630-e2753e02-47cc-11e8-9620-12f7713afd3a.png)
and am also able to get restricted subscriptions working:
![image](https://user-images.githubusercontent.com/22754674/39190731-1d505426-47cd-11e8-8611-af37ee41ca71.png)

**Comment by ryandawsonuk** [comment]
The changes to security policies are now included so that they can match on long or short name. Outstanding is the concern that app version and service version are populated with empty string when omitted. Makes sense for these to be optional so would like to change RuntimeBundleProperties so that it stops putting that empty string in there.
