### ISSUE TITLE
[Core] Application Service working in Kubernetes with spring-cloud-k8s

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#1871]
We need to make sure that the Application Service project in the incubator also works in kubernetes and not only with Eureka and Spring Cloud Config

**Comment by Salaboy** [comment]
Initial work done for Beta1, more polishing is needed for beta2

**Comment by salaboy** [comment]
We need to do the infrastructure work of adding the HELM charts and the routing

**Comment by mteodori** [comment]
obsolete
