### ISSUE TITLE
Process Instances Model is not working with the Accept Image/svg

### ISSUE THREAD

**Issue by mauriziovitale** [Activiti/Activiti#1872]
When I call the api 

http://{{domain}}/myapp-rb/v1/process-instances/4159a15f-3f1b-11e8-aa83-0a586460031e/model
Accept image/svg+xml

I'm getting a 406 error.

The API is working fine if I have in the header 
Content-Type  image/svg+xm

**Comment by erdemedeiros** [comment]
Fix: remove `consumes` from [@RequestMapping](https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-api/src/main/java/org/activiti/cloud/services/rest/api/ProcessInstanceController.java#L34).
It's a `GET` so it's not consuming anything.

**Comment by lucianoprea** [comment]
changes in this [PR](https://github.com/Activiti/activiti-cloud-runtime-bundle-service/pull/7/files) introduced the Content-Type and I thinks it should be reviewed again to fix this problem everywhere

**Comment by salaboy** [comment]
@mauriziovitale this is working correctly in Beta4. 
Correctly means:
- if you don't add Accept header it will return a image/svg+xml content
- if you add Accept: image/svg+xml it will return correctly
- if you add Accept: application/json it will return 406 not acceptable
