### ISSUE TITLE
When I created the MySQL database (two database ), the property of databaseSchemaUpdate don't working.

### ISSUE THREAD

**Issue by clickear** [Activiti/Activiti#1875]
Sorry for my poor English.
When i create two catalog, It only create one catalog scheme.
It need to add the property of databaseCatalog.But the document is not explained

**Comment by Salaboy** [comment]
@clickear hi there, can you please provide more information? Which version are you using? 
How can we reproduce that problem?

**Comment by clickear** [comment]
i create two database, eg activitidemo1 , activitidemo2

**Comment by Salaboy** [comment]
@clickear ok, but it is not clear what do you want to achieve by having two databases. Can you explain why do you need to have those 2 databases?

**Comment by Salaboy** [comment]
@daisuke-yoshimoto you probably can help here, have you seen this scenario before?

**Comment by daisuke-yoshimoto** [comment]
@Salaboy 
Perhaps it is a multi-tenant use case.
For dividing the database for each tenant, there are two methods below.

1. Creating an instance of the process engine for each tenant -> I'm using this method.

2. Use MultiTenantProcessEngineConfiguration
http://www.jorambarrez.be/blog/2015/10/06/multi-tenancy-separate-database-schemas-in-activiti/
https://github.com/Activiti/Activiti/issues/1537

**Comment by Salaboy** [comment]
@clickear did you tried the method suggested by @daisuke-yoshimoto ?
