### ISSUE TITLE
Improvement - Error "Condition expression returns null"

### ISSUE THREAD

**Issue by roneigebert** [Activiti/Activiti#1876]
I suggest adding the sequenceFlowId in the exception message (UelExpressionCondition.java). Why? To easily find the sequence flow with error.

Or change the code:
```java
public boolean evaluate(String sequenceFlowId, DelegateExecution execution) {
    Object result = expression.getValue(execution);
     return Boolean.TRUE.equals( result );
  }
```

**Comment by balsarori** [comment]
@roneigebert makes sense to add the sequenceFlowId to the thrown exception. Can you create a PR for that?

**Comment by roneigebert** [comment]
@balsarori  https://github.com/Activiti/Activiti/pull/1877

**Comment by balsarori** [comment]
@roneigebert thanks!

If you can also create PRs for 5.x and 6.x branches that will great.

**Comment by roneigebert** [comment]
@balsarori  https://github.com/Activiti/Activiti/pull/1878 (5.x), https://github.com/Activiti/Activiti/pull/1879 (6.x)

**Comment by Salaboy** [comment]
merged the one in develop

**Comment by balsarori** [comment]
merged PRs on 5.x and 6.x 
Thanks @roneigebert 

@Salaboy can you look into the PR for develop?

**Comment by Salaboy** [comment]
@balsarori merged already.. 
can we add in a separate issue and PR the execution ID as suggested by @daisuke-yoshimoto ?
I'm closing this one, because all PRs were merged.

**Comment by balsarori** [comment]
@Salaboy what about this one https://github.com/Activiti/Activiti/pull/1882 ?
