### ISSUE TITLE
Make Modeling REST API return responses conform to Alfresco guidelines

### ISSUE THREAD

**Issue by constantin-ciobotaru** [Activiti/Activiti#1880]

**Comment by mteodori** [comment]
PR:
* Activiti/activiti-cloud-build#45
* Activiti/activiti-cloud-org-service#12
* Activiti/activiti-cloud-modeling#8

**Comment by constantin-ciobotaru** [comment]
The correct list of PRs is:
https://github.com/Activiti/activiti-cloud-build/pull/45
https://github.com/Activiti/activiti-cloud-modeling/pull/8
https://github.com/Activiti/activiti-cloud-org-service/pull/13
https://github.com/Activiti/activiti-cloud-process-model-service/pull/13

**Comment by constantin-ciobotaru** [comment]
All PSs merged.
