### ISSUE TITLE
can't understand  TaskService to query Task 

### ISSUE THREAD

**Issue by pressmore** [Activiti/Activiti#1881]
recently , i use TaskService to query Tasks , i meet a trouble i cannot figure it out.

description: i use code as below  to search myTasks,  i cannot found any tasks but it absolutely exist in db.  
`	
              
    public static List<Task> getMyTasks(String userId) {

		TaskService taskService = processEngine.getTaskService();

		TaskQuery taskQuery = taskService.createTaskQuery();

		return taskQuery.taskAssignee(userId).orderByTaskDueDate().asc().list();
	}
`
i try many ways, but it's still have problems, anybody have ever meet this question ? 

wait help ! thanks !

**Comment by pressmore** [comment]
used activiti version: 6.0.0

**Comment by pressmore** [comment]
sorry. i just want obtain much attention. sorry.  

 in db, it exist task records assgeed to specify user, but i cannot found any result with same user by previous method .

applogize for my behaviour and my poor english.

**Comment by Salaboy** [comment]
@pressmore, no worries, but there are better channels for asking those questions. Can you share the code on how did you created the task?
Cheers

**Comment by pressmore** [comment]
#### @Salaboy  sir , i print the log when search myTasks , can you help me to explain it ? 

`
2018-42-25 09:42:32, 297 [org.activiti.engine.impl.persistence.entity.TaskEntityImpl.selectTaskByQueryCriteria] [DEBUG] ==>  Preparing: select distinct RES.* from ACT_RU_TASK RES WHERE RES.ASSIGNEE_ = ? order by RES.DUE_DATE_ asc LIMIT ? OFFSET ? 
2018-42-25 09:42:32, 297 [org.activiti.engine.impl.persistence.entity.TaskEntityImpl.selectTaskByQueryCriteria] [DEBUG] ==> Parameters: liushengwei(String), 1000(Integer), 0(Integer)
2018-42-25 09:42:32, 297 [org.activiti.engine.impl.persistence.entity.TaskEntityImpl.selectTaskByQueryCriteria] [DEBUG] <==      Total: 0
`
#### this is my search code:

`taskQuery.taskAssignee(userId).orderByTaskDueDate().asc().listPage(0, 1000);`

my parameters of listPage have problem? why it will replace Limit with 1000, but OFFSET with 0???

####  i look forward to your reply

**Comment by pressmore** [comment]
@Salaboy  i confirm it caused by LIMIT and OFFSET , there  have any method to get rid of  LIMIT and OFFSET , such as : 
`select distinct RES.* from ACT_RU_TASK RES WHERE RES.ASSIGNEE_ = 'liushengwei' order by RES.DUE_DATE_ asc  ;
`

**Comment by Salaboy** [comment]
@pressmore you will need to create a reproducer, so we can reproduce the problem. 
@balsarori have you seen something like this before? I remember seeing something that was fixed already regarding limits and pages, but this looks a little bit different.

**Comment by daisuke-yoshimoto** [comment]
@pressmore 
How about the following method?

`taskQuery.taskCandidateUser(userId).orderByTaskDueDate().asc().list();`
