### ISSUE TITLE
request.getPathInfo() function question

### ISSUE THREAD

**Issue by wuweiit** [Activiti/Activiti#1883]
![image](https://user-images.githubusercontent.com/4202865/39233941-67950bf8-48a4-11e8-9bbb-54c9ac363654.png)

can look this page：
https://my.oschina.net/sub/blog/182408

**Comment by balsarori** [comment]
Can you explain the issue/question more? Unfortunately I couldn't understand the link you provided. Maybe @daisuke-yoshimoto can help :)

**Comment by Salaboy** [comment]
This looks to be a recommendation about how to get the PathInfo, but that in itself is not an issue, so we will close this unless it is properly reported as a bug or a feature request/enhancement.

**Comment by daisuke-yoshimoto** [comment]
@balsarori 

> Maybe @daisuke-yoshimoto can help :)

I'm sorry that I can not understand details as well as you becaseu this page is written in Chinese 😢

**Comment by wuweiit** [comment]
my project integration  activiti-spring-boot-starter-rest-api jar package .

DeploymentResourceResource.java

`String pathInfo = request.getPathInfo();`

debug startup project,  `pathInfo` equals null in my project， this page  describe  request.getPathInfo() and request.getServletPath()  difference 

sorry my english is poor. Maybe I understand it wrong.

**Comment by wuweiit** [comment]
if pathInfo equals null that invoke pathInfo.replace() throw NullPointerException.

**Comment by wuweiit** [comment]
suggest make verification  pathInfo not null

**Comment by Salaboy** [comment]
@wuweiit totally. Can you submit a PR with that verification? it is a great way to contribute with an open source project.
