### ISSUE TITLE
[Core] Update Acceptance tests for application service

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1887]
First need to be able to move project out of incubator by adding an autoconfiguration so we can use on registry and check that it is able to recognise metadata

**Comment by ryandawsonuk** [comment]
Screenshot from running using the referenced PRs
![image](https://user-images.githubusercontent.com/22754674/39365118-2b608dee-4a28-11e8-8952-a8aae3f86365.png)

**Comment by ryandawsonuk** [comment]
Let's aim for 'apps/v1/apps', 'apps/config' and 'apps/registry/apps' (which means changing the registry's spring.application.name to 'apps' or at least getting it to use a different route with the gateway and getting the eureka path changed to 'registry')

**Comment by ryandawsonuk** [comment]
Seems like we can't change the '/eureka' path (https://github.com/spring-cloud/spring-cloud-netflix/issues/2046). I tried changing dashboard path, serviceUrl.defaultZone and server.servlet.path but they don't change that 'eureka/apps'. 

(Sidenote - we may want to enable eureka reporting of health checks in our examples https://dzone.com/articles/the-mystery-of-eureka-health-monitoring )

**Comment by ryandawsonuk** [comment]
Will need a repo for the apps service and to add its deps to cloud-build then update registry to get version from cloud-build

**Comment by ryandawsonuk** [comment]
Current status of this is that the cloud-example setup from the PR works but it has apps service on different external port and not through GW. This is because it can't be a eureka client since then it comes into conflict with SCK client.

**Comment by Salaboy** [comment]
we have more work to do on this front.. @ryandawsonuk can we create a new issue for beta2?

**Comment by salaboy** [comment]
closing due the initial work was done. It needs to be refreshed after we add APP Service to HELM charts
