### ISSUE TITLE
Empty collections are not assembled like in spring data rest in case of HAL response

### ISSUE THREAD

**Issue by constantin-ciobotaru** [Activiti/Activiti#1891]
Expected response:
` {
  "_embedded" : {
    "strings" : [ ]
  },
  "_links" : {
    "self" : {
      "href" : "http://localhost/mock/empty-list?page=0&size=100"
    }
  },
  "page" : {
    "size" : 100,
    "totalElements" : 0,
    "totalPages" : 0,
    "number" : 0
  }
}`

Actual response:
`{
  "_links" : {
    "self" : {
      "href" : "http://localhost/mock/empty-list?page=0&size=100"
    }
  },
  "page" : {
    "size" : 100,
    "totalElements" : 0,
    "totalPages" : 0,
    "number" : 0
  }
}`

**Comment by Salaboy** [comment]
@constantin-ciobotaru @erdemedeiros so are we closing this issue and all the PRs? Or did I understood it wrong?

**Comment by constantin-ciobotaru** [comment]
Due to the fact that the default behavior of PagedResourcesAssembler.toResource() is to not add any _embedded element in response for empty collections, even if spring-data-rest add { "_embedded" : { "strings" : [ ] }, and because an eventual fix is more complex than expected implying to modify all controllers that use AlfrescoPagedResourcesAssembler, we decided to not fix this issue.
