### ISSUE TITLE
The API subtasks return a different response compared to the standard

### ISSUE THREAD

**Issue by mauriziovitale** [Activiti/Activiti#1893]
The api
http://{{domain}}/rb-my-app/v1/tasks/5f716c0b-5383-11e8-ab55-0a5864600352/subtasks
returns
```
{
    "links": [
        {
            ...
        }
    ],
    "content": [
        {
            "id": "ef2c3e4c-5385-11e8-ab55-0a5864600352",
            "assignee": "hruser",
            "createdDate": 1525869534321,
            "priority": 50,
            "parentTaskId": "5f716c0b-5383-11e8-ab55-0a5864600352",
            "status": "ASSIGNED"
       },
       {
            "id": "5c2cd61d-5388-11e8-ab55-0a5864600352",
            "assignee": "hruser",
            "createdDate": 1525870576190,
            "priority": 50,
            "parentTaskId": "5f716c0b-5383-11e8-ab55-0a5864600352",
            "status": "ASSIGNED"
       }]
}
```
I was expecting to have something like the getTasks API
```json
{
    "list": {
        "entries": [
            {
                "entry": {
                    "id": "397f2d88-5382-11e8-ab55-0a5864600352",
                    "assignee": "hruser",
                    "createdDate": 1525867941029,
                    "priority": 50,
                    "status": "ASSIGNED"
                }
            },
            {
                "entry": {
                    "id": "4d4dde09-5383-11e8-ab55-0a5864600352",
                    "assignee": "hruser",
                    "createdDate": 1525868403757,
                    "priority": 50,
                    "status": "ASSIGNED"
                }
            }
]
}
```
Related to the issue
https://github.com/Activiti/Activiti/issues/1813

**Comment by lucianoprea** [comment]
right now to get subtasks the `TaskService >  getSubtasks(parentTaskId) method` is used. 
@balsarori suggested to use 

> `HistoricTaskInstanceQuery` https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/history/HistoricTaskInstanceQuery.java#L57
> use unfinished to get only active tasks

or add `parentTaskId` inside `TaskQuery` and create a new method that will return tasks filtered on _parentTaskId_ to support pagination and return the expected response.

**Comment by mauriziovitale** [comment]
Right now the task list API returns all the task and subtasks.
```
http://{{domain}}/query/v1/tasks
```
 I'd like to have a filter property to fetch only the parent tasks.
```
http://{{domain}}/query/v1/tasks?parentTaskId=null
```

**Comment by salaboy** [comment]
@CTI777 the only thing that we need to do here is to implement the filter for parentTaskId = null, which means root tasks only.

**Comment by salaboy** [comment]
@mauriziovitale @CTI777 as I mention in my comments of the PR I would prefer something like

```
v1/tasks?rootTasksOnly  (or rootTasksOnly=true)
```
to avoid exposing =null to the user

**Comment by salaboy** [comment]
ok so v1/tasks/rootTasksOnly.. implemented in develop .. We need to have a acceptance tests for this.
