### ISSUE TITLE
subscriptions through demo UI

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#1897]
I can do a graphql subscription and get websocket responses through the apollo client embedded in the query module:

![image](https://user-images.githubusercontent.com/22754674/40068218-03de707e-5860-11e8-8819-3fce0603f0c7.png)

When I submit the same subscription through the demo-ui client I get told that it's not a query:

![image](https://user-images.githubusercontent.com/22754674/40068293-2cb8e510-5860-11e8-97f5-a9c45bfb7368.png)

And indeed it's not a query, it's a subscription request. But I'd still like to be able to submit it.

**Comment by mteodori** [comment]
obsolete
