### ISSUE TITLE
Create subtask endpoint has the wrong path

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#1901]
The curent path is `/{taskId}/subtask`. It should be `/{taskId}/subtasks` instead.

Make sure that @mauriziovitale is aware when you are going to fix it.

**Comment by erdemedeiros** [comment]
Actually `/{taskId}/sub-tasks` it's probably a better name.

**Comment by CTI777** [comment]
@salaboy 
Some questions to clarify
**Given:**
For subprocesses we have endpoint:  /v1/process-instances/{processInstanceId}/subprocesses
For get subtasks we have endpoint: /v1/tasks/{taskId}/subtasks
For createSubtask we have endpoint: /v1/tasks/{taskId}/subtask

**Questions**
1. Do we need to rename subtasks to sub-tasks (see subprocesses to compare)?
2. Do we need the end point to create subtask if we have already createNewTask (where parentTaskId is a member of CreateTaskPayload and it is used)?
 @RequestMapping(method = RequestMethod.POST)
    TaskResource createNewTask(@RequestBody CreateTaskPayload createTaskPayload);

**Comment by salaboy** [comment]
@CTI777 great questions
1) subtasks should be fine. so we keep it plural but without the -
2) no need for endpoint to create subtasks because we can create a task with a parentId

**Comment by CTI777** [comment]
@salaboy 
So I may remove endpoint: /v1/tasks/{taskId}/subtask and correct tests?

**Comment by salaboy** [comment]
merged in develop
