### ISSUE TITLE
The Process Instances Query endpoint returns wrong values

### ISSUE THREAD

**Issue by mauriziovitale** [Activiti/Activiti#1903]
I have a deployed app called 
**app4** 
When I call the process instances end point 
```
http://{{domain}}/app4-query/v1/process-instances
```
I'm getting this response
```
 {
                "entry": {
                    **"serviceName": "app4-rb",**
                    "serviceFullName": "app4-rb",
                    "serviceVersion": "",
                    **"appName": "default-app",**
                    "appVersion": "",
                    "id": "cf2562ca-632a-11e8-8258-0a58646004aa",
                    "processDefinitionId": "Aps2:1:dfeb5371-6033-11e8-8258-0a58646004aa",
                    "processDefinitionKey": "Aps2",
                    "initiator": "hruser",
                    "startDate": 1527589614991,
                    "status": "RUNNING",
                    "lastModified": 1527589614991
                }
            }
``` 
I think the 
serviceName and the appName are wrong.
I was expecting to see 
**"serviceName": "rb"**
 **"appName": "app4"**

am I wrong?

**Comment by erdemedeiros** [comment]
@ffazzini could you double check which are the values that you are setting when you are deploying to kubernates? `default-app` is [the default name for query](https://github.com/Activiti/activiti-cloud-query/blob/develop/src/main/resources/application.properties#L76). Probably you need to override it.
Still `fullServiceName` and `serviceName` seems to be always the [same](https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-services-runtime-bundle/activiti-cloud-services-events/src/main/java/org/activiti/cloud/services/events/configuration/RuntimeBundleProperties.java#L50). @ryandawsonuk could you take a look on this?

**Comment by ffazzini** [comment]
By setting the env var *ACTIVITI_CLOUD_APPLICATION_NAME* we now have the expected behaviour.
