### ISSUE TITLE
Remove application.properties from starters

### ISSUE THREAD

**Issue by pancudaniel7** [Activiti/Activiti#1904]
Projects that have starter dependency get properties from application.properties|yaml and bootstrap.properties|yaml to be overwritten by the starter properties. 
These configuration files should be removed from starters.
As a solution if the starter module needs application properties for specific configuration, this configurations should rather be written in configuration classes.

**Comment by erdemedeiros** [comment]
The necessary properties can be loaded via `@PropertySource` in a auto-configuration class.
I.e. https://github.com/Activiti/activiti-cloud-query-service/blob/develop/activiti-cloud-services-query/activiti-cloud-services-query-graphql/src/main/java/org/activiti/cloud/services/query/graphql/autoconfigure/ActivitiGraphQLAutoConfiguration.java#L51

**Comment by ryandawsonuk** [comment]
Related issue is https://github.com/Activiti/Activiti/issues/1850
