### ISSUE TITLE
use docker up  installed ,  i can not login with  testuser/password.

### ISSUE THREAD

**Issue by zyu** [Activiti/Activiti#1906]

**Comment by Salaboy** [comment]
@zyu hi there, sorry to hear about that. We are working hard in our first beta1 release for Activiti Cloud. 
We are focusing in the service sides, not yet the UI or tooling. So the UI example might be failing. We will aim to fix those UI issues right after the Beta1 release. 

We are currently working in updating the examples, if you are interested in helping us out please ping us in our gitter channel and we will try to help you to troubleshoot issues and also guide you on how you can contribute with your fixes: https://gitter.im/Activiti/Activiti7?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by salaboy** [comment]
We have moved to HELM charts for installation in Kubernetes Cluster, docker compose approach sounds like a great contribution.
