### ISSUE TITLE
Remove Spring Cloud Config Client from Activiti Cloud Service Metadata

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#1910]
Having Spring Cloud Config Client as transitive dependency in Activiti Cloud Connectors Starter clash with Spring Cloud Kubernetes Config. 
Having the config client library should be optional.

**Comment by ryandawsonuk** [comment]
I guess you mean remove it at the starter level.

I wonder if we should be applying this principle to other deps in our starters where you'd have to exclude to switch to another option e.g. keycloak or rabbit. Graphql could be a separate starter too. We could add extra more opinionated starters that just extend the base ones but with extra deps https://github.com/Activiti/Activiti/tree/6.x/modules/activiti-spring-boot/spring-boot-starters

**Comment by Salaboy** [comment]
We need to review this for Beta2, so the guidelines are clear about how do we plugin in the Netflix OSS libraries when we need them.

**Comment by mteodori** [comment]
obsolete
