### ISSUE TITLE
activiti-image-generator: task names missing (box too small?)

### ISSUE THREAD

**Issue by c14s** [Activiti/Activiti#1911]
In DefaultProcessDiagramCanvas.drawTask(), the boxHeight is computed as follows:

``
   int boxHeight = height - 16 - ICON_PADDING - ICON_PADDING - MARKER_WIDTH - 2 - 2;
``

In my environment (bpmn files created using Eclipse BPMN2 Modeler with default settings), this leads to the situation, that in method drawMultilineText() the condition

``
   currentHeight + height > boxHeight
``

becomes true (for a single line of text), and thus task names are completely left out.

I would suggest to add an else-block in method drawMultilineText(),
in order to draw at least one line of text.

```
if(currentHeight + height > boxHeight) {
        if (!layouts.isEmpty()) {
           [...]
        } else { // at least, draw one line
            layouts.add(layout);
            currentHeight += height;
        }
        break;
}
```

**Comment by Salaboy** [comment]
@c14s interesting.. it sounds like you can provide a PR with that code change and a way to test it. That will be a great community contribution.

**Comment by c14s** [comment]
Changed implementation in activiti-image-generator/DefaultProcessDiagramCanvas.drawMultilineText().

empty box before the change
---
![processdiagram_without_labels](https://user-images.githubusercontent.com/9110225/43533083-3f544002-95b4-11e8-9682-ab0be79de79f.png)

box incl. label after commit
---
![processdiagram_with_labels](https://user-images.githubusercontent.com/9110225/43533084-3fc62d98-95b4-11e8-9be7-64483b9932e4.png)

**Comment by c14s** [comment]
Sorry - pressed "closed" - that was not my intention ;-)

**Comment by Salaboy** [comment]
merged in 6.x, would you mind see if it applies to develop?

**Comment by c14s** [comment]
Thanks for merging into 6.x

Applies also to develop; code for drawMultilineText() is the same there.
Unfortunately I wasn't able to test it, because API has changed for generating the image.
