### ISSUE TITLE
Is this an activiti-app ui bug?

### ISSUE THREAD

**Issue by qq253498229** [Activiti/Activiti#1915]
I found that this angular controller can show list of options,but none objects in this array,it is still assigned to the first element.

<img width="1342" alt="wx20180621-152734 2x" src="https://user-images.githubusercontent.com/31200516/41704081-d77b9776-7567-11e8-82d1-b2937b5dc6c7.png">

If i check the enum,it cause an error:

![image](https://user-images.githubusercontent.com/31200516/41704287-6dff3748-7568-11e8-9d37-31d1b4b5e1ea.png)

I manually execute the following code then the error disappeared, but still did not get the result I want

> $scope.selectedProperties.push({});

<img width="1008" alt="wx20180621-152747 2x" src="https://user-images.githubusercontent.com/31200516/41704084-d83152a0-7567-11e8-8120-5e9fb396a3c4.png">

**Comment by MkkOF** [comment]
解决了么，我也遇到同样的问题了，same problem!

**Comment by salaboy** [comment]
@MkkOF @qq253498229 are you guys using activiti 6.0.0.Final? or 5.22?
