### ISSUE TITLE
angular error

### ISSUE THREAD

**Issue by qq253498229** [Activiti/Activiti#1916]
![image](https://user-images.githubusercontent.com/31200516/41704525-0cab622c-7569-11e8-9481-4238df99f8b8.png)

https://github.com/Activiti/Activiti/blob/6.x/modules/activiti-ui/activiti-app/src/main/webapp/editor/editor-app/configuration/properties-form-properties-controller.js#L143

**Comment by Salaboy** [comment]
@qq253498229 can you please elaborate on when are you getting that issue?
