### ISSUE TITLE
Activiti Designer Plugin for Eclipse Update Site is no more available

### ISSUE THREAD

**Issue by achemek** [Activiti/Activiti#1918]
I tried to get Activiti from this update site https://www.activiti.org/designer/update/ but it is no more available,
then i tried to download the zip file from here http://www.activiti.org/designer/archived/activiti-designer-5.18.0.zip and also i got a negative result "Page not found"
can anyone give me the new updatesite if it exists? thanks.

**Comment by lucianoprea** [comment]
@achemek I just followed the steps provided in the Activiti5 docs and the Eclipse Designer for Activiti works. Follow the steps documented [here](https://www.activiti.org/5.x/userguide/#activitiDesigner). Can you try it and confirm?

**Comment by daisuke-yoshimoto** [comment]
@lucianoprea 
Entering the update site( http://activiti.org/designer/update/ ) according to the document, it will certainly result in an error.

![eclipse-setting](https://user-images.githubusercontent.com/16251291/41847402-ce1723a8-78b4-11e8-91d3-6cb6a29315d0.png)

![eclipse-update-site-error](https://user-images.githubusercontent.com/16251291/41847400-cdf12da6-78b4-11e8-940b-63dcd9e01a60.png)

**Comment by achemek** [comment]
@lucianoprea : i got the same result as @daisuke-yoshimoto

**Comment by achemek** [comment]
@lucianoprea just now the update site is available, but it seems that it is not always available

**Comment by lucianoprea** [comment]
For me worked from the first time. I have the Eclipse Neon.

**Comment by daisuke-yoshimoto** [comment]
@lucianoprea It is not a problem of how to use Eclipse, but materials are simply not placed on the update site.

For example, the following urls(required for the eclipse update site) are all 404.
https://activiti.org/designer/update/content.xml
https://activiti.org/designer/update/site.xml
https://activiti.org/designer/update/artifacts.xml

**Comment by achemek** [comment]
Before when i get this problem i download the zip file from http://www.activiti.org/designer/archived/activiti-designer-5.18.0.zip and this always solve me but now the zip file is also no more available

**Comment by achemek** [comment]
The problem is that the update site is not always available, and the [ZIP file](http://www.activiti.org/designer/archived/activiti-designer-5.18.0.zip) has been deleted

**Comment by balsarori** [comment]
Here is the Zip file
[activiti-designer-5.18.0.zip](https://github.com/Activiti/Activiti/files/2144413/activiti-designer-5.18.0.zip)

**Comment by daisuke-yoshimoto** [comment]
@balsarori 
If you put it here, can we access it from the site?
https://github.com/Activiti/activiti.github.io

**Comment by balsarori** [comment]
Added [ZIP file](http://www.activiti.org/designer/archived/activiti-designer-5.18.0.zip) to the website.

@daisuke-yoshimoto 

> For example, the following urls(required for the eclipse update site) are all 404.
https://activiti.org/designer/update/content.xml
https://activiti.org/designer/update/site.xml
https://activiti.org/designer/update/artifacts.xml

do you have these files?

**Comment by achemek** [comment]
@balsarori thank you, this solve my problem

**Comment by daisuke-yoshimoto** [comment]
@balsarori 
Thanks. I made the pull request for this issue.
https://github.com/Activiti/activiti.github.io/pull/18

**Comment by balsarori** [comment]
@daisuke-yoshimoto that's great!!!

**Comment by balsarori** [comment]
@daisuke-yoshimoto site still doesn't seem to work on eclipse. It's complaining that it can't find content.xml. 

Also the Download here https://www.activiti.org/designer/update/ point to non-existing jar

**Comment by daisuke-yoshimoto** [comment]
@balsarori 
Sorry, I will check it. But, the preview page works now.
https://5b37647402ed837e3a0e2198--activiti.netlify.com/designer/update/

**Comment by ramunask** [comment]
I just installed Activiti Designer plugin and it worked for me correctly:

![Installation Details](https://user-images.githubusercontent.com/4812724/43248688-5321ab3a-90c1-11e8-83a9-ff25c131a274.png)

Eclipse (STS) version:
```
Spring Tool Suite 

Version: 3.9.5.RELEASE
Build Id: 201807031753
Platform: Eclipse Photon (4.8.0)
```

**Comment by spoorani** [comment]
Cannot complete the install because one or more required items could not be found.
  Software being installed: Flowable Eclipse BPMN 2.0 Designer 5.22.0 (org.flowable.designer.feature.feature.group 5.22.0)
  Missing requirement: Graphiti (Incubation) 0.13.1.v20160830-1309 (org.eclipse.graphiti 0.13.1.v20160830-1309) requires 'osgi.bundle; org.eclipse.emf.transaction [1.8.0,2.0.0)' but it could not be found
  Cannot satisfy dependency:
    From: Graphiti (Incubation) 0.13.1.v20160830-1309 (org.eclipse.graphiti.feature.feature.group 0.13.1.v20160830-1309)
    To: org.eclipse.equinox.p2.iu; org.eclipse.graphiti [0.13.1.v20160830-1309,0.13.1.v20160830-1309]
  Cannot satisfy dependency:
    From: Flowable Eclipse BPMN 2.0 Designer 5.22.0 (org.flowable.designer.feature.feature.group 5.22.0)
    To: org.eclipse.equinox.p2.iu; org.eclipse.graphiti.feature.feature.group [0.13.1.v20160830-1309,0.13.1.v20160830-1309]

**Comment by alaeddineberri** [comment]
@balsarori 

hello ,

i know it's been a time but i tried your zip but it seems there is a problem in installation
can you please review your zip
