### ISSUE TITLE
Link broken on the Activiti 6 announcement page

### ISSUE THREAD

**Issue by proth1** [Activiti/Activiti#1922]
The Activiti 6 announcement page I'm talking about is here: 

https://community.alfresco.com/community/bpm/blog/2017/06/01/activiti-6-is-here?commentID=6972&et=blogs.comment.created

and then the broken link is as follows:

Running the process on Activiti 5 will result in a StackOverflowError. In Activiti 6 the process will run without any issues. Check it yourself by running [this test](https://github.com/Activiti/Activiti/blob/6.0-release/modules/activiti-engine/src/test/java/org/activiti/engine/test/api/v6/Activiti6Test.java#L123) available on github.

**Comment by balsarori** [comment]
Thanks @proth1 I updated the link.
