### ISSUE TITLE
Add Release Endpoints to Organization Endpoints

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#1925]
We need to add the concept of an Application Release to our endpoints. This is to cover the scenario where we want to deploy a new application to a runtime environment.
Application Releases are immutable packages (ZIP files) that are stored in the backend services. 

We need to extend the Application Service to have the following endpoints

- POST /applications/{appId}/release -> Generates a new release for an application (we also need a strategy here, to bump the version of an application) 

The release mechanism (for community) should trigger internally the export functionality and store the zip of the release + the JSON object representing the release in a separate entity (separate from the models) 

We need a Release Object that store minimal information about the released artefacts (Zip files) for consuming that data from the UI. This object should contain information about the Application Name, Release Date and Version. 

Releases Endpoint should look like this:

You should be able to list and delete releases. 

- GET {server}/releases/ -> Get All releases

- GET {server}/releases/?applicationId={id} -> filter the releases by ID

- DELETE {server}/releases/{releaseId}

**Comment by mteodori** [comment]
deprecated
