### ISSUE TITLE
Move to community Export/Import functionality and review

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#1926]
In community we should have import/export applications as and from Zip files. 

@constantin-ciobotaru can you describe what is the current behaviour of the implemented functionality so we use that as requirement from community?

**Comment by Salaboy** [comment]
@constantin-ciobotaru ok so this is still open because we need to have acceptance tests for these endpoints 👍

**Comment by salaboy** [comment]
merged to develop and acceptance tests create. Let's create another issue if there still gaps in the tests.
