### ISSUE TITLE
potentialStarter not found

### ISSUE THREAD

**Issue by dongwenting** [Activiti/Activiti#1929]
I watch the document. https://www.activiti.org/userguide/index.html#_getting_started

8.8. Process Initiation Authorization

> List<Group> authorizedGroups =  identityService().createGroupQuery().potentialStarter("processDefinitionId").list();

but In Activiti 7.0 , GroupQuery does not have the method potentialStarter, how can I query processdefinition that can be initialled by some groups?

**Comment by Salaboy** [comment]
@dongwenting that is the getting started for 6 not 7. Activiti 7 is going to go Beta1 soon. I will close this issue. You can re-open it for 7 beta1 when it is out.

**Comment by dongwenting** [comment]
@Salaboy  thank you for your reply. but I need to Process Initiation Authorization, how can I do it in activiti 6.3.1

**Comment by Salaboy** [comment]
@dongwenting can you please clarify what do you mean by Activiti 6.3.1 ?

**Comment by dongwenting** [comment]
Sorry, my English is not good. 
My goal is different groups have permission to start different processes. In Activiti 6.3.1, chapter 8.8. Process Initiation Authorization can achieve it, but this api ( identityService.createGroupQuery().potentialStarter("processDefinitionId").list();) not exists any more.

So is there another way to give permissions to start processes for different groups ? 
Thank you very much!

**Comment by dongwenting** [comment]
I figure out how to do this.

```
 <process id="SealApply" name="印章申请" isExecutable="true" activiti:candidateStarterGroups="SEAL_APPLY_STARTER_GROUP">

		SELECT d.*           FROM (
         	SELECT t0.* FROM ACT_RE_PROCDEF t0 JOIN (
          		SELECT key_, MAX(version_) AS version_ FROM ACT_RE_PROCDEF GROUP BY key_) t 
          	ON t0.key_ = t.key_ AND t0.version_ = t.version_) d
  		 LEFT JOIN ACT_RU_IDENTITYLINK i
    	 ON d.id_ = i.proc_def_id_  WHERE i.group_id_ IN ('SEAL_APPLY_STARTER_GROUP')
```

**Comment by Salaboy** [comment]
@dongwenting I think that now I understand more.. but what version of Activiti are you using? can you share your pom files? (are you using Maven?)

**Comment by dongwenting** [comment]
@Salaboy  In fact, I use flowable, here is my pom:
	<properties>
		<flowable.version>6.3.1</flowable.version>	
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.flowable</groupId>
			<artifactId>flowable-spring-boot-starter-rest-api</artifactId>
			<version>${flowable.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-tomcat</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jetty</artifactId>
		</dependency>
	</dependencies>

**Comment by Salaboy** [comment]
@dongwenting so why are you asking in this repo then? they can add and remove methods in a completely different cycle or approach. You started saying "but In Activiti 7.0"
