### ISSUE TITLE
NullPointerException at ByteArrayRef

### ISSUE THREAD

**Issue by HubbsLS** [Activiti/Activiti#1932]
Running on 5.22.0.
The error seems to occur randomly (sometimes not at all) when trying to call getVariable(String).

> java.lang.NullPointerException: while trying to invoke the method org.activiti.engine.impl.persistence.entity.ByteArrayEntity.getName() of a null object loaded from field org.activiti.engine.impl.persistence.entity.ByteArrayRef.entity of an object loaded from local variable 'this'
> 	at org.activiti.engine.impl.persistence.entity.ByteArrayRef.ensureInitialized(ByteArrayRef.java:98)
> 	at org.activiti.engine.impl.persistence.entity.ByteArrayRef.getBytes(ByteArrayRef.java:46)
> 	at org.activiti.engine.impl.persistence.entity.VariableInstanceEntity.getBytes(VariableInstanceEntity.java:160)
> 	at org.activiti.engine.impl.variable.ByteArrayType.getValue(ByteArrayType.java:32)
> 	at org.activiti.engine.impl.variable.SerializableType.getValue(SerializableType.java:49)
> 	at org.activiti.engine.impl.persistence.entity.VariableInstanceEntity.getValue(VariableInstanceEntity.java:187)
> 	at org.activiti.engine.impl.persistence.entity.VariableScopeImpl.getVariable(VariableScopeImpl.java:236)
> 	at org.activiti.engine.impl.persistence.entity.VariableScopeImpl.getVariable(VariableScopeImpl.java:213)

At first sight it seems there's a missing check if the 'entity' (ByteArrayEntity) object is null, because in the getBytes() method, there's a check if entity is null, and if it is, then null is returned, but this point will never be reached because if the entity is indeed null then ensureInitialized() will fail with NPE because of trying to call entity.getName().

But it makes me think that is not the case since it happens randomly, and I assume there's a problem on my side. If that is not the case then what would be the reason for `Context.getCommandContext().getByteArrayEntityManager().findById(id);` to return null at all?

**Comment by Salaboy** [comment]
maybe that some other thread already remove the context for that ID. Context.getCommandContext().getByteArrayEntityManager().findById(id);

**Comment by HubbsLS** [comment]
@Salaboy 
No removeVariable(String) is executed in my code

**Comment by Salaboy** [comment]
@HubbsLS but the variable might be deleted by the process completion right? You can add a listener to the engine to see if the VariableDeleted event is triggered.
