### ISSUE TITLE
Activit5.16.4 to Activiti6.0.0  External form rendering

### ISSUE THREAD

**Issue by Jarvan89** [Activiti/Activiti#1933]
in Activiti5.16.4  and Activiti 6.0.0 I deploy bpmn to H2  Use  this code

```
        // 获取上传的文件名
        String fileName = file.getOriginalFilename();

        try {
            // 得到输入流（字节流）对象
            InputStream fileInputStream = file.getInputStream();

            // 文件的扩展名
            String extension = FilenameUtils.getExtension(fileName);

            // zip或者bar类型的文件用ZipInputStream方式部署
            DeploymentBuilder deployment = repositoryService.createDeployment();
            if (extension.equals("zip") || extension.equals("bar")) {
                ZipInputStream zip = new ZipInputStream(fileInputStream);
                deployment.addZipInputStream(zip);
            } else {
                // 其他类型的文件直接部署
                deployment.addInputStream(fileName, fileInputStream);
            }
            deployment.deploy();
        } catch (Exception e) {
            logger.error("error on deploy process, because of file input stream");
        }
```

Then I read the data using the following code
```
ProcessDefinition processDefinition = repositoryService.createProcessDefinitionQuery().processDefinitionId(processDefinitionId).singleResult();
        boolean hasStartFormKey = processDefinition.hasStartFormKey();
        // 根据是否有formkey属性判断使用哪个展示层
        String viewName = "home/projects";
        ModelAndView mav = new ModelAndView(viewName);
        // 判断是否有formkey属性
        if (hasStartFormKey) {
            Object renderedStartForm = formService.getRenderedStartForm(processDefinitionId);
            mav.addObject("startFormData", renderedStartForm);
            mav.addObject("processDefinition", processDefinition);
        } else { // 动态表单字段
            StartFormData startFormData = formService.getStartFormData(processDefinitionId);
            mav.addObject("startFormData", startFormData);
        }

        mav.addObject("hasStartFormKey", hasStartFormKey);
        mav.addObject("processDefinitionId", processDefinitionId);
        return mav;
````
bpmn file is：
`<startEvent id="startevent1" name="Start" activiti:initiator="applyUserId" activiti:formKey="leave-formkey/leave-start.form"></startEvent>`

same code in Activiti5  hasStartFormKey method  and in H2  HAS_START_FORM_KEY_   is true
but in Activiti6 hasStartFormKey  and in H2  HAS_START_FORM_KEY_    is fasle
I don't know if the BPMN file is a problem or a version problem.

**Comment by Salaboy** [comment]
@Jarvan89 can you please create a reproducer for this problem? It will be way much easier to test if we can have a maven project where we can reproduce the issue that you are experiencing. 
It sounds like there is a difference in the APIs from 5.x to 6.x but we should be able to reproduce the problem first.

**Comment by Salaboy** [comment]
@balsarori is this a well known issue?

**Comment by balsarori** [comment]
Yeah, I came across this issue before. I'm not sure why hasStartFormKey is no longer updated.

**Comment by daveleenew** [comment]
@Jarvan89 6.0?

**Comment by Jarvan89** [comment]
@daveleenew yes  6.0.0

**Comment by Jarvan89** [comment]
@Salaboy i will try to create a maven demo  Tonight。

**Comment by balsarori** [comment]
@Jarvan89 To determine if a process definition has a start form or not you can use ```formService.getStartFormKey(processDefinitionId)```

No need for a demo since it's a known issue. Adding ```assertTrue(processDefinition.hasStartFormKey());``` to one of the [FormServiceTest](https://github.com/Activiti/Activiti/blob/5.x/modules/activiti-engine/src/test/java/org/activiti/engine/test/api/form/FormServiceTest.java#L53) unit tests can verify the issue

**Comment by Jarvan89** [comment]
@balsarori That's what I'm doing now 。 thank you
