### ISSUE TITLE
Refactor eureka runtime configs in metadata

### ISSUE THREAD

**Issue by ffazzini** [Activiti/Activiti#1936]
I could not get Runtime Bundle running by default without Eureka(i was using only ingress).
The error i got:
```
Field appInfoManager in org.activiti.cloud.services.metadata.eureka.dynamic.DynamicRegistrationConfiguration required a bean of type 'com.netflix.appinfo.ApplicationInfoManager' that could not be found.
```

After applying the config below suggested by @Salaboy it works now:
```
- name: ACTIVITI.CLOUD.SERVICES.METADATA.EUREKA.DYNAMIC.ENABLED value: “false”
```
Possible solutions:
1. The property above should be set to false by default.
2. Remove the metadata eureka part as it is not a mandatory building block.

**Comment by Salaboy** [comment]
@ffazzini I am closing this one because for beta1 we have removed all the Netflix OSS dependencies, so this issue by default shouldn't appear.
