### ISSUE TITLE
Found Activiti 5 process definition, but no compatibility handler on the classpath

### ISSUE THREAD

**Issue by daveleenew** [Activiti/Activiti#1938]
How to fix this problem?

**Comment by daveleenew** [comment]
@Test
    public void getTask() {
        List<Task> list = taskService.createTaskQuery().list();

        for (Task task:list) {

            //it's work
            ProcessInstance processInstance = runtimeService.createProcessInstanceQuery().processInstanceId(task.getProcessInstanceId()).singleResult();

            BpmnModel bpmnModel = repositoryService.getBpmnModel(processInstance.getProcessDefinitionId());

            List<Process> processes = bpmnModel.getProcesses();

            for (Process process: processes
                 ) {
                System.out.println(process.getFlowElements().size());
            }


            //it does't work.throw "Found Activiti 5 process definition, but no compatibility handler on the classpath" exception
            BpmnModel tempModel = ProcessDefinitionUtil.getBpmnModel(processInstance.getProcessDefinitionId());

        }
    }

**Comment by daveleenew** [comment]
@ryandawsonuk  thank you for your replay.

but i don't need to compatibility activiti 5.0

i want to just use the activiti 6.0.?

**Comment by balsarori** [comment]
@daveleenew 
seems that [ProcessDefinitionUtil.getBpmnModel](https://github.com/Activiti/Activiti/blob/6.x/modules/activiti-engine/src/main/java/org/activiti/engine/impl/util/ProcessDefinitionUtil.java#L55) requires an active context when called. You should not call it directly instead call repositoryService.getBpmnModel

**Comment by daveleenew** [comment]
@balsarori thanks
   How to call an active context first?

**Comment by balsarori** [comment]
@daveleenew use [managementService execute command](https://www.activiti.org/javadocs/org/activiti/engine/managementservice#executeCommand-org.activiti.engine.impl.interceptor.Command-)

Why do you want to call it directly repositoryService.getBpmnModel does the same thing.

**Comment by daveleenew** [comment]
@balsarori 

Thank you for you reply. U R right.  repositoryService.getBpmnModel does the same thing with the ProcessDefinitionUtil.

**Comment by balsarori** [comment]
@daveleenew I'll close this issue then.
