### ISSUE TITLE
Start Process With Process Instance Name via rest and Java APIs

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#1952]
We should be able to start a process instance with an associated name.

**Comment by mauriziovitale** [comment]
for my point of view the name should be mandatory

**Comment by salaboy** [comment]
I disagree, there are situations where you don't want to set a name and it also adds an extra step for the user, we should automate this when possible, probably in the modeling app.

**Comment by erdemedeiros** [comment]
@lucianoprea I merged the PR on query-service, but it will be great if you can add this check in the acceptance tests as well.

**Comment by salaboy** [comment]
@lucianoprea this was tested with beta3 pre released artifacts and the problem seems to be in query not reflecting this information. I guess that there is a PR missing in query to apply the name based on the events information.

**Comment by salaboy** [comment]
@miguelruizdev missing ACC in scenarios repo.. The missing PR cannot be merged in that repo, it needs to be moved to acc-tests-scenarios

**Comment by erdemedeiros** [comment]
@miguelruizdev @lucianoprea in case the acceptance test is failing I've added a [test](https://github.com/Activiti/activiti-cloud-runtime-bundle-service/pull/144/files#diff-f51a63e6103a343ffe4255d23efbeeafR135) checking that the information is sent in `PROCESS_STARTED` event, but it seems to be missing in `PROCESS_CREATED` event. So you may need to update the information in [ProcessStartedEventHandler](https://github.com/Activiti/activiti-cloud-query-service/blob/develop/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/ProcessStartedEventHandler.java)
