### ISSUE TITLE
Tasks and ProcessInstances filter with "LIKE" operator 

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#1954]
Create Filters for Like of the following field:
```
private String name;
private String description;
```

**Comment by salaboy** [comment]
@CTI777 check with @miguelruizdev if he cannot work on this.. please check this one as well.

**Comment by miguelruizdev** [comment]
@salaboy does the scope of this issue include the actual addition of the feature?
We are setting "EQUALS" as the default behaviour in all the repositories: 
 - https://github.com/Activiti/activiti-cloud-query-service/blob/develop/activiti-cloud-services-query/activiti-cloud-services-query-repo/src/main/java/org/activiti/cloud/services/query/app/repository/ProcessInstanceRepository.java#L37
 - https://github.com/Activiti/activiti-cloud-query-service/blob/develop/activiti-cloud-services-query/activiti-cloud-services-query-repo/src/main/java/org/activiti/cloud/services/query/app/repository/VariableRepository.java#L38
 - https://github.com/Activiti/activiti-cloud-query-service/blob/develop/activiti-cloud-services-query/activiti-cloud-services-query-repo/src/main/java/org/activiti/cloud/services/query/app/repository/TaskRepository.java#L37

**Comment by miguelruizdev** [comment]
If we change it, we would support 'LIKE' behaviour all across the board, in every case.
Do we really want to do that?

**Comment by miguelruizdev** [comment]
@salaboy That opens the question of wether we need to make it optional for every field, or just clasify fields and their susceptibilty in being queried using LIKE or EQUALS

**Comment by CTI777** [comment]
@miguelruizdev 
I think it would be better to add Like only for the fields like name and description...

**Comment by salaboy** [comment]
@CTI777 I guess that 
```
private String owner;
private String assignee;
private String formKey;
private String processDefinitionId;
````
should be only matched if they are EQUAL so.. we don't really need LIKE functionality on those fields.

**Comment by salaboy** [comment]
merged in develop
