### ISSUE TITLE
Activiti db password encryption

### ISSUE THREAD

**Issue by sagitsofan** [Activiti/Activiti#1962]
Hey,
Don't you have an infrastructure for encryption db password inside Avctiviti engine?
In this guide: https://www.activiti.org/assets/pdf/Alfresco_Content_Services_Administration_Guide_2017.pdf"
page 360 you explain about how to encrypt the password inside the db.properties file.

But when i am looking at the source code i cant see any decryption of the password key.
File: "DbSchemaExport.java" line: 48, the code is just reading the value without any support to decryption.

![image](https://user-images.githubusercontent.com/1827994/43902656-4dad644a-9bf3-11e8-9a01-d5cc10bff38d.png)

**Comment by balsarori** [comment]
Hey @sagitsofan 
Thats specific to ACS not the Activiti engine. In Activiti engine there is no encryption/decryption done. However, you can encrypt and decrypt values yourself and set the password to Activiti engine configuration (ProcessEngineConfiguration) directly.

**Comment by sagitsofan** [comment]
I am already using the "jasypt-spring-boot lib"
But i don't know where can i add the encryption/decryption logic for the db password.
Can you guide me where exactly can i add the change? in which line / class? 
Thanks!

**Comment by balsarori** [comment]
what version of Activiti are you using?

In 5.22 and 6.0, you just get the password property (which should have been already decrypted) and set it to 
https://www.activiti.org/javadocs/org/activiti/engine/processengineconfiguration#setJdbcPassword-java.lang.String-

**Comment by Salaboy** [comment]
Guys, this sounds more like a user question than an issue. Can you guys move the conversation to the forums?

**Comment by balsarori** [comment]
@sagitsofan you can post your question here -> https://community.alfresco.com/community/bpm
