### ISSUE TITLE
Unable Fork

### ISSUE THREAD

**Issue by liusiying65200** [Activiti/Activiti#1969]
unable fork and git https://github.com/Activiti/Activiti/tree/activiti-7-201709-EA/activiti-services/activiti-services-identity-keycloak

**Comment by Salaboy** [comment]
@liusiying65200 not sure to understand what do you want to fork? You can fork a repository not a branch or a tag. What is the error? This is not an issue, so I'm closing it. Feel free to jump into our gutter channel if you want to have a discussion about this, or if you want to ask questions there. This is reserved for code issues. https://gitter.im/Activiti/Activiti7?utm_source=share-link&utm_medium=link&utm_campaign=share-link
