### ISSUE TITLE
[Core] Business key in list of tasks

### ISSUE THREAD

**Issue by krishnashum** [Activiti/Activiti#1970]
I think it would be good to have the business key to be a part of taskInfo, as In some scenarios the business key plays a [vital role](https://community.alfresco.com/thread/226323-business-key-in-list-of-tasks).

**Comment by Salaboy** [comment]
@krishnashum +1, I think that we can easily add that in the new APIs that we released for beta1. Would you be interested in contributing back with those changes? It sounds like a great opportunity to get involved with the project. We are happy to guide you in the process.

**Comment by krishnashum** [comment]
sure. I will do the needful changes. Could you please provide some heads up on the process.

**Comment by Salaboy** [comment]
@krishnashum I would recommend you to clone the activiti-examples project and then fork activiti-api and activiti repositories. 
The behaviour that you want to implement needs to be added to the engine when creating a task. But in order to validate that the behaviour is correct we need to create first an example to demonstrate it. Please popup in the gitter channel and we can guide you further.

**Comment by salaboy** [comment]
related to https://github.com/Activiti/Activiti/issues/2069

**Comment by salaboy** [comment]
@erdemedeiros this is a duplicate from @igdianov issue

**Comment by igdianov** [comment]
@salaboy I have investigated and made initial spike to explore the scope of the changes required to add support process instance businessKey attribute in Tasks. At the top of the chain we will need to modify acitiviti-api. In Activiti core, we will need to create business key persistent attribute mapping in persistence layer to store it as part of task record across all supported databases in Activiti core. 

Then, we will also need to support updating business key in related tasks when someone updates process instance business key.

Then, we will also need to add support for cloud events api and cloud services (audit, query)

**Comment by salaboy** [comment]
@igdianov after our discussion, I think that we should solve this only in the Query services, where we have all the data, that will avoid any major change in the RB.

**Comment by salaboy** [comment]
initial check at process level for business key in events: https://github.com/Activiti/activiti-cloud-runtime-bundle-service/pull/174

**Comment by salaboy** [comment]
@igdianov we merged the events decoration with metadata such as business key.. should this be solved already?

**Comment by salaboy** [comment]
@igdianov you have too many jx bots accounts ;)

**Comment by salaboy** [comment]
done
