### ISSUE TITLE
the old activiti load the new process key,help me

### ISSUE THREAD

**Issue by wy545** [Activiti/Activiti#1976]
hi,please help me.
Now, I add one branch on the base of the existing process, and according to the different condition to decide to go to which branch. As follows:
![image](https://user-images.githubusercontent.com/20380902/44618805-ca34c800-a8af-11e8-83d1-5fb8abd5ee90.png)

the new as flows:
![image](https://user-images.githubusercontent.com/20380902/44618822-05cf9200-a8b0-11e8-90c7-8204f5f32b0f.png)

There are 2 machines running the activiti project. When i release the new version at the A machine, B
machinet still processes the request, but B machine reprort the following error:
Unknown property used in expression: ${xiaodai}

I think the B machine should run the old project and load the old process, but the result is that B machine run the old project and reload the new process.....please help me

**Comment by daisuke-yoshimoto** [comment]
What do you mean about that machine B loads the old process definition?
If you start process instances by specifying the process definition key not process definition id, process instances load old process definition? https://www.activiti.org/userguide/#versioningOfProcessDefinitions

Also, how do you creating clustering between machine A and machine B? Can not machine A and machine B refer to the same DB?

**Comment by wy545** [comment]
@daisuke-yoshimoto 
thanks your answer. 
what I mean  is that, by example, machine A and B process the request using a process definition of version of 111, that is ok. However, when I modify this process definition and deploy it only in machine
A, we can know the version is to 112. Now, machine A process the request using version 112, machine B
process the request using which version?
From the machine B reporting error ： Unknown property used in expression: ${xiaodai} ， I guess machine B process the request using version 112. Is this correct?
If that is, machine B stills run the old code project , as a result, machine B can not process request correctly. 
Thank you, please help me.

**Comment by wy545** [comment]
@daisuke-yoshimoto 
machine A and B refer to the same DB. And, I use spring and activi, using this configuration.
![image](https://user-images.githubusercontent.com/20380902/44644657-7b9a4180-aa07-11e8-8589-2c28c5957fff.png)

**Comment by daisuke-yoshimoto** [comment]
@wy545 
If machine A and B refer to the same DB and you create new process insntace by specifying the process definition key not process definition id, process instances load new process definition(the version  112).

If you want to use old version at only machine B, you should start process insntace byspecifying the process definition id not process definition key.

**Comment by wy545** [comment]
@daisuke-yoshimoto 
I know what you mean. But as we all know, starting the process using key is reasonable. I wonder why machine B is affected by other machine. And ,if this is true, we modify process and then deploy at some machines , other machines can not process the request correctly which I think is not properly.

**Comment by daisuke-yoshimoto** [comment]
@wy545 
f machine A and B refer to the same DB and you create new process insntace by specifying the process definition key not process definition id, process instances load only new process definition(the version 112). But, since machine B project is old and process instances created in machine B cannot load new Business Logic, so process instances created in machine B have no variables named 'xiaodai'

**Comment by salaboy** [comment]
I will close this issue because it is not an issue, it is a question that seems to be answered.
