### ISSUE TITLE
Runtime Bundle - ProcessInstanceVariable create update endpoint

### ISSUE THREAD

**Issue by lucianoprea** [Activiti/Activiti#1989]
There is not endpoint to update the process variables but only  to set them.
`**POST**  v1/process-instances/{{processInstanceId}}/variables` so we need to create a dedicated one for this and also fix that the path parameter **processInstanceId** that is never used. You need to send the **processInstanceId** inside body to work.
```{
  "processInstanceId": "{{processInstanceId}}",
  "variables": {
    "firstName": "Paulo updated",
    "lastName": "Silva updated",
    "age": 26
  },
  "payloadType":"SetProcessVariablesPayload"
}
```

**Comment by salaboy** [comment]
@lucianoprea this will be solved by the admin APIs here: https://github.com/Activiti/Activiti/issues/2182

**Comment by erdemedeiros** [comment]
Do we really need an endpoint to explicitly update variables? Currently if a variable already exists when you call `POST v1/process-instances/{{processInstanceId}}/variables` they will be updated.

**Comment by salaboy** [comment]
@erdemedeiros we just wanted to make sure that we have the right method POST/PUT/PATCH to make sure that we don't allow people to create new ones.. just update existing ones.. we might need to add that into the logic of the controller to just ignore the variables that doesn't exist.

**Comment by cristianflorescu** [comment]
Raised similar issue https://github.com/Activiti/Activiti/issues/2445

**Comment by salaboy** [comment]
closing due duplicate with #2445
