### ISSUE TITLE
Create pipelines for Activiti Cloud

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#1995]
This work includes the refactoring of the following repositories:

- activiti-cloud-build
- activiti-cloud-api
- activiti-cloud-service-common
- activiti-cloud-runtime-bundle-service
- activiti-cloud-query-service
- activiti-cloud-audit-service
- activiti-cloud-dependencies

**Comment by erdemedeiros** [comment]
https://github.com/Activiti/Activiti/issues/1995

**Comment by salaboy** [comment]
done, more specific issues will be created to refine this
