### ISSUE TITLE
Application Zip file structure definition conformance

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2001]
The application zip file for Beta2 needs to conform to the following structure:
- {Application.Name-Application.Version}.zip 
  - processes/ -> directory which will contain all process bpmn xml definitions
     - bpmn files
     - process extensions file (after beta2)
  - app.json -> descriptor of application metadata

After beta2 we might support more definitions such as connectors, forms, decision tables. 
Each model type will have a separate directory such as:
- connectors/
- decisions/

Always in plural. Community import/export logic should be adapted to follow this pattern and the mechanism needs to be simple enough to add more types.

**Comment by ffazzini** [comment]
From our conversation on Friday we will have one single extension file at application level extensions.json

**Comment by salaboy** [comment]
@ffazzini I don't think so.. we will have one per process. Are you talking about process extensions? those ones are one per process.

**Comment by salaboy** [comment]
let me update the description of this issue

**Comment by salaboy** [comment]
initial work for beta2 done.. more specific issues needed for further features
