### ISSUE TITLE
Create HELM charts for Modeling

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2003]
A HELM chart for activiti-cloud-modeling should be created in conformance with the activiti-cloud-charts. 
This chart needs to include 
1) the backend services first
2) the front end modeling app when it is available in community 

This HELM chart needs to define 2 containers inside the same pod so we can manage the connection between the two as local. 
This requires https://github.com/Activiti/Activiti/issues/1990

**Comment by mteodori** [comment]
The backend URL needs to be accessible from the browser in the front-end app, so the local connection wouldn't help

**Comment by mteodori** [comment]
didn't mean to close, just add the comment

**Comment by constantin-ciobotaru** [comment]
@ryandawsonuk I pushed a stub in a separate branch for Miguel. His in charge with the modeling helm chart, from what I know.
