### ISSUE TITLE
activiti demo can only set in jdk1.8

### ISSUE THREAD

**Issue by 83521166** [Activiti/Activiti#2064]

**Comment by 83521166** [comment]
it present http error 401 in jdk 1.9

**Comment by salaboy** [comment]
@83521166 can you please clarify which demo with which version? 

Thanks

**Comment by 83521166** [comment]
@salaboy demo is activiti 6.0.0/wars , can't open in Tomcat 7, then I switch jdk9 to jdk1.8, it works well 
Thanks for your reply

**Comment by salaboy** [comment]
@83521166 hi there, we are not planning to upgrade activiti 6 due the fact that we are working with full speed on Activiti 7 / Cloud. Activiti Core and Cloud are targeting JDK 11 for the GA release. 
We happily accept contributions on the 6.x branch, so feel free to open a new issue if you are planning to contribute that back.
