### ISSUE TITLE
Improve TaskAdminController in runtime-bundle-service

### ISSUE THREAD

**Issue by lucianoprea** [Activiti/Activiti#2066]
Currently an admin can currently only query for all tasks. The api for other operations like update/delete is available but the endpoints in [TaskAdminController](https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-api/src/main/java/org/activiti/cloud/services/rest/api/TaskAdminController.java) (RB) are missing.

**Comment by salaboy** [comment]
Duplicated from this one: 
https://github.com/Activiti/Activiti/issues/2182
