### ISSUE TITLE
Support spring 2 in Spring-boot-starter-basic 

### ISSUE THREAD

**Issue by miladamery** [Activiti/Activiti#2068]
Hi. in our company we use activiti with spring. currently we use spring boot 1.5.x but new requirements need us to migrate to spring boot 2 so we can handle those new requirements. in the process of migrating i saw you are using spring boot 1.2.x (which has security vulnerabilities too according to #1957). so i want to ask first will you migrate this project to spring boot 2? and second if you are going to migrate when exactly? this is urgent for our company so i will be very thankful if you answer me.

**Comment by salaboy** [comment]
@miladamery we already migrated to spring boot 2 for Activiti Core 7 and Activiti Cloud. You can find that in our "develop" branch under activiti-spring-boot-starter. Also in Maven central with the Beta1 release.

**Comment by pjypjy** [comment]
Excuse me, how do I get it FromProperties in Activiti 7 ?I can't found the FormService and I can't found the document about this change.Thank you very much.

**Comment by pjypjy** [comment]
:) Thank you ~
