### ISSUE TITLE
is spring-boot-starter-basic project (the one that use spring boot 2) compatible with activiti version 5?

### ISSUE THREAD

**Issue by miladamery** [Activiti/Activiti#2073]
Hi. i need to get answer of some questions for my boss in company. in our company we use activiti v5.x with spring boot 1.5 and now we need to migrate to spring boot 2. i know that activiti 7 goes well with spring boot 2 but it is still in beta so i can't convince my boss yet for migration. i need answer of some questions.
first: "is spring-boot-starter-basic project (the one that use spring boot 2) compatible with activiti version 5?". can i use it with activiti 5.x?
second: "if it is not why is the reason?" is it that you don't support it or there is technical issues?
third: if there is technical issues what are they?
i ask this because as long as we know, activiti itself does not rely on spring (so migrating from boot v1.5 to boot v2 shall not affect our activiti v5.x codes) but has a good integration with it. because of this presumption i can't give a good reason for migration. we don't need features in activiti 7 we need support for spring boot 2 (which we think does not have any impact on activiti v5.x codes). so i need to know if spring-boot-starter-basic project with spring boot 2 support can be used with activiti 5.x. if not why?

**Comment by salaboy** [comment]
@miladamery ok.. so questions are ok, but we prefer them in gitter.
1) nope that is SB 2 is only for Activiti 7+
2) no time to work on version 5.. small team.. if you want to contribute that back that will be great
3) no technical issues besides 5 has very old dependencies that will probably clash with SB2

HTH
