### ISSUE TITLE
Serialization of variable of object

### ISSUE THREAD

**Issue by daisuke-yoshimoto** [Activiti/Activiti#2074]
### Class loading problem in cloud

* In MicroService approach, each service does not necessarily share the same class definition.Therefore, it is necessary to exchange between services by general data method.

### SerializableType variable in Activiti

* On the other hand, Activiti can store objects as variables. In this case, it is also possible to save we own bean as a variable as it is.
* But, if the object includes its own bean, there is a possibility that deserialization can not be performed when reading with the cooperation destination service(like connector services).

* In Activiti Cloud, it is necessary to limit the ability to store variables with its own bean.
  * https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/impl/variable/SerializableType.java

### SerializableType variable in Activiti Cloud

* However, Activiti Cloud currently relies on SerializableType. Activiti Cloud saves the object deserialized by Jackson by Spring Framework as it is in a variable.
  * https://github.com/Activiti/activiti-api/blob/develop/activiti-api-process-model/src/main/java/org/activiti/api/process/model/payloads/StartProcessPayload.java#L16

* In order to avoid the above, we need to save the variable as JsonNode. If we save it as JsonNode, the result serialized as json is saved in the variable, and there is no problem of deserialization.
  * https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/impl/variable/JsonType.java
  * https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/impl/variable/LongJsonType.java

**Comment by daisuke-yoshimoto** [comment]
@qiudaoke 
Thanks. I see.
But, after understanding it, we are discussing the method of serialization here.

SerializableType is Java's native serialization method, but this should not be used in a cloud environment. It is an argument that JSON should be used.

**Comment by ryandawsonuk** [comment]
Is anyone currently working on this? Just want to check what the current status is.

**Comment by daisuke-yoshimoto** [comment]
@ryandawsonuk 
Sorry. I'm not working on this now. No progress.

**Comment by ryandawsonuk** [comment]
That's fine, thanks for the update.

**Comment by ryandawsonuk** [comment]
FYI, I'm now working on providing a way to serialize to json without needing the type of the variable object to be JsonNode - work ongoing under https://github.com/Activiti/Activiti/commits/balsarori-2049-process-vars-extension for https://github.com/Activiti/Activiti/issues/2049
