### ISSUE TITLE
BroadcastSignal not work with Activiti Core API and Activiti Cloud Rest API

### ISSUE THREAD

**Issue by daisuke-yoshimoto** [Activiti/Activiti#2075]
BroadcastSignal works only with Bpmn Signal Throw Event.
BroadcastSignal doesn't works with Activiti Core API and Activiti Cloud Rest API.

BroadcastSignal was removed when changing from ProcessEngineWrapper to ProcessRuntime.

### BroadcastSignal
* https://github.com/Activiti/Activiti/issues/1687
* https://github.com/Activiti/activiti-cloud-runtime-bundle-service/pull/38

### PR

* https://github.com/Activiti/Activiti/pull/2229
* https://github.com/Activiti/activiti-cloud-runtime-bundle-service/pull/171

**Comment by daisuke-yoshimoto** [comment]
I am going to fix this bug.
Should I deal with Activiti Cloud Rest API alone, not Activiti Core API layer?
Should I broadcast it even if I use Activiti Core API directly?

**Comment by salaboy** [comment]
@daisuke-yoshimoto yes.. sounds like a great contribution. We need that change in Activiti Core API as well. We would love to keep a 1 to 1 relationship between Core and Cloud APIs. 
In the case of the Core API, the event should be only broadcasted inside the ProcessRuntime. Does this make sense? Feel free to ask more questions in Gitter or we can organise a Skype call if you want to go over the details.

**Comment by daisuke-yoshimoto** [comment]
@salaboy 
Hi. I'm back.
First, I wil work on this issue.

**Comment by salaboy** [comment]
merged in develop, we need acceptance tests for signals
