### ISSUE TITLE
ActivitiObjectNotFoundException: Form with formKey 'repair.form' does not exist

### ISSUE THREAD

**Issue by Shaun-Yao** [Activiti/Activiti#2079]
I using spring boot v2.0.6, activiti v6.0.0
`<startEvent id="testRepairSt" name="StartEvent" activiti:formKey="repair.form" />`
Object renderedStartForm = formService.getRenderedStartForm(processDefinitionId);
<img width="210" alt="formkey" src="https://user-images.githubusercontent.com/18024481/47690700-024ae500-dc2a-11e8-908b-cbf1e7b37871.png">

**Comment by salaboy** [comment]
@Shaun-Yao can you create a reproducer for this problem? 
Also sharing more information about how are you deploying your process will be good.

**Comment by Shaun-Yao** [comment]
@salaboy  https://github.com/Shaun-Yao/activiti-test
the processes folder would be automatically deployed, and The process will start when the project starts.

`@SpringBootApplication(exclude = SecurityAutoConfiguration.class)
public class ActivitiTestApplication implements CommandLineRunner {

    @Autowired
    private RuntimeService runtimeService;

    @Autowired
    private TaskService taskService;

    @Autowired
    private RepositoryService repositoryService;

    public static void main(String[] args) {
        SpringApplication.run(ActivitiTestApplication.class, args);
    }

    @Override
    public void run(String... args) throws Exception {
        final String processId = "testRepair";
        System.out.println("Number of process definitions : "
                + repositoryService.createProcessDefinitionQuery().count());
        System.out.println("Number of tasks : " + taskService.createTaskQuery().count());
        runtimeService.startProcessInstanceByKey(processId);

        System.out.println("Number of tasks after process start: " + taskService.createTaskQuery().count());
    }
}`

`@GetMapping("/repairForm/{processDefinitionId}")
    public String repairForm(@PathVariable("processDefinitionId") String processDefinitionId, Model model) {

        Object renderedStartForm = formService.getRenderedStartForm(processDefinitionId);
        model.addAttribute("renderedStartForm", renderedStartForm);
        model.addAttribute("processDefinitionId", processDefinitionId);

        return "repairForm";
    }
`
The issue will appear when visit http://localhost:8080/repairForm/testRepair:1:4 .

**Comment by Shaun-Yao** [comment]
@salaboy Any suggestions?

**Comment by salaboy** [comment]
@Shaun-Yao hi there.. not yet.. we are working quite hard on releasing Activiti Core/ Cloud Beta2 and forms are not included in such release, so it is not high on the priority list. 
@balsarori can you spot the problem there?

**Comment by balsarori** [comment]
@Shaun-Yao only resources matching ``**.bpmn20.xml`` and ``**.bpmn `` are autodeployed no other resources will be deployed even if they are under the processes folder.
https://github.com/Activiti/Activiti/blob/6.x/modules/activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter-basic/src/main/java/org/activiti/spring/boot/ActivitiProperties.java#L45

**Comment by daisuke-yoshimoto** [comment]
@Shaun-Yao @balsarori 
How about adding the following prop to application.properties. https://github.com/Shaun-Yao/activiti-test/blob/master/src/main/resources/application.properties
```
spring.activiti.processDefinitionLocationSuffixes[0]=**.bpmn20.xml
spring.activiti.processDefinitionLocationSuffixes[1]=**.bpmn
spring.activiti.processDefinitionLocationSuffixes[2]=**.form
```

**Comment by balsarori** [comment]
@daisuke-yoshimoto yes that will probably work.

**Comment by daisuke-yoshimoto** [comment]
@Shaun-Yao Sorry. Please give us more detail about not working.

**Comment by Shaun-Yao** [comment]
@daisuke-yoshimoto I have add processDefinitionLocationSuffixes to the application.properties, and it is also reporting "Form with formKey 'repairStart.form' does not exist"

**Comment by daisuke-yoshimoto** [comment]
@Shaun-Yao Thanks. Ok. I will try to reproduce it.
However, I am sorry, I think I will keep you waiting for a while. I am working at a company.

**Comment by salaboy** [comment]
@Shaun-Yao ok.. if there is a new issue please create a separate issue to track it.. I will close this on now.

**Comment by Shaun-Yao** [comment]
em. I have created a new issue #2112
