### ISSUE TITLE
When a task has been claimed by another user, I shouldn't be able to see it in my task list in query

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2091]
Claim a task as `testuser` and then check whether `hruser` can see that task in their `/tasks/` list in query. They shouldn't see it.

Question: If `hruser` goes to `/tasks/{taskId}` should `hruser` see the task there?

Similar to scenario https://github.com/Activiti/activiti-cloud-acceptance-tests/blob/develop/runtime-acceptance-tests/src/main/resources/stories/runtime-bundle/task-actions.story#L67

**Comment by erdemedeiros** [comment]
Covered by https://github.com/Activiti/Activiti/issues/2103
