### ISSUE TITLE
When a task is completed in RB, it should show as completed in query

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2092]
Claim and complete a task. Check the task status in `/tasks/{taskId}` in the query module. The status should be `COMPLETED`. We are currently observing a situation where it remains `ASSIGNED` in query, despite having moved to `COMPLETED` in the runtime bundle.

We do have an acceptance test for this - https://github.com/Activiti/activiti-cloud-acceptance-tests/blob/develop/runtime-acceptance-tests/src/main/java/org/activiti/cloud/qa/story/ProcessInstanceTasks.java#L174

**Comment by erdemedeiros** [comment]
The problem is coming from the event sent by the runtime bundle which is inferring the status as `ASSIGNED` instead of `COMPLETED`.
