### ISSUE TITLE
Should not see task which has a candidateGroup specified if I'm not in that group

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2093]
Create a task for `testgroup`. Make sure `testuser` can see it and claim it. `hruser` should not see it in their list, either before or after the claim because `hruser` is not in `testgroup`.

Could be a new story for https://github.com/Activiti/activiti-cloud-acceptance-tests/blob/develop/runtime-acceptance-tests/src/main/resources/stories/runtime-bundle/task-actions.story or a new step within `create a process with group candidates, create a task and complete it`  (could be if we remove `hr` as a candidate group on that process)?

Question: What should the user see if they go to the `tasks/{taskId}` endpoint?

**Comment by miguelruizdev** [comment]
Thanks to the additional check in the step: 'the task cannot be claimed by $user', seeing and claiming a task are checked in the same step ('claiming' is the check in  the runtimeBundleSteps, and 'seeing' is the check in the querySteps)

**Comment by miguelruizdev** [comment]
This scenario is another basic one in order to test whether group candidates is behaving correctly

**Comment by erdemedeiros** [comment]
Actually the problem is happening only on completed tasks in query service. We are processing taskCandidate remove events and removing the candidates, which makes tasks visible by everyone.
