### ISSUE TITLE
Automate Docker Image & Helm Charts release and tagging

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2100]
Currently our Acceptance Tests depends on Docker Images and HELM charts that needs to be released and updated manually. In order to automate acceptance tests we need to automate also the release and tagging process for these artifacts.

**Comment by igdianov** [comment]
Let's try step by step in Jenkins-X cluster with PROW enabled:

1) importing a single microservice and make sure that we can build and release the chart in GitHub pages
2) see if we can automate the acceptance tests against that single microservice
3) add one more microservice and see if we can create the aggregator chart to be updated by each chart release

**Comment by almerico** [comment]
@salaboy Looks like 1,3,4  is working but 2 need clarification.
