### ISSUE TITLE
Multi Tasks

### ISSUE THREAD

**Issue by wangzhenhui1992** [Activiti/Activiti#2106]
I have a sequence workflow and only one user. How can I run two workflow instances at the same time.

**Comment by daisuke-yoshimoto** [comment]
@wangzhenhui1992 
Please more details.

**Comment by wangzhenhui1992** [comment]
@daisuke-yoshimoto 
BPMN like this  :   UserTask1-Service1-Service2
Every time the server gets a request, it will start a ProcessInstance and claim the task to my user.
Suppose that the server gets two request, 
the later ProcessInstance will be suspended if the previous one does not finished.
How can I run ProcessInstances in parallel.

同じユーザとプロセスで、複数プロセスインスタンスを非同期に実行させる方法を教えていただきたいんですが、可能性ありますか。

**Comment by daisuke-yoshimoto** [comment]
@wangzhenhui1992 
I'm sorry that I still do not know which layer is your problem.

If you only want to run ProcessInstances in parallel, you can execute startProcessInstance API from each request thread. 

Also, if you want to suspend ProcessInstances, you can call the suspended API.
RuntimeService.suspendProcessInstanceById(String processInstanceId)
https://www.activiti.org/javadocs/6.latest/org/activiti/engine/runtimeservice#suspendProcessInstanceById(java.lang.String)

**Comment by wangzhenhui1992** [comment]
@daisuke-yoshimoto Thank you

**Comment by wangzhenhui1992** [comment]
@daisuke-yoshimoto 
タスクに「activiti:async="true" activiti:exclusive="false"」がついてないので？
