### ISSUE TITLE
Variable mapping for call activity and user task

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2118]
Currently variable mappings are supported for call activity

The changes under https://github.com/Activiti/Activiti/issues/2104 mean that all variables will be copied to task level if the `copyVariablesToLocalForTasks` flag is set (which it is by default from spring boot level)

If we had mappings on user tasks then we could restrict which variables were copied (performance gain) and also allow two tasks to map in the same proc variable and map it out to a different proc variable (avoid conflict)

We could approach this by moving the [in and output parameters from the CallActivity](https://github.com/Activiti/Activiti/blob/develop/activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/CallActivity.java#L22) to the parent Activity class so that it could be read from all task types

**Comment by ryandawsonuk** [comment]
Happy to track this but I think it's @balsarori that will be working on it

**Comment by ryandawsonuk** [comment]
I think this was done for connectors under https://github.com/Activiti/Activiti/issues/2213 but not for user tasks

**Comment by erdemedeiros** [comment]
Latest status from https://issues.alfresco.com/jira/browse/ACTIVITI-3288:

As part of this epic, we decided also to do the following changes:

**1. Remove the need to look up in the definition files to apply the mappings at runtime**

From now on the definition files will be used only to create the mappings inside the modeling app and not used for the mapping at runtime, the mapping will be fully described from the extension file.

The new mappings logic has the 3 following cases and is applied for any type of task (user tasks, service tasks / connectors and call activities):

- **Send all** - If no mapping is found for a task inside the process extension file: all the variables are made available to the connector.
`mapping: {}`
- **Map** - If a mapping is found for a task inside the process extension file: only  the variables which are mapped are available to the task.
- **Send Nothing** - It's possible to say "do not make any variable available to the connector" by having a mapping without inputs for the task, like following:
`mapping: { taskid:{ input {}, output:{} } }`
 
**Changes in the current behaviour:**

So far, service tasks were using connector definitions to automatically map process variables from/to connector inputs/outputs which have matching names. As we are no longer taking into account connector definitions, this will not be possible anymore.

**2. Move the constant logic in another place**

Today inside the mapping section of the process extension file we also have the possibility to define constants (`static_value` type).
```json
"mappings": {
    "taskId": {
        "inputs": {
            “_constant_value_": {
                "type": "static_value",
                "value": "myConstantValue"
            }
        }
    }
}
```
The new place for the constant is a new section called "constants" inside the extension file. We will also remove the possibility to define "static_value" inside the mappings.

```json
"mappings": {},
"constants" : {
    "taskId": {
        "_constant_value_" : {
          "value": "myConstantValue"
        }
    }
}
 
```

**Legacy mapping for call activities:**

Currently, there is already a variable mappings mechanism coming from version 6. This mapping is defined inside the XML file and not in the extension files (which is a new concept introduced by Activiti 7). If a mapping is found in the extension file, we ignore the old behavior and we apply the new one. We will cut the support for mapping in the xml process definition.
