### ISSUE TITLE
How to get the comments of the ProcessInstance that has finished

### ISSUE THREAD

**Issue by Shaun-Yao** [Activiti/Activiti#2123]
```
ProcessInstance processInstance = 
 runtimeService.createProcessInstanceQuery().processInstanceBusinessKey(businessKey).singleResult(); 
List<Comment> comments = taskService.getProcessInstanceComments(processInstance.getId());
```
The above code is work for the running ProcessInstance, but it is not work for the  finished ProcessInstance.

**Comment by ryandawsonuk** [comment]
Could you try with `historyService.createHistoricProcessInstanceQuery().processInstanceBusinessKey(businessKey).singleResult()` ?

**Comment by daisuke-yoshimoto** [comment]
@Shaun-Yao 
You need to use  TaskService.getProcessInstanceComments(String processInstanceId)
https://www.activiti.org/javadocs/org/activiti/engine/taskservice#getProcessInstanceComments-java.lang.String-

https://www.activiti.org/javadocs/6.latest/org/activiti/engine/taskservice#getProcessInstanceComments(java.lang.String)

**Comment by ryandawsonuk** [comment]
Googling reveals an example at https://github.com/emdev-limited/activiti-liferay/blob/master/activiti-web/src/main/java/net/emforge/activiti/WorkflowLogManagerImpl.java

**Comment by Shaun-Yao** [comment]
Thanks for the reply! getProcessInstanceComments is work for historicProcessInstanceId.
taskService.getProcessInstanceComments(historicProcessInstanceId);
