### ISSUE TITLE
how can I get x, y, width, height

### ISSUE THREAD

**Issue by zx445146042zx** [Activiti/Activiti#2124]
`ActivityImpl activity = processDefinitionEntity.findActivity(activityId);`
`Map<String, Object> map = new HashMap<String, Object>();`
`map.put("x", activity.getX());`
`map.put("y", activity.getY());`
`map.put("width", activity.getWidth());`
`map.put("height", activity.getHeight());`
in 5.x , I can get these properties;
but 6.x , How can I get these?
please help me!

**Comment by salaboy** [comment]
you now needs to get the BpmnModel and then check the GraphicInfo ->  public GraphicInfo getGraphicInfo(String key) which gives you the coordinates: 

```
public class GraphicInfo {

  protected double x;
  protected double y;
  protected double height;
  protected double width;

```

Check the test called: BpmnParseTest -> https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/test/java/org/activiti/engine/test/bpmn/parse/BpmnParseTest.java#L120

**Comment by zx445146042zx** [comment]
@salaboy think you very much!

**Comment by salaboy** [comment]
@zx445146042zx you are welcome :)
