### ISSUE TITLE
Rename REST endpoint to resume a suspended process

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#2126]
Current endpoint is `/v1/process-instances/{ID}/activate`. It should be renamed to `/v1/process-instances/{ID}/resume` to be consistent with the Java API.

**Comment by erdemedeiros** [comment]
Make sure that @mauriziovitale is aware when this get released as this will impact the UI.

**Comment by mauriziovitale** [comment]
Thanks, @erdemedeiros going to raise an issue from our side.

**Comment by salaboy** [comment]
@mauriziovitale thanks!
