### ISSUE TITLE
ProcessRuntime autodeploy process behaviour too aggressive

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2138]
The current behaviour of the Activiti Spring configuration is to automatically deploy the process definitions located inside the /processes/ directory. This behaviour works well when all the process definitions are valid, but if a single process has any parsing problems (standard xml schema validation) the whole runtime fail to start. 

The expected behaviour should be:
- Log and expose (actuator) the correctly deployed process definitions with clear keys and names
- Log and expose (actuator) the processes that were not deployed and the errors causing the failure to deploy
- The Runtime should start if there is at least a process definition deployed
- The user should be able to parameterise when to fail 
   - fail on the first error
   - fail on no process definition
   - never fail (for the case where the application might be providing other functionality besides process endpoints) 

Example process that cause the runtime not to start today: https://github.com/salaboy/bpmn-scenarios/blob/master/processes/ServiceTask%20without%20Implementation.bpmn20.xml

**Comment by salaboy** [comment]
@daisuke-yoshimoto amazing stuff! now we need to make sure that we use a sensible default in the RB project.

**Comment by daisuke-yoshimoto** [comment]
@salaboy Ok. I will apply optin to rb in the following issue.
https://github.com/Activiti/Activiti/issues/2315

**Comment by salaboy** [comment]
initial work done by @daisuke-yoshimoto merged into develop
