### ISSUE TITLE
variable event visibility for copied task vars

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2144]
offshoot of https://github.com/Activiti/Activiti/issues/2104

ended up having to take out this part of test - https://github.com/Activiti/activiti-cloud-acceptance-tests/commit/3415679f30a329b6d66dd472739a80698bdd1626#diff-93f52a851ac32ca6775085ead75617d8L112

testuser starts a process that leads to task being created for testuser and hruser

Both see their own copies of the task variables. But only testuser has visibility of the variable creation events, at least when policies are enabled. This is presumably because testuser took the action that led to the creation. 

To make those events visible to hruser I guess audit would have to somehow know that the task variables are for a task that is assigned to that user

**Comment by salaboy** [comment]
@ryandawsonuk we need to follow up on this one.. because I don't even know what needs to be done for this one.

**Comment by salaboy** [comment]
@ryandawsonuk is this a problem in audit? because you mention events. You are correct on this assertion: "filtering should be based on process definition only and not who took the action" did you find where that is not the case in the code?

**Comment by salaboy** [comment]
@ryandawsonuk is it not a problem of defaults when user is not included in the security policies? Does both users contains the same policies?

**Comment by ryandawsonuk** [comment]
@salaboy that might well be it. The process seems to be https://github.com/Activiti/example-runtime-bundle/blob/6a59e17a3c3a3642cd460375f9a34590a1b443a7/src/main/resources/processes/SingleTaskProcessGroupCandidatesTestGroup.bpmn20.xml#L3 and while testUser has * access I don't see it in [the list for hruser](https://github.com/Activiti/activiti-cloud-example-chart/blob/master/charts/activiti-cloud-full-example/values.yaml#L30). I guess we need to update the policies and [put that part of the test back in](https://github.com/Activiti/activiti-cloud-acceptance-tests/commit/3415679f30a329b6d66dd472739a80698bdd1626#diff-93f52a851ac32ca6775085ead75617d8L112) and see

**Comment by salaboy** [comment]
@ryandawsonuk can you please do that?

**Comment by salaboy** [comment]
This might be solved also by @CTI777 changes in Query where we now store process and task variables as separate entities.

**Comment by miguelruizdev** [comment]
Issue solved: https://github.com/Activiti/activiti-cloud-acceptance-scenarios/pull/121
