### ISSUE TITLE
filtering by instance id and event type in audit

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2148]
The acceptance tests call an endpoint that is meant to filter by process instance id and event type:

https://github.com/Activiti/activiti-cloud-acceptance-tests/commit/3415679f30a329b6d66dd472739a80698bdd1626#diff-66367d62043d244a38d6b955c22d2bd3R144

But with more data present I found I had to add an extra in-memory filter as it was returning non-matching data:

https://github.com/Activiti/activiti-cloud-acceptance-tests/commit/3415679f30a329b6d66dd472739a80698bdd1626#diff-66367d62043d244a38d6b955c22d2bd3R153

Also checked this with postman

**Comment by salaboy** [comment]
@miguelruizdev we need to confirm this one is fixed

**Comment by salaboy** [comment]
@miguelruizdev please confirm.. the acceptance test lib was updated so now we need to validate with the new images only

**Comment by miguelruizdev** [comment]
Everything green 👍
