### ISSUE TITLE
It would be useful to have hashCode(), equals() and toString() methods in events 

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2154]
so that, the event instance objects can be compared, cached and debugged in logs

**Comment by salaboy** [comment]
@igdianov I am on it.. if you look here: https://github.com/Activiti/activiti-api/pull/36/files

**Comment by salaboy** [comment]
@igdianov dependent PR merged with the changes required here: https://github.com/Activiti/activiti-api/pull/36/files
