### ISSUE TITLE
Remove `consumes` property from ProcessInstanceController.getProcessDiagram

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#2155]
Currently this method has the following property `consumes = "image/svg+xml"`. However it's a `GET` method so it's not consuming anything. This should be removed.

**Comment by erdemedeiros** [comment]
This may impact @mauriziovitale that might be using `CONTENT-TYPE` header.

**Comment by abdotalaat** [comment]
@CTI777  are you currently working in this issue?

**Comment by CTI777** [comment]
I have just removed this property, because it was assigned to me:
https://github.com/Activiti/activiti-cloud-runtime-bundle-service/pull/150
I think you may do any other changes if needed...
