### ISSUE TITLE
delegateExpression fields are not cleared

### ISSUE THREAD

**Issue by LukasKraushofer** [Activiti/Activiti#2161]
Hi, I run across a strange behaviour of delegateExpressions...

If I take your ```ServiceTaskFieldInjectionTest``` example and edit the ```ServiceTaskFieldInjectionTest.testDelegateExpressionWithPrototypeBean.bpmn20.xml``` slightly so I have multiple ```<serviceTask>``` elements and each uses "the same" delegateExpression, **but** does not set every field I get the Expression value for the field of the delegateExpression called before.

```xml
<process id="delegateExpressionPrototype">

        <startEvent id="start"/>
        <sequenceFlow id="flow1" sourceRef="start" targetRef="serviceTask1"/>

        <serviceTask id="serviceTask1" activiti:delegateExpression="${prototypeDelegateExpressionBean}">
            <extensionElements>
                <activiti:field name="fieldA" expression="${input * 2}"/>
                <activiti:field name="fieldB" expression="${1 + 1}"/>
                <activiti:field name="resultVariableName" stringValue="resultServiceTask1"/>
            </extensionElements>
        </serviceTask>

        <sequenceFlow id="flow2" sourceRef="serviceTask1" targetRef="serviceTask2"/>
        
        <serviceTask id="serviceTask2" activiti:delegateExpression="${prototypeDelegateExpressionBean}">
            <extensionElements>
                <activiti:field name="fieldA" expression="${123}"/>
                <!-- <activiti:field name="fieldB" expression="${456}"/> I want 'fieldB' to be not set at all -->
                <activiti:field name="resultVariableName" stringValue="resultServiceTask2"/>
            </extensionElements>
        </serviceTask>
        
        <sequenceFlow id="flow3" sourceRef="serviceTask2" targetRef="userTask"/>

        <userTask id="userTask" name="theTask"/>
        <sequenceFlow id="flow4" sourceRef="userTask" targetRef="end"/>

        <endEvent id="end"/>

</process>
```

As I said, what happens is that in **serviceTask2** the value of the Expression for **fieldB** has the same value as in **serviceTask1**, I would expect it to be null instead.

This happens with Activiti 5.22.0

**Comment by salaboy** [comment]
@balsarori do you know if this has been fixed in 5.23?

**Comment by LukasKraushofer** [comment]
ok, it seems like my spring bean with scope prototype wont be recreated and is used as a singleton, that could explain the problem.
maybe there is something wrong in my test configuration, I'll check
I didn't know there's a version 5.23

**Comment by salaboy** [comment]
@LukasKraushofer let's check with @balsarori who has been working on that.

**Comment by balsarori** [comment]
@LukasKraushofer
Field Injection for delegate expressions isn't thread safe see -> https://www.activiti.org/userguide/#serviceTaskFieldInjectionThreadSafety

And there isn't a 5.23 release yet.

**Comment by LukasKraushofer** [comment]
After my investigation I found out that our `JavaDelegates` are written into a map and that map is used by Alfresco, that explains why the prototype beans are not recreated and that could explain why reused Expression Fields are not cleared and are holding the values of the last serviceTask with the same delegateExpression.

I would say you can close this Issue.

**but** I'm not sure if I correctly understood the thread safety of *singleton* JavaDelegates.
Is it save to use `DelegateHelper#getFieldExpression` in the JavaDelegates `execute` method especially when I use the JavaDelegate like in the example of the first post, or should i put a `synchronized` block inside the `execute` method?
What if the process has been started multiple times concurrently ?

**Comment by salaboy** [comment]
@balsarori ^ 

@LukasKraushofer can you share the link to where is that consumed in your tests? When you say 'is used by Alfresco' what do you mean exactly? which class so I can take a look as well to confirm.

**Comment by LukasKraushofer** [comment]
@salaboy i suppose you know Alfresco

As you can see in the [Alfresco activiti-context.xml](https://github.com/Alfresco/alfresco-repository/blob/master/src/main/resources/alfresco/activiti-context.xml#L75) the bean `activitiProcessEngineConfiguration` extends from `ProcessEngineConfigurationImpl` and from my understanding only beans contained in its `beans` property gets populated and will be usable in (Alfresco)workflows.
That means, I have to add every `JavaDelegate` I write into Alfrescos `activitiBeanRegistry` which is a Map and that means every `JavaDelegate` I write is used as a *singleton*

**Comment by salaboy** [comment]
@LukasKraushofer I know what Alfresco is but it means different things for different people.. so without that context that you provided now it was difficult to know for sure. 

Regarding 
```
I have to add every JavaDelegate I write into Alfrescos activitiBeanRegistry which is a Map and that means every JavaDelegate I write is used as a singleton
```

yes.. in that case you have singleton Delegates, because you are adding them into a map.. and then yes you will need to syncronize them for concurrency. But that is the Alfresco Content repository integration that can be improved to not impose that restriction. It is not Activiti itself.

**Comment by balsarori** [comment]
@LukasKraushofer does your beans have shared state? If not then I guess is safe to use them as Java delegates without having to synchronize

**Comment by LukasKraushofer** [comment]
@balsarori my JavaDelegates are like the `SingletonDelegateExpressionBean`.
They used to have `Expression` properties, but I removed them and would now read the field expressions with `DelegateHelper#getFieldExpression`. 
The delegate itself doesnt have a shared state, just reads the expression fields and than calling a service

e.g.
```java
    @Override
    public void execute(DelegateExecution execution) {
        String pId= execution.getProcessInstanceId();
        Expression fieldx= DelegateHelper.getFieldExpression(execution, "fieldx");
        this.someService(pId, fieldx.getValue(execution));
    }
```

**Comment by balsarori** [comment]
@LukasKraushofer using ``DelegateHelper.getFieldExpression`` is a better approach than injecting fields directly to the Java delegate bean and should be thread safe.

**Comment by LukasKraushofer** [comment]
@balsarori that's the reason I'm now using `DelegateHelper.getFieldExpression` ;)
Without instance properties inside the `JavaDelegate` and by reading field expressions with the `DelegateHelper` class inside my `execute` method there should be nothing to worry about and it should be thread-safe, shouldn't it?

**Comment by balsarori** [comment]
@LukasKraushofer we are using it in APS and we didn't have face concurrency issues.

**Comment by LukasKraushofer** [comment]
@balsarori good to hear
@all thanks for your help!
