### ISSUE TITLE
EntityId is set to the wrong value on cloud events

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#2165]
The method [CloudRuntimeEvent.getEntityId](https://github.com/Activiti/activiti-cloud-api/blob/develop/activiti-cloud-api-model-shared/src/main/java/org/activiti/cloud/api/model/shared/events/CloudRuntimeEvent.java#L35) should always be a shortcut to `RuntimeEvent.getEntity().getId()`. So it should always be set with the value `entity.getId()`.

It's wrong set with `processInstanceId` in the following events
- CloudIntegrationResultReceivedImpl
- CloudSequenceFlowTakenImpl
- CloudBPMNActivityEventImpl
- CloudIntegrationRequestedImpl

**Comment by salaboy** [comment]
@erdemedeiros @CTI777 can you guys clarify if this is done or more work is missing here?. If the work is done please close.
