### ISSUE TITLE
Review Maven Deploy plugin configuration for multi-module projects

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2172]
It is best practice in multi-module Maven projects to deploy artifacts at the the end of the successful reactor build, so that if any of the module builds fail, none of the reactor projects is deployed.  

In Jenkins-X release pipelines, the multi-module artifacts are deployed into activiti-releases Nexus repository. The `<deployAtEnd>` configuration  will ensure that deployment is done atomically similar to Maven release workflow into Maven Central.

```xml
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-deploy-plugin</artifactId>
        <version>2.8.2</version>
        <configuration>
          <deployAtEnd>true</deployAtEnd>
        </configuration>
      </plugin>
    </plugins>
  </build>
```

**Comment by salaboy** [comment]
@igdianov should we add this everywhere? Should we start at the Activiti Core level?

**Comment by igdianov** [comment]
Done.
