### ISSUE TITLE
Missing id for BPMNElement

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#2175]
[BPMNElement](https://github.com/Activiti/activiti-api/blob/develop/activiti-api-process-model/src/main/java/org/activiti/api/process/model/BPMNElement.java) should provide a `getId()` method.

The value should be set in the related converters:
- [ToSequenceFlowTakenConverter](https://github.com/Activiti/Activiti/blob/develop/activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ToSequenceFlowTakenConverter.java)
- [ToActivityConverter](https://github.com/Activiti/Activiti/blob/develop/activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/model/impl/ToActivityConverter.java)

**Comment by erdemedeiros** [comment]
Blocks https://github.com/Activiti/Activiti/issues/2165

**Comment by salaboy** [comment]
@CTI777 To make this issue more explicit, we need to move one level up the method getElementId() from BPMNActivity to BPMNElement, so SequenceFlow can also have the getElementId() method.

**Comment by salaboy** [comment]
@erdemedeiros @CTI777 I will close this one because it is merged
