### ISSUE TITLE
How to call back execution

### ISSUE THREAD

**Issue by xingjl6280** [Activiti/Activiti#2181]
Hi team,

There are many scenarios a user regret his submission, and he should have a chance to call back his submission if the current task is still active.

I tried a lot to find related questions or articles but got nothing.

We tried to manipulating the bpm flow of the instance by adding identical node and sequence, but it's really complicated and not that straightforward. 
Especially, when using multi-instance task with custom completion condition, the solution doesn't work well.

Is there any build-in mechanism or any suggestion?

please kindly advise. tons of thanks

**Comment by salaboy** [comment]
@xingjl6280 hi there, we usually use this issues to report issues with the current code not about questions. Also it is really important for us to understand which version of Activiti are you using, without that is really difficult to help. For questions, we recommend the user forums: https://community.alfresco.com/community/bpm

**Comment by xingjl6280** [comment]
understood, i will post questions there. thank you very much
