### ISSUE TITLE
Handling expressions for json variables

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2184]
We're making it easier to work with json vars under https://github.com/Activiti/Activiti/issues/2049

However, it can still be tricky to work with json vars in expressions. Exactly how tricky depends on how the variable is stored in the first place - as JsonNode, LinkedHashMap or a custom POJO.

A custom POJO is easy. Then you can use the structure and methods of the POJO.

With JsonNode it's tricky. Navigating the jackson tree when there are vars of different types seems to require a lot of type casting that I can't see how to do in expressions.

With LinkedHashMap you can get elements out of the map and access them as their original types. This is much better but we could still do with more tests and examples for using types like java collections.

I think json posted in via REST will be handled as LinkedHashMap but I am not entirely sure.

My impression from searching engine for examples of `activiti:expression` is that the favoured activiti way to do this sort of thing is to write java code to evaluate complex conditions and call that java code from the expression.

**Comment by balsarori** [comment]
@ryandawsonuk might be easier to convert jsons to maps? With maps it would be possible to do ``myObject.myprop.mysubprop``

**Comment by ryandawsonuk** [comment]
Yeah [am doing so in the referenced example PR](https://github.com/Activiti/Activiti/pull/2185/files#diff-a97b66303c25d797834ed789495b5725R35). If we do favour maps we could do with building out more examples though.

**Comment by ryandawsonuk** [comment]
If we do go that road we could force conversion of JsonNode to LinkedHashMap in JaonType and LongJsonType in the engine.

**Comment by ryandawsonuk** [comment]
@nitinkrgoyal has shared example process https://gist.github.com/nitinkrgoyal/0d98ac6c707946a111343fdfad502090#file-multi-instance-bpmn20-xml-L17 

With a test like

```
@Test
public void createMultiInstanceProcessAndValidate() {

    securityUtil.logInAs("salaboy");

    List<String> userList = new ArrayList<>();
    userList.add("salaboy");
    userList.add("salaboy");
    userList.add("salaboy");

    System.out.println(" userList --- " + userList );

    ProcessInstance processInstance = processRuntime.start(ProcessPayloadBuilder
            .start()
            .withProcessDefinitionKey("multi-instance")
            .withVariable("userCollection", userList)
            .build());
   System.out.println(">>> Created Process Instance: " + processInstance);

   Page<Task> tasks = taskRuntime.tasks(Pageable.of(0, 10));
   if (tasks.getTotalItems() > 0) {
       for (Task t : tasks.getContent()) {

           List<VariableInstance> variables2 = taskRuntime.variables(TaskPayloadBuilder.variables().withTaskId(t.getId()).build());
           Task task1 = taskRuntime.complete(TaskPayloadBuilder.complete()
                   .withTaskId(t.getId()).build());
       }
   }
}
```

and using MultiInstanceActivityBehavior.java
```
@SuppressWarnings("rawtypes")
protected Collection resolveAndValidateCollection(DelegateExecution execution) {
Object obj = resolveCollection(execution);
if (collectionExpression != null) {
if (!(obj instanceof Collection)) {
throw new ActivitiIllegalArgumentException(collectionExpression.getExpressionText() + "' didn't resolve to a Collection");
}

} ......

return (Collection) obj;
}
```
And hit:
"When i am setting the variables on process, it's being set as Array List which is of type collection. When i am trying to complete the task without passing any variable then it gets the variable from process and that time "userCollection" variable
value is ArrayNode and not ArrayList and ArrayNode is not type of Collection and because of that it fails."

**Comment by ryandawsonuk** [comment]
Have added related issue https://github.com/Activiti/Activiti/issues/2364

**Comment by daisuke-yoshimoto** [comment]
@ryandawsonuk 
I created pr for this issue. Please review it.
https://github.com/Activiti/Activiti/pull/2374

**Comment by daisuke-yoshimoto** [comment]
@ryandawsonuk 
Can I close this issue by following PR?
https://github.com/Activiti/Activiti/pull/2374

**Comment by daisuke-yoshimoto** [comment]
@ryandawsonuk
Can I close this issue by following PR?
#2374

**Comment by salaboy** [comment]
@daisuke-yoshimoto sorry.. for some reason we missed your comments here :)
