### ISSUE TITLE
MessageValidator returning false positive

### ISSUE THREAD

**Issue by AGrzes** [Activiti/Activiti#2188]
I have the following (fragment) of the process definition.

```xml
<bpmn2:definitions targetNamespace="myNamespace" xmlns="myNamespace"
...
  <bpmn2:itemDefinition id="ItemDefinition_5650" isCollection="false" structureRef="java.util.Map"/>
  <bpmn2:message id="Message_2" itemRef="ItemDefinition_5650" name="redirectCallback">
    <bpmn2:extensionElements>
      <ext:style/>
    </bpmn2:extensionElements>
  </bpmn2:message>
...
```

The [MessageValidator](https://github.com/Activiti/Activiti/blob/develop/activiti-process-validation/src/main/java/org/activiti/validation/validator/impl/MessageValidator.java) is checking if itemRefs and returning error. 

```java
if (!bpmnModel.getItemDefinitions().containsKey(message.getItemRef())) {
            addError(errors, Problems.MESSAGE_INVALID_ITEM_REF, null, message, "Item reference is invalid: not found");
}
```

Debuggin it it looks like the keys on the ItemDefinitions map are prefixed with `myNamespace` but the ItemRef is not prefixed.

If I change the bpmn to 

```xml
<bpmn2:definitions targetNamespace="myNamespace" xmlns="myNamespace" xmlns:my="myNamespace" 
...
  <bpmn2:itemDefinition id="ItemDefinition_5650" isCollection="false" structureRef="java.util.Map"/>
  <bpmn2:message id="Message_2" itemRef="my:ItemDefinition_5650" name="redirectCallback">
    <bpmn2:extensionElements>
      <ext:style/>
    </bpmn2:extensionElements>
  </bpmn2:message>
...
```

The error goes away.

**Comment by salaboy** [comment]
@AGrzes hi there.. thanks for reporting this. Can you please share with us which version of Activiti are you using? 
Also if you can share a simple reproducer so we can make sure that we can fix the issue. Notice that depending on which version of Activiti you are using, there must be a test in the Activiti-engine process showing how messages are used and how they are validated.

**Comment by salaboy** [comment]
@AGrzes awesome! thanks a lot. 
I guess that you will find the same issue in Beta3, but we recommend to upgrade to beta3 if possible.. so if we fix this one for Beta4 in 2 weeks you can get the fix in.

**Comment by salaboy** [comment]
@AGrzes thanks a lot.. this fix will be included in Beta4
