### ISSUE TITLE
Let's enforce same build parent version in dependency convergence tests

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2200]
so that we can have automated aggregator pom releases downstream without manual merge step, unless we need to block it with a label, i.e. `work-in-progress' using Mergify conditions. 

To enforce same build parent version in dependency convergence tests for automated aggregator pom release requires a including simple build parent marker artifact of type pom with release version as dependency propagated into all downstream repositories. The same build parent marker artifact version is also pushed into aggregator pom and included as dependency in dependencies-tests via single pull request from upstream. 

The CI pipeline for the PR will try building PoM with dependency test keep failing until all artifacts versions with the same build marker version are propagated and converged into aggregator via single PR. 

Thus, we can ensure that aggregator pom release will not contain dependencies with different parent versions releases.

**Comment by igdianov** [comment]
@salaboy I have added same parent version convergence test in every repo, so that push version commits from every repository accumulate in a single PR until all versions match to merge and cut the release with consistent versions. 

I think it is best to let it fail fast and wait for consistent versions to save time and number of builds.

Activiti/activiti-dependencies#77
Activiti/activiti-api#55
Activiti/activiti-core-common#27
#2199
Activiti/activiti-build#46

Let's validate this approach and then replicate the best practice to Activiti Cloud repos.

**Comment by salaboy** [comment]
@igdianov all merged.. let's create another issue for cloud.
I will ask Ryan to check the version of the cloud environment.. I am pretty sure that we did the upgrade
