### ISSUE TITLE
Activiti Cloud Modeling repos dependencies alignment

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2202]
We upgraded to Spring Boot 2.1 and Spring Cloud Greenwhich M3. We need to make sure that we align our starters (all of them) to those dependencies. 
Now Activiti Cloud Modeling is pointing to random Spring Cloud modules such as Contracts 
https://github.com/Activiti/activiti-cloud-modeling-build/blob/develop/pom.xml#L74

which drags a bunch of old stuff into the classpath.

**Comment by salaboy** [comment]
Related to this issue is also the need to add 
```
 <dependency>
       <groupId>org.springframework.cloud</groupId>
       <artifactId>spring-cloud-stream-test-support</artifactId>
       <scope>test</scope>
   </dependency>
```

Due to activiti-cloud-service-common / tests includes spring-cloud-streams which force you to have a binder in the classpath.

**Comment by salaboy** [comment]
@constantin-ciobotaru can you take a look at this?

**Comment by mteodori** [comment]
obsoleted by #3050
