### ISSUE TITLE
ttc projects in pipelines and tests

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2226]
We have the following ttc projects:

ttc-campaigns-service
ttc-connectors-dummytwitter
ttc-rb-english-campaign
ttc-query-campaign
ttc-connectors-processing
ttc-connectors-ranking
ttc-connectors-reward
ttc-dashboard-ui
ttc-acceptance-tests

From a release perspective, these are examples like all the others which are tagged and docker images published. But these projects are currently not being updated by updatebot. They are listed in the updatebot yaml - https://github.com/Activiti/activiti-cloud-dependencies/blob/develop/.updatebot.yml#L5
But https://github.com/Activiti/ttc-rb-english-campaign/pull/22 should currently say 91 and not 83. This means we're not testing them against the latest library versions. I suspect the cause is that we had open updatebot PRs when we swichted to singlePullRequest and now we probably need to merge them all and run pipeline again.

Also, we haven't decided where to put a helm chart for deploying this example (though we did create one https://github.com/Activiti/ttc-acceptance-tests/pull/23) and haven't been running those acc tests so they've not been updated in the recent acc test refactoring.

**Comment by ryandawsonuk** [comment]
Pipelines now updating the master branch for these repos. Not clear what to do about acc tests for these.

**Comment by miguelruizdev** [comment]
We haven't addressed the tests under this issue
