### ISSUE TITLE
History tables missing

### ISSUE THREAD

**Issue by sujithgeorge** [Activiti/Activiti#2228]
I am using Activiti 7.0.0.Beta3 core (and not cloud) in my Spring Boot application. I enabled history by setting spring boot config property: spring.activiti.historyLevel=full. When I start Activiti , it fails by reporting a missing table "Table '.ACT_HI_VARINST' doesn't exist". I have auto DDL enabled(I know this for sure because the other non-history Activiti tables got created automatically). What should I do to get all the history tables created automatically? I was expecting it to be driven by the spring.activiti.historyLevel, but apparently it doesn't.

**Comment by salaboy** [comment]
@sujithgeorge as I mention on the gitter channel we discourage the use of Local History, but we will look into this issue to at least not fail. Moving forward this might be supported.

**Comment by salaboy** [comment]
closing due inactivity, if this is still a problem after testing @ryandawsonuk suggestion we can reopen

**Comment by ryandawsonuk** [comment]
@prajwal11 reports on gitter "@salaboy I tried enabling spring.activiti.historyLevel=full but this dint create history tables in activiti 7 database.I also tried enabling spring.activiti.isDbHistoryUsed=true and even that dint create any database.Is there anything else that should be enabled?"

**Comment by prajwal11** [comment]
I am using Activiti 7 core in my spring boot application and I tried enabling spring.activiti.historyLevel=full but this dint create history tables in activiti 7 database.I also tried enabling spring.activiti.isDbHistoryUsed=true and even that dint create any database.Is there anything else that should be enabled?

**Comment by salaboy** [comment]
@prajwal11 thanks a lot for confirming that the proposed work around doesn't work .. we will look into it and fix it before GA

**Comment by daisuke-yoshimoto** [comment]
I created pr for fixing thie issue.
https://github.com/Activiti/Activiti/pull/2423

**Comment by prajwal11** [comment]
Thanks a lot for fixing the issue.Adding spring.activiti.dbHistoryUsed = true and spring.activiti.historyLevel=audit will create history tables and is storing all the data is proper format.

**Comment by salaboy** [comment]
This fix will be included in the GA release.

**Comment by salaboy** [comment]
merged

**Comment by tjad** [comment]
@salaboy Could you provide clarity on what is meant by "Local History" and why it will not be supported in future ?
(What is preferred environment setup for handling history/audit ?)
