### ISSUE TITLE
develop branch on activiti-modeling-app

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2234]
https://github.com/Activiti/activiti-modeling-app is an example-level repo

For other example-level repos we only have a master branch and not a develop. The idea is that we build it from jenkins-x it deploys.

If we have a develop branch then currently develop branch will be used for tagging and docker build at time of release - https://github.com/Activiti/activiti-scripts/pull/12

We would remove develop branch but this needs to be agreed with @popovicsandras as could cause problems outside activiti

**Comment by salaboy** [comment]
moved to master.
