### ISSUE TITLE
Is any option to get list of completed tasks in the process instance?

### ISSUE THREAD

**Issue by mkawczynski07** [Activiti/Activiti#2243]
Is any option to get list of completed tasks in the process instance?

**Comment by mkawczynski07** [comment]
I found:
https://www.activiti.org/userguide/#historyConfig

Does activiti 7 runtimes support history?

**Comment by salaboy** [comment]
@mkawczynski07 in Activiti Cloud we rely on the query service for historic information. The Runtime Bundle is not supposed to keep the information, just act as an executor following the CQRS pattern. 

So, the answer is yes, you need to use the Query Service, or implement a ProcessInstanceCompletedEvent listener to store which processes were completed. (Which is pretty much what the Query Service does). So it is really up to what are you trying to achieve.

**Comment by salaboy** [comment]
I am closing this issue due I got a thumbs up.
