### ISSUE TITLE
Make sure method property is defined in @RequestMapping

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#2244]
In some places the property `method` is not set in the annotation `@RequestMapping`. For instance in [ProcessInstanceTasksController.getTasks(...)](https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-api/src/main/java/org/activiti/cloud/services/rest/api/ProcessInstanceTasksController.java#L14). This means that Spring will create endpoints not only for `GET`, but for all other verbs (`POST`, `PUT`, `DELETE`).

In order to fix it, we need to either specify the method or use more specific anotations (`@GetMapping`, `@PostMapping`).

- [x] Runtime Bundle
- [x] Query Service
- [x] Audit Service

**Comment by salaboy** [comment]
- Runtime Bundle
- Query Service 
- Audit Service
