### ISSUE TITLE
there is no process diagram generated when activiti6 dynamic deploy

### ISSUE THREAD

**Issue by DestinyWang** [Activiti/Activiti#2246]
When I was using Activiti, I found that:

- When the project path BPMN file is deployed, two data files are inserted into the ACT_GE_BYTEARRAY table, one an XML file and the other an automatically generated image file.

![image](https://user-images.githubusercontent.com/17758731/49625989-c79b5000-fa12-11e8-9f90-3f7e9e95c969.png)

- However, when using dynamically deployed BpmnModel classes, the ACT_GE_BYTEARRAY table inserts only one XML file instead of a corresponding image file.

![image](https://user-images.githubusercontent.com/17758731/49625993-ce29c780-fa12-11e8-842c-054456faf08e.png)

here is the source code of dynamic deploy process:

```
BpmnModel model = new BpmnModel();
Process process = new Process();
model.addProcess(process);
process.setId("news");
///~ init process...
Deployment deployment = activitiRule.getRepositoryService()
            .createDeployment()
            .addBpmnModel(process.getId() + ".bpmn", model)
            .name(process.getName() + "_deployment")
            .deploy();
```

**Comment by balsarori** [comment]
I'm not sure that an auto generated image will be inserted in the DB (only resources specified during deployment will be deployed). 

Deployment using dynamic BPMN model doesn't contain BPMNDiagram and therefore will have no image (it's the same if you deploy an XML that doesn't contain BPMNDiagram).

**Comment by DestinyWang** [comment]
My guess is that the problem depends on whether the XML file contains <bpmndi:BPMNDiagram> and its child nodes
