### ISSUE TITLE
avoid colons in stream names

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2247]
This was hit by @grasolondraibe and reported on gitter:

> Hi everyone, with Apache Kafka, i have this error : Caused by: java.lang.IllegalArgumentException: Topic name can only have ASCII alphanumerics, '.', '_' and '-', but was: 'integrationResult:myapp'
at org.springframework.cloud.stream.binder.kafka.utils.KafkaTopicUtils.validateTopicName(KafkaTopicUtils.java:39)

So we could change [`${ACT_INT_RES_CONSUMER:integrationResult:${spring.application.name}}`](https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/3ec314eb1503ba397f62bd24eb15d2ad2a996aa2/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/resources/config/integration-result-stream.properties#L2) to `${ACT_INT_RES_CONSUMER:integrationResult_${spring.application.name}}` and also switch to an underscore at https://github.com/Activiti/activiti-cloud-connectors/blob/f56c987ea146b8e3f3fc7ab9308e68957ddfce21/activiti-cloud-starter-connector/src/main/java/org/activiti/cloud/connectors/starter/channels/IntegrationResultSenderImpl.java#L42

Then it should work OOTB with kafka as well as rabbit

**Comment by salaboy** [comment]
@grasolondraibe thanks for reporting this :)

**Comment by grasolondraibe** [comment]
You can see a sample projet here https://github.com/grasolondraibe/activiti-cloud-kafka

**Comment by salaboy** [comment]
@grasolondraibe it looks like a simple fix.. if you want to contribute with a PR to fix that..

**Comment by salaboy** [comment]
PR ready to review: 
https://github.com/Activiti/activiti-cloud-connectors/pull/77

**Comment by salaboy** [comment]
@ryandawsonuk @grasolondraibe merged in connectors develop branch. This should be included in beta5. @grasolondraibe we will appreciate if you can test this change.
