### ISSUE TITLE
[Acceptance tests] Revert the workaround that replace "http://activiti-cloud-modeling-backend" with config.getModelingUrl()

### ISSUE THREAD

**Issue by constantin-ciobotaru** [Activiti/Activiti#2254]
[Acceptance tests] Revert the workaround that replace "http://activiti-cloud-modeling-backend" with config.getModelingUrl() as an workaround for the bug in spring-boot about the HAL links.

**Comment by ryandawsonuk** [comment]
I think the bug being referred to is https://github.com/Activiti/Activiti/issues/2481

**Comment by salaboy** [comment]
@constantin-ciobotaru what is the status of this issue?

**Comment by constantin-ciobotaru** [comment]
@salaboy the issue is still reproducible with the current spring-cloud Greenwich.RELEASE and spring-boot 2.1.2.RELEASE. So, I just kept the workaround but without using hardcoded values. Is that ok from you point of view?

**Comment by salaboy** [comment]
@constantin-ciobotaru I think that it is.. as soon as we can parameterise those values.. we should be fine for now..
