### ISSUE TITLE
[Acceptance Tests] The check why using the same application name when exporting in modeling lead to failing tests

### ISSUE THREAD

**Issue by constantin-ciobotaru** [Activiti/Activiti#2255]

**Comment by salaboy** [comment]
@constantin-ciobotaru what is the status of this issue?

**Comment by constantin-ciobotaru** [comment]
I tests this issue and it's not reproducible anymore. So I've changed back the scenarios to use the same 'Mission Europa' project: https://github.com/Activiti/activiti-cloud-acceptance-scenarios/pull/272

**Comment by salaboy** [comment]
@constantin-ciobotaru 👍
