### ISSUE TITLE
Can Multi-schema multi-tenant select all data of all database schema at once?

### ISSUE THREAD

**Issue by yangpancode** [Activiti/Activiti#2256]
Can Multi-schema multi-tenant select data in all databases schema ?  
```
 tenantInfoHolder.setCurrentTenantId(tenantid);
    long count = processEngine.getRuntimeService().createExecutionQuery().onlyProcessInstanceExecutions().count();
    long count1 = processEngine.getHistoryService().createHistoricProcessInstanceQuery().unfinished().count();
    tenantInfoHolder.clearCurrentTenantId();
```
this code can only select data in one database.
how to get data from all databases at once?

**Comment by salaboy** [comment]
@yangpancode you can do that unless the DB provider supports that. That is part of the design of the Databases implementations. You will need to use another tool to aggregate from different schemas, that is not something that Activiti providers. Projects like Teiid provide such functionality: http://teiid.jboss.org/
