### ISSUE TITLE
Tasks assignments and claims with users containing @ 

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2257]
Claiming and searching tasks created with users containing an email format as the username make the RB to not find the task.

**Comment by ryandawsonuk** [comment]
Can we check what the username is in the token in the request header and whether [email login is enabled in the realm](https://codehumsafar.wordpress.com/2018/09/24/keycloak-enable-login-with-username-or-email/)?

**Comment by salaboy** [comment]
ok... so further investigation revealed that the JWT token doesn't contain the email in the preferred_username field and it only contains  
"preferred_username": "admin.adf"

This is in fact not an activiti issue, but more a problem on how you configure users into Keycloak.

**Comment by salaboy** [comment]
I am closing this issue because this is not a problem for Activiti Cloud
