### ISSUE TITLE
Assigning a task through  task update does not perform same checks as claim

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#2259]
A task can be assigned via `TaskRuntime.claim()` or via `TaskRuntime.update()`. However the second method is missing the checks done by the first one.

**Comment by CTI777** [comment]
We will provide reassign method for admins only (in TaskAdminRuntimeImpl):
For admin it will be possible to assign/reassign a user for the task, if the user is a task user/group candidate (this should be checked).
As a payload we may use ClaimTaskPayload or UpdateTaskPayload (maybe ClaimTaskPayload is more close?).

We will update following properties in Task update method (possible for task assignee only!):
_name
_description_
_duedate_
_priority_ 
_formKey__

Should we also update _parentTaskId_? I think not…
Candidate Users/Groups: for this we have an issue (to clarify, seems that we will update this using other door): 
https://github.com/Activiti/Activiti/issues/2262

@erdemedeiros @salaboy
