### ISSUE TITLE
Let's review and optimize activiti-cloud-acceptance-scenarios release pipeline

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2273]
so, that we only release `activiti-cloud-example-chart` when it passes all acceptance tests with aggregated `activiti-cloud-application-chart`, `activiti-cloud-infrastructure-chart`, `activiti-cloud-modeler-chart`, etc versions 

It will be much more efficient to run the tests within the change to the full example chart rather than testing the change to the chart outside within an updatebot pr in the acceptance tests...

To make it work, we need to make install current chart version into preview namespace, git clone latest activiti-cloud-acceptance-scenarios repo inside pipeline workspace and run acceptance tests with `mvn` command. 

If tests pass, we automatically merge PR and run release pipeline to build and release Helm chart in Github repository. 

We can also automate publishing aggregated chart version into consumer chart repository in activiti-cloud-charts.

**Comment by ryandawsonuk** [comment]
I think it would be OK to update full-example ahead of scenarios running but not propagate that to activiti-cloud-charts until the scenarios tests pass. So activiti-cloud-charts remains the repo for public consumers but is a consumer from acceptance-scenarios

**Comment by igdianov** [comment]
We need to configure a separate node pool with cheap fat preemptive instances and enable auto-scaling to run acceptance scenarios pipelines using dedicated nodes with enough resources.
We also need to disable concurrent builds for acceptance tests pipelines in order not to run many acceptance tests pipelines at the same time.
