### ISSUE TITLE
Missing Task Details duration and end Date attributes

### ISSUE THREAD

**Issue by davidcanonieto** [Activiti/Activiti#2281]
The current Task Details Model lacks duration and end date. It can be achieved by combining other attributes but this might lead to further confusion and complication.

**Comment by salaboy** [comment]
this was solved . by the history service, now the Query service should provide this information: https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/history/HistoricTaskInstance.java#L37

Due the task basic entity doesn't have this information:
https://github.com/Activiti/activiti-api/blob/develop/activiti-api-task-model/src/main/java/org/activiti/api/task/model/Task.java

**Comment by miguelruizdev** [comment]
Neither the TaskInfo that Task extends: https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/task/TaskInfo.java

**Comment by miguelruizdev** [comment]
Probably that type conversion should take place on the client side, though

**Comment by miguelruizdev** [comment]
> Besides the missing fields, there was a difference regarding the date treatment that @davidcanonieto pointed out: the retrieved tasks have Date objects whereas the expected deal with number of milliseconds

**Comment by miguelruizdev** [comment]
PRs addressing this issue:

- https://github.com/Activiti/activiti-api/pull/67
- https://github.com/Activiti/activiti-cloud-query-service/pull/162

**Comment by miguelruizdev** [comment]
This are the changes in the acceptance test covering the newly added code: https://github.com/Activiti/activiti-cloud-acceptance-scenarios/commit/9b854f74fd183e05f43a277d5b1abe02799de16a
Only mergeable when the above PRs are merged

**Comment by salaboy** [comment]
@miguelruizdev the last comment about acceptance tests points to a commit not to a PR.. why is that?

**Comment by miguelruizdev** [comment]
@salaboy yep, it's the acceptance test covering the added changes across this issue. Should I open the PR even though I know it will fail anyway?

**Comment by salaboy** [comment]
@miguelruizdev we need a PR to see if it builds or not (compilation errors)

**Comment by miguelruizdev** [comment]
PRs addressing this issue:

- https://github.com/Activiti/activiti-api/pull/67
- https://github.com/Activiti/activiti-api/pull/69
- https://github.com/Activiti/activiti-cloud-api/pull/53
- https://github.com/Activiti/activiti-cloud-api/pull/54
- https://github.com/Activiti/activiti-cloud-query-service/pull/162
- https://github.com/Activiti/activiti-cloud-service-common/pull/125
- https://github.com/Activiti/activiti-cloud-service-common/pull/126
- https://github.com/Activiti/activiti-cloud-acceptance-scenarios/pull/106
