### ISSUE TITLE
It would be awesome to prioritize merging and releasing PR's in Api and upstream repos

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2292]
for any pending or blocking issues.  It will make it so much easier to work on the implementations in downstream repositories without manual version overrides in local environments esp. when switching between different PRs. It will also help to run downstream PR's through Travis pipelines with real feedback. 

The Api's layer PR's are usually quite small, so it should not take a lot of time to review them.

Github added dependency linking for PR's recently. It should help us with linking and tracking blocking dependencies between upstream and downstream PR's.

**Comment by salaboy** [comment]
Totally agree. changes in the API should be quickly merged.. 
I will take the lead on this one. We also need fixed days for PR review and merging.. we are not organised just yet.
