### ISSUE TITLE
Let's make Activiti Cloud Example Docker compose files up-to-date

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2301]
in https://github.com/Activiti/activiti-cloud-examples and keep it in sync with published Activiti Cloud Docker images, so that anyone can run Activiti Cloud in local Docker (Virtualbox and Docker for Desktop) on local machine with limited resources (~4 CPUs/16GB RAM) without Minikube overhead

We could make use of `Makefile` to automate Docker-Compose commands to be able to control sets containers for infrastructure, application, and modeler or whole stack, i.e.

```sh
# start the whole stack
make up 

# start infrastructure
make infrastructure

# start application
make application

# stop application
make application/stop

# start runtime-bundle
make runtime-bundle

# stop runtime-bundle
make runtime-bundle/stop

# stop and remove whole stack
make down
``` 

The `Makefile` can also be used to manage version tags of the published Docker images via updatebot PRs. Alternatively Docker tags can be maintained in `.env` file consumed by Docker compose. 

We should also disable Postgresql persistence to reduce resource requirements to be able to run it locally.

**Comment by salaboy** [comment]
@igdianov I would love to have time for this.. but we will need to push this for after feb

**Comment by guoziqin** [comment]
make application step error

**Comment by guoziqin** [comment]
make[2]: 离开目录“/root/activiti-cloud-examples/docker-compose”
make[1]: *** 没有规则可以创建目标“activiti-cloud-audit”。 停止。

**Comment by guoziqin** [comment]
make[1]: *** No rule can create a target “activiti-cloud-audit”. stop
