### ISSUE TITLE
Generate swagger artifacts

### ISSUE THREAD

**Issue by mteodori** [Activiti/Activiti#2305]
Generate swagger documentation and attach as maven artifact with api-docs classifier in order to make it consumable from code generators

**Comment by salaboy** [comment]
@mteodori any update on this one?

**Comment by erdemedeiros** [comment]
Example of plugin configuration:

```xml
      <plugin>
        <groupId>com.github.kongchen</groupId>
        <artifactId>swagger-maven-plugin</artifactId>
        <version>3.1.8</version>
        <configuration>
          <apiSources>
            <apiSource>
              <attachSwaggerArtifact>true</attachSwaggerArtifact>
              <outputFormats>json,yaml</outputFormats>
              <springmvc>true</springmvc>
              <locations>
                <location>org.activiti</location>
              </locations>
              <info>
                <title>${project.artifactId} API</title>
                <version>v1</version>
                <description>${project.description}</description>
                <contact>
                  <email>support@alfresco.com</email>
                  <name>Alfresco</name>
                  <url>https://www.alfresco.com</url>
                </contact>
              </info>
              <swaggerDirectory>${project.build.outputDirectory}/static</swaggerDirectory>
              <swaggerFileName>api-docs</swaggerFileName>
              <modelSubstitute>/swagger-model-substitute.txt</modelSubstitute>
            </apiSource>
          </apiSources>
        </configuration>
        <executions>
          <execution>
            <phase>compile</phase>
            <goals>
              <goal>generate</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```
Example of swagger-model-substitute.txt
```
org.activiti.api.process.model.payloads.StartProcessPayload : org.activiti.cloud.starter.rb.configuration.PayloadsDocketCustomizer$StartProcessPayloadApiModel
org.activiti.api.process.model.payloads.SignalPayload : org.activiti.cloud.starter.rb.configuration.PayloadsDocketCustomizer$SignalPayloadApiModel
org.activiti.api.process.model.payloads.UpdateProcessPayload : org.activiti.cloud.starter.rb.configuration.PayloadsDocketCustomizer$UpdateProcessPayloadApiModel
org.activiti.api.process.model.payloads.SetProcessVariablesPayload : org.activiti.cloud.starter.rb.configuration.PayloadsDocketCustomizer$SetProcessVariablesPayloadApiModel
org.activiti.api.process.model.payloads.RemoveProcessVariablesPayload : org.activiti.cloud.starter.rb.configuration.PayloadsDocketCustomizer$RemoveProcessVariablesPayloadApiModel
org.activiti.api.task.model.payloads.AssignTaskPayload : org.activiti.cloud.starter.rb.configuration.PayloadsDocketCustomizer$AssignTaskPayloadApiModel
org.activiti.api.task.model.payloads.CompleteTaskPayload : org.activiti.cloud.starter.rb.configuration.PayloadsDocketCustomizer$CompleteTaskPayloadApiModel
org.activiti.api.task.model.payloads.CandidateGroupsPayload : org.activiti.cloud.starter.rb.configuration.PayloadsDocketCustomizer$CandidateGroupsPayloadApiModel
org.activiti.api.task.model.payloads.CandidateUsersPayload : org.activiti.cloud.starter.rb.configuration.PayloadsDocketCustomizer$CandidateUsersPayloadApiModel
org.activiti.api.task.model.payloads.CreateTaskPayload : org.activiti.cloud.starter.rb.configuration.PayloadsDocketCustomizer$CreateTaskPayloadApiModel
org.activiti.api.task.model.payloads.SetTaskVariablesPayload : org.activiti.cloud.starter.rb.configuration.PayloadsDocketCustomizer$SetTaskVariablesPayloadApiModel
org.activiti.api.task.model.payloads.UpdateTaskPayload : org.activiti.cloud.starter.rb.configuration.PayloadsDocketCustomizer$UpdateTaskPayloadApiModel
```

To that list we need to add everything that is referenced here https://github.com/Activiti/activiti-cloud-service-common/blob/develop/activiti-cloud-services-swagger/src/main/java/org/activiti/cloud/common/swagger/SwaggerDocketBuilder.java#L88: 
* Map:
  * PagedResources -> ListResponseContent
  * Resources -> ListResponseContent
  * Resource -> EntryResponseContent

* Add extra parameters (`skipCount`, `maxItems`, `sort`) (https://github.com/Activiti/activiti-cloud-service-common/blob/develop/activiti-cloud-services-swagger/src/main/java/org/activiti/cloud/common/swagger/SwaggerDocketBuilder.java#L115-L120).

The generated swagger file should be the same we get currently by accessing `/v2/api-docs` endpoint.

**Comment by erdemedeiros** [comment]
Link to the project https://github.com/kongchen/swagger-maven-plugin

**Comment by salaboy** [comment]
Some comments about this approach that makes me think that we shouldn't use **swagger-maven-plugin**:
- Not maintained by an org.. it is an individual project
- No relationship with Spring Fox, which we are using extensively
- The swagger.json generated is completely different from the one provided by spring fox

Alternative solution:
- Use the approach suggested by : https://github.com/springfox/springfox/issues/1959 , same as jhipster to generate the swagger.json file, in the Activiti Cloud Starter projects. 
- Release the artefact as a maven artifact using a maven goal in the pipelines

By following this approach we will keep consistence with the libraries that we are using, and the libraries that are already working to generate clients.

**Comment by salaboy** [comment]
@almerico For the Pipelines we should add: https://blog.arnoldgalovics.com/introducing-swagger-brake/

**Comment by salaboy** [comment]
Objective is to generate a client with https://github.com/swagger-api/swagger-codegen for java

**Comment by mteodori** [comment]
I am fine with whatever approach provides json/yaml to maven as the swagger-maven-plugin does, but against creating a custom plugin when there is one that already works, springfox is not maintained as it looks like, last release 2018 plus adds runtime libraries that are not needed so removing it would make the application leaner, so I still advocate for the swagger-maven-plugin approach that already works in enterprise in order to avoid to maintain it

**Comment by erdemedeiros** [comment]
@mteodori current problem with `swagger-maven-plugin` is that unlikely `SpringFox` it doesn't seem to support java generics for substitutes. Currently we were not able to find an equivalent to this customisation https://github.com/Activiti/activiti-cloud-service-common/blob/develop/activiti-cloud-services-swagger/src/main/java/org/activiti/cloud/common/swagger/SwaggerDocketBuilder.java#L92-L95 (We may be missing something). So `swagger-maven-plugin` is not really working as provided swagger is wrong. Workaround would be created specific classes to erase the generics for every return type for Spring classes (Resource, Resources, PagedResources) and for Alfresco classes (ListResponseContent, EntriesResponseContent and EntryResponseContent), but this would be painful to maintain.

**Comment by mteodori** [comment]
if it 6 dummy one line classes similar to the mixin ones for a solution which is closer to swagger-core, it looks better to me and not tied to springfox

**Comment by salaboy** [comment]
@miguelruizdev @almerico so: json and yaml files are required to be released.. @miguelruizdev is going to add the yaml generation in his PR as well. Once we solved it for json (generate and release) we can solve it for yaml as well in the same way

**Comment by erdemedeiros** [comment]
@mteodori just keep a record of our conversation:
Actually there are 6 classes to cover, but number of classes to be created is a combination of it as you need to have one class per type: `ProcessDefinitionResource`, `ProcessDefinitionResources`, `PagedProcessDefinitionResources`, `ProcessDefinitionListResponse`, `ProcessDefinitionEntryResponse`. Then the same for process instance, task, variables, connectors and maybe something else. So I’d expect at least 20 classes  to be created (and all the controllers are to be updated to use new types). In addition, every time a new type is added we need to think about adding it to the mapping otherwise specification will be wrong.
As conclusion, without a solution to cover generics this represent a lot of work.

**Comment by salaboy** [comment]
@erdemedeiros totally agree.. hence my previous proposal.. we should stick with springfox and try to imitate what the other plugin is doing to make sure that we don't adopt/inherit all the maintenance burden. At the end of the day, we need to maintain the project

**Comment by mteodori** [comment]
can you make a plan on when this is going to be available for platform services? changing the classes in swagger however boring is no more than a day's work, if this is gong to take longer I will still push for the swagger-maven-plugin

**Comment by salaboy** [comment]
@mteodori this is work in progress ..and the alternative with the swagger-maven-plugin is not viable. 
I think that we are almost done.. just adding the generation to the pipelines and when M1 is released we should have that in maven central, for me that is the success criteria.

**Comment by mteodori** [comment]
that's great news, can you keep platform updated on which snapshot they can start testing? thanks

**Comment by salaboy** [comment]
@erdemedeiros @almerico as soon as the files start hitting nexus.. please update here with some links so we can notify the other teams.

**Comment by mteodori** [comment]
you need to upgrade the version of guava to one without vuln https://cve.mitre.org/cgi-bin/cvename.cgi?name=2018-10237

**Comment by miguelruizdev** [comment]
Current state of things after merging this PR: https://github.com/Activiti/activiti-cloud-runtime-bundle-service/pull/287
Need for changes in the following services:
- [x] Runtime-bundle
- [ ] Query
- [ ] Audit
- [ ] Modelling

Scope of the changes:

- Adding SwaggerITSupport test
- Modifying pom configuration
- Add changes to pipelines

**Comment by erdemedeiros** [comment]
@mteodori I created an issue to upgrade guava https://github.com/Activiti/Activiti/issues/2690. Thanks for the reminder.

**Comment by salaboy** [comment]
@erdemedeiros @almerico are all things merged for Runtime Bundle? if we have a link to a deployed swagger.json file in nexus please paste it here.. 
@almerico please also update the pipelines to not have the DinD included .. as we don't need it anymore.

**Comment by almerico** [comment]
@salaboy sure

**Comment by erdemedeiros** [comment]
@salaboy

**Comment by salaboy** [comment]
@erdemedeiros @almerico AWESOME!!!
I think that now @miguelruizdev can replicate to the other projects with @almerico help for the pipelines

**Comment by almerico** [comment]
I tested latest build and looks like during ``mvn deploy`` json and jaml files are created successfully.
But during compilation of generated sources I got errors related to java11  

- First one is 
```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /private/tmp/test/src/main/java/io/swagger/client/model/TypeIdResolver.java:[30,18] package javax.annotation does not exist
[ERROR] /private/tmp/test/src/main/java/io/swagger/client/model/Member.java:[30,18] package javax.annotation does not exist
```
Easily fixed by adding 
```
<dependency>
  <groupId>javax.annotation</groupId>
  <artifactId>javax.annotation-api</artifactId>
  <version>1.3.2</version>
</dependency>
```

- second one is javadoc related 

```
ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar (attach-javadocs) on project swagger-java-client: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in http://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
[ERROR]
[ERROR] Command line was: /Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home/bin/javadoc @options @packages
[ERROR]
[ERROR] Refer to the generated Javadoc files in '/private/tmp/test/target/apidocs' dir.
[ERROR]
```
can be fixed by adding dummy’s configuration to the maven-javadoc-plugin
```
 <configuration>
                    <javaApiLinks>
                        <property>
                            <name>foo</name>
                            <value>bar</value>
                        </property>
                    </javaApiLinks>
                </configuration>
```

**Comment by erdemedeiros** [comment]
@salaboy no changes are require in the pipeline as the profile to generate swagger files is enabled by default.

**Comment by salaboy** [comment]
@erdemedeiros awesome! 
All done then.. 

@mteodori all artefacts published as part of our fixed version(internal) releases. These artefacts can be found here: 
```
https://artifacts.alfresco.com/nexus/content/repositories/activiti-releases/org/activiti/cloud/rb/activiti-cloud-starter-runtime-bundle/7.1.x/activiti-cloud-starter-runtime-bundle-7.1.x-api-docs.json 
https://artifacts.alfresco.com/nexus/content/repositories/activiti-releases/org/activiti/cloud/audit/activiti-cloud-starter-audit/7.1.x/activiti-cloud-starter-audit-7.1.x-api-docs.json
https://artifacts.alfresco.com/nexus/content/repositories/activiti-releases/org/activiti/cloud/query/activiti-cloud-starter-query/7.1.x/activiti-cloud-starter-query-7.1.x-api-docs.json
https://artifacts.alfresco.com/nexus/content/repositories/activiti-releases/org/activiti/cloud/modeling/activiti-cloud-starter-org/7.1.x/activiti-cloud-starter-org-7.1.x-api-docs.json
```

@mteodori can you let me know who do we need to notify about that?

**Comment by mteodori** [comment]
the above URLs are 404 for me, is there some typo?

**Comment by mteodori** [comment]
this is related to https://github.com/Activiti/Activiti/issues/2588 please verify with @rpopa and @zanatyk it fixes what is required once they switch to REST client java generation to the new URLs thanks

**Comment by erdemedeiros** [comment]
@mteodori I think @salaboy "templated" the path. You need to replace `7.1.x`, by an actual version, i.e. https://artifacts.alfresco.com/nexus/content/repositories/activiti-releases/org/activiti/cloud/modeling/activiti-cloud-starter-org/7.1.44/activiti-cloud-starter-org-7.1.44-api-docs.json

**Comment by mteodori** [comment]
thanks @erdemedeiros so latest as of today are:

|service|swagger json url|
|---|---|
|runtime-bundle|https://artifacts.alfresco.com/nexus/content/repositories/activiti-releases/org/activiti/cloud/rb/activiti-cloud-starter-runtime-bundle/7.1.35/activiti-cloud-starter-runtime-bundle-7.1.35-api-docs.json|
|audit|https://artifacts.alfresco.com/nexus/content/repositories/activiti-releases/org/activiti/cloud/audit/activiti-cloud-starter-audit/7.1.28/activiti-cloud-starter-audit-7.1.28-api-docs.json|
|query|https://artifacts.alfresco.com/nexus/content/repositories/activiti-releases/org/activiti/cloud/query/activiti-cloud-starter-query/7.1.30/activiti-cloud-starter-query-7.1.30-api-docs.json|
|modeling|https://artifacts.alfresco.com/nexus/content/repositories/activiti-releases/org/activiti/cloud/modeling/activiti-cloud-starter-org/7.1.44/activiti-cloud-starter-org-7.1.44-api-docs.json|


I see also yaml and a hal.json are generated, what is the latter as the json/yaml already seem to include that accept type?

**Comment by mteodori** [comment]
also you might want to validate against https://editor.swagger.io as the type names with << don't seem to be ok for the spec but maybe it's not a problem for UI and client generation so we might ignore

**Comment by salaboy** [comment]
added in bom
