### ISSUE TITLE
[Modeling] Align process extensions from modeling with the process extensions from runtime bundle

### ISSUE THREAD

**Issue by constantin-ciobotaru** [Activiti/Activiti#2311]
Runtime Bundle and Modeling share the same logic and model objects .. so we need to unify and share those artifacts between services.

**Comment by salaboy** [comment]
@constantin-ciobotaru @balsarori to add more context this is to unify the models used to parse the extensions between modeling and runtime. This probably push us to add those models to APIs, which is fine in my opinion. @ryandawsonuk just for you to be aware of this

**Comment by erdemedeiros** [comment]
I'm closing this for now. Please, re-open it if necessary.
