### ISSUE TITLE
Task formKey property not propagated to Query when updated

### ISSUE THREAD

**Issue by miguelruizdev** [Activiti/Activiti#2322]
The updated value of the property formKey of a task is not propagated to query.
When formKey is updated, among other properties:
![image](https://user-images.githubusercontent.com/32025234/50598555-62b90580-0eab-11e9-9356-e5eabeb9ff46.png)

The value is correctly updated in the Runtime Bundle:
![image](https://user-images.githubusercontent.com/32025234/50598617-8e3bf000-0eab-11e9-9910-2335c6d4a37e.png)

However, the same value is not propagated to query, which still has the original value set by the [process definition](https://github.com/Activiti/example-runtime-bundle/blob/6a59e17a3c3a3642cd460375f9a34590a1b443a7/src/main/resources/processes/SingleTaskProcess.bpmn20.xml#L12):
![image](https://user-images.githubusercontent.com/32025234/50598649-ab70be80-0eab-11e9-913d-9f03045bfe2e.png)

**Comment by salaboy** [comment]
merged in query
