### ISSUE TITLE
Default SequenceFlow option should be added to Exclusive Gateway

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2329]
When having an exclusive gateway a default sequence flow option should be provided. 
It needs to be provided in the properties of the Exclusive Gateway element.

<img width="1168" alt="screenshot 2019-01-04 at 08 47 11" src="https://user-images.githubusercontent.com/271966/50679932-7d02f880-0ffd-11e9-85e1-64de3ab6d0ad.png">

**Comment by salaboy** [comment]
@daisuke-yoshimoto yes.. i think that he is into it already..

**Comment by daisuke-yoshimoto** [comment]
@salaboy 
OK. I thought about trying a bit.

**Comment by salaboy** [comment]
@daisuke-yoshimoto I think that you could really help us with this one: https://github.com/Activiti/Activiti/issues/2328

**Comment by salaboy** [comment]
<img width="1015" alt="screenshot 2019-02-05 at 12 47 11" src="https://user-images.githubusercontent.com/271966/52274317-3bd76e80-2944-11e9-841c-4f6120816b76.png">

@balsarori do we have that default sequence flow implemented? Even the docs for 6.x looks incomplete.

**Comment by balsarori** [comment]
@salaboy yes here is a unit test --> https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/test/java/org/activiti/engine/test/bpmn/gateway/ExclusiveGatewayTest.java#L153

**Comment by salaboy** [comment]
@popovicsandras ok.. so it is in the exclusiveGateway element and not in the sequence flow:
https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/gateway/ExclusiveGatewayTest.testDefaultSequenceFlow.bpmn20.xml#L13

You can see the xml generated there.. @popovicsandras can you please do the same check that we did in the properties in the exclusiveGateway element?

**Comment by magemello** [comment]
This should be done.... @popovicsandras can you confirm?

**Comment by popovicsandras** [comment]
Confirmed, this issue was resolved on 12-Feb-19.
Please see the attached Jira issue:
https://issues.alfresco.com/jira/browse/APM-729

**Comment by salaboy** [comment]
@popovicsandras is this merged into the community repo as well?

**Comment by popovicsandras** [comment]
@salaboy, yes this was merged into the community repo. (enterprise inherits it).
