### ISSUE TITLE
full automation for customer helm chart creation

### ISSUE THREAD

**Issue by almerico** [Activiti/Activiti#2333]

**Comment by ryandawsonuk** [comment]
Does this issue replace https://github.com/Activiti/Activiti/issues/2269 ?

**Comment by salaboy** [comment]
@ryandawsonuk yes.. this is just about unifying internal and community helm charts to avoid overlapping. We can do this as soon as we enough confidence on the internal ones that are being published by the pipelines.

**Comment by salaboy** [comment]
depends on https://github.com/Activiti/Activiti/issues/2347

**Comment by salaboy** [comment]
these ones can be done as part of this issue: 
- https://github.com/Activiti/Activiti/issues/2335
- https://github.com/Activiti/Activiti/issues/2332
