### ISSUE TITLE
Activiti Cloud Notifications GraphQL Service and Microservice Example

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2336]
- [x] Create Notifications GraphQL Services implementation and Starter PR in https://github.com/Activiti/activiti-cloud-notifications-service-graphql/pull/1
- [x] Add Updatebot push version configuration to Activiti Cloud Build: https://github.com/Activiti/activiti-cloud-build/pull/80
- [x] Add Updatebot push version configuration to Activiti Cloud Query:  https://github.com/Activiti/activiti-cloud-query-service/pull/156
- [x] Add Activiti Cloud Dependencies management in https://github.com/Activiti/activiti-cloud-dependencies/pull/264
- [x] Import https://github.com/Activiti/activiti-cloud-notifications-graphql repo into Travis CI/Jenkins-X CI/CD pipelines
- [x] Create Notifications GraphQL Microservice PR in https://github.com/Activiti/activiti-cloud-notifications-graphql/pull/1
- [x] Add Notifications GraphQL Microservice dependency enforcement in https://github.com/Activiti/activiti-cloud-application-chart/pull/51
- [x] Add Open JDK 11 support
- [x] Import https://github.com/Activiti/activiti-cloud-notifications-service-graphql repo into Travis CI/Jenkins-X CI/CD pipelines
- [x] Import https://github.com/Activiti/activiti-cloud-notifications-graphql repo into Travis CI/Jenkins-X CI/CD pipelines
- [x] Enable Mergify.io on https://github.com/Activiti/activiti-cloud-notifications-graphql and https://github.com/Activiti/activiti-cloud-notifications-service-graphql repos
- [x] Create Acceptance Test Scenarios in https://github.com/Activiti/activiti-cloud-acceptance-tests 
- [ ] Add Notification Service into https://github.com/Activiti/activiti-cloud-charts

**Comment by salaboy** [comment]
I will close this issue.. if something new appears let's track it separately
