### ISSUE TITLE
Add Variables Conformance Tests

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2338]
Add Conformance tests for variable handling around processes and tasks. 

https://docs.google.com/document/d/1-3ek-02fYteHURdQYDwUeVxqODmhZP0DwtyXNweGkOc/edit#

**Comment by miguelruizdev** [comment]
@salaboy Does checking the variable related events fall within the scope of this issue, or we are covering all events in a single and centralized place?
It would be good to discuss this PR https://github.com/Activiti/Activiti/pull/2449 for me to find out if we need to add new ways of coverage.

**Comment by salaboy** [comment]
@miguelruizdev great.. let's have a catch up after the standup today.. 
This looks good.. but I will need to review in more detail.. so we can do it together.

**Comment by salaboy** [comment]
merged
