### ISSUE TITLE
Mark as @Deprecated and @Internal old Activiti APIs

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2342]
We need to mark and document `@Deprecated` and `@Internal` APIs.

**Comment by erdemedeiros** [comment]
@salaboy we cannot really mark the internal services as `@deprecated`. I mean the Java annotation because we are using those in our implementations.

**Comment by salaboy** [comment]
Deprecated in this PR
- Attachements
- Comments
- Async Executor
- Business Calendars
- JobManager
- MultiTenant

**Comment by salaboy** [comment]
done
