### ISSUE TITLE
Upgrade to Spring Cloud Greenwich and SCK8s when released

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2346]
Spring Cloud Greenwich Final is about to be released so we should release RC1 with the final version of Greenwich

**Comment by salaboy** [comment]
https://github.com/spring-cloud/spring-cloud-release/milestone/63

**Comment by ryandawsonuk** [comment]
For boot the places to upgrade
https://github.com/search?q=org%3AActiviti+%27spring-boot.version%27++in%3Afile+filename%3Apom.xml&type=Code
and
https://github.com/search?q=org%3AActiviti+%27spring-boot-starter-parent%27++in%3Afile+filename%3Apom.xml&type=Code

For cloud:
https://github.com/search?q=org%3AActiviti+%27spring-cloud.version%27++in%3Afile+filename%3Apom.xml&type=Code

And spring cloud k8s:
https://github.com/search?q=org%3AActiviti+%27spring-cloud-k8s%27++in%3Afile+filename%3Apom.xml&type=Code

**Comment by salaboy** [comment]
initial work done.
