### ISSUE TITLE
Split Acceptance Test Scenarios Pipelines and Repos

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2347]
Split the maven modules located here into separate repositories:
https://github.com/activiti/activiti-cloud-acceptance-scenarios

This will require to have split pipelines for running these tests against different configurations of the Full Example HELM Chart

https://github.com/activiti/activiti-cloud-example-chart

**Comment by ryandawsonuk** [comment]
@almerico will do activiti-cloud-example-chart-modeling
@ryandawsonuk will do activiti-cloud-example-chart-security-policies

**Comment by ryandawsonuk** [comment]
Tests passing under [activiti-cloud-example-chart-security-policies](https://github.com/Activiti/activiti-cloud-example-chart-security-policies/), updatebot from [activiti-cloud-application-chart](https://github.com/Activiti/activiti-cloud-application-chart/blob/master/.updatebot.yml) and [activiti-cloud-infrastructure-chart](https://github.com/Activiti/activiti-cloud-infrastructure-chart/blob/master/.updatebot.yml) have been updated.

Have changed activiti-cloud-example-chart to [only run runtime-acceptance-tests](https://github.com/Activiti/activiti-cloud-example-chart/commit/1ebc3f6abb5ad5594642836c96c4882e4e67c6f3)

**Comment by almerico** [comment]
https://github.com/Activiti/activiti-cloud-example-chart-modeling tests are passed as part of pipeline for now

**Comment by ryandawsonuk** [comment]
We should remove application from the activiti-cloud-modeling-example-chart requirements file and remove modeling from the activiti-cloud-example-chart's requirements file. Then we should switch modeling's updatebot file to point to the modeling-example-chart - https://github.com/Activiti/activiti-cloud-modeling/blob/master/.updatebot.yml#L5
