### ISSUE TITLE
Update Task Name in the same way as we update priority

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2355]
When updating a task we should be able to also update the task name. @mauriziovitale can you please add more details?

**Comment by CTI777** [comment]
@salaboy 
In RB and Activiti core  we have this possibility:
https://github.com/Activiti/Activiti/blob/develop/activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskRuntimeImpl.java#L235
Where should we implement this? 
In QueryService as a separate endpoint for update?

**Comment by mauriziovitale** [comment]
Not able to update the `name` value.
```
PUT http://domain/rb-my-app/v1/tasks/83278a5a-1362-11e9-bf92-0a580a340231
{
  "name": "New Task",
  "payloadType":"UpdateTaskPayload"
}
```
Result 
```
{
    "name": "My First Task",
    "createdDate": "2019-01-08T16:29:03.960+0000",
    "claimedDate": "2019-01-08T16:33:06.604+0000",
    "status": "ASSIGNED"
}
```

**Comment by CTI777** [comment]
@salaboy
I have tested in RB different cases to set task properties... It seems that there no problems...
I have made a PR with extended test to check UpdateTaskPayload with and without taskId.
Maybe the problem appears because of some version conflicts?

**Comment by erdemedeiros** [comment]
@CTI777 @salaboy @mauriziovitale I've just figured out the problem. The name of the property used to update the task name is misleading `taskName` instead of simply `name`. So to get it working right now the payload should be 

```
{
  "taskName": "New Task",
  "payloadType":"UpdateTaskPayload"
}
```
However I think it's worth to rename it to `name` to avoid confusion.

**Comment by salaboy** [comment]
merged to develop in all repos
