### ISSUE TITLE
upgrade keycloak, postgres and rabbit chart versions

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2360]
Want to pick up the latest fixes from these charts, in particular [older versions of the charts ](https://github.com/helm/charts/pull/8736/files)had hard-coded busybox images in the initContainers that are difficult to override to point at private registries for locked down environments

**Comment by salaboy** [comment]
related to https://github.com/Activiti/Activiti/issues/2450

**Comment by ryandawsonuk** [comment]
Postgres and rabbit now upgraded in user-facing charts - https://github.com/Activiti/activiti-cloud-charts/commit/6d08705e443c88a61c66e09beec9ba90be619f32

Remaining item is to switch [to alfresco identity service version of keycloak](https://github.com/Activiti/Activiti/issues/2450)
