### ISSUE TITLE
BUG：when task Completed，error：Variable assigneeList' is not a Collection

### ISSUE THREAD

**Issue by cverdela** [Activiti/Activiti#2362]
when `taskService.complete()` , variable assigneeList is not a ArrayList but a ArrayNode,
at org.activiti.engine.impl.bpmn.behavior.MultiInstanceActivityBehavior.resolveAndValidateCollection(MultiInstanceActivityBehavior.java:225)
in Activiti7
ps. <multiInstanceLoopCharacteristics isSequential="false"
     activiti:collection="assigneeList" activiti:elementVariable="assignee" >

**Comment by cverdela** [comment]
```
 <multiInstanceLoopCharacteristics isSequential="false"
     activiti:collection="assigneeList" activiti:elementVariable="assignee" >
```

**Comment by salaboy** [comment]
closing as it is a duplicate of #2364 ,
thanks for reporting. A work around is to disable the JSON variable serialization. Look at the other issue suggestion

**Comment by ming820214** [comment]
> assigneeList

the " trying with spring.activiti.serializePOJOsInVariablesToJson=false in the properties file" not valid，
