### ISSUE TITLE
mutliinstance with json variables

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2364]
@nitinkrgoyal has shared example process https://gist.github.com/nitinkrgoyal/0d98ac6c707946a111343fdfad502090#file-multi-instance-bpmn20-xml-L17 

With a test like

```
@Test
public void createMultiInstanceProcessAndValidate() {

    securityUtil.logInAs("salaboy");

    List<String> userList = new ArrayList<>();
    userList.add("salaboy");
    userList.add("salaboy");
    userList.add("salaboy");

    System.out.println(" userList --- " + userList );

    ProcessInstance processInstance = processRuntime.start(ProcessPayloadBuilder
            .start()
            .withProcessDefinitionKey("multi-instance")
            .withVariable("userCollection", userList)
            .build());
   System.out.println(">>> Created Process Instance: " + processInstance);

   Page<Task> tasks = taskRuntime.tasks(Pageable.of(0, 10));
   if (tasks.getTotalItems() > 0) {
       for (Task t : tasks.getContent()) {

           List<VariableInstance> variables2 = taskRuntime.variables(TaskPayloadBuilder.variables().withTaskId(t.getId()).build());
           Task task1 = taskRuntime.complete(TaskPayloadBuilder.complete()
                   .withTaskId(t.getId()).build());
       }
   }
}
```

and hitting an error in the engine in [MultiInstanceActivityBehavior.resolveAndValidateCollection](https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/MultiInstanceActivityBehavior.java#L212):

"When i am setting the variables on process, it's being set as Array List which is of type collection. When i am trying to complete the task without passing any variable then it gets the variable from process and that time "userCollection" variable
value is ArrayNode and not ArrayList and ArrayNode is not type of Collection and because of that it fails."

I've suggested trying with `spring.activiti.serializePOJOsInVariablesToJson=false` in the properties file to see whether the problem is related to json serialization and @nitinkrgoyal reports that works

**Comment by salaboy** [comment]
This PR https://github.com/Activiti/Activiti/pull/2374 fix this issue

**Comment by salaboy** [comment]
closing due the PR mentioned above solve this issue.
