### ISSUE TITLE
Add a way to filter tasks by name and return all matching results

### ISSUE THREAD

**Issue by davidcanonieto** [Activiti/Activiti#2375]
As a developer, I would like to have an endpoint that, given a string parameter, return all the tasks that have a name that matches the given parameter.

 Complete library: [Task 1, Task 2, TasO 3]

Call => taskContainingName('Task)
Response => [Task 1, Task 2]

**Comment by salaboy** [comment]
duplicate of #1921

**Comment by salaboy** [comment]
duplicate of https://github.com/Activiti/Activiti/issues/1954
