### ISSUE TITLE
Add Service Task Name in connector Integration Request payload 

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2381]
Add Service Task name to IntegrationRequest to be able to identify which Service Task is calling a connector. 
The property might be Client ID, or Requester ID to make sure that it is not specific to a process calling the connector but more to identify who is request the "operation".

**Comment by erdemedeiros** [comment]
Current `flowElementId` in `IntegrationContext` is too BPM specific. It could be moved inside a generic key/value map which holds other metadata as well, i.e. `"serviceTask"`.

**Comment by erdemedeiros** [comment]
@salaboy I think it would make sense to have 3 properties in the `IntegrationContext`:
- `requesterId` (renamed from `getActivityElementId`)
- `requesterName` (task name)
- `requesterType` (Service task)

**Comment by CTI777** [comment]
@salaboy @erdemedeiros 
Should I add a new field **requesterId** which equals activityElementId, or should I rename  activityElementId?
** requesterType** - which types can be supported here, is it a string?

**Comment by salaboy** [comment]
@CTI777 you should rename the fields.. but let's use the following names:
 “clientId” (rename * getActivityElementId * to getClientId), “clientName”, “clientType"
