### ISSUE TITLE
Let's make sure Activiti Cloud Application Helm chart  supports HTTPS 

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2388]
so, that folks could deploy Activiti behind with reverse proxy that terminates HTTPS and then forwards the requests to Keycloak and Activiti Ingresses as pure HTTP. To handle the request, Keycloak container must be told that the incoming HTTP requests from reverse proxy must be handled like they were HTTPS. 

To make this work, according to Keycloak documentation, we have to modify Keycloak web container configuration with PROXY_ADDRESS_FORWARDING="true" environment variable, i.e.

```
 extraEnv: |
      - name: PROXY_ADDRESS_FORWARDING
        value: "true"
```

Also, the `X-Forwarded-For` and `X-Forwarded-Proto` headers from upstream load balancers must reach Keycloak container. `X-Forwarded-For` should be the domain of Keycloak which routes to the LB and `X-Forwarded-Proto` should be the protocol. The load balancer should set `Host`, `X-Real-IP`, `X-Forwarded-For`, `X-Forwarded-Proto` similar to Nginx configuration:

```
user  nginx;
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  text/html;

    server {
        listen 8080;

        location /keycloak/ {
            proxy_pass          http://keycloak:8080/;
            proxy_set_header    Host               $host;
            proxy_set_header    X-Real-IP          $remote_addr;
            proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header    X-Forwarded-Host   $host;
            proxy_set_header    X-Forwarded-Server $host;
            proxy_set_header    X-Forwarded-Port   $server_port;
            proxy_set_header    X-Forwarded-Proto  $scheme;
        }


        location /keycloak/auth/ {
            proxy_pass          http://keycloak:8080/keycloak/auth/;
            proxy_set_header    Host               $host;
            proxy_set_header    X-Real-IP          $remote_addr;
            proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header    X-Forwarded-Host   $host;
            proxy_set_header    X-Forwarded-Server $host;
            proxy_set_header    X-Forwarded-Port   $server_port;
            proxy_set_header    X-Forwarded-Proto  $scheme;
        }
    }
}
```

After that, we need to configure Keycloak url in the chart to use HTTPS:

```
global:
  keycloak:
    url: "https://activiti-keycloak.jx-staging.domain.com/auth"
```

In addition, if using Modeler, the Modeler backend url must be configured to use HTTPS scheme:

```
activiti-cloud-modeling:
  enabled: true
  backend:
    url: "https://activiti-cloud-gateway.jx-staging.domain.com"
```

To test, obtain token send POST request to https://activiti-keycloak.jx-staging.domain.com:

```
POST /auth/realms/activiti/protocol/openid-connect/token HTTP/1.1
Host: activiti-keycloak.jx-staging.cloud.introproventures.com
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache

client_id=activiti&grant_type=password&username=hruser&password=password
```
The expected response should look like: 
```
{
    "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJoTUJPYnNyb1BJS2JJeTVOUGdnU0pPSGRDcmZFUWlva2otQUIwQjBaS3U0In0.eyJqdGkiOiJhYTE2NDJkYS04NGJjLTQ5MDMtYTc5MS03NWI5YTA4MTYyZDEiLCJleHAiOjE1NDgwNjYxMjQsIm5iZiI6MCwiaWF0IjoxNTQ4MDY1ODI0LCJpc3MiOiJodHRwczovL2FjdGl2aXRpLWtleWNsb2FrLmp4LXN0YWdpbmcuY2xvdWQuaW50cm9wcm92ZW50dXJlcy5jb20vYXV0aC9yZWFsbXMvYWN0aXZpdGkiLCJhdWQiOiJhY3Rpdml0aSIsInN1YiI6Ijc4NGNhMDI2LWNmYWEtNDIyYy04OGU4LWI3NTY1NTE1ZmY3MSIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFjdGl2aXRpIiwiYXV0aF90aW1lIjowLCJzZXNzaW9uX3N0YXRlIjoiNGQ0MTcxOTAtMjk4MS00OTE0LTkxOWYtMWEyMDllYzFiNDA4IiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsIkFDVElWSVRJX1VTRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6ImggciIsInByZWZlcnJlZF91c2VybmFtZSI6ImhydXNlciIsImdpdmVuX25hbWUiOiJoIiwiZmFtaWx5X25hbWUiOiJyIiwiZW1haWwiOiJockB0ZXN0LmNvbSJ9.F1j87CnOh8OmVXWUN7vVjajEiZRBwqz5xVs-SZdNCMqDjnFYLhKLw6NdZ9rDFtUFdbZ0wDssXLIJnrciZcaT1LfGLe85A-g1nDKOIJW51xl_aJSuL4KsjZPXlp0E_JkzwG7xGFq2LY6a8uejvG_x8X8AJXeri6vap7a2BkKTR_1nJiAPKQ4PDxPyaEKdtEuTH8jCR6JtXxq4EwZu82EisCBsmqvhSCb_WBj5x0QkmcudsQ5vw9JB4tygHrFHeorlW9HG-alvAEUDo-uteXljGUKcA6Hzz2h0ag8h8caMY6t_joGFN4mEYpOMXUoQXm4sEPfYw1FJqYGoTe4-BvHEWw",
    "expires_in": 300,
    "refresh_expires_in": 1800,
    "refresh_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJoTUJPYnNyb1BJS2JJeTVOUGdnU0pPSGRDcmZFUWlva2otQUIwQjBaS3U0In0.eyJqdGkiOiJiOTNiMTFhZS1kZjcwLTQ2MjUtOGJhMy1iNjBmMDkxYjhjNGEiLCJleHAiOjE1NDgwNjc2MjQsIm5iZiI6MCwiaWF0IjoxNTQ4MDY1ODI0LCJpc3MiOiJodHRwczovL2FjdGl2aXRpLWtleWNsb2FrLmp4LXN0YWdpbmcuY2xvdWQuaW50cm9wcm92ZW50dXJlcy5jb20vYXV0aC9yZWFsbXMvYWN0aXZpdGkiLCJhdWQiOiJhY3Rpdml0aSIsInN1YiI6Ijc4NGNhMDI2LWNmYWEtNDIyYy04OGU4LWI3NTY1NTE1ZmY3MSIsInR5cCI6IlJlZnJlc2giLCJhenAiOiJhY3Rpdml0aSIsImF1dGhfdGltZSI6MCwic2Vzc2lvbl9zdGF0ZSI6IjRkNDE3MTkwLTI5ODEtNDkxNC05MTlmLTFhMjA5ZWMxYjQwOCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsIkFDVElWSVRJX1VTRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCJ9.RW4LpXRWsAvGG9W7eMZRCgOG_XzePZjcTQuIAiM-RN3oRggIsYmkDb9QXcpFVLf3bvge5B07sRlAPJk_fGXu62RGg_TlCz-7r1MDjQRadeLWE9IC0a_mAe-TSdueWP0YrwxreNmKs2S_zFfQP5YV17k99dVTtBQ_kW3v_6jc54iuRZ0Me8sOerqMymn9KQwJqEfeLjoJ76k_bELArxJpOXrrVPC5zuqqa-LE7xdtH8trWCSsrSokai2sV_MUAOflL8WT8bdJvQW8nqLkLfg0qew-oYf1TSliO-vKy0h1ZuTWfTexhpftx14mWkPnOCgZBA4EF3pHLkjyXfc1q5vF_w",
    "token_type": "bearer",
    "not-before-policy": 0,
    "session_state": "4d417190-2981-4914-919f-1a209ec1b408",
    "scope": "profile email"
}
```

Then use `access_token` to validate request via gateway into rb-my-app microservice:

```
curl -X GET \
  https://activiti-cloud-gateway.jx-staging.domain.com/rb-my-app/v1/process-instances \
  -H 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJoTUJPYnNyb1BJS2JJeTVOUGdnU0pPSGRDcmZFUWlva2otQUIwQjBaS3U0In0.eyJqdGkiOiJhYTE2NDJkYS04NGJjLTQ5MDMtYTc5MS03NWI5YTA4MTYyZDEiLCJleHAiOjE1NDgwNjYxMjQsIm5iZiI6MCwiaWF0IjoxNTQ4MDY1ODI0LCJpc3MiOiJodHRwczovL2FjdGl2aXRpLWtleWNsb2FrLmp4LXN0YWdpbmcuY2xvdWQuaW50cm9wcm92ZW50dXJlcy5jb20vYXV0aC9yZWFsbXMvYWN0aXZpdGkiLCJhdWQiOiJhY3Rpdml0aSIsInN1YiI6Ijc4NGNhMDI2LWNmYWEtNDIyYy04OGU4LWI3NTY1NTE1ZmY3MSIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFjdGl2aXRpIiwiYXV0aF90aW1lIjowLCJzZXNzaW9uX3N0YXRlIjoiNGQ0MTcxOTAtMjk4MS00OTE0LTkxOWYtMWEyMDllYzFiNDA4IiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsIkFDVElWSVRJX1VTRVIiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6ImggciIsInByZWZlcnJlZF91c2VybmFtZSI6ImhydXNlciIsImdpdmVuX25hbWUiOiJoIiwiZmFtaWx5X25hbWUiOiJyIiwiZW1haWwiOiJockB0ZXN0LmNvbSJ9.F1j87CnOh8OmVXWUN7vVjajEiZRBwqz5xVs-SZdNCMqDjnFYLhKLw6NdZ9rDFtUFdbZ0wDssXLIJnrciZcaT1LfGLe85A-g1nDKOIJW51xl_aJSuL4KsjZPXlp0E_JkzwG7xGFq2LY6a8uejvG_x8X8AJXeri6vap7a2BkKTR_1nJiAPKQ4PDxPyaEKdtEuTH8jCR6JtXxq4EwZu82EisCBsmqvhSCb_WBj5x0QkmcudsQ5vw9JB4tygHrFHeorlW9HG-alvAEUDo-uteXljGUKcA6Hzz2h0ag8h8caMY6t_joGFN4mEYpOMXUoQXm4sEPfYw1FJqYGoTe4-BvHEWw' \
  -H 'cache-control: no-cache' \
```

**Comment by igdianov** [comment]
@mteodori I spent some quality time today digging deeper into AWS rabbit hole to figure out AWS NLB TLS puzzle. In short, my guts feeling is that this is going to be very hard problem to solve on many levels, which will make all charts and services AWS specific.

The long version, is the problem is caused at the infrastructure layer between NLB in AWS and Nginx in K8s. After experimenting with a simple echo headers application in my EKS environment, I ran into HTTP -> HTTPS redirect on TCP ELB terminating TLS, that results in a 308 redirect loop.

After digging further, I found this issue: https://github.com/kubernetes/ingress-nginx/issues/2724#issuecomment-444835897 with a posted workaround to enable integration between AWS NLB and Nginx Service Controller using PROXY protocol and who knows what else as we start digging deeper.

So, then, I threw away AWS TLS listener on NLB and replaced it with TCP 443 listener that forwards encrypted traffic to Nginx service HTTPS nodeport and configured TLS termination on Nginx Ingresses. Everything worked OOB => https://activiti-cloud-gateway.activiti7-eks.youbpm.com/activiti-cloud-modeling

The former approach to configure TLS termination on Nginx level is going to be portable in all K8s environments. I already successfully used this setup with GKE, AKS and EKS and requires no changes to charts or services.

**Comment by mteodori** [comment]
SSL termination should be on AWS, moving it to nginx is not an option

**Comment by mteodori** [comment]
the working version of nginx-ingress used the installation of devcon demo and pen test env is 1.1.2 so we should just advice to use that

handling of X-Forwarded headers must be configured on the microservices for the correct generation of the URLs but as Tomcat does not support X-Forwarded-Prefix the app must be mounted on the same path as the proxy, the "nginx.ingress.kubernetes.io/rewrite-target: /" is not enough

**Comment by mteodori** [comment]
if a redirect of http to https is happening there is a misconfiguration of the system, the http port should be off

**Comment by proth1** [comment]
> SSL termination should be on AWS or similar cloud provided level, moving it to nginx is not an option

Why is this not an option?

**Comment by igdianov** [comment]
@mteodori The HTTP->HTTPS redirect is the standard feature that any website, app or service should implement. It is not a good practice to turn HTTP port off because the redirect does not work. IMO, the redirect should be handled by AWS proxy by default, but there is no option to use it with NLB. 

AFAIK, we have to configure Nginx controller in K8s to be aware that AWS NLB proxy in front of it uses HTTPS and force redirect for all HTTP requests to NLB HTTPS port. This is where it gets interesting because you have to start dealing with K8s Nginx configuration in AWS swarm pit. 

> SSL termination should be on AWS or similar cloud provided level, moving it to nginx is not an option

It is a valid portable solution, that works in GKE, AKS, and EKS and uses K8s cert-manager with Let's Encrypt to issue TLS certificates on demand on the fly without hacking Nginx and Cloud Provider infrastructure. Also, all services work OOB without changes to configurations. 

> the working version of nginx-ingress used in the installation of devcon demo and pen test env is 1.1.2 so we should just advice to use that

There is a breaking change in Nginx Helm chart released 9 days ago that makes `rewrite-path: /` annotations incompatible with earlier versions of nginx. We should not be relying on these annotations in Modeler, Gateway and Graphiql ingresses anymore because the new rewrite-path format is not backward compatible with nginx versions before 0.22.0. See for details: https://github.com/Activiti/Activiti/issues/2460

**Comment by salaboy** [comment]
@ryandawsonuk @igdianov do we have the PRs for the public facing charts at least?

**Comment by salaboy** [comment]
should we switch our acceptance tests to use HTTPS only.. or the setup (certificates) is too complicated?

**Comment by mteodori** [comment]
@igdianov all the installations we do in alfresco offload the HTTPS certificate to the cloud infrastructure which is how it should be done, we are not redeploying infrastructure pieces that are provided by the cloud already

**Comment by ryandawsonuk** [comment]
For GA I think we just need to be able to know that @mteodori is able to enable https. Anything further is post-GA. @mteodori are you happy for us to move take the GA milestone off this issue on the basis that we've got what we need for GA?

**Comment by mteodori** [comment]
we managed to install the pen test environment without notifications and it works with https so I am happy to move it as long as notifications is not part of the release

**Comment by ryandawsonuk** [comment]
@igdianov , @mteodori are we good to close this now?

**Comment by mteodori** [comment]
yep this was done in GA already
