### ISSUE TITLE
Create admin delete variables endpoint

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#2390]
Add endpoint `DELETE admin/v1/process-instances/${id}/variables`

**Comment by erdemedeiros** [comment]
@daisuke-yoshimoto we are planning to move this endpoint and the create variables one to admin only (remove the non-admin ones). Is that ok for you?

**Comment by salaboy** [comment]
@daisuke-yoshimoto we remembered that you created this endpoint.. but we are not sure what kind of use cases were covered.. in general removing process variables might cause issues unless you know what you are doing.. for that reason we will leave the endpoint as admin only.
