### ISSUE TITLE
tracking of external documentation of examples

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2391]
We've got pages like https://community.alfresco.com/community/bpm/blog/2018/12/10/activiti-7-deep-dive-series-using-the-core-libraries and others on activiti 7. I say 'external' because this isn't about an example repo under the Activiti org. Should we add them to https://github.com/Activiti/Activiti/wiki/Articles-and-Blogs-on-Activiti ? It is useful to have a single place so that we can easily find examples and refer to them when answering community questions.

**Comment by mteodori** [comment]
Added with a DEPRECATED warning as the page is not maintained
