### ISSUE TITLE
Reenable code coverage on cloud projects

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#2395]
Reenable code coverage for cloud projects. In order to do so, you need to update `activiti-cloud-build` and include the same configuration we have for jacoco plugin in activiti-build. See [here](https://github.com/Activiti/activiti-build/blob/develop/pom.xml#L295..L299) and [here](https://github.com/Activiti/activiti-build/blob/develop/pom.xml#L438..L473).

*Note*: you will also need to update [Surefire argLine](https://github.com/Activiti/activiti-cloud-build/blob/develop/pom.xml#L141) to include `jacoco` customisations (`@{argLine}`). See [activiti-build](https://github.com/Activiti/activiti-build/blob/develop/pom.xml#L427) as example.

**Comment by salaboy** [comment]
@erdemedeiros can you close this already? or there are still open PRs?

**Comment by erdemedeiros** [comment]
It's done. Closing it.
