### ISSUE TITLE
Query Service Task Entity contains fields for filters that shouldn't be returned 

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2396]
We currently have:

```
   @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
    private Date lastModifiedTo;

    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
    private Date lastModifiedFrom;

```

that are use by query DSL to do filtering with from and to dates. The problem is that these fields shouldn't be returned as part of the response body of the requests. These are always null. 

Also there is 

```
private String category;
```

that is not being used and it should be removed. This is legacy.

**Comment by CTI777** [comment]
@salaboy @erdemedeiros 
ProcessInstanceEntity and TaskEntity both have 
    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
    private Date lastModifiedTo;

    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
    private Date lastModifiedFrom;

Should I apply changes only for  TaskEntity (or ProcessInstanceEntity should also be changed)

**Comment by salaboy** [comment]
@CTI777 I will close this one.. please reopen if something is missing.
