### ISSUE TITLE
timed out waiting for a condition

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2402]
We see this intermittently on helm installs in pipelines e.g.

http://jenkins.jx.35.228.195.195.nip.io/blue/organizations/jenkins/Activiti%2Factiviti-cloud-example-chart-security-policies/detail/PR-10/2/pipeline

We could try running with a larger `--timeout` but the default 300s should be enough. We could try `--no-hooks` but we're not intentionally using any hooks anyway. For now we're just retriggering manually.

We should keep an eye on https://github.com/helm/helm/issues/3980

**Comment by almerico** [comment]
after setting --timeout I don't see this issue
