### ISSUE TITLE
Remove RabbitMQ binder from starters and move to example projects

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2414]
The RabbitMQ binder shouldn't be added to our Spring Boot starters, it is up to the applications to add their binder of choice.

**Comment by salaboy** [comment]
Reference:

https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit

and

https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-starter-runtime-bundle/pom.xml#L73

**Comment by Claireedenton** [comment]
Linked to JIRA https://issues.alfresco.com/jira/browse/ACTIVITI-3097

**Comment by erdemedeiros** [comment]
Release notes and documentation: mention that from now you need to add the binder manually.

**Comment by igdianov** [comment]
@salaboy So, we will keep RabbitMQ binder in the starter test scope and explicitly add it to each micro-service in the examples. Is it correct?

**Comment by CTI777** [comment]
@salaboy @igdianov 
I have made a pair of PR's related to runtime-bundle. Is this what we need? If this is OK I will add same logic for query, Audit and Notifications

**Comment by salaboy** [comment]
@CTI777 this needs to be done for Query and Audit right? 
the changes looks good to me

**Comment by CTI777** [comment]
@salaboy Thank you for the comment.
I have checked query service and have found that `spring-cloud-starter-stream-rabbit` is not in starter `activiti-cloud-starter-query`, as I have expected, but in `activiti-cloud-services-query-rest`:
https://github.com/Activiti/activiti-cloud-query-service/blob/develop/activiti-cloud-services-query/activiti-cloud-services-query-rest/pom.xml#L140
Should I move it to starter and set a test scope (so that it looks like in runtime bundle)?

**Comment by salaboy** [comment]
@CTI777 yes please.. let's unify and align

**Comment by salaboy** [comment]
Audit and query (Examples are failing due this dependencies were removed) -> https://travis-ci.org/Activiti/activiti-cloud-query/builds/540615383?utm_source=github_status&utm_medium=notification

@CTI777 can you please add the dependencies at the example level and link the PRs here? Thanks!

**Comment by CTI777** [comment]
@salaboy @igdianov 
Do we need the same for 
https://github.com/Activiti/activiti-cloud-notifications-service-graphql
https://github.com/Activiti/activiti-cloud-notifications-graphql

**Comment by salaboy** [comment]
@CTI777 can you please check.. I guess that we should do the same for notifications.

**Comment by igdianov** [comment]
@CTI777 We need to check Connector Starter and Example as well.

**Comment by igdianov** [comment]
@salaboy We also need to review and merge PRs for Notifications

**Comment by salaboy** [comment]
done all merged
