### ISSUE TITLE
Standardise modeling service path

### ISSUE THREAD

**Issue by mteodori** [Activiti/Activiti#2419]
For backend:
  ${gatewayUrl}/activiti-cloud-modeling-backend
should become:
  ${gatewayUrl}/modeling-service

and for front-end:
  ${gatewayUrl}/activiti-cloud-modeling
should become:
  ${gatewayUrl}/modeling

and API_URL should be the only var passed to front-end with /modeling-service as prefix as agreed with @popovicsandras

**Comment by ryandawsonuk** [comment]
You'll need to change the chart to support that as `-backend` is hardcoded into the way it works https://github.com/Activiti/activiti-cloud-charts/blob/master/activiti-cloud-modeling/templates/service-backend.yaml#L5

**Comment by salaboy** [comment]
@mteodori what is the status of this issue?

**Comment by mteodori** [comment]
it was more difficult than estimated due the complexity of the frontend/backend in one container setup, I can try and give it another go

**Comment by salaboy** [comment]
ok I will leave open

**Comment by salaboy** [comment]
closing as it is a duplicate of: https://github.com/Activiti/Activiti/issues/2733
