### ISSUE TITLE
Add default labels to charts

### ISSUE THREAD

**Issue by mteodori** [Activiti/Activiti#2425]

**Comment by salaboy** [comment]
@mteodori are these Ingress related labels?

**Comment by mteodori** [comment]
No the standard ones of an helm scaffold that are used to search everything installed by a release, they shouldn’t have been removed unless there are reasons I am not aware of

On 27 Jan 2019, at 09:02, salaboy <notifications@github.com<mailto:notifications@github.com>> wrote:


@mteodori<https://github.com/mteodori> are these Ingress related labels?
