### ISSUE TITLE
decrease size of docker images

### ISSUE THREAD

**Issue by almerico** [Activiti/Activiti#2427]

**Comment by almerico** [comment]
https://github.com/Activiti/activiti-cloud-modeling/pull/56
https://github.com/Activiti/example-cloud-connector/pull/91
https://github.com/Activiti/activiti-cloud-audit/pull/115
https://github.com/Activiti/activiti-cloud-gateway/pull/5
https://github.com/Activiti/activiti-cloud-query/pull/115

**Comment by almerico** [comment]
@salaboy After several tries finally I selected smallest available working Docker image openjdk:11.0.1-jre-slim-stretch all masters are updated,  all three acceptance scenarios passed.

**Comment by salaboy** [comment]
@almerico you rock!
