### ISSUE TITLE
jdk 8 support ?

### ISSUE THREAD

**Issue by c14s** [Activiti/Activiti#2428]
We're using Activiti in a container that is running with jdk 8 (IBM WebSphere classic 9).
We were using Activiti 7.0.0.Beta5 before and noticed that RC1 was upgraded to jdk 11.

Is there a release line with jdk 8 support?
Do we have to switch back to Activiti 6 ?

**Comment by c14s** [comment]
@salaboy Thanks for your reply.

We have the situation, that the AppServer is provided by an existing installation at customer side
(my wording "container" was misleading; I just wanted to mention, that we're running on an ApplicationServer; WebSphere is *not* installed in a (docker) container; we cannot change the runtime).

If you're not using any Java 11 features, it would be an option to compile with -target 8
But of course, I could understand if you do not really want to do this...

**Comment by salaboy** [comment]
@c14s let's find a way around it.. we want to start leveraging JDK 9, 10 and 11 features without the need to backport any of those to JDK 8, that is also a blocker. But as today, we should be able to do our release processes with both targets.. @almerico do you know if we can include that in our pipelines?

**Comment by almerico** [comment]
@salaboy I can add one more compilation with ``mvn  -Djava.version=1.8  clean install`` which will produce classes data version 5.2  to test java8 compatibility to all pipelines

**Comment by almerico** [comment]
@salaboy adding and supporting parallel pipeline sounds bit complicated to support, but creating of java8 jars with different names and deploying them during pipeline is not so complicated.

**Comment by salaboy** [comment]
@almerico we can investigate on that front.. but I am afraid that as soon as we do that we will just add extra work that we cannot afford right now. I will need to check internally to see how other projects are doing this. I imagine that the option is to have a profile that we execute with JDK8 classifier or something like that .. but that will increase the testing and release process a lot.

**Comment by salaboy** [comment]
ok so starting point is to look at to create a profile for our maven projects

 <profile>
      <id>java-11</id>
      <activation>
        <jdk>11</jdk>
      </activation>
      <properties>
        <hibernate-validator.version>6.0.13.Final</hibernate-validator.version>
        <javassist.version>3.23.1-GA</javassist.version>
        <mockito.version>2.23.0</mockito.version>
      </properties>
      <dependencyManagement>
        <dependencies>
          <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
            <version>${javax-jaxb.version}</version>
          </dependency>
          <dependency>
            <groupId>org.javassist</groupId>
            <artifactId>javassist</artifactId>
            <version>${javassist.version}</version>
          </dependency>
        </dependencies>
      </dependencyManagement>
      <dependencies>
        <dependency>
          <groupId>javax.xml.bind</groupId>
          <artifactId>jaxb-api</artifactId>
        </dependency>
        <dependency>
          <groupId>com.sun.xml.bind</groupId>
          <artifactId>jaxb-impl</artifactId>
        </dependency>
      </dependencies>
    </profile>

**Comment by salaboy** [comment]
We need to change our POM files to use java version to 8

https://github.com/Activiti/activiti-build/blob/develop/pom.xml#L91

For the maven compiler plugin to build with JDK 8 compatibility

https://github.com/Activiti/activiti-build/blob/develop/pom.xml#L308

**Comment by salaboy** [comment]
@c14s this is going to be fixed in SR1..which we are going to try to get out by next week.

**Comment by c14s** [comment]
@salaboy sounds good, thanks! As soon as you've released SR1, I'll try it out in my java 8 environment.

**Comment by salaboy** [comment]
Cherry pick from here: 
https://github.com/Activiti/Activiti/issues/2541

**Comment by salaboy** [comment]
all changes applied in 7.0.x waiting for confirmation

**Comment by ryandawsonuk** [comment]
Something to note on this is https://github.com/Activiti/Activiti/issues/2577#issuecomment-467950597

**Comment by Sohnny0** [comment]
jdk8 is free... @salaboy

**Comment by salaboy** [comment]
@sohnny0 it is not about being free or not free.. it is already EOL, you shouldn’t be running stuff in production with a platform that ia not longer supported and it will
Not receive patches to newly found issues
