### ISSUE TITLE
[k8s configurations] on services check memory and cpu limits

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2429]
Are they set? 
Are we stopping the services to start faster?

**Comment by almerico** [comment]
@salaboy can you please add more details

**Comment by salaboy** [comment]
We need to review this values: 
https://github.com/Activiti/example-runtime-bundle/blob/master/charts/example-runtime-bundle/values.yaml#L58

I can see that we are not setting CPU limits.. but CPU 400 means that it will allocate 0.4 cpu resources by default to this container, which is why the spring boot app takes forever to start. 

We also need to change the liveness probe to not use the actuator path.. the liveness check should check that the JVM is active, and it should never kill the container unless the JVM crash.. today we are killing the container even if we are still retrying to connect to rabbitMQ. 

https://github.com/Activiti/example-runtime-bundle/blob/master/charts/example-runtime-bundle/values.yaml#L64

hopefully that makes more sense.

**Comment by salaboy** [comment]
wow!!!!! great news!! @ryandawsonuk @erdemedeiros @miguelruizdev ^^^^^

**Comment by miguelruizdev** [comment]
That's amazing!!! 
Thanks @almerico

**Comment by salaboy** [comment]
let's close this one then
