### ISSUE TITLE
Core services to use PostgreSQL inside community charts by default

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2431]
Each service should connect to a different schema into PostgreSQL in order to support enable/disable notification service which require access to the DB instance of the query service. 

Each service should create a schema based on the service name and version. 

We should run our acceptance tests against the services configured against PostgreSQL

**Comment by ryandawsonuk** [comment]
A shared postgres is now used but not sure if using different schemas

https://github.com/Activiti/activiti-cloud-charts/commit/e1bbbd0b1aeaffeb5cbd13f5ed5ea8cfe873b0f2
