### ISSUE TITLE
Process Variables Mappings

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2433]
following #2213 we need to improve this code and test it in our acceptance tests end to end from modeller to cloud. 
We also need the modeller UI for mappings in community.

**Comment by erdemedeiros** [comment]
@salaboy what is the difference between this and https://github.com/Activiti/Activiti/issues/2213?

**Comment by salaboy** [comment]
probably none.. should we use the other one? or this one?

**Comment by salaboy** [comment]
let's close one

**Comment by erdemedeiros** [comment]
Duplicate of https://github.com/Activiti/Activiti/issues/2213

**Comment by erdemedeiros** [comment]
Closed this one because the there is already a PR referencing the other one.
