### ISSUE TITLE
Add warning in RB if your process has the async=true property in a bpmn element

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2440]
This needs to be done at the runtime bundle level starter. 

Using async=true in ServiceTasks inside the runtime bundle will cause the default behaviour not being picked up so Cloud Connectors will not work. We need to at least warn the users that is happening.

**Comment by salaboy** [comment]
@daisuke-yoshimoto this might be one for you..but after the other ones

**Comment by daisuke-yoshimoto** [comment]
@salaboy 
Is it OK to target only ServiceTask? The async option itself is useful.

**Comment by daisuke-yoshimoto** [comment]
@salaboy 
Should I output this log at startup?
Also, should I output the log at the timing of calling the deploy API after starting?

**Comment by salaboy** [comment]
@daisuke-yoshimoto we need to do this in the runtime bundle starter.. in such environment we cannot use Async=true for anything because by default the job executor is disabled. So let's start with ServiceTask first.

**Comment by daisuke-yoshimoto** [comment]
> in such environment we cannot use Async=true for anything because by default the job executor is disabled.

I see. Basically, if we want to use asynchronous processing, is it to use connectors?

> So let's start with ServiceTask first.

It does not matter to do with all elements. 

Ok. I will modify it so that a warning log is outputed when the deployment process at startup and the deploy API are called.

**Comment by salaboy** [comment]
@daisuke-yoshimoto 👍

**Comment by daisuke-yoshimoto** [comment]
@salaboy 

> because by default the job executor is disabled.

How about checking the process engine configuration and outputing warning log only if job executor is disabled?

**Comment by salaboy** [comment]
@daisuke-yoshimoto yes.. that sounds like a good idea.. we want to avoid service tasks being scheduled but not actioned by any mechanism.

**Comment by salaboy** [comment]
@daisuke-yoshimoto not right now, unless you enable the job executor, because it can be enabled, but by default is disabled. We don't want to promote the usage of the AsyncExecutor, so after GA we will provide a different mechanism to support timers. 
We had a discussion with @igdianov where he proposed a different approach that we can also use, including a modified version of the Job Executor for scalability, but that is still under discussion.

**Comment by daisuke-yoshimoto** [comment]
@salaboy 
Ok. Then, I will check timer event definition too.

**Comment by daisuke-yoshimoto** [comment]
@salaboy @igdianov 
I created the pr for this issue. Please review this.
https://github.com/Activiti/Activiti/pull/2467

**Comment by salaboy** [comment]
merged! @daisuke-yoshimoto thanks a lot!
