### ISSUE TITLE
Modeler Services: Wrong file format for process extensions when export

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2442]
Process extensions should follow the format of "name of the process"-extensions.json and that it is currently not the case.

<img width="450" alt="screenshot 2019-01-31 at 10 04 29" src="https://user-images.githubusercontent.com/271966/52046830-9c7b3b80-253f-11e9-98f2-7499369246ec.png">

**Comment by salaboy** [comment]
@popovicsandras can we make sure that we follow that convention.. I think that we started with that.. due all the development of the backend was doing following such convention.

**Comment by constantin-ciobotaru** [comment]
@salaboy This is part of the BE side, so the fix is export endpoint. We should agree on the same convention also on aps side: https://issues.alfresco.com/jira/browse/ACTIVITI-2359.

**Comment by salaboy** [comment]
@constantin-ciobotaru yes.. I will change the title.. we did all the coding (@balsarori did) with that -extensions.json format.. so there is an out of sync between what the modeler is generating and what the runtime is expecting.

**Comment by salaboy** [comment]
initial work done.. requires verification
