### ISSUE TITLE
Where is activiti7.0.0.RC1 modeler?

### ISSUE THREAD

**Issue by qiudaoke** [Activiti/Activiti#2443]
When I was using activiti7.0.0.RC1, I couldn't find how to draw the process.

**Comment by salaboy** [comment]
@qiudaoke we are working on a standalone version of the cloud modeller now, that will be included in GA. If you want to use the modeler today you need to install it using HELM charts as explained here: https://activiti.gitbook.io/activiti-7-developers-guide/getting-started/getting-started-activiti-cloud
