### ISSUE TITLE
Do we need POST admin/v1/process-instances/${id}/variables?

### ISSUE THREAD

**Issue by cristianflorescu** [Activiti/Activiti#2445]

**Comment by cristianflorescu** [comment]
In initial request https://issues.alfresco.com/jira/browse/ACTIVITI-2413
only GET and DEL are requested

**Comment by mauriziovitale** [comment]
As discussed with @salaboy we don't need a POST endpoint but just a PUT.
From the Admin UI, a user should be able to update only existing variables but not to create/delete the existing one.

**Comment by salaboy** [comment]
@erdemedeiros @cristianflorescu ^

**Comment by balsarori** [comment]
I think a POST to create a variable is important otherwise it will be not possible for admins to troubleshoot processes that are broken due to a missing variable (i.e. deleted or not created by error).

**Comment by salaboy** [comment]
Let's support update for now.. 
@balsarori can you share an example where creating a new variable will help to solve a problem?

**Comment by salaboy** [comment]
@balsarori @mauriziovitale it was decided to use PUT because the implementation now allows you to update variables values only, instead of creating new ones.

**Comment by salaboy** [comment]
merged
