### ISSUE TITLE
[Core] Let's create Activiti Cloud Application Helm Chart Quickstarts

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2448]
so that folks could use 'jx create quickstart' command to import and promote Activiti Cloud Application Helm charts into their DevOps environment via GitOps. 

Todos: 

- [x] Create activiti-cloud-infrastructure-quickstart
- [x] Create activiti-cloud-application-quickstart

**Comment by salaboy** [comment]
@igdianov done

**Comment by ryandawsonuk** [comment]
We need to look at how to get the latest chart changes reflected in these quickstarts, especially https://github.com/Activiti/activiti-cloud-charts/pull/42

After discussion what we will do is release the quickstarts manually after the rest of the projects, so that we have more time to get those changes reflected. So https://github.com/Activiti/activiti-scripts/pull/13 will remain open

**Comment by ryandawsonuk** [comment]
So now I think we need to get these into the release process and officially incorporate the documentation

**Comment by salaboy** [comment]
@ryandawsonuk can you please suggest what do you have in mind for making that happening?

**Comment by ryandawsonuk** [comment]
For release process we have https://github.com/Activiti/activiti-scripts/pull/13 above. 

For documentation actually we were just discussing that on standup. We remember you suggesting to put a stripped-down version into gitbook. But we're not sure how much to strip down. Specifically whether to take out the sections in the GKE and EKS docs that introduce activiti and introduce JX.

**Comment by ryandawsonuk** [comment]
I'll simply try to convert the entirety of the google docs to markdown and submit a PR and we can then review the PR.

**Comment by salaboy** [comment]
@igdianov how are we doing with this one? Any idea? 
I have the feeling that we closed this one already. If so.. can you please close.

**Comment by mteodori** [comment]
obsolete
