### ISSUE TITLE
[Infrastructure] Switch from keycloak directly to alfresco identity service (which is still keycloak)

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2450]
Have started a branch to do this on the user-facing charts - https://github.com/Activiti/activiti-cloud-charts/tree/alfrescoidentity

When we do eventually get this working then we need change all the default config in the examples (and quickstarts) to use 'alfresco' realm and change the internal-facing charts to use it and retest examples and ttc.

We probably want to upgrade the version of the keycloak adapter in the code too (at least backend, maybe in the ttc frontend)

**Comment by ryandawsonuk** [comment]
Proposed changes so far cover defaulting of realm.

Outstanding items would be internal-facing charts and upgrading to adapter version 4.8.3.Final (which is AIS version at time of writing)

**Comment by ryandawsonuk** [comment]
Many of the PRs should now be changed as client and resource can be 'activiti' - it is only realm that has to become 'alfresco' - see https://github.com/Activiti/activiti-cloud-charts/pull/51#issuecomment-472405765

**Comment by ryandawsonuk** [comment]
Above PRs now all updated to use client and resource as 'activiti' and realm as 'alfresco', as per above.

**Comment by salaboy** [comment]
@almerico please wait for more instructions on this one..

**Comment by almerico** [comment]
Done

**Comment by salaboy** [comment]
@almerico should we close all the open PRs from @ryandawsonuk then? Can you please do that if this is done already?

**Comment by almerico** [comment]
@salaboy yes they are out of date now
