### ISSUE TITLE
[Infrastructure] garbage collection for old running helm charts 

### ISSUE THREAD

**Issue by almerico** [Activiti/Activiti#2452]

**Comment by ryandawsonuk** [comment]
@salaboy I'm guessing we can remove the GA label from this?

@almerico I think this could do with a little more explanation

**Comment by almerico** [comment]
@ryandawsonuk  I noticed that during jx builder issue and system update some helm releases has not removed even if Jenkins job is already finished and impacted jx pipeline because used cluster resources.

**Comment by almerico** [comment]
it is already fixed
