### ISSUE TITLE
Update probes and values in helm charts 

### ISSUE THREAD

**Issue by almerico** [Activiti/Activiti#2454]
example-cloud-connector
ttc-connectors-ranking
ttc-connectors-reward1
ttc-connectors-processing
ttc-connectors-dummytwitter
and the user-facing charts
activiti-cloud-charts
and the quickstart
activiti-cloud-connector-quickstart

**Comment by almerico** [comment]
@salaboy updated in all user faced charts

**Comment by salaboy** [comment]
@almerico can you close this one?

**Comment by almerico** [comment]
done
