### ISSUE TITLE
Generated swagger for rb-my-app:startProcess api request is missing payload type

### ISSUE THREAD

**Issue by rpopa** [Activiti/Activiti#2456]
After I generated using open feign the api client for activiti process runtime, I found out that the startProcess request is missing `payloadType` and it can't be used.

Stacktrace: "status":400,"error":"Bad Request","message":"JSON parse error: Missing type id when trying to resolve subtype of [simple type, class org.activiti.api.process.model.payloads.StartProcessPayload]: missing type id property 'payloadType'; nested exception is com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class org.activiti.api.process.model.payloads.StartProcessPayload]: missing type id property 'payloadType'\n at [Source: (PushbackInputStream); line: 1, column: 193]","path":"/admin/v1/process-instances"}

**Comment by salaboy** [comment]
@rpopa thanks for reporting this, we are aware of the issue, but it seems to be a problem of swagger and polymorphism. We are investigating the issue to see if we can fix it in the short term.

**Comment by mteodori** [comment]
jackson mixins seem to be ignored https://github.com/Activiti/activiti-api/blob/4748bc180e9037ace50dc5a4204f4c9221023afe/activiti-api-model-shared-impl/src/main/java/org/activiti/api/runtime/conf/impl/PayloadMixIn.java#L28

**Comment by salaboy** [comment]
@mteodori I think that those are working but not being picked up by swagger

**Comment by mteodori** [comment]
@salaboy yes that is what I meant, swagger configuration is not the same as the app one

**Comment by constantin-ciobotaru** [comment]
I've added an workaround for this: https://github.com/Activiti/activiti-cloud-runtime-bundle-service/pull/248

A proper fix would be to update springfox to pickup the jackson mixin config.

**Comment by ouyangshixiong** [comment]
I think it's nothing deal with swagger,postman return the same error .
![1550483739 1](https://user-images.githubusercontent.com/2086862/52942815-b5407980-33a6-11e9-97b5-70a7b45c53ac.png)

**Comment by mteodori** [comment]
@ouyangshixiong I believe the postman collection hasn't been updated in a while, can you create a separate issue for that? thanks

**Comment by ouyangshixiong** [comment]
@mteodori  OK

**Comment by salaboy** [comment]
@ouyangshixiong instead of CommandType -> PayloadType and then
StartProcessPayload is the payload for that request.. that should work.
We will probably not maintain Postman collections as they go out of date quite fast. We will favour swagger and swagger files aggregations in the future.

**Comment by salaboy** [comment]
fixed merge in develop
