### ISSUE TITLE
[Infrastructure] Activiti Cloud Build dependency management priority problem

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2461]
is caused by incorrect dependencyManagement inclusion hierarchy inside `dependency` module, which imports SB dependencies versions from Activiti Build via external core modules and overrides SB versions defined in Activiti Cloud Build.

Instead, any external dependencies should be moved to the parent level after activiti-cloud-build-dependencies, so that activiti cloud build dependencies take priority, i.e.

https://github.com/Activiti/activiti-cloud-notifications-service-graphql/pull/11

**Comment by salaboy** [comment]
@igdianov sorry what was this? 
I can see a merged PR in notifications.. but should we follow the same approach in all other starters?

**Comment by salaboy** [comment]
@igdianov can you update this one?

**Comment by erdemedeiros** [comment]
@igdianov what is the status of this one?
