### ISSUE TITLE
Add Activiti Cloud Starters version into Spring Boot Actuator

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2463]
The idea is to have in each starter a new Activiti Endpoint that expose which Activiti Cloud version is being used.
I've also used this in the past: 

https://github.com/salaboy/s1p_gateway/blob/master/pom.xml#L92

Which was quite useful to expose metadata about the spring boot app.

**Comment by mteodori** [comment]
@salaboy @ffazzini of all the approaches listed here https://codeboje.de/spring-boot-info-actuator/ I would like to have this implemented as an InfoContributor on a shared spring config across all micro-services so we can avoid changing all the poms or application configs WDYT?

**Comment by salaboy** [comment]
@mteodori excellent article.. I think that we need to expand on that.. we need to be able to read a maven property (activiti.cloud.dependencies-version, for example) and include that into the actuator information. 
I really like the build-info approach and it seems to be the standard approach used by the spring community and tools around it.

**Comment by mteodori** [comment]
that has the drawback of requiring to change all the poms I highlighted above

**Comment by Claireedenton** [comment]
Linked to JIRA https://issues.alfresco.com/jira/browse/ACTIVITI-3095

**Comment by mteodori** [comment]
available in /actuator/info as activiti.version
