### ISSUE TITLE
Activiti Modeler is broken in the cluster with latest stable/nginx chart 1.30 (nginx:0.22.0)

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2476]
![image](https://user-images.githubusercontent.com/20428629/52542616-8bf46d80-2d56-11e9-88d2-ebc4d69eeded.png)

Related to #2460

**Comment by igdianov** [comment]
@salaboy Temporary workaround is to use prior Nginx chart 1.1.2

`helm install stable/nginx-ingress --version 1.1.2`

**Comment by salaboy** [comment]
thanks a lot I will update the git book first
