### ISSUE TITLE
[Core] HAL response don't include Service name

### ISSUE THREAD

**Issue by balsarori** [Activiti/Activiti#2481]
When accessing a task using `http://myhost.com/my-rb/v1/tasks/075f20c7-2deb-11e9-a588-0a58646003dd`

The response doesn't return back full URLs (missing the rb service name in this case my-rb)
```{
    "appName": "default-app",
    "appVersion": "",
    "serviceName": "rb-my-app",
    "serviceFullName": "rb-my-app",
    "serviceType": "runtime-bundle",
    "serviceVersion": "",
    "id": "075f20c7-2deb-11e9-a588-0a58646003dd",
    "assignee": "devopsuser",
    "name": "Task One V2",
    "createdDate": "2019-02-11T10:51:47.575+0000",
    "priority": 50,
    "processDefinitionId": "TwoTasksProcess:2:f0ad4dc6-2de9-11e9-8c6c-0a58646003dd",
    "processInstanceId": "075ef9b4-2deb-11e9-a588-0a58646003dd",
    "status": "ASSIGNED",
    "_links": {
        "self": {
            "href": "http://myhost.com/v1/tasks/075f20c7-2deb-11e9-a588-0a58646003dd"
        },
        "release": {
            "href": "http://myhost.com/v1/tasks/075f20c7-2deb-11e9-a588-0a58646003dd/release"
        },
        "complete": {
            "href": "http://myhost.com/v1/tasks/075f20c7-2deb-11e9-a588-0a58646003dd/complete"
        },
        "processInstance": {
            "href": "http://myhost.com/v1/process-instances/075ef9b4-2deb-11e9-a588-0a58646003dd"
        },
        "home": {
            "href": "http://myhost.com/v1"
        }
    }
}
```

**Comment by ryandawsonuk** [comment]
See https://github.com/Activiti/activiti-cloud-charts/commit/fe1f57fc491c265e42ca483807189084737fc1f0#diff-5830a2234a42db58333e9f8f5b7bce49R17 - it might be that we need to get ensure the x-forwarded-host is read and used. That PR there shows how to add it but doesn't actually add it as it's commented there.

**Comment by ryandawsonuk** [comment]
Checked with @igdianov. He reports that it is enough to enable those properties when using ingress instead of gateway. He also advises that the extraEnv at global level is not applied to gateway

**Comment by salaboy** [comment]
@ryandawsonuk I would like to make sure that we support the same things with the gateway.. it should be our default approach. @igdianov are we missing something in the gateway?

**Comment by mteodori** [comment]
obsolete as per #3151
