### ISSUE TITLE
publish modeling UI to npm

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2484]
We will tag the modeling UI in GA and then publish it from the tag through bamboo after GA

@popovicsandras @mteodori

**Comment by ryandawsonuk** [comment]
```
#!/bin/bash

touch .npmrc
echo 'strict-ssl=false' >> .npmrc
echo 'registry=http://${bamboo.npmregistry_address}' >> .npmrc
echo '//${bamboo.npmregistry_address}/:_authToken="${bamboo.npmregistry_token}"' >> .npmrc

if ${bamboo.is_development} == true; then
    
    ./scripts/update-version.sh -nextalpha -gnu -major -components
    ./scripts/npm-publish.sh -r ${bamboo.npmregistry_address} -token ${bamboo.npmregistry_token} -t alpha --sleep 120 || exit 1

fi

```
https://github.com/Alfresco/alfresco-ng2-components/blob/development/scripts/npm-publish.sh

**Comment by mteodori** [comment]
where is this going to be published and how can we test it? I would have expected using the publish script of an app rather than a library as it is closer like content app while this is the one of ADF, would it work in the same way?

**Comment by ryandawsonuk** [comment]
@mteodori , I asked @DenysVuika and he advised that "ACA is application, not library, we don't publish it to NPM"... does this mean we don't want to publish the modeling app after all?

**Comment by DenysVuika** [comment]
Fyi, we publish every ACA build to Docker Hub: https://cloud.docker.com/u/alfresco/repository/docker/alfresco/alfresco-content-app

**Comment by mteodori** [comment]
closing this one as won't do, we agreed it is fine the code is just tagged and there are instructions to compile it
