### ISSUE TITLE
versions of docker images from jx start with 7

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2485]
Our example docker images are being generated starting with 7 because the versions of our tags are incrementing from 7.0.x. But this is confusing as our pom says 1.0.0:

https://github.com/Activiti/example-runtime-bundle/commit/ae6ec8f0a7d525e39e41113d8e3f210746550a7f#diff-600376dffeb79835ede4a0b285078036

The reason seems to be that in the past our pom.xml did say 7.0.0 and we then moved our version number down. However we can't go back to 1.0.x as `jx-release-version` [won't let us go backwards](https://github.com/jenkins-x/jx-release-version/blob/master/main.go#L274). Need to come up with a way to make the versions easier to understand as 7.0.x for internal builds is misleading

**Comment by almerico** [comment]
@ryandawsonuk not sure that I fully understand the what have to be done.

**Comment by ryandawsonuk** [comment]
I guess we should check with @salaboy as I think your change to `jx-release-version` will let us do versions of the form `1.0.x` if we want to... I'm not entirely sure either what form we want for internal version numbers.

**Comment by ryandawsonuk** [comment]
I think we're now using 7.0.x and 7.1.x formats for the different release trains. So my impression is we can close this issue.
