### ISSUE TITLE
Missing Description field In StartProcessPayload and Engine

### ISSUE THREAD

**Issue by miguelruizdev** [Activiti/Activiti#2487]
StartProcessPayload: 
https://github.com/Activiti/activiti-api/blob/develop/activiti-api-process-model/src/main/java/org/activiti/api/process/model/payloads/StartProcessPayload.java#L9

Engine: https://github.com/Activiti/Activiti/blob/006b8a3e388fa6ac7fab62abf53c6c086852cf91/activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/ProcessRuntimeImpl.java#L214

**Comment by proth1** [comment]
Should the title be updated to spell out 'StartProcessPayload" vs. "StarProcessPayload"?

**Comment by erdemedeiros** [comment]
@miguelruizdev as far as I understood from https://github.com/Activiti/Activiti/issues/2510 this is no longer necessary. Instead of adding `description` to `StartProcessPayload` we need to remove it from `ProcessInstance`. Is that right?

**Comment by miguelruizdev** [comment]
That is correct, @erdemedeiros.
I'll close this issue now
