### ISSUE TITLE
modeling UI requires that process variable values be strings in the json

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2488]
This is not allowed:

![image](https://user-images.githubusercontent.com/22754674/52583934-adbe2500-2e28-11e9-96a2-f175e25a0a3a.png)

But this is:

![image](https://user-images.githubusercontent.com/22754674/52583946-b9a9e700-2e28-11e9-93ad-2c563bd780b2.png)

That's a problem as we want to be able to [read variables as json](https://github.com/Activiti/Activiti/blob/develop/activiti-spring-boot-starter/src/test/resources/processes/json-vars-extensions.json#L10)

**Comment by salaboy** [comment]
schema validation removed for values
