### ISSUE TITLE
modeling UI does not show all process variables

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2489]
I loaded some [example process variable json](https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-starter-runtime-bundle/src/test/resources/processes/variable-mapping-extensions.json#L11) into the modeling UI.

After [changing all the values of the variables to be strings (which I shouldn't have to do)](https://github.com/Activiti/Activiti/issues/2488) then I was able to set up the variables and save them. But I can't then see them all in the UI, only a subset:

![image](https://user-images.githubusercontent.com/22754674/52584288-8f0c5e00-2e29-11e9-9da2-8761a8cfac6b.png)

If I then use the '+' button to add another then that one appears in the json but also not in the table... it only shows the first three

**Comment by salaboy** [comment]
cannot reproduce after testing
