### ISSUE TITLE
modeling UI doesn't support 'icon' in connector definition json

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2490]
We should remove from the backend examples - https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-starter-runtime-bundle/src/test/resources/connectors/connector-with-variable-mapping.json#L5

**Comment by salaboy** [comment]
closing as duplicated with https://github.com/Activiti/Activiti/issues/2490
