### ISSUE TITLE
[Modeling] Can't save or validate invalid connector definition after a change

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2491]
Import https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/959053856b587b831fbf176d03db93229c1e4f23/activiti-cloud-starter-runtime-bundle/src/test/resources/connectors/connector-with-variable-mapping.json

Then save it - you get errors. One of them tells you that you can't have an 'icon' line so remove that. Now you want to save again to see what errors you still have... But you can't because the save button is now greyed out:
![image](https://user-images.githubusercontent.com/22754674/52585210-19ee5800-2e2c-11e9-969a-87838b1a4131.png)

**Comment by erdemedeiros** [comment]
Unable to reproduce it in 7.1.0.M4
