### ISSUE TITLE
Remove Icon from ConnectorDefinition class

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2494]
Remove Icon property, because it is not being used:
https://github.com/Activiti/activiti-core-common/blob/develop/activiti-connector-model/src/main/java/org/activiti/core/common/model/connector/ConnectorDefinition.java#L13

and it is causing the front end modeller to not validate the FE schema that is being used for connectors

**Comment by miguelruizdev** [comment]
Remove the presence from connectors as well.
Eg: https://github.com/Activiti/Activiti/blob/develop/activiti-spring-boot-starter/src/test/resources/connectors/connector-with-variable-mapping.json#L5

**Comment by salaboy** [comment]
@magemello should we merge these PRs? or should we leave it here for future use?
