### ISSUE TITLE
Modeling Backend Process Extension & Process Definition ID link

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2497]
We created a process definition which contains the ID:

```
<bpmn2:process id="process-8abc837368e1806c0168e249d6be0008" name="SimpleProcess" isExecutable="true">
```
In this case **process-8abc837368e1806c0168e249d6be0008**
And the -extensions.json file contains the following ID
```
"id": "8abc837368e1806c0168e249d6be0008",
```

This needs to match with the process id defined in the process definition, because we are linking in the engine the two entities by that ID.

Attached app was created with Modeller UI and demonstrate the problem

[allModeler.zip](https://github.com/Activiti/Activiti/files/2856451/allModeler.zip)

**Comment by salaboy** [comment]
merged in develop

**Comment by saraarif** [comment]
@salaboy can you please guide how to create extension.json file through modeling app and how to define input and output mapping .what is the purpose of input and output mapping.Please
