### ISSUE TITLE
[Modeling] Allow in process variable to have typed value

### ISSUE THREAD

**Issue by constantin-ciobotaru** [Activiti/Activiti#2500]
For now process variables are formatted in json as strings, no matter what is the real type of the variable:

`{
    "id": "f593b2a8-01e5-4186-a6e9-cb0f060ab8ea",
    "name": "p1",
    "type": "int",
    "required": false,
    "value": "34"
}
`

We should allow typed values like:

`{
    "id": "f593b2a8-01e5-4186-a6e9-cb0f060ab8ea",
    "name": "p1",
    "type": "int",
    "required": false,
    "value": 34
}
`

or

`{
    "id": "f593b2a8-01e5-4186-a6e9-cb0f060ab8ea",
    "name": "p1",
    "type": "boolean",
    "required": false,
    "value": true
}
`

or even json objects:

`{
    "id": "f593b2a8-01e5-4186-a6e9-cb0f060ab8ea",
    "name": "p1",
    "type": "json",
    "required": false,
    "value": {"A": "b"}
}
`

See:
https://github.com/Activiti/Activiti/blob/develop/activiti-spring-process-extensions/src/main/java/org/activiti/spring/process/ProcessExtensionService.java#L84 

https://github.com/Activiti/Activiti/blob/develop/activiti-spring-process-extensions/src/main/java/org/activiti/spring/process/model/VariableDefinition.java#L20

**Comment by salaboy** [comment]
@constantin-ciobotaru where are we with this one?

**Comment by constantin-ciobotaru** [comment]
@salaboy Sorry, I didn't worked on any ticket in community, we were focused on aps side.
