### ISSUE TITLE
[Infrastructure] NodeJS bump package.json version based on JX Release Mechanism

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2504]
For https://github.com/activiti/activiti-modeling-app we need to include in the release stage the bump up of the package.json version field to match with the release. The version should be 1.0.0 instead of v0.0.x

**Comment by salaboy** [comment]
References:
https://github.com/muirp/nodejs-demo/blob/master/Jenkinsfile#L42

```

if you're not sure if it'll work, branch master and make a PR and then check the preview environment.

salaboy   [1 hour ago]
but let's say that we already have a PR with some changes .. we want to bump up the version in master when the PR get merged

salaboy   [1 hour ago]
we can probably include the version bumping automatically in the PR.. but not sure how to do that

salaboy   [1 hour ago]
@almerico ^

Eamon Keane   [1 hour ago]
ah ok, well auto-bumping of dependencies is something that I see bitnami do by monitoring upstream and making PRs with bots, but you're prob better off doing it yourself on the same PR

salaboy   [1 hour ago]
this might be a common requirement for nodeJS apps

salaboy   [1 hour ago]
so I wonder if someone else is doing so

salaboy   [1 hour ago]
@James Rawlings I guess that you have some nodeJS apps?

Pete Muir   [21 minutes ago]
Normally we do this by just bumping the version in the tag alone, not master

Pete Muir   [21 minutes ago]
as otherwise you get a cycle

salaboy   [20 minutes ago]
yep.. avoiding the cycle is the main problem

salaboy   [20 minutes ago]
how do you do that in the tag.. do you have an example?

Pete Muir   [17 minutes ago]
just looking

salaboy   [16 minutes ago]
@Pete Muir :+1:

Pete Muir   [14 minutes ago]
ok, looks like we don't do that for nodejs

fiunchinho   [15 minutes ago]
normally (at least in maven projects) you add changes to the `*-SNAPSHOT` version, and then the version bumping change is added to the version thats released, right? you never get to a cycle, because the PR is adding changes to *-SNAPSHOT

salaboy   [14 minutes ago]
@fiunchinho yep.. we do the same in maven projects.. but nodeJS guys is different

salaboy   [14 minutes ago]
they need to bump that version to work with a different version number for some weird reasons.. they are used to do that

Pete Muir   [14 minutes ago]
I know that the updatebot maven plugin can handle versioning java projects

Pete Muir   [12 minutes ago]
Just building updatebot to see I can figure out the magic to make it update a `package.json`

fiunchinho   [9 minutes ago]
you mean updatebot or jx-release-version? updatebot accepts any arbitrary regex AFAIK?

salaboy   [9 minutes ago]
I was looking at this: https://github.com/jenkins-x/builder-nodejs/blob/master/jx/scripts/release.sh#L20
jx/scripts/release.sh:20
```git push origin v${VERSION}```
jenkins-x/builder-nodejsAdded by GitHub

Pete Muir   [9 minutes ago]
I mean updatebot

salaboy   [9 minutes ago]
but yeah.. updatebot works with java and helm

salaboy   [9 minutes ago]
so we might be able to extend it to work with nodejs

Pete Muir   [8 minutes ago]
yeah, we create a versioned tag, but I don't think the npm version is updated

salaboy   [8 minutes ago]
no it is not

Pete Muir   [8 minutes ago]
updatebot will handle `package.json`

Pete Muir   [7 minutes ago]
Can you use something like https://docs.npmjs.com/cli/version.html

Pete Muir   [7 minutes ago]
you have the version available in `./VERSION`

salaboy   [7 minutes ago]
yeah.. but when we do the tag.. then..

salaboy   [6 minutes ago]
npm version VERSION

salaboy   [6 minutes ago]
should do it

Pete Muir   [6 minutes ago]
yep

salaboy   [6 minutes ago]
but still not clear.. the version will be only in the tag

salaboy   [6 minutes ago]
which might be ok.. i need to get back to the nodeJS guys to see if that is enough

salaboy   [6 minutes ago]
it is a workflow problem.

Pete Muir   [6 minutes ago]
If you do it at https://github.com/muirp/nodejs-demo/blob/master/Jenkinsfile#L42
Jenkinsfile:42
          ```sh "echo \$(jx-release-version) > VERSION"```
muirp/nodejs-demoAdded by GitHub

Pete Muir   [5 minutes ago]
then it should be tagged properly

fiunchinho   [2 minutes ago]
I found out about the `jx step next-version` wrapper last week, which outputs the version to the VERSION file for you

fiunchinho   [1 minute ago]
> This pipeline step command works out a semantic version, writes a file ./VERSION and optionally updates a file

salaboy   [1 minute ago]
:+1:

fiunchinho   [< 1 minute ago]
interestingly enough, the example is using a package.json file :stuck_out_tongue:
`jx step next-version --filename package.json --tag --version 1.2.3`


```

**Comment by salaboy** [comment]
this is suggested in the JenkinsFile
```
jx step next-version --filename package.json --tag --version 1.2.3

```

**Comment by salaboy** [comment]
James Strachan   [< 1 minute ago]
the `jx step tag` we use to create the tag already handles dealing with local changes (e.g. to `pom.xml` or `Chart.yaml` or whatever to deal with version upgrades) - which get committed into the new tag - so we should be able to modify the `package.json` by default in the nodejs build pack using `jx step next-version --filename package.json` and it should all just work :crossed_fingers: (edited)

**Comment by salaboy** [comment]
he is going to experiement with pushing the actual commit to master as well (which changes VERSION) but not triggering builds on that


James Strachan   [23 hours ago]
here’s a project I created thats spring boot - see the `pom.xml` is modified within the tag https://github.com/jstrachan/demo256/blob/v0.0.1/pom.xml#L13
pom.xml:13
    ```<version>0.0.1</version>```
jstrachan/demo256Added by GitHub

James Strachan   [23 hours ago]
via a commit thats pushed to the tag https://github.com/jstrachan/demo256/commit/58d6140f20212d59c656a77dc0778c77742ccbe1

James Strachan   [23 hours ago]
so it could just be the nodejs build pack is not quite working in the same way?

Pete Muir   [23 hours ago]
The problem is the commit is missing - see https://github.com/jstrachan/demo256/tree/v0.0.1

Pete Muir   [23 hours ago]
you can't click on it

James Strachan   [23 hours ago]
i can click on the `release 0.0.1` commit on here https://github.com/jstrachan/demo256/commits/v0.0.1

James Strachan   [23 hours ago]
or the last commit here https://github.com/jstrachan/demo256/tree/v0.0.1

Pete Muir   [20 hours ago]
yeah, so IDK - this one is on @hardy :slightly_smiling_face:

James Strachan   [20 hours ago]
here’s a patch that fixes `jx step next-version` to update the package.json and push it to a tag https://github.com/jenkins-x/jx/pull/3101
jstrachan
#3101 fix: jx step next-version update the package.json
this change allows us to use `jx step next-version --filename package.json --tag` in a pipeline to update the package.json and optionally the `Chart.yaml` and then push the commit to a tag
Labels
size/XS
Comments
1
jenkins-x/jxYesterday at 12:59 PMAdded by GitHub

James Strachan   [20 hours ago]
I just ran `jx step next-version --filename package.json --tag` and got this versioned tag https://github.com/jstrachan/nodey43/commit/0c6246c70b8dc4b7aef2290eb7a7c9441454b908

Pete Muir   [20 hours ago]
excellent

Pete Muir   [20 hours ago]
does that work for charts as well?

James Strachan   [20 hours ago]
once the PR is released into the platform, I’ll switch the nodejs build pack to use this

Pete Muir   [20 hours ago]
:smile:

James Strachan   [20 hours ago]
we should be able to use `jx step next-version --tag` on other build packs

James Strachan   [20 hours ago]
which also does the `jx step tag` too in one line

Pete Muir   [20 hours ago]
even better

James Strachan   [20 hours ago]
mind you for maven we do this via `mvn versions:set` so its not a biggie for the maven build pack

**Comment by almerico** [comment]
fixed
