### ISSUE TITLE
Redundant description field in ProcessInstance

### ISSUE THREAD

**Issue by miguelruizdev** [Activiti/Activiti#2510]
The **description** of a process instance comes from the process definition it's based on.

The engine does not support the fact of passing any specific value to it at process creation. Neither it does when updating the process instance.

This fact makes the Description field in a process instance redundant, since it never gets populated.

As [this question raised in Activiti forums](https://community.alfresco.com/thread/225930-processinstancegetname-and-getdescription-are-null) shows, the fact that the API offers the possibility to populate it in the same fashion as the name is rather misleading.

Since extracting the value of description from the process definition and set it in each instance does not enrich the instance itself (as it occurs with **processDefinitionId**), there's no reason why description should exist as a field in our Process Instance Model.

**Comment by miguelruizdev** [comment]
@erdemedeiros just copying you here for you to be aware of this change

**Comment by salaboy** [comment]
@erdemedeiros this might be ready to review and merge.. 
As far as I remember, it is ok to remove the description field because as @miguelruizdev stated that comes from the process definition. There is no reason to have that at the process instance level.

**Comment by salaboy** [comment]
done .. we need to validate the acceptance tests validations
