### ISSUE TITLE
An admin only cannot update process instance variables

### ISSUE THREAD

**Issue by cristianflorescu** [Activiti/Activiti#2512]
Steps to reproduce:

Login with an admin
Select an app where the admin has the ACTIVITI_ADMIN role but no ACTIVITI_USER role
Select a process instance that has variables

Expect behaviour
The admin should be able to update the variables

Current behaviour
The admin is not able to update a variable

Related with https://issues.alfresco.com/jira/browse/ACTIVITI-2689, https://issues.alfresco.com/jira/browse/DW-1055

https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/95ca4668a58cd0069d6a15311f0815d3aa8a80f9/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/ProcessInstanceVariableAdminControllerImpl.java#L52
should be ```private final ProcessAdminRuntime processAdminRuntime;```

**Comment by salaboy** [comment]
merged in develop
