### ISSUE TITLE
[Modeling] UI doesn't redirect to login when session time out

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2513]
The Alfresco JS api should deal with silent auto refresh for the session. 
but for some reason the app is not dealing correctly with the time outs.

**Comment by salaboy** [comment]
@popovicsandras this might be fixed already, can you please confirm?

**Comment by popovicsandras** [comment]
@salaboy, No, unfortunately this hasn't been fixed yet this way. The temporary solution what we have atm:
"If the application is not used for few minutes, the active session expires and the user is notified, with a snackbar error message that operations can no longer be performed."

We created an issue for that now, please follow this thread:
https://issues.alfresco.com/jira/browse/APM-1033
