### ISSUE TITLE
Personal issue found during activiti 7 + local kubernetes installation

### ISSUE THREAD

**Issue by csckcac** [Activiti/Activiti#2521]
Just write a summaries here so that someone may find it useful.
Following
https://community.alfresco.com/community/bpm/blog/2018/12/10/getting-started-with-activiti-7-beta

Windows 10 docker + kubernetes is not working, postgresql will complain about the file sharing permission, so i switched to use CentOS 7 + kubeadm

After installation, you should pick a network addon here, just make sure you don't forget to do it.
https://kubernetes.io/docs/concepts/cluster-administration/addons/#networking-and-network-policy

I am using a single master cluster for development testing. Check the note here so the pod scheduler works.
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#control-plane-node-isolation

You will find PostgreSQL unbound error, complain the PersistentVolume Claim, you have to create default storage class, and then a persistent volume. In my case, it is just inside my harddisk.
https://kubernetes.io/docs/concepts/storage/storage-classes/#local
https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/
https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#create-a-persistentvolume

You will find the nginx-ingress-controller does not expose external IP, it is because the service type is LoadBalancer and the list of supporting lb are
https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer

You are recommendeded to install metallb, it is load balancer for bare-metal cluster.
https://metallb.universe.tf/installation/#installation-with-kubernetes-manifests
https://metallb.universe.tf/configuration/#layer-2-configuration

**Comment by salaboy** [comment]
related to https://github.com/Activiti/Activiti/issues/2518
