### ISSUE TITLE
intermittent helm publish errors

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2528]
Sometimes see `Merge conflict in index.yaml` in the pipelines, especially when example repos build in parallel. An example is http://jenkins.jx.35.228.195.195.nip.io/job/Activiti/job/example-cloud-connector/job/master/5/console

Looks like we tried to [lessen the problem with by doing 5 retries ](https://github.com/Activiti/example-cloud-connector/blob/master/Jenkinsfile#L82) but sometimes it just fails 5 times (as in the case above).

I think this is because the examples are all having their charts published to the same activiti-cloud-helm-charts repo so there can be parallel updates there, resulting in conflicts when its index.yaml file is updated.

**Comment by almerico** [comment]
@ryandawsonuk yes looks like 5 times repeat doesn't help here

**Comment by almerico** [comment]
found easy workaround will go through all repos and will fix.

**Comment by almerico** [comment]
part of https://github.com/Activiti/Activiti/issues/2528

**Comment by ryandawsonuk** [comment]
Oh I see. So presumably the retries were only failing because they were trying to redo the clone and the directory already existed?

**Comment by almerico** [comment]
Fixed. Looks like now it is working as expected.
