### ISSUE TITLE
[Modeling] Deal with names vs UUIDs in connectors and variable mappings

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#2529]
Currently we use UUIDs to define variable mappings and to reference connector implementations on service tasks. It's ok when you are using the modeler to create the mappings but it makes the work of creating the mappings very painful.

**Example of mapping based on UUIDs:**

```
"mappings": {
      "Task_1xqe2ob": {
        "inputs": {
          "movieNameId": {
            "type": "variable",
            "value": "35c54866-e134-4b9d-9d82-54e2052989f7"
          }
        },
        "outputs": {
          "0eac1bbd-2612-42cc-8e4a-0425cf273d4f": {
            "type": "variable",
            "value": "movieDescriptionId"
          }
        }
      }
    }
```

Related input variable:
```
"35c54866-e134-4b9d-9d82-54e2052989f7": {
        "id": "35c54866-e134-4b9d-9d82-54e2052989f7",
        "name": "movieToRank",
        "type": "string",
        "required": true,
        "value": ""
      }
```

Related output variable:
```
"0eac1bbd-2612-42cc-8e4a-0425cf273d4f": {
        "id": "0eac1bbd-2612-42cc-8e4a-0425cf273d4f",
        "name": "movieDesc",
        "type": "string",
        "required": false,
        "value": ""
      }
```

**What it would be nice to have** is something like (note the task uuid was replaced by task name as well):
```
"mappings": {
      "Add Rating": {
        "inputs": {
          "movieName": {
            "type": "variable",
            "value": "movieToRank"
          }
        },
        "outputs": {
          "movieDesc": {
            "type": "variable",
            "value": "movieDescription"
          }
        }
      }
    }
```

Another points where it might be better to don't use UUIDs is reference to connector implementation in bpm file:
`implementation="connector-8abc839468e609ca0168e61babb60005.getMovieDescId"` --> `implementation="Movies.getMovieDesc"`

**Comment by balsarori** [comment]
Totally agree with this.

**Comment by magemello** [comment]
If we do this, are we going also to avoid to look up in the connector definitions for the mapping?

**Comment by erdemedeiros** [comment]
Currently we are using connector input variables as entry point https://github.com/Activiti/Activiti/blob/develop/activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/connector/InboundVariablesProvider.java#L41, https://github.com/Activiti/Activiti/blob/develop/activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/connector/InboundVariableValueProvider.java. If we go with names only and we assume that we don't need to validate mapping against the declared connector inputs, we could just set the variables defined in the mapping and send them to the connectors (without looking inside connector definition). However that means we can eventually send more variables than the ones defined in the connector (if the mapping is wrong for some reason). By the way, I'm not sure we are handling the `required` property right now.

**Comment by magemello** [comment]
Understood, so we still need to look in the connector definition for the filtering...

**Comment by CTI777** [comment]
This is what we have now:
```
    "mappings": {
      "Task_1xqe2ob": {
        "inputs": {
          "movieNameId": {
            "type": "variable",
            "value": "35c54866-e134-4b9d-9d82-54e2052989f7"
          }
        },
        "outputs": {
          "0eac1bbd-2612-42cc-8e4a-0425cf273d4f": {
            "type": "variable",
            "value": "movieDescriptionId"
          }
        }
      }
    }
```

This is what we want to have:

```
"mappings": {
      "Task_1xqe2ob": {
        "inputs": {
          "movieName": {
            "type": "variable",
            "value": "movieToRank"
          }
        },
        "outputs": {
          "movieDesc": {
            "type": "variable",
            "value": "movieDescription"
          }
        }
      }
    }
```

**Comment by CTI777** [comment]
@salaboy @erdemedeiros 
I hope that this set of PR's cover all cases... When modeler will be ready (as I understand - soon) we may add any other test cases...
