### ISSUE TITLE
Docs: Creating BPMN supported Elements for Cloud Native approach

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2534]
We need a section with the whole list of supported BPMN elements and the comparison with the Activiti 6.x approach.

**Comment by Claireedenton** [comment]
Linked to JIRA https://issues.alfresco.com/jira/browse/ACTIVITI-3099

**Comment by salaboy** [comment]
Initial work done here: https://activiti.gitbook.io/activiti-7-developers-guide/overview/bpmn
It will be nice to have some kind of table with all the available elements in the spec and checks for the ones that are covered.
