### ISSUE TITLE
java8 backward compatibility

### ISSUE THREAD

**Issue by almerico** [Activiti/Activiti#2541]

**Comment by almerico** [comment]
https://github.com/Activiti/activiti-cloud-audit-service/pull/141

**Comment by almerico** [comment]
https://github.com/Activiti/activiti-cloud-runtime-bundle-service/pull/250

**Comment by almerico** [comment]
https://github.com/Activiti/activiti-cloud-build/pull/83

**Comment by almerico** [comment]
https://github.com/Activiti/activiti-build/pull/49

**Comment by salaboy** [comment]
applied to 7.0.x waiting for confirmation to close
