### ISSUE TITLE
run 7.0.x pipeline

### ISSUE THREAD

**Issue by almerico** [Activiti/Activiti#2547]

**Comment by ryandawsonuk** [comment]
Currently blocked on this as needs https://github.com/jenkins-x/updatebot/pull/73

**Comment by salaboy** [comment]
@almerico @ryandawsonuk was this solved already?

**Comment by ryandawsonuk** [comment]
No https://github.com/jenkins-x/updatebot/pull/73 is still open

**Comment by ryandawsonuk** [comment]
The updatebot PR has now been merged. But to get the update we'll need to upgrade to a new JX version. (After a cluster upgrade we'd then need to re-enable the 7.0.x branches for scanning in the Jenkins console.) Seems to me it would be good if https://github.com/Activiti/Activiti/issues/2553 could be tackled at the same time but that one is waiting on a different (still open) JX issue.

**Comment by almerico** [comment]
@ryandawsonuk I think maven11 image upgrade is enough

**Comment by ryandawsonuk** [comment]
Oh that would be cool. Unfortunately seems [new version of it has not yet been published](https://hub.docker.com/r/jenkinsxio/builder-maven) as last one is from yesterday, which is before updatebot PR was merged

**Comment by salaboy** [comment]
@almerico @ryandawsonuk what is the status of this?

**Comment by ryandawsonuk** [comment]
There are no new[ builder-maven-java11](https://hub.docker.com/r/jenkinsxio/builder-maven-java11) and all the new [builder-maven](https://hub.docker.com/r/jenkinsxio/builder-maven) images are snapshots that seem to relate to particular PRs. I can't see any version that we can point to so still waiting for the JX guys,.

**Comment by ryandawsonuk** [comment]
@almerico has pointed out that JX have moved their docker images to GCR :)

**Comment by salaboy** [comment]
@almerico can you close this if this is done?

**Comment by almerico** [comment]
Done
