### ISSUE TITLE
Replace @Lob annotation with TEXT column definition everywhere in audit service

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#2554]
`@Lob` annotation makes query very slow, see https://github.com/Activiti/activiti-cloud-query-service/issues/105 for more details. Currently `@Lob` annotation is widely used in audit-service, it should be replaced by TEXT column definition instead. Note that this will break the database schema from previous versions (`7.0.0.GA`).

**Comment by igdianov** [comment]
@CTI777 Here are the implementation details to replace `@Lob` annotation: 5ab3a8c6dacb47bdc27e2b514b45ddddb5d0cc6b

**Comment by igdianov** [comment]
Modeling Service JPA Entity Models also use `@Lob` annotation to store content: https://github.com/Activiti/activiti-cloud-org-service/blob/b00bacba455ba6b8cfd4bbc26883de22a80e22bb/activiti-cloud-services-org/activiti-cloud-services-org-jpa/src/main/java/org/activiti/cloud/services/organization/entity/ModelVersionEntity.java#L58
