### ISSUE TITLE
Notification Service GraphQL URL is fixed to one audit in its URL

### ISSUE THREAD

**Issue by doug4j** [Activiti/Activiti#2564]
Unlike other URLs in the system where can be dynamic per app and connected throughout the architecture, this capability is coded to a single URL (and thus app):  PROTOCOL}://activiti-cloud-gateway.{DOMAIN}/graphiql 

This will cause unexpected results when more than one app is used. 
Remediation for now: limit Notification Service to one application for GraphQL

**Comment by igdianov** [comment]
Duplicate of  https://github.com/Activiti/Activiti/issues/2543. This is already fixed in https://github.com/Activiti/activiti-cloud-notifications-service-graphql/pull/21 and tagged for SR1

**Comment by salaboy** [comment]
closing as duplicate

**Comment by salaboy** [comment]
cherry-picked to 7.0.x
