### ISSUE TITLE
Publish sources jars for internal releases

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#2565]
Currently related `-sources.jar` is not being published for internal releases.

**Comment by ryandawsonuk** [comment]
I think this is now included - see https://artifacts.alfresco.com/nexus/content/repositories/activiti-releases/org/activiti/api/activiti-api-task-model-impl/7.0.88/

I suspect it was because of https://github.com/jenkins-x/jenkins-x-builders/issues/236
