### ISSUE TITLE
the last activiti version spport by jdk8

### ISSUE THREAD

**Issue by mataoqun** [Activiti/Activiti#2568]
Hello, what is the last activiti version supported by jdk8?
and 
When is the custom process service released?

**Comment by salaboy** [comment]
@mataoqun hi there. The 7.1.x release train will support JDK8 and also 7.0.0.SR1 that will be release shortly (this or next week) will support JDK8, JDK9, JDK10 and JDK11. 

I am not sure to understand what this means:
"When is the custom process service released?"

Can you please elaborate?

**Comment by mataoqun** [comment]
Hello, I am referring to activiti UI

**Comment by salaboy** [comment]
We are re architecting the UI and that will come in further releases, for now we are releasing the new Activiti Modeler app: 
https://activiti.gitbook.io/activiti-7-developers-guide/components/activiti-cloud-modeling

We are aiming to provide ADF components for Activiti Cloud: https://www.alfresco.com/abn/adf/docs/release-notes/relnote300/

so you can build your own applications with such components.
