### ISSUE TITLE
Fix support for Spring Boot 2.0.8 

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2569]
Using Activiti Core in Spring Boot 2.0.8 breaks due some auto configuration classes that are only present in Spring Boot 2.1.x . By fixing this AutoConfigurations we can support both.

**Comment by ryandawsonuk** [comment]
Is this https://github.com/Activiti/Activiti/commit/5bf2e1e6cc2828ea7181b7974492a002fb084c8c or something further?

**Comment by salaboy** [comment]
that's it.. let's close this one..
