### ISSUE TITLE
Can activiti support task query use regular matching of group?

### ISSUE THREAD

**Issue by yangpancode** [Activiti/Activiti#2580]
In some scenes，the user‘s group is group_01. He can process the data of the child groups like group_01_01 and group_01_02.......
Can activiti support task query use regular matching of group?

**Comment by ryandawsonuk** [comment]
It depends which version you are using and how you are using it.

If you are using the engine embedded in your app and you are using spring then there is an example of supplying your own code that dynamically resolves the groups. So in your process definition you can have an expression that refers to logic to get the groups:

https://github.com/Activiti/Activiti/blob/c8666252c669d89f2c6d7063e4a89aadf6b73175/activiti-spring/src/test/resources/org/activiti/spring/test/taskassignment/CustomTaskAssignmentTest.testSetCandidateUsersThroughSpringService.bpmn20.xml#L13

Which can have any logic you want:

https://github.com/Activiti/Activiti/blob/c8666252c669d89f2c6d7063e4a89aadf6b73175/activiti-spring/src/test/java/org/activiti/spring/test/taskassignment/FakeLdapService.java#L30

And your task queries should then return tasks in line with your assignment logic:

https://github.com/Activiti/Activiti/blob/c8666252c669d89f2c6d7063e4a89aadf6b73175/activiti-spring/src/test/java/org/activiti/spring/test/taskassignment/CustomTaskAssignmentTest.java#L33

There is also a non-spring example which instead uses a listener:
https://github.com/Activiti/Activiti/blob/c8666252c669d89f2c6d7063e4a89aadf6b73175/activiti-engine/src/test/resources/org/activiti/examples/bpmn/tasklistener/CustomTaskAssignmentTest.testCandidateGroupAssignment.bpmn20.xml#L18
https://github.com/Activiti/Activiti/blob/c8666252c669d89f2c6d7063e4a89aadf6b73175/activiti-engine/src/test/java/org/activiti/examples/bpmn/tasklistener/CandidateGroupAssignment.java
https://github.com/Activiti/Activiti/blob/c8666252c669d89f2c6d7063e4a89aadf6b73175/activiti-engine/src/test/java/org/activiti/examples/bpmn/tasklistener/CustomTaskAssignmentTest.java

If you are using cloud then I'd expect either approach to work in a runtime bundle but not entirely sure if the first would work in the query component as I'm not sure if we're currently resolving the candidate users and groups before sending the runtime event to query. Would be good to check that.

**Comment by ryandawsonuk** [comment]
Actually if it were v7 and/or cloud a better way would be plugging in a custom user group manager implementation. OOTB impl for core is:

https://github.com/Activiti/activiti-core-common/blob/65e2bc1655191fbd9a3db107c58c7f9d931df3ca/activiti-spring-identity/src/main/java/org/activiti/core/common/spring/identity/ActivitiUserGroupManagerImpl.java#L21

And for cloud see:

https://github.com/Activiti/activiti-cloud-service-common/tree/f2cf379b16e582e77713f146fdcbe24b152aace0/activiti-cloud-services-common-identity-keycloak
https://github.com/Activiti/activiti-cloud-service-common/blob/f2cf379b16e582e77713f146fdcbe24b152aace0/activiti-cloud-services-common-identity-keycloak/src/main/java/org/activiti/cloud/services/identity/keycloak/KeycloakUserGroupManager.java
