### ISSUE TITLE
Postgres condition name mismatch in activiti-cloud-charts/application/requirements.yaml

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2581]
The application/requirement.yaml uses `postgres.enabled` condition:
https://github.com/Activiti/activiti-cloud-charts/blob/7f06387cceb8f17c5c4030a1fe19e761ed1d3ffc/application/requirements.yaml#L19
vs. runtime-bundle/values.yaml uses `postgres.enable` value key: https://github.com/Activiti/activiti-cloud-charts/blob/7f06387cceb8f17c5c4030a1fe19e761ed1d3ffc/runtime-bundle/values.yaml#L36

This is causes Postgres instance to be always deployed.

**Comment by ryandawsonuk** [comment]
ah so `enabled` vs `enable` - yeah looks like a typo

**Comment by ryandawsonuk** [comment]
I would say enabled is clearer. Also https://github.com/helm/charts/search?q=enabled&unscoped_q=enabled wins vs https://github.com/helm/charts/search?q=enable&unscoped_q=enable

**Comment by almerico** [comment]
https://github.com/Activiti/activiti-cloud-charts/pull/59
