### ISSUE TITLE
Activiti-cloud-example-chart-modeling pipeline error (recurring)

### ISSUE THREAD

**Issue by miguelruizdev** [Activiti/Activiti#2586]
![image](https://user-images.githubusercontent.com/32025234/53584050-a910a500-3b7a-11e9-966c-f4b95820bcd4.png)

This recurrent error seems to be due to a race condition between different pipelines, with the current pipeline trying to use a version that has not been published at that point.

This is error in jenkins-x:
![image](https://user-images.githubusercontent.com/32025234/53584167-f4c34e80-3b7a-11e9-9159-8cc0e0cdde41.png)

**Comment by ryandawsonuk** [comment]
The push comes from https://github.com/Activiti/activiti-cloud-modeling/blob/master/.updatebot.yml
So the sleep added in the referenced PR should prevent this in future

**Comment by ryandawsonuk** [comment]
This seems to be resolved now
