### ISSUE TITLE
[Core] Task completed - The owner cannot complete a task if is not assigned

### ISSUE THREAD

**Issue by miguelruizdev** [Activiti/Activiti#2593]
In the previous activiti engine it was possible for the owner of the task to complete it even when the task was not assigned (hence the owner was not the assignee). 

Trying to do so now will result in the error: **Task is not claimed**

This example illustrates a the problematic scenario:

- User1 creates a task and select  user2 as assignee
- User2 unclaims the task

Who should be able to complete the task?
Given the current state of things, no one.

Issue originally raised by @mauriziovitale here: https://issues.alfresco.com/jira/browse/ACTIVITI-2731

**Comment by miguelruizdev** [comment]
As long as we can find a reason why this is the current behavior, we can keep it.
But the issue has a point.
The weak point of this current behavior is about **visibility**.
Problematic use cases:

- If the task is no visible to anyone (does not have user candidates or groups other than the original assignee), no one will be able to see that there's an unclaimed task.
- If the task is assigned to someone, and that person stops working (temporarily or forever), the tasks is blocked, and no ond can handle it

@salaboy any thoughts in the action that is needed here?

**Comment by miguelruizdev** [comment]
This is the commit that changes the old behavior of the engine:
https://github.com/Activiti/Activiti/pull/1959/files#diff-2ea375b6fa67abeb2b92eef94bb6bdb6R157
Prior to that there was no check on who could or could not complete a task.

Maybe this can help us cast some light on this.

**Comment by salaboy** [comment]
@miguelruizdev we are still not covering owner use cases, so for now the answer is "Is not supported yet" For now the only one how can "work" on a task is the assignee or an ADMIN.

**Comment by miguelruizdev** [comment]
Should we leave this issue open so that we can track this or is there any other way to specify future use case coverage?

**Comment by salaboy** [comment]
@miguelruizdev yes totally.. we need to cover owner use cases

**Comment by CTI777** [comment]
At least to allow an owner to complete a task (not assigned) could be useful...
