### ISSUE TITLE
need a retry block around updatebot push-version commands

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2599]
Because we can have brief github connectivity problems. See https://github.com/Activiti/activiti-cloud-application-chart/pull/139#issuecomment-469334644

Similar to https://github.com/Activiti/Activiti/issues/2587 but in that case you don't actually get an error. For this case we do get an error (commonly 'Failed to retrieve' or 'socket closed') so we need a retry like https://github.com/Activiti/example-runtime-bundle/commit/a5fac08014681bc0e32a55ee79eb198b284812a3 - this really applies to all github operations but updatebot does several things in one so is more intensive

**Comment by ryandawsonuk** [comment]
Got this in most places now but could do with adding it to connector at service layer and to cloud-dependencies

**Comment by salaboy** [comment]
@ryandawsonuk what is the status of this issue? I can see one open PR still..

**Comment by ryandawsonuk** [comment]
Last one is now merged
