### ISSUE TITLE
activiti-scripts to support activiti-cloud.version

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2600]
Currently seeing this in a build of acceptance-scenarios from 7.0.x branch:

![image](https://user-images.githubusercontent.com/22754674/53750971-1a19ca80-3ea3-11e9-854e-5c98b72dec0e.png)

That should've been replaced but it wasn't - the problem is this format:

https://github.com/Activiti/activiti-cloud-acceptance-scenarios/blob/master/pom.xml#L41

The release script doesn't know to replace that property name because it isn't a repo name. Other projects use property names that match repo names e.g.:

https://github.com/Activiti/example-runtime-bundle/blob/master/pom.xml

It is likely this is a long-standing issue that hasn't made a difference until now as we we just tag the scenarios during the release process. It seems it is [present in the GA tag](https://github.com/Activiti/activiti-cloud-acceptance-scenarios/blob/7.0.0.GA/pom.xml#L41) there.

We should look at making activiti-scripts more flexible on this. Note that in doing so if we change [EXTRA_SED](https://github.com/Activiti/activiti-scripts) then we need to change references to it in bamboo jobs too. Anything we do should be tested in bamboo as a sed that works locally may not work in the bamboo agent.

**Comment by ryandawsonuk** [comment]
Temporary workaround on this is https://github.com/Activiti/activiti-cloud-acceptance-scenarios/commit/8c5418c67adbbe07f0ed076ea3127a83984ff98b
and 98ecb660e84ee5eefecaf8f1cba21984e4fbd048

For 7.0.x https://github.com/Activiti/activiti-cloud-acceptance-scenarios/commit/c321d9f8a14ac915bc765c17aa78c3ddab76dede and https://github.com/Activiti/activiti-cloud-acceptance-scenarios/commit/18df43ec0637f4b8ca0e1e94055080329b1fa146

**Comment by ryandawsonuk** [comment]
To do something truly general like replacing all `activiti*.version` elements would be a change to the approach that we take with the sed. Currently we match the whole element so we need to specify the element to [replace with as well as the target element](https://github.com/Activiti/activiti-scripts/blob/master/update-pom-version.sh#L41). To change that we'd need a regex that matches just the value inside the tag - so a number pattern preceded and followed by the element pattern.

We could add add activiti-cloud-version to the EXTRA_SED list but that is already quite a long list.

**Comment by salaboy** [comment]
@ryandawsonuk what is status of this issue?

**Comment by ryandawsonuk** [comment]
Currently the name used for a property referencing an activiti artifact in a pom file has to either match an activiti git repository name or an item in EXTRA_SED. So `activiti-cloud.version` is not covered.

**Comment by ryandawsonuk** [comment]
Actually I think we could use this regex - `(version\>.*?\<\/activiti)`:

![image](https://user-images.githubusercontent.com/22754674/54522985-61559000-4966-11e9-99c4-4a6cb2409c03.png)

So the current project-specific sed of `s@<${REPO}.version>.*</${REPO}.version>@<${REPO}.version>${NEXT_VERSION}</${REPO}.version>@g` 

could be replaced or supplemented a more general `s@version>.*</activiti@version>${NEXT_VERSION}</activiti@g`

**Comment by ryandawsonuk** [comment]
PR merged and bamboo now updated
