### ISSUE TITLE
[Cherry Pick] Patch to maven prop name in acc scenarios

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2601]
See https://github.com/Activiti/Activiti/issues/2600#issuecomment-469348482 - it explains and references the commits and the cherry-picks

**Comment by salaboy** [comment]
@ryandawsonuk was this done for SR1?

**Comment by salaboy** [comment]
can  you please close this?

**Comment by ryandawsonuk** [comment]
Yeah this was done, the cherry-picks are in the linked comment
