### ISSUE TITLE
apache-shiro  realm  doGetAuthorizationInfo多次认证导致数据库请求频繁

### ISSUE THREAD

**Issue by zhaogituser** [Activiti/Activiti#2602]
use “@RequiresPermissions “  标签来控制URL 权限， 可是realm 认证中 需要每次请求数据库，无疑增加数据库访问， 且有的页面不只一个  URL     。请教 你们如何来实现 。

**Comment by ryandawsonuk** [comment]
Please specify which activiti version you are trying to use and what it is about the question that is specific to activiti.

Do note that in activiti 7 there is out of the box support for spring security (which supports requiring a role for accessing a method) when embedding activiti in your app (activiti core) and for keycloak with activiti cloud (which supports requiring a role for accessing a URL)
