### ISSUE TITLE
[Infrastructure] modeling UI path to backend var change

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2605]
See https://github.com/Activiti/activiti-modeling-app/pull/74

Unfortunately the PR is a breaking change in the modeling-app docker image and was submitted after we'd already started the 7.0.0.SR1 release process so it's not included in those tags or images. However it was a blocking issue for the UI guys so it is now in the internal images and the internal charts were changed to support it.

Current situation therefore is that public-facing and internal-facing charts need to be different. Currently the public-facing charts still point at 7.0.0.GA but pointing at 7.0.0.SR1 won't change this situation as the change missed the cutoff.

**Comment by ryandawsonuk** [comment]
@salaboy you'll want to be aware of this

**Comment by salaboy** [comment]
@ryandawsonuk @popovicsandras  not sure to follow.. why the PR was merged if that was breaking the charts? what do you mean exactly by "it was a blocking issue for the UI guys". That usually is not a reason to merge stuff. We are the gatekeepers for merges to make sure that we don't end up in situations where external releases gets broken. It sounds like again, we don't have the right place or control over this repo that keeps getting in the middle of releases. We need to fix this process for 7.1 M1 at the end of the month. so I will mark this as high risk

**Comment by Claireedenton** [comment]
Linked to JIRA https://issues.alfresco.com/jira/browse/ACTIVITI-3094

**Comment by erdemedeiros** [comment]
Covered here https://github.com/Activiti/activiti-cloud-modeling/commit/e62ac9cf539b3ef9ea25d4346986359bead456b9
