### ISSUE TITLE
[Infrastructure] Upgrade Spring Boot and Spring Cloud to Greenwich SR2

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2616]
https://github.com/spring-projects/spring-cloud/wiki/Spring-Cloud-Greenwich-Release-Notes

https://spring.io/projects/spring-cloud

**Comment by Claireedenton** [comment]
Linked to JIRA https://issues.alfresco.com/jira/browse/ACTIVITI-3093

**Comment by erdemedeiros** [comment]
- Spring boot: 2.1.6.RELEASE
- Spring cloud: Greenwich.SR2
