### ISSUE TITLE
Enhance installation support in activiti cloud for external postgres

### ISSUE THREAD

**Issue by fourier134949** [Activiti/Activiti#2617]
The activiti-cloud-full-example chart of activiti cloud 7.0 GA allows to skip the postgres installation by specifying  the following snippet in values.yaml :

application:
   postgres:
       enabled: false

That way we can use a 3rd party provided postgres instance.
However if we disable the installation and if we try to use an external postgres instance, we are not able to deploy  runtime-bundle successfully, because the deployment.yaml of runtime-bundle has this initContainers section:

    {{- if or .Values.postgres.enable .Values.extraInitContainers }}
      initContainers:
      {{- if .Values.postgres.enable }}
        - name: wait-for-postgresql
          image: "{{ .Values.init.image.repository }}:{{ .Values.init.image.tag }}"
          imagePullPolicy: {{ .Values.init.image.pullPolicy }}
          command:
            - sh
            - -c
            - |
              until printf "." && nc -z -w 2 {{ .Release.Name }}-{{ .Values.postgres.name }} {{ .Values.postgres.port }}; do
                  sleep 2;
              done;

              echo 'PostgreSQL OK ✓'
      {{- end }}
      {{- if .Values.extraInitContainers }}

The init container script assumes that the check must be performed on the activiti-provided postgres instance and this is wrong in case we use another instance of postgres.

**Comment by salaboy** [comment]
@fourier134949 first of all you rock for raising this issue. 
@ryandawsonuk @almerico can you guys take a look at this one.. this might be a low hanging fruit that is easy to fix and bring a lot of value.

**Comment by ryandawsonuk** [comment]
Looks like the `enable` vs `enabled` discrepancy raised https://github.com/Activiti/Activiti/issues/2581

**Comment by ryandawsonuk** [comment]
Following

https://github.com/Activiti/activiti-cloud-charts/commit/bb37c0779b93c6ceff6129e899795659af845a95

[published as 1.1.10 of the full example](https://github.com/Activiti/activiti-cloud-charts/commit/88463bd4415680fac6f4fb1a03663e5f80214622), it should now work with

```
application:
  postgres:
     enabled: false
runtime-bundle:
  postgres:
     enabled: false
```

**Comment by salaboy** [comment]
@ryandawsonuk should we close this one then?

**Comment by ryandawsonuk** [comment]
It might be nice to bring it [under a single condition as we have for keycloak](https://github.com/Activiti/activiti-cloud-charts/blob/master/runtime-bundle/templates/deployment.yaml#L71) but that could be a separate item so yeah - closing this now.
