### ISSUE TITLE
maven build pods need renaming in Jenkinsfiles

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2620]
Our maven build pods are called `maven-java11`:

![image](https://user-images.githubusercontent.com/22754674/54028392-ba6e3880-419c-11e9-88fe-ffdd45df4d26.png)

and this is[ referenced in our Jenkinsfiles](https://github.com/Activiti/ttc-rb-english-campaign/blob/master/Jenkinsfile#L6)

The [JX guys have recently renamed this](https://github.com/jenkins-x/jenkins-x-platform/commit/3784c16457b194e536d200ed86a168ec6f3328d6). We can simply change the name in our cluster configuration for internal builds but we tell people to fork our projects for [ttc-workshop](https://github.com/Activiti/ttc-docs) so @ouyangshixiong is now encountering issues with this as his new cluster has:

![image](https://user-images.githubusercontent.com/22754674/54028518-25b80a80-419d-11e9-9efd-4283c8e3774a.png)

Interestingly the error encountered was `‘Jenkins’ doesn’t have label ‘maven-dind’` but the actual problem turned out to be that ‘maven-dind’ was trying to inherit from a build pod template whose name didn't match in that cluster

I think it will also affect quickstarts - https://github.com/Activiti/activiti-cloud-connector-quickstart/blob/master/Jenkinsfile#L3

**Comment by salaboy** [comment]
@ryandawsonuk this sounds like a low hanging fruit that can be solved now :)

**Comment by ryandawsonuk** [comment]
Interestingly this doesn't affect the quickstarts. I created a new cluster and was able to get the quickstarts building fine. Yet the new cluster does indeed have the pod template name matching that reported by @ouyangshixiong

![image](https://user-images.githubusercontent.com/22754674/54430561-e1d48080-471b-11e9-936a-b161f8c2cba6.png)

But renaming did resolve the problem faced by @ouyangshixiong:

![image](https://user-images.githubusercontent.com/22754674/54430746-6d4e1180-471c-11e9-8456-e560c3a977b6.png)

So it must be that the problem only affects [`inheritFrom` used for dind configurations](https://github.com/Activiti/ttc-rb-english-campaign/blob/master/Jenkinsfile#L7)

This means we don't need to change quickstarts. But we do need to change all the other projects that build docker images (and change all of them at once) and also change the pod template in the jx admin console.

**Comment by ryandawsonuk** [comment]
Also when we do this it will need to be changed in or cherry-picked to the 7.0.x branches or it would break the 7.0.x pipelines, [when we have those running](https://github.com/Activiti/Activiti/issues/2547)

**Comment by ryandawsonuk** [comment]
The remaining part of this is the cherry-picking

**Comment by ryandawsonuk** [comment]
Now the commits are also cherry-picked to the 7.0.x branches.

**Comment by ryandawsonuk** [comment]
We're seeing builds get stuck waiting for agents on the examples cluster. Had to put the pod template back to `maven-java11` in order to get the builds running. So this seems to need a bit more work.

**Comment by ryandawsonuk** [comment]
It seems the `maven` template is applied correctly to master branch but PRs still look for `maven-java11`, even though that isn't in the Jenkinsfile (not for master or the branch).

I suspect upgrading the cluster would resolve this but that would take a while so for now what I'm doing is simply duplicating the whole kubernetes build pod template.

**Comment by salaboy** [comment]
@almerico I will close this.. but please feel free to re-open if this is still an issue

**Comment by ouyangshixiong** [comment]
@ryandawsonuk  Thank you for your had work. 
There are much much more problems using Jenkin X with activiti cloud, anyway it can work. 
Because Jenkins X always made the k8s cluster running in high IO situation. So I had to fall back to use activiti core + springboot to build my applications. Until now, All applications works file :)

**Comment by salaboy** [comment]
@ouyangshixiong thanks a lot for your feedback. Some of this would be very valuable for the JenkinsX project. I believe that they have built something that is pluggable, so most of the issues you mention can be fixed (custom docker registry, other git providers, etc). 
We are currently working hard to improve the modeler experience, at this stage is early access, so feedback is more than welcome.

**Comment by salaboy** [comment]
@ouyangshixiong feel free to get in touch and share what you use case is if you want to join the community and help other people with common problems on kubernetes will be highly appreciated.
