### ISSUE TITLE
Installing on GKE cluster helm install fails with rendering template failed

### ISSUE THREAD

**Issue by rishisinghal** [Activiti/Activiti#2623]
Following the instructions provided at https://activiti.gitbook.io/activiti-7-developers-guide/getting-started/getting-started-activiti-cloud the helm install command fails

$ helm install --name example activiti-cloud-charts/activiti-cloud-full-example --set global.gateway.domain=<ipAddressRemoved>.nip.io
2019/03/10 12:24:46 warning: destination for annotations is a table. Ignoring non-table value <nil>
2019/03/10 12:24:46 warning: destination for annotations is a table. Ignoring non-table value <nil>
2019/03/10 12:24:46 warning: destination for annotations is a table. Ignoring non-table value <nil>
2019/03/10 12:24:46 warning: destination for annotations is a table. Ignoring non-table value <nil>
2019/03/10 12:24:46 warning: destination for annotations is a table. Ignoring non-table value <nil>
2019/03/10 12:24:46 warning: destination for annotations is a table. Ignoring non-table value <nil>
Error: rendering template failed: runtime error: invalid memory address or nil pointer dereference

Other Details
-------------
Master version	1.11.7-gke.4
Node version	1.11.7-gke.4
Node image	Container-Optimized OS (cos)
Total size	 3
Machine type	n1-standard-2 (2 vCPUs, 7.5 GB memory)
Total cores	6 vCPUs
Total memory	22.50 GB

Please let me know if any further details are required. I am also trying to figure this out

**Comment by ryandawsonuk** [comment]
What helm version are you using? We've seen this before on older helm versions

**Comment by salaboy** [comment]
Yeah.. that is a known HELM 2.9.2 issue.. you need to upgrade your HELM version.

**Comment by rishisinghal** [comment]
I had used 2.11.0 version

$ helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

**Comment by ryandawsonuk** [comment]
Are you able to upgrade to the latest version and try again?

**Comment by rishisinghal** [comment]
$ helm init --upgrade
$HELM_HOME has been configured at /Users/rishisinghal/.helm.

Tiller (the Helm server-side component) has been upgraded to the current version.
Happy Helming!
$ helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

**Comment by rishisinghal** [comment]
Upgrading to v2.13.0 worked. Thanks for the help

$ helm version
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}

**Comment by salaboy** [comment]
@rishisinghal good to hear.. we lost a couple of days on that one as well. It deserves a tweet.
