### ISSUE TITLE
[Acceptance Tests] Move reusable modeling steps from activiti-cloud-acceptance-scenarios to activiti-cloud-acceptance-tests repository

### ISSUE THREAD

**Issue by constantin-ciobotaru** [Activiti/Activiti#2624]

**Comment by salaboy** [comment]
@constantin-ciobotaru that will be really useful.. we need to unify how we create steps. Is there any chance that you can work on this before the end of this milestone? (7th april?)

**Comment by miguelruizdev** [comment]
@constantin-ciobotaru is there any criteria by which we should pick the reusable steps, or should we move them all in the same fashion runtime test are?

**Comment by constantin-ciobotaru** [comment]
@miguelruizdev I think we can move all of them
