### ISSUE TITLE
[Modeling] enable BPMN Signal Events

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2630]
related to backend task #2272 

@popovicsandras we need to enable the BPMN Signal elements and properties. 
You can discuss with @erdemedeiros about which properties are needed for the first cut. Please guys get together to understand what is needed from the FrontEnd, @erdemedeiros first make sure that you understand the backend work that needs to be done, so the scope is clear. 

Please create this feature as a PR so we can decide when to merge. 

This is a blocker for 7.1.0.M1 release.

**Comment by salaboy** [comment]
The name of the signal elements is missing, making it impossible to use for a real example. We need to add the name property to the signal xml tag and enable the user to change the name as they wish

**Comment by salaboy** [comment]
The image shows a process with a start signal with a generated ID, which doesn't make any business sense. 

<img width="1357" alt="Screenshot 2019-04-24 at 08 59 30" src="https://user-images.githubusercontent.com/271966/56642440-554ca480-666f-11e9-9596-c3a600fc6d9a.png">

And in the XML the ID and the Name are the same:

<img width="951" alt="Screenshot 2019-04-24 at 09 00 18" src="https://user-images.githubusercontent.com/271966/56642496-71e8dc80-666f-11e9-93c4-81e026770ada.png">

Without this change we cannot use the signal elements. The name must be editable

**Comment by popovicsandras** [comment]
Thanks for the feedback, we are on it.

**Comment by salaboy** [comment]
signal with names done and merged in master
