### ISSUE TITLE
[BPMN] Add Support for BPMN Timer elements

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2636]
we need to define which timer scenarios we will support for the first iteration this includes
- Define conformance tests in spring-boot-starter
- Define default value for local job executor (enabled for timers only and not for async tasks)
- Define acceptance tests to validate correct behaviour
- Enable elements in BPMN modeler
   - Define which properties are needed

**Comment by igdianov** [comment]
@salaboy I think it will make sense to use message based job manager for timer jobs. Also, we can port  existing bpmn timer tests in Activiti Core to Activiti Cloud to validate the execution and behaviors of timers with audit events. 

In addition to you task list, we also need to define timer audit event apis.

**Comment by igdianov** [comment]
There is already PR https://github.com/Activiti/activiti-cloud-runtime-bundle-service/pull/188 that enables Async Executor in Rb and configures Message Based Job Manager to distribute jobs execution. I wlll start adding tests with timers. 

We also need to create and implement Timer Events in activiti-api and activiti-cloud-api to be able to emit timer and job events from Rb.

**Comment by CTI777** [comment]
@salaboy @erdemedeiros @igdianov 
I have prepared a test version for handling TIMER_FIRED and TIMER_SCHEDULED events...
Only API and activiti-core modules are affected currently
Please take a look once...
If this is more or less OK I can do Cloud part as well...
