### ISSUE TITLE
[Modeling] Model validation passes even for invalid content

### ISSUE THREAD

**Issue by roxanaspatariu** [Activiti/Activiti#2639]
Steps to reproduce:
- validate a invalid process content of type "text/plain" and return code is 204
- currently all validations pass even thought the content is invalid

**Comment by salaboy** [comment]
@roxanaspatariu @constantin-ciobotaru is this fixed already? 
I can see a PR merged.. @constantin-ciobotaru can you please closed if this is validated already?

**Comment by constantin-ciobotaru** [comment]
Done by https://github.com/Activiti/activiti-cloud-org-service/pull/199
