### ISSUE TITLE
versions in process definition xml

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2640]
There are some references online to `activiti:versionTag` but if you search this repo for `versionTag` you don't see any implementation code referencing it or any tests making use of versions at the XML level. There are versions generated at the time of deployment in the database but I can't find anything that could be set at design time.

@balsarori are you aware of anything?

**Comment by balsarori** [comment]
@ryandawsonuk no I'm not aware of that.

**Comment by balsarori** [comment]
A quick search in github https://github.com/search?q=org%3AActiviti+versionTag&type=Code

I'm not sure what's that for but my guess it's just meta-data.

**Comment by ryandawsonuk** [comment]
Yeah seems to be supported by modeler but currently not used in the engine.

**Comment by salaboy** [comment]
the impact of versioning all these in the DB will cause us a huge pain.. we need to design a proper solution

**Comment by magemello** [comment]
Version it's already in the db for processes

**Comment by salaboy** [comment]
Closing due no action required
