### ISSUE TITLE
add process definition version to messages

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2643]
If the message to the connector contained the process definition version then it would be possible to write connector code that decides whether a message is for that version of the connector. So then builders of connectors could decide for themselves which connector versions should handle process instances from which proc def versions.

Unfortunately I think this needs to a [proc def version](https://github.com/Activiti/Activiti/issues/2640) and not a proc def ID as you don't know the ID until after deployment and the version would need to be known at the time of writing the code.

If a connector were to decide that it shouldn't handle messages for a particular version of a process then it would be able to ignore those messages - see [content-based routing in the spring cloud streams guide](https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#_using_streamlistener_for_content_based_routing). So the code in a connector could be:
```
    @StreamListener(value = "connectorConsumer", condition = "headers['version']=='1'")
    public void receiveOld(IntegrationRequest event) {
       // handle the message
    }

    @StreamListener(value = "connectorConsumer", condition = "headers['version']!='1'")
    public void receiveNew(IntegrationRequest event) {
       // handle the message
    }
```

From the docs it seems like [partitioning using a partition key](https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#_partitioning_with_the_rabbitmq_binder) might be another option (and that goes in properties so could feasibly be set by env var) or even using the partition key to [provide a router](https://stackoverflow.com/questions/40485421/spring-cloud-stream-to-support-routing-messages-dynamically). I guess we would want to pick one and document it as the suggested approach.

**Comment by ryandawsonuk** [comment]
An alternative to the process definition version might be to use the runtime bundle version, since changes to the process definition would also be changes to the runtime bundle. And the [runtime bundle or application version can be set as an environment variable ](https://github.com/Activiti/activiti-cloud-service-common/tree/develop/activiti-cloud-services-metadata) and sent with the messages.

**Comment by salaboy** [comment]
I don't agree with this one at all.. if you add a filter hardcoded in the stream listener then it becomes a mess. 
This defeats the whole purpose of using Spring Cloud Streams where you wire things up at runtime and based on configurations. 
Also it is important to notice that moving to a FaaS approach this becomes irrelevant and part of the infrastructure.. so we might need to integrate instead of add the filters ourselves.. our components should be agnostic of this information in the source code.

**Comment by magemello** [comment]
I agree that filter on the connector would be messy, if we could use the partition key would be better. I understand the FaaS but we need also a solution for connectors as we have implementations that depends from it.

**Comment by CTI777** [comment]
@salaboy @erdemedeiros 
Just to summarize what should be done:
We need that processDefinitionVersion  is added to messages related to the connector...
After discussion with @erdemedeiros it seems that we have it already:
**The message is sent here:**
```
https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/activiti/services/connectors/IntegrationRequestSender.java#L68
```
**The message itself contains a header with processDefinitionVersion**
```
https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/activiti/services/connectors/message/IntegrationContextMessageBuilderAppender.java#L42
```
**A test is here:**
```
https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/959053856b587b831fbf176d03db93229c1e4f23/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/test/java/org/activiti/services/connectors/IntegrationRequestSenderTest.java#L198
```

**Comment by salaboy** [comment]
@CTI777 I see what you mean.. so we have all the fields inside entity.* but not in the payload itself. 
We might have a problem there.. because I can see that all the things inside payload.* besides the entity are null.. I wonder why we have those fields there.. and they are all null.

**Comment by salaboy** [comment]
I am closing this issue, as there is nothing that we need to fix there. The data is in the right place and what we need to test this features is a more complex example where the bindings for the streams use a partition key. We don't have such example right now, but there is no issue here. We might find issues when we create such example and we should link back to this at that point.

**Comment by magemello** [comment]
I'm using the following "integrationContext.processDefinitionVersion" from the IntegrationRequest object. Is it correct?

**Comment by magemello** [comment]
ok the solution at the end was to use: 
```
condition = "headers['processDefinitionVersion']==1"
```
also this would work if you have a property in the app config
```
condition = "headers['processDefinitionVersion']==${app.version}"
```

**Comment by salaboy** [comment]
@magemello we discussed about doing that and we agreed that is that not the way to go. You can inject the header in the method signature and then check inside. I would recommend evaluating that approach to not promote something that we don't want.

**Comment by salaboy** [comment]
@magemello
```
@StreamListener(Sink.INPUT)
 public void listen(String in, @Header(name = "x-death", required = false) Map<?,?> death)
```
