### ISSUE TITLE
[Core] Versioning Support Release concept by Deploying a set of related artefacts

### ISSUE THREAD

**Issue by ryandawsonuk** [Activiti/Activiti#2645]
When a new version of the process definition is deployed a new record is put in the database. Process instances for old and new versions can be live in parallel.

But we also have json files that define the variables expected for the connectors in the process definition. Could a breaking change be made to one of these json files e.g. old version of connector and process expects a certain variable values and new version expects another. Imagine moving from 'yes/no' format to 'true/false' - if these values were referenced in the json then perhaps this could be a breaking change and if so without versioning the old instances could then get stuck.

Could do with a more concrete example on this.

**Comment by magemello** [comment]
I would add also the following impacts :
- Connectors variable mapping and filtering logic needs to be update to make use of the right version of the extension file
- Process variable logic need to be update to use the right version of the extension file.

**Comment by salaboy** [comment]
the impact of versioning all these in the DB will cause us a huge pain.. we need to design a proper solution

**Comment by magemello** [comment]
Can you list what is all?
I only see process definition and extension file, wich before were in the same xml file and now we split in two so it make sense that we keep them versioned together.

**Comment by salaboy** [comment]
All means everything else besides the process definitions (connectors, variables definitions, rules, decision tables, etc..) .. So we are going from only deploying the process definition to all other descriptors. This is **wrong** and it put us in a place where we end up with runtimes that are impossible to migrate and that will not reflect the status of the source code that was used to build that version. This will limit the possibility to rollback changes and it will increase the complexity of the management of each runtime.

**Comment by magemello** [comment]
I haven't proposed to store here also the other versions...(connectors, rules, decision tables, etc..)

**Comment by CTI777** [comment]
@salaboy @erdemedeiros 
I have made a PR with a simple test to show possible solution to store process extensions inside deployment (with some changes, as discussed with @erdemedeiros).
Questions: 
1.	How will we store process extensions and connector definitions in a deployment (as a resource) or bytes?
2.	How will we separate what resource is what?
Maybe we will store resource and add a corresponding prefix to the name: 
extension_resourceName
connector_resourceName
3.	How many extension files can be connected to the process? Should we check here anything?
4.	Will it have a sense to implement first only extensions (because they are in one model with process definitions) an then connectors?

**Comment by CTI777** [comment]
@salaboy @erdemedeiros @igdianov 
Currently we have decided to load all resources to deployment and then resources should be parsed as process extension or connector...
To separate process extensions a filter '-extension.json' can be used for the file names of resources. 
For connectors we have only '.json', which is not very flexible...
The best way would be to have something like '-connector.json' in connectors file names...
Another way would be to have custom resources, having type of resource, custom resourceName and resource itself. But then we have to change 
https://github.com/Activiti/Activiti/blob/c027e7c19b4ddea821c37ab53287ff45aeecf1d6/activiti-spring/src/main/java/org/activiti/spring/autodeployment/DefaultAutoDeploymentStrategy.java#L38
and use there custom resources... 
We can save here to deployment normal Resource, as it comes, but use, for example, custom name...
What is the best way to go here?

**Comment by CTI777** [comment]
After talk with @erdemedeiros we have agreed that process extension resources will be filtered like '-connector.json'. Connector resources can be filtered like '\\connectors\\': everything which is inside connectors folder

**Comment by salaboy** [comment]
moving this to M2 because this is not ready to be merged without a larger work and including the release concept into the APIs

**Comment by salaboy** [comment]
Related to https://github.com/Activiti/Activiti/issues/2482
I will be renaming this issue to represent the exact nature of the work that needs to be done

**Comment by Claireedenton** [comment]
Linked to JIRA https://issues.alfresco.com/jira/browse/ACTIVITI-3085
