### ISSUE TITLE
Could not build and debug Activiti

### ISSUE THREAD

**Issue by AnhND35** [Activiti/Activiti#2652]
I have tried to build and debug Activity project but it did not work at all. Could you please give me some instructions about how to build this project in localhost. I have read this project and found that it is really interesting, so I want to contribute something to this project as well as customizing this project to make it adapt to my business requirements. Thanks.

**Comment by salaboy** [comment]
@AnhND35 Hi there.. sorry for the late reply. Can you please give more information about what you tried to do? 
Under the github.com/Activiti/ organization we have 88 repositories, so you will need to be more specific.
