### ISSUE TITLE
updatebot lost commits 

### ISSUE THREAD

**Issue by almerico** [Activiti/Activiti#2655]
During single pr configuration value commit is lost 
https://github.com/Activiti/activiti-cloud-dependencies/commit/bdebb343d78d9fabb308575638e476ccb2342c0e
as part of https://github.com/Activiti/activiti-cloud-dependencies/pull/336/files

details in http://jenkins.jx.35.242.205.159.nip.io/job/Activiti/job/activiti-cloud-acceptance-tests/job/develop/92/console 

Looks like git client concurrency problem during multiple simultaneous updatebot commands.

**Comment by salaboy** [comment]
@almerico what is the status of this one?

**Comment by almerico** [comment]
looks like this it can't be fixed, because we are working from different repos and rarely this can cause sync problems and they are can't be fixed easily.

**Comment by salaboy** [comment]
@almerico should we close this as no action? or. if you can add your findings here.. that will be great.

**Comment by almerico** [comment]
this related to concurrent call of github API can't fix it
