### ISSUE TITLE
Let's create example how to run Activiti Cloud locally in Docker

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2658]
so, it will be possible to use Docker Compose to build, run and debug  Activiti Cloud micro-services in local development environment without Kubernetes using Virtualbox or Docker for Desktop

**Comment by salaboy** [comment]
@almerico @igdianov this is related to this PR right? -> https://github.com/Activiti/activiti-cloud-examples/pull/97

**Comment by almerico** [comment]
Yes
