### ISSUE TITLE
[Infrastructure] Let's tag Quickstarts for each Activiti Cloud Charts release

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2659]

**Comment by salaboy** [comment]
@igdianov @almerico was this implemented? Just checking to see in which milestone we should add it.

**Comment by Claireedenton** [comment]
Linked to JIRA https://issues.alfresco.com/jira/browse/ACTIVITI-3091

**Comment by igdianov** [comment]
Fixed. See the following: 

https://github.com/Activiti/activiti-cloud-environments/releases
https://github.com/Activiti/activiti-cloud-platform-quickstart/releases
https://github.com/Activiti/activiti-cloud-runtime-bundle-quickstart/releases
https://github.com/Activiti/activiti-cloud-connector-quickstart/releases
