### ISSUE TITLE
Signal chain does not work

### ISSUE THREAD

**Issue by ggrnd0** [Activiti/Activiti#2664]
Must what works?
1) start SIGNALS_CHAIN process
2) trigger trigger message
3) process done

Actually process waits for ev2

![image](https://user-images.githubusercontent.com/5565134/55082287-7773f680-50b2-11e9-9bed-5670409d863e.png)

[ActivitiSignalsChainFeatureTest.testSignalsChain.bpmn.zip](https://github.com/Activiti/Activiti/files/3013520/ActivitiSignalsChainFeatureTest.testSignalsChain.bpmn.zip)

Reason, agenda&commandInvokers walks throught process bypassing wide.
And when ev2 fired, ev2 catchEvent not exists yet.

There is some strange with flow.

In one process that pattern works fine.
In second does not works.
In that test also does not works with exclusiveGateway added.

**Comment by ggrnd0** [comment]
sorry, that is our mistake..

**Comment by ggrnd0** [comment]
Oh, no. not only our XD

I updated image/scenario/description

**Comment by ggrnd0** [comment]
overriding in Agenda does not work

```                    @Override
                    public Runnable getNextOperation() {
                        return operations.pollLast();
                    }
```

**Comment by ggrnd0** [comment]
With overriding in Agenda ```public Runnable getNextOperation() {
                        return operations.pollLast();
                    }``` and in IntermediateThrowSignalEventActivityBehavior.execute ```
    // that line was last
    Context.getAgenda().planTakeOutgoingSequenceFlowsOperation((ExecutionEntity) execution, true);

    for (SignalEventSubscriptionEntity signalEventSubscriptionEntity : subscriptionEntities) {
      Context.getProcessEngineConfiguration().getEventDispatcher().dispatchEvent(
          ActivitiEventBuilder.createSignalEvent(ActivitiEventType.ACTIVITY_SIGNALED, signalEventSubscriptionEntity.getActivityId(), eventSubscriptionName,
              null, signalEventSubscriptionEntity.getExecutionId(), signalEventSubscriptionEntity.getProcessInstanceId(),
              signalEventSubscriptionEntity.getProcessDefinitionId()));

      eventSubscriptionEntityManager.eventReceived(signalEventSubscriptionEntity, null, signalEventDefinition.isAsync());
    }```

process ended correctly.

that 2 changes forces bypassing deep and place event rising at end.

But HOW that will affect other processes??? >_<

that little process repaired but original process still stucks...

**Comment by ggrnd0** [comment]
That works fine too. Also for original process.
But, is there eny better solution?

![image](https://user-images.githubusercontent.com/5565134/55085722-31ba2c80-50b8-11e9-98b7-b12367b15007.png)

**Comment by salaboy** [comment]
@ggrnd0 can you please try to explain what are you trying to achieve? 
Which version are you using? and how is it failing? 
Which is the element that is failing to behave as you expect?

**Comment by ggrnd0** [comment]
@salaboy, throwSignalEvent fire event and wait until triggered flow chain stopped.

i did it. Yahoo! there is a code
with some additional improvement

IntermediateThrowSignalEventActivityBehavior.execute
```
    @Override
    public void execute(DelegateExecution execution) {

        CommandContext commandContext = Context.getCommandContext();

        String eventSubscriptionName = null;
        if (signalEventName != null) {
            eventSubscriptionName = signalEventName;
        } else {
            Expression expressionObject = commandContext.getProcessEngineConfiguration().getExpressionManager().createExpression(signalExpression);
            eventSubscriptionName = expressionObject.getValue(execution).toString();
        }

        ExecutionEntityManagerImpl executionEntityManager = commandContext.getExecutionEntityManager();
        EventSubscriptionEntityManager eventSubscriptionEntityManager = commandContext.getEventSubscriptionEntityManager();

        List<SignalEventSubscriptionEntity> subscriptionEntities;
		
        if (processInstanceScope) {			
			// original process instance bind
			// {
			//     	subscriptionEntities = eventSubscriptionEntityManager.findSignalEventSubscriptionsByProcessInstanceAndEventName(execution.getProcessInstanceId(), eventSubscriptionName);
			// }
			
			// process tree bind: root process and all subprocesses
			// {
					List<ExecutionEntity> allChildExecutions = executionEntityManager.findExecutionsByRootProcessInstanceId(execution.getRootProcessInstanceId());

					subscriptionEntities = new ArrayList<>();

					for (ExecutionEntity childExecution : allChildExecutions) {
						if (childExecution.isProcessInstanceType()) {
							subscriptionEntities.addAll(
									eventSubscriptionEntityManager.findSignalEventSubscriptionsByProcessInstanceAndEventName(childExecution.getId(), eventSubscriptionName)
							);
						}
					}
			// }
        } else {
            subscriptionEntities = eventSubscriptionEntityManager.findSignalEventSubscriptionsByEventName(eventSubscriptionName, execution.getTenantId());
        }

        for (SignalEventSubscriptionEntity signalEventSubscriptionEntity : subscriptionEntities) {
            Context.getProcessEngineConfiguration().getEventDispatcher().dispatchEvent(
                    ActivitiEventBuilder.createSignalEvent(
                            ActivitiEventType.ACTIVITY_SIGNALED,
                            signalEventSubscriptionEntity.getActivityId(),
                            eventSubscriptionName,
                            null,
                            signalEventSubscriptionEntity.getExecutionId(),
                            signalEventSubscriptionEntity.getProcessInstanceId(),
                            signalEventSubscriptionEntity.getProcessDefinitionId()
                    )
            );

			// forcing signal handling priority:
			// 1) create new commandContext and agenda
			// 2) use current sessions: entityCache and dbSqlSession
			// {
					Command cmd = x -> {
						eventSubscriptionEntityManager.eventReceived(signalEventSubscriptionEntity, null, signalEventDefinition.isAsync());

						return null;
					};
					CommandContext ctx = commandContext.getProcessEngineConfiguration().getCommandContextFactory().createCommandContext(cmd);

					ctx.getSessions().putAll(commandContext.getSessions());

					Context.setCommandContext(ctx);
					try {
						commandContext.getProcessEngineConfiguration().getCommandExecutor().execute(cmd);
					} finally {
						Context.removeCommandContext();
					}
			// }
        }

        commandContext.getAgenda().planTakeOutgoingSequenceFlowsOperation((ExecutionEntity) execution, true);
    }
```

**Comment by salaboy** [comment]
@ggrnd0 this might be the right solution.. but without a test and an example showing what is fixing and how it is almost impossible for us to add to the code. This might be the right solution, but we need to make sure that this solution doesn't break something else, and the only way to make sure that this is the case is by providing a PR with a test to run along all the other engine tests. 
Can you please provide a PR with your suggested changes and a test with the right assertions to make sure that the execution state is the one that you expect from these changes?

**Comment by ggrnd0** [comment]
not sure about effects for already implemented processes.
We did not test our processes yet.

Example in first post.
I will try create PR later...

**Comment by ggrnd0** [comment]
Walking throuht process tree can and will definitely break something...

**Comment by ggrnd0** [comment]
I have cleaner idea!

push/pop Agenda for reused CommandContext in interceptor.

**Comment by ggrnd0** [comment]
In that way any commandExecutor invocations will have separate agenda and where will no unexpected effects with concurrent commands executions...

Debugging will be so easy! XD

**Comment by ggrnd0** [comment]
and i think there must be some changes in intercepting/execution chain...
Where can i post that?

**Comment by salaboy** [comment]
@ggrnd0 I am ok with ideas.. but we need to have PRs with tests in order to evaluate the ideas and the impact in other places of the execution. If you create a branch with your changes and your tests you can easily then send a PR

**Comment by ggrnd0** [comment]
@salaboy , i will try at weekend.

I have another idea. Too big for thai issue. Where i can post that?

**Comment by salaboy** [comment]
@ggrnd0 try to create an issue with a summary of the idea and use the label "feature request"

**Comment by ggrnd0** [comment]
ok

**Comment by ggrnd0** [comment]
i cannot understand...
now test do not fail...
