### ISSUE TITLE
[Core] candidateGroup is removed from task after Completion 

### ISSUE THREAD

**Issue by slamkalukas** [Activiti/Activiti#2669]
We have prepared a simple process:

start -> task1 (candidateGroup **hr**) -> task2 (candidateGroup **testgroup**) -> end

After we start a process, task1 is created. User **hruser** claim task via REST api.
Now when we check the task again via query APIs, we see that **candidateGroup** is missing.

**Comment by igdianov** [comment]
@slamkalukas This sounds like a bug. Could you, please, post the BPMN model and your test case code if possible. We will look into it.

@erdemedeiros Let's put this on the appropriate milestone to fix in the next release?

**Comment by salaboy** [comment]
yeah.. the candidateGroup information is not there yet.. We can add these structures, but that will mean to expand the information that we send in our events. We are analysing how and when we can add this feature. In query you will find the runtime state of the task, not the task definition (at least not now, that is the principle that we used so far, but we understand the limitations).
