### ISSUE TITLE
The  Object of   MultiInstanceLoopCharacteristics  does not have the property  Collection?

### ISSUE THREAD

**Issue by zhuzhiyang** [Activiti/Activiti#2672]
I want to create a BpmnModel manually, my problem is  the object of   MultiInstanceLoopCharacteristics  does not have the property  Collection?   the activiti  version is activiti7

![image](https://user-images.githubusercontent.com/20536244/55484454-1cff0b00-565b-11e9-9b80-eb46121c492d.png)

![image](https://user-images.githubusercontent.com/20536244/55484505-330ccb80-565b-11e9-9eaa-258bbe5c60ab.png)

![image](https://user-images.githubusercontent.com/20536244/55484300-d7424280-565a-11e9-8e1c-b3632046c30b.png)

**Comment by 2738671** [comment]
你好，请问ACTIVITI7怎么实现多实例会签得？能给点提示案例吗
