### ISSUE TITLE
[Infrastructure / Docs ]Generate Postman Collection from Swagger spec

### ISSUE THREAD

**Issue by miguelruizdev** [Activiti/Activiti#2673]
Right now, the current state of the Activiti Postman Collection is this:
https://github.com/Activiti/activiti-cloud-examples/blob/af09c29f7f4fea7b06360475ab342ecd4c166d4d/Activiti%20v7%20REST%20API.postman_collection.json

Thus, this manual maintenance leads to an almost ever-outdated collection, that cannot catch up with the updates of our APIs.

Thanks to our swagger specs, we can maintain this in an easier non-manual way

**Comment by Claireedenton** [comment]
Linked to JIRA https://issues.alfresco.com/jira/browse/ACTIVITI-3092

**Comment by miguelruizdev** [comment]
Main issues when importing a swagger spec right into Postman:
- The path is not parameterized:
![image](https://user-images.githubusercontent.com/32025234/57637403-3e7cdc00-75a3-11e9-8635-40700266cca7.png)
- The body of the request is incomplete
![image](https://user-images.githubusercontent.com/32025234/57637520-8ac81c00-75a3-11e9-972c-a7485694b166.png)

It is worth mentioning that in the Swagger UI, the body of the request is complete:

![image](https://user-images.githubusercontent.com/32025234/57637625-cebb2100-75a3-11e9-9340-37152f60bda3.png)

**Comment by miguelruizdev** [comment]
For the moment, instead of generating a postman collection out of the swagger definition, the main intention is to provide a full integration between the swagger UI and keycloak, so that our services can be tried out in the UI directly (with examples on how the body a of request should look like, and the correct payload types)

The authorization option is given, redirecting the user to the keycloak login, and taking them back to swagger UI again, fully authenticated and ready to use all endpoints in the API: 

![image](https://user-images.githubusercontent.com/32025234/58622379-60749f00-82c3-11e9-82e8-268260ed994d.png)

![image](https://user-images.githubusercontent.com/32025234/58622579-d416ac00-82c3-11e9-9b05-5693b1a3e5e3.png)

**Comment by miguelruizdev** [comment]
Useful links to the gateway aggregation under swagger UI:

- https://github.com/jhipster/jhipster-sample-app-gateway/blob/master/pom.xml#L154
- https://github.com/jhipster/jhipster-sample-app-gateway/blob/master/src/main/java/io/github/jhipster/sample/config/apidoc/GatewaySwaggerResourcesProvider.java
