### ISSUE TITLE
[Documentation]Let's update Developers Guide to add common troubleshooting section

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2675]
Q: ELK setup is working now after using <ip>.nip.io instead of long hostname. question: how did you identify that this was due to long host?

The problem with using AWS NLB DNS name to install Activiti Helm chart in EKS is that it is not a wildcard DNS name. By resolving NLB DNS name to one of the IP addresses and using <IP>.nip.io wildcard DNS service does the trick, because Activiti Helm chart exposes services via dynamically created sub-domains, i.e. activiti-cloud-gateway.<namespace>.<ip>.nip.io.

It is OK to use nip.io for quick testing, but the best best practice will be to register your own wildcard DNS A record for domain name that you own in Route 53 or your NS provider that uses AWS NLB DNS name alias with provided load balancing support.

Q: I am now installing the full example on GCP. Do you think that a Cluster like this: 4 vCPUs 15.00 GB is big enough?
I am getting errors after a while of deploying the chart:

Warning FailedScheduling 44s (x17 over 11m) default-scheduler 0/1 nodes are available: 1 Insufficient cpu.
It is better to have 8 CPUs (i.e. 2 nodes with 4 CPUs each) .

Q: Deployed the full-example on a GCP environment, but I can access the auth endpoint nor anything else. I can ping it, but the call hangs.

The external IP on GCP is provisioned dynamically when you install nginx-ingress that creates service with type LoadBalancer. You should pick and use nginx-controller 'External-IP.nip.io' to for deployment.

Q: I use *.nip.io but to deploy Activiti using Docker Compose, but it is not working.

it's working now.. till now i was behind corporate network.. to test i disconnected it and connected from my phone. after that i updated .env with new ip that i got and ran make application and make modeler. now I can see it loaded projects and i was able to create new project as well.

Q:  we are trying to build gradle file with following dependency "compile group: 'org.activiti', name: 'activiti-engine', version: '7.0.0.GA'"
I am trying with java 8 annd 11 both in local system. its build but when i execute in wildfly server 9.1 its give me error like " class file has wrong version 55.0, should be 52.0" .can you please suggest which version i used for build gradle and how to resolved this error.

7.0.0.GA is compiled with JDK 11. You must be using JDK8 to compile using Gradle and run Activiti 7.0.0.GA.

**Comment by salaboy** [comment]
We need a FAQ section for sure.. there are too many of these questions and answers that we keep repeating in the gitter channel.. 

Let's split the questions into Core, Cloud, Infrastructure to start with and then refine as needed.

**Comment by Claireedenton** [comment]
Linked to JIRA https://issues.alfresco.com/jira/browse/ACTIVITI-3090

**Comment by salaboy** [comment]
done
