### ISSUE TITLE
Incorrect error status when creating a Task with no name

### ISSUE THREAD

**Issue by miguelruizdev** [Activiti/Activiti#2679]
Related to: 
https://github.com/Activiti/Activiti/pull/2455

![image](https://user-images.githubusercontent.com/32025234/55797058-661fe680-5ac3-11e9-87af-2c5783d1a285.png)

The correct error status should be **400**

**Comment by salaboy** [comment]
closing this because it will be done by https://github.com/Activiti/activiti-cloud-service-common/pull/165
