### ISSUE TITLE
No default behavior for writing the "implementation" attribute of the "serviceTask" xml element

### ISSUE THREAD

**Issue by constantin-ciobotaru** [Activiti/Activiti#2680]
We set a default behavior for reading service task "implementation" from xml. The commit change is here: https://github.com/Activiti/Activiti/commit/6eddc90262f75060b412a736422caf952c919f08#diff-6800c437acd17076d0fe75f2ead36a70R61.
But we don't do the same for writing into xml. See  https://github.com/Activiti/Activiti/blob/develop/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/ServiceTaskXMLConverter.java#L91

**Comment by salaboy** [comment]
merged for M1
