### ISSUE TITLE
The twoTaskProcess process definition comes with a null value into the property 'name'

### ISSUE THREAD

**Issue by fcorti** [Activiti/Activiti#2689]
Into the following Getting Started example, the twoTaskProcess process definition comes with a null value into the property 'name'.
 
https://github.com/Activiti/activiti-cloud-charts

This is an issue for an ADF application built on top of the Activiti BPM Engine.

The request is to give a value to the property 'name', as it is happening for all the others process definitions in the examples.

**Comment by salaboy** [comment]
@fcorti did you created also the ADF issue to deal with those situations? Can you please link it here? 

As part of this issue we will add an acceptance test to check that the name is null. We will not change the process, due we will need a process with the name property in null to validate that we are getting the right data in the acceptance test. 

Thanks for reporting.

**Comment by fcorti** [comment]
Below the link to the ADF issue to face this.
https://issues.alfresco.com/jira/browse/ADF-4389

**Comment by salaboy** [comment]
@fcorti can we close this one?

**Comment by Claireedenton** [comment]
I created https://issues.alfresco.com/jira/browse/ACTIVITI-3070 to mirror this in JIRA against the Activti 7.1.0 M2 release.

**Comment by fcorti** [comment]
Yes
