### ISSUE TITLE
[Core] Create acceptance test to cover signal events

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#2691]
Currently signal events are only covered in `multiple-runtime-acceptance-tests`, but those are not executed in the pipeline. We need to cover them in `runtime-acceptance-tests` as well. Scenario could be:
Same signal caught by:
- start signal event
- intermediate catch signal
- boundary signal event

1. start process with intermediate catch signal
1. start process with boundary signal event
1. start process with with intermediate throw event
1. check that signal is caught by `start signal event`, `intermediate catch signal event` and `boundary signal event`

**Comment by Claireedenton** [comment]
Linked in JIRA to https://issues.alfresco.com/jira/browse/ACTIVITI-3089
