### ISSUE TITLE
Breaking configuration changes in activiti-modeling-app 

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2703]
There was a breaking change that removed api prefix from Dockerfile in https://github.com/Activiti/activiti-modeling-app/commit/9a4f746cf99f63ecc0761a0da7cbdf0e005e8669#diff-60713fb19f6c50a2473835df63ff17f9

This makes currently published charts in activiti-cloud-charts repository not compatible with new Modeling App Docker image.

**Comment by almerico** [comment]
Fixed
