### ISSUE TITLE
error accours when applying the quickstart heml chart: error: unable to decode

### ISSUE THREAD

**Issue by LeoQuote** [Activiti/Activiti#2708]
errors when trying to apply the quickstart helm chart
```
error: unable to decode "/tmp/helm-template-workdir-813127549/jx/output/env/charts/activiti-cloud-platform/charts/infrastructure/charts/activiti-keycloak/templates/part0-realm-secret.yaml": Object 'Kind' is missing in '{"metadata":{"annotations":{"jenkins.io/chart":"env","jenkins.io/chart-app-version":"7.0.0.GA"},"labels":{"jenkins.io/chart-release":"jx","jenkins.io/version":"12"}}}''
```

according to the https://activiti.gitbook.io/activiti-7-developers-guide/getting-started/getting-started-activiti-cloud/getting-started-activiti-cloud-jx/google-cloud-gke-jx doc , I set up a jx cluster and started a quickstart , but these error appears when jx trying to apply the staging environment.

It seems to be the problem of keycloak. Any solutions?

**Comment by igdianov** [comment]
@LeoQuote What is the output of `jx version` command? What type of Jenkins-X installation do you have: Static or Serverless?

**Comment by igdianov** [comment]
@LeoQuote New Jenkins-X version has enabled tiller-less Helm as default option, but there is a bug in `jx step helm apply` command that corrupts templates if there is an empty template generated. 

I have fixed `activiti-ingress.yaml` in `activiti-keycloak` chart to workaround this problem. You will need to update `infrastructure` chart to version `1.1.7` in your `charts/activiti-cloud-platform/requirements.yaml` to release and promote it to environment. Let me know if there is any other questions in a separate issue.

**Comment by LeoQuote** [comment]
Thanks for your work! I'll try it on monday!
