### ISSUE TITLE
Can I use two datasource for Activiti in a Spring Boot app?

### ISSUE THREAD

**Issue by VAEAZE** [Activiti/Activiti#2709]
Now I have two database called db1 and db2,which both have the save process flow diagram.I want to execute the activiti process according according the parameter. For example,if I pass the para which value is 1,I want to execute the activiti process using db1.if I pass the para which value is 2,I want to execute the activiti process using db2.Can I use two datasource for Activiti in a Spring Boot app?

**Comment by ggrnd0** [comment]
See ProcessEngineConfigurationImpl.getSessionFactories()
Create your own SessionFactory for org.activiti.engine.impl.db.DbSqlSession class.
which used in CommandContext.getDbSqlSession() 

Simple way to store param is CommanContext.addAttribute()/getAttribute(key) 
currentCommandContext will passed into factory...

Context.getCommandContext() exist only inside commandExecutor.execute call

you can override CommandExecutor & CommandContextFactory for passing param in....
