### ISSUE TITLE
Activiti-cloud-modeling does not work properly

### ISSUE THREAD

**Issue by qiudaoke** [Activiti/Activiti#2711]
I launch and access the activiti-cloud-modeling project at http://127.0.0.1/activiti-cloud-modeling/dashboard/projects
![image](https://user-images.githubusercontent.com/17612111/56476697-b426e800-64ce-11e9-9a87-cc89da24af30.png)
![image](https://user-images.githubusercontent.com/17612111/56476699-c012aa00-64ce-11e9-9265-94b3dd753788.png)
![image](https://user-images.githubusercontent.com/17612111/56476702-cc970280-64ce-11e9-8481-7c23fce5ebde.png)

Program error
![image](https://user-images.githubusercontent.com/17612111/56476705-dd477880-64ce-11e9-9277-3cc734413872.png)

![image](https://user-images.githubusercontent.com/17612111/56476712-fc460a80-64ce-11e9-835e-2d9c8f164f09.png)
![image](https://user-images.githubusercontent.com/17612111/56476714-08ca6300-64cf-11e9-8976-13d0d9c11fa0.png)

**Comment by salaboy** [comment]
@qiudaoke it sounds like a Single Sign On / Keycloak configuration problem. Which version are you using?

**Comment by aenciso** [comment]
@salaboy Same here I'm on 7.1.0.M2

**Comment by salaboy** [comment]
@aenciso unfortunately, I do not work anymore for the project, neither I am responsible for 7.1.0.M2 release.

**Comment by promise06** [comment]
@aenciso turn off the firewall works for me

**Comment by aenciso** [comment]
It turned out I was using 127.0.0.1 which is wrong, it started working when I used my local IP 192.168.... instead
