### ISSUE TITLE
[BPMN/Core] Business Exception Handlers [Cloud connectors]

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2712]
We should implement a mechanism to report back errors at the connector level.
This mechanism should provide a simple way to deal with exceptions and report back to the Runtime Bundles.

Some references: 
- https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit#spring-cloud-stream-overview-error-handling
- https://github.com/Activiti/activiti-cloud-connector-quickstart/pull/8

The flow in my head should work like this:
**If something fails in the connector logic with an Exception**

- it will be retried X amount of times based on configurations
- If the error persist it should go to a DLQ
- We should have DLQ consumer to report business exceptions to business processes

**Comment by proth1** [comment]
@salaboy might it make sense to wire up the DLQ reporting mechanism to the BPMN 'error' constructs including 'Start error event', 'End error event' and 'Boundary error event'.

**Comment by salaboy** [comment]
@proth1 that is the last point "We should have DLQ consumer to report business exceptions to business processes" The missing bit is a component that translate "technical exception" to "business exceptions"

**Comment by igdianov** [comment]
![image](https://user-images.githubusercontent.com/20428629/56615459-f126d380-65cf-11e9-9679-7db53d355957.png)

**Comment by salaboy** [comment]
@igdianov we should use that diagram in the docs :) because that is explaining exactly how it should work.. the only trick there is that I want to make sure that the "Dead Message Monitor Consumer" does the technical to business translation of the exceptions.
