### ISSUE TITLE
[Infrastructure] Avoid HELM chart duplication

### ISSUE THREAD

**Issue by almerico** [Activiti/Activiti#2713]
For now we have two sets of helm charts: User faced charts(https://github.com/Activiti/activiti-cloud-charts) and pipeline charts like (https://github.com/Activiti/activiti-cloud-query/tree/master/charts/activiti-cloud-query and https://github.com/Activiti/activiti-cloud-modeling/tree/master/charts/activiti-cloud-modeling ) .
The task is 
1)avoid two sets of charts and leave only different values files for two purposes.
2)gather all chart code duplications in common component. 
3)chart version updates automatically in pipeline
4)easy release of helm charts for users

**Comment by almerico** [comment]
https://github.com/Activiti/activiti-cloud-common-chart/pull/1

**Comment by Claireedenton** [comment]
Linked in JIRA to https://issues.alfresco.com/jira/browse/ACTIVITI-3087

**Comment by almerico** [comment]
Fixed
