### ISSUE TITLE
[Core] Refactor return type in acc. tests libraries

### ISSUE THREAD

**Issue by miguelruizdev** [Activiti/Activiti#2715]
The current state of the **return type** of the methods in the services of our [acceptance tests libraries](https://github.com/Activiti/activiti-cloud-acceptance-tests) is this:
``PagedResources<CloudRuntimeEvent> getEvents();``

The aim of this issue is to refactor that to:
``Resources<Resource<CloudRuntimeEvent>> deleteEvents();``

This way we will deal with the Resource type of our domain objects and their attached links

**Comment by Claireedenton** [comment]
Created linked JIRA issue https://issues.alfresco.com/jira/browse/ACTIVITI-3071

**Comment by miguelruizdev** [comment]
We hit a wall when dealing with resources instead of plain objects since the **getId** method of an object is overridden by the **getId** method of the Resource that is wrapped around it, ending up in failing contexts like this one:

![image](https://user-images.githubusercontent.com/32025234/59189034-000e1900-8b71-11e9-81ec-03736faa0eac.png)
The assertion made by the test is not comparing the same fields anymore.
Dealing with this incongruence is not one among our priorities now, that is why we proceed to close this issue.
