### ISSUE TITLE
[Infrastructure]Liquibase integration in audit and query

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2717]
https://www.baeldung.com/database-migrations-with-flyway

We need to add Flyway or Liquibase into the mix for migration of the schemas of audit and query and evaluate the impact and flow between releases.

**Comment by salaboy** [comment]
We need to evaluate liquibase as we are already using this in the engine. We need to find out a unified way of dealing with DB schemas and migration

**Comment by mteodori** [comment]
checked with @balsarori and the engine has its own custom implementation of database migrations in order to be lightweight https://github.com/Activiti/Activiti/tree/master/activiti-engine/src/main/java/org/activiti/engine/impl/db
