### ISSUE TITLE
Expose Notifications Service ingress on /notifications

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2720]
The Notifications service will need to be exposed on `/notifications` base path to be able to provide its own `/actuator` endpoint.

**Comment by igdianov** [comment]
@salaboy All the PRs for this issue have been merged: Activiti/Activiti#2720. The acceptance tests also passed in http://jenkins.jx.35.228.195.195.nip.io/blue/organizations/jenkins/Activiti%2Factiviti-cloud-example-chart/detail/PR-235/7/pipeline

**Comment by salaboy** [comment]
all merged
