### ISSUE TITLE
[Modeling] When the process is created, create also the extensions (by default, no variables, no mappings) with the process id inside

### ISSUE THREAD

**Issue by constantin-ciobotaru** [Activiti/Activiti#2722]
By default, empty extensions (with no variables, no mappings, but with id) should be created for any new process model.

**Comment by Claireedenton** [comment]
Linked to JIRA https://issues.alfresco.com/jira/browse/ACTIVITI-3086

**Comment by salaboy** [comment]
@constantin-ciobotaru any progress on this?

**Comment by salaboy** [comment]
merged
