### ISSUE TITLE
[Core] Task variables should not be removed after completion of the task

### ISSUE THREAD

**Issue by CTI777** [Activiti/Activiti#2724]
We have to ensure that task variables are not deleted after completion of the task
Should be done in the same way like here: https://github.com/Activiti/Activiti/issues/2669

**Comment by Claireedenton** [comment]
Linked to JIRA https://issues.alfresco.com/jira/browse/ACTIVITI-3073

**Comment by salaboy** [comment]
This looks like it is done.. @CTI777 if there is something missing here please add a link and reopen the issue.
