### ISSUE TITLE
[DevOps] Automation of version retrieval - Activiti Scripts

### ISSUE THREAD

**Issue by miguelruizdev** [Activiti/Activiti#2725]
Currently, we need to **manually** retrieve the versions present in these text files:

- https://github.com/Activiti/activiti-scripts/blob/master/repos-activiti.txt
- https://github.com/Activiti/activiti-scripts/blob/master/repos-activiti-cloud.txt
- https://github.com/Activiti/activiti-scripts/blob/master/repos-activiti-cloud-modeling.txt

The **[activiti-scripts](https://github.com/Activiti/activiti-scripts)** repo needs to be updated with a version retrieval script.

**Comment by Claireedenton** [comment]
Linked to JIRA https://issues.alfresco.com/jira/browse/ACTIVITI-3072

**Comment by Claireedenton** [comment]
Linked to JIRA https://issues.alfresco.com/jira/browse/ACTIVITI-3072
