### ISSUE TITLE
[Infrastructure] Run e2e tests for activiti-modeling-app in our JX pipelines

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2727]
Point to JX staging runtime environment, to run e2e tests as we are doing for travis here:
https://github.com/Activiti/activiti-modeling-app/blob/master/.travis.yml#L23

Look into travis job configuration for credentials and env variables.

**Comment by almerico** [comment]
for travis exists chrome addon https://github.com/Activiti/activiti-modeling-app/blob/5609a4492cab7b38216ec72ce709310bc13fc363/.travis.yml#L7 for jenkins in the JX installation clusterwide installation needs to be changed and  how stable  this change will be

**Comment by salaboy** [comment]
@almerico can we check with the jenkinsx guys.. I will assume that the node build agent will have some way to add extra plugins for such things.. having a chrome engine to run the tests sounds like a very basic thing to have.

**Comment by Claireedenton** [comment]
Linked to JIRA https://issues.alfresco.com/jira/browse/ACTIVITI-3082

**Comment by salaboy** [comment]
@popovicsandras @almerico is finding some issues with the Chrome Driver.. have you seen this before: 
https://gist.github.com/almerico/c30673f0a3cc8ea7d7e37eeeb2f8ef68

**Comment by almerico** [comment]
done
