### ISSUE TITLE
[Documentation]Move the conformance documentation to Gitbook

### ISSUE THREAD

**Issue by miguelruizdev** [Activiti/Activiti#2728]
All the behaviour described in the conformance [doc](https://docs.google.com/document/d/1-3ek-02fYteHURdQYDwUeVxqODmhZP0DwtyXNweGkOc/edit#) needs to be present in the [Gitbook](https://activiti.gitbook.io/activiti-7-developers-guide/).

**Comment by Claireedenton** [comment]
Linked to JIRA https://issues.alfresco.com/jira/browse/ACTIVITI-3076

**Comment by salaboy** [comment]
initial iteration done.. needs to refine links and add images for process defintions
https://activiti.gitbook.io/activiti-7-developers-guide/overview/comformance
