### ISSUE TITLE
[Documentation] Expand Query and Audit documentation

### ISSUE THREAD

**Issue by miguelruizdev** [Activiti/Activiti#2729]
In a sort of **specification** of our own services, we need to further describe the behaviour of Query and Audit services in regards to the operations they perform with the events described in the conformance doc: https://docs.google.com/document/d/1-3ek-02fYteHURdQYDwUeVxqODmhZP0DwtyXNweGkOc/edit#

**Comment by Claireedenton** [comment]
Linked to JIRA https://issues.alfresco.com/jira/browse/ACTIVITI-3075

**Comment by salaboy** [comment]
Initial work on Query done, more work on audit is required.
