### ISSUE TITLE
[Documentation] Documentation alignment

### ISSUE THREAD

**Issue by miguelruizdev** [Activiti/Activiti#2730]
We need to establish a single source of truth that will rely on the combination of these different elements in Activiti 7:

- Acceptance tests libraries: https://github.com/Activiti/activiti-cloud-acceptance-tests
- Acceptance tests scenarios: https://github.com/Activiti/activiti-cloud-acceptance-scenarios
- Conformance document: https://docs.google.com/document/d/1-3ek-02fYteHURdQYDwUeVxqODmhZP0DwtyXNweGkOc
- Gitbook: https://activiti.gitbook.io/activiti-7-developers-guide/

This issue is an umbrella for: 

- https://github.com/Activiti/Activiti/issues/2729
- https://github.com/Activiti/Activiti/issues/2728

**Comment by Claireedenton** [comment]
Linked to JIRA https://issues.alfresco.com/jira/browse/ACTIVITI-3074

**Comment by salaboy** [comment]
initial work done in gitbook
