### ISSUE TITLE
[Infrastructure] Refactor Full Example Services names to follow temporary convention

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2733]
The idea is to make sure that the services deployed by our full example helm chat will be exposed under the following URLs.

Service |  New Community URL for full example
-- |  --
Audit |  /audit
Query |  /query
Runtime Bundle |  /rb
Notifications |  /notifications
Modeling Service |  /modeling-service
Modeling UI |  /modeling
KeyCloak | identity.{domain}/auth
Gateway |  gateway.{domain}/

The idea is to not change the charts but the service names. Because we have the Gateway component that automatically expose the routes for the services, we need to change the spring.application.name in each example repo.

We should add a filter to the gateway to only expose services with an activiti-cloud label/annotation.

**Comment by Claireedenton** [comment]
linked to JIRA https://issues.alfresco.com/jira/browse/ACTIVITI-3080

**Comment by salaboy** [comment]
This is a temporary change until we get the AppService into our example which will provide the following paths:
gateway.host/apps/<app-name>/rb/<rb service name>
gateway.host/apps/<app-name>/audit/<audit service name>
gateway.host/apps/<app-name>/query/<query service name>
gateway.host/apps/<app-name>/notifications/

Also.. 
GET gateway.host/apps/
should return the list of available apps with their structure

**Comment by almerico** [comment]
https://github.com/Activiti/activiti-cloud-full-chart/pull/42

**Comment by salaboy** [comment]
done
