### ISSUE TITLE
[Core] Acceptance Test Step Library in a consumable artifact

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2734]
We need to provide the steps required for:
1) Scenario Testing
2) Conformance Testing

Which should be divided into separate libraries:
0) Shared: Authentication, cross cutting concerns
1) Core for RB, Audit, Query and Connectors
2) Modeling Services

The libraries should be able to be extended to add extra assertions. 
The main objective for the library is to enable the testing of the execution of processes into the Activiti Cloud Infrastructure.

As soon as we the steps library into the right shape the Scenario testing needs to be streamlined to make sure that we can isolate tests which are testing different scenarios to avoid testing a single big scenario.

**Comment by erdemedeiros** [comment]
@salaboy do you have any example in mind about what we expect from this library?

**Comment by salaboy** [comment]
Yes. The idea is to have generic steps that can be configured to create different scenarios. 
So the steps should be like:
- Start Process which inside it should check that a call to RB start a process and generate a certain set of events in Audit and a Process Instance in Query
- Complete a task, the same events in audit and query state change
- Signal, the same. 

The library should only provide the steps and glue code so the scenario project who adds the library can easily create different simple, intermediate and complex scenarios. 
Shared Steps for Authentication and other cross cutting concerns needs to be provided as well. 
Today our steps are already a mess, so we need to clean those up and make sure that we stream line the scenarios creation.

**Comment by Claireedenton** [comment]
Linked in JIRA https://issues.alfresco.com/jira/browse/ACTIVITI-3078

**Comment by salaboy** [comment]
More information about how we should get this done:
- We should refactor our core conformance tests to understand what the shape of the steps should be
- We should have the basic operations/steps/assertions into our gitbook
- We need to move out the core conformance tests to a separate repository that can be used as a gate for Activiti Dependencies. This means that before releasing Activiti Dependencies we should make sure that these conformance tests are executed and are green. We will need @almerico help for this one
- This needs to be propagated to cloud and **activiti-cloud-acceptance-tests** needs to be transformed into a core set of steps that allows us to execute operations and run assertions on the state of different  services. 
- The **activiti-cloud-acceptance-scenarios** needs to be split and new pipelines needs to be created for each scenario allowing us fast addition of new scenarios to be used as gate for releasing activiti-cloud-dependencies. We will need @almerico help for this one
