### ISSUE TITLE
[BPMN] SubProcess Embedded support

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2735]
Add support for BPMN Embedded Subprocess Cloud Events into RB, Query and Audit

**Comment by erdemedeiros** [comment]
@salaboy should we cover only "simple" Subprocesses or event subprocesses as well?
- example of subprocess: https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/test/resources/org/activiti/engine/test/api/oneSubProcess.bpmn20.xml#L11
- example of event subprocess: https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/test/resources/org/activiti/engine/test/api/event/ActivityEventsTest.testActivityMessageEventsInEventSubprocess.bpmn20.xml#L18-L21

I think the generated events will be very similar, but it's better to what should be covered exactly.

**Comment by Claireedenton** [comment]
Linked to JIRA https://issues.alfresco.com/jira/browse/ACTIVITI-3077

**Comment by Claireedenton** [comment]
linked to JIRA https://issues.alfresco.com/jira/browse/ACTIVITI-3077

**Comment by CTI777** [comment]
@salaboy @erdemedeiros 
I have created a test to check what we have currently for embedded sub processes
It seems that the best way will be to have special embedded subProcess events, somehing like:
SubProcessStartedEvent
SubProcessCompletedEvent
Maybe
SubProcessCancelledEvent
What do you think?

**Comment by salaboy** [comment]
@CTI777 exactly that is what we need :)

**Comment by salaboy** [comment]
@erdemedeiros hmm the triggerByEvent property is not coming from the BPMN spec as far as I remember.. so that kinda sucks.. but I think that we can cover that scenario as well.
I will be more inclined to cover this one first: https://github.com/Activiti/Activiti/blob/develop/activiti-engine/src/test/resources/org/activiti/engine/test/api/oneSubProcess.bpmn20.xml#L11

**Comment by erdemedeiros** [comment]
@salaboy, @CTI777, before adding `SubProcessStartedEvent`, `SubProcessCompletedEvent`, I'd rather check which are the internal events triggered by the engine. In similar way we are already doing to for call activities I think we can reuse `ProcessStartedEvent`, `ProcessCompletedEvent`, `ProcessCancelledEvent`. Then a subprocess can be identified because it has parent process instance set (and process definition id is the same as the one of parent process instance). In addition to those events I'd expect to have a `BPMNActivityStartedEvent` and `BPMNActivityCompletedEvent` related to the subprocess.

@salaboy I've check in the spec and `triggerByEvent` is part of it:

> triggeredByEvent: boolean = false | A flag that identifies whether this Sub-Process is an Event Sub-Process. 
> - If false, then this Sub-Process is a normal Sub-Process.  								
> - If true, then this Sub-Process is an Event Sub-Process and is subject to additional constraints (see page 174).

**Comment by salaboy** [comment]
@erdemedeiros awesome! I cannot keep every property in my head, thanks for checking.. 
@erdemedeiros @CTI777 totally agree.. about using the internal events, but I think that we definitely need to send new types (higher level) to make sure that the API is clear and the events are consistent. 
Usually this is the layer where we translate from low-level to high-level concepts that can be easily understood and consumed by clients/UIs. If we just use the parentId to differentiate, then we will add complexity on the READ (consumer) side and we will be leaking internal information. Does this make sense @erdemedeiros ? Do you have any concrete concern about these high level types?

**Comment by erdemedeiros** [comment]
@salaboy I'm more concerned about APIs retrieving subprocess instances. I guess they will be retrieved by the same endpoints as "normal" process instances (at least in RB). And in query they will be probably stored in the same table as other process instances. I'm just wondering if it's worth the create new types if they are going to be handled in the same way by the consumer (query). If we go on that direction we also need to make sure that we are not producing a `ProcessStartedEvent` and a `SubProcessStartedEvent` for the same internal event. I think that with the current implementation we are already producing `ProcessStartedEvent` when a subprocess is reached. My feeling is that having specific types will make the implementation more complex.

**Comment by salaboy** [comment]
@erdemedeiros that is a good concern.. I was not thinking to remove the Start/Complete Process, but more to have the new types as decorators. In query as you mention we will have the parent child relationship (not even sure if there is a new process instance for the embedded subprocess). What I want to make sure is:
1) In audit there is an event when we go into a sub process
2) In query we can quickly find out when a task is inside a subprocess

But I totally agree this becomes complex quite fast if we don't make the right choices.

**Comment by erdemedeiros** [comment]
@salaboy that's why I wanted to see which are the internal events produced when we reach a subprocess and how the subprocess instance is stored in activiti core. Maybe the related ActivityStartedEvent (if there is one) can be mapped to SubProcessStarted to be handled by audit.

Concerning tasks we need to figure out if tasks from subprocess instance should be returned or not when we ask for for tasks specifying the parent process instance as process instance Id.

**Comment by CTI777** [comment]
@salaboy @erdemedeiros 
Just to clarify what we have now:
When embedded subProcess is started we get **ACTIVITY_STARTED** event, and inside the event we have Entity, having getActivityType: **subProcess**
The problem we have now is coming from task (inside subProcess): it is not clear exactly currently, that task is coming from subProcess. So, for sure we will need changes here...

**Comment by CTI777** [comment]
For events related to tasks inside subProcess we have event.processInstanceId not same like evant.entity.processInstanceId

**Comment by CTI777** [comment]
@salaboy @erdemedeiros 
I have added a test to have subProcess with CallActivity process inside.
It seems that for events related to the tasks from CallActivity process (which is inside subprocess) we have a behavior like for the CallActivity tasks outside subProcess. Maybe we have to decide also what to do in these cases...

**Comment by CTI777** [comment]
@salaboy @erdemedeiros 
We have to remember also that there is already API for subProcesses, which are CallActivity processes 
```
@RequestMapping(value = "/{processInstanceId}/subprocesses", method = RequestMethod.GET)
    PagedResources<Resource<CloudProcessInstance>> subprocesses(@PathVariable("processInstanceId") String processInstanceId,
                                                         Pageable pageable);
```

**Comment by CTI777** [comment]
@salaboy @erdemedeiros
After double checking of handling subProcess behavior we have following:

- When embedded subProcess is started we get an event: `ACTIVITY_STARTED` with `event.getEntity().getActivityType() == subProcess`
- When embedded subProcess is completed we get an event: `ACTIVITY_COMPLETED` with `event.getEntity().getActivityType() == subProcess`
- When task is executed, which is inside subProcess, all events for this task will have processInstanceId corresponding to parent process (not to subProcess). The behavior of the task is similar to tasks outside subProcess...
- When CallActivity is executed, which is inside subProcess, all events for the new CallActivity  process,  are handled as if there is not subProcess. Tasks inside CallActivity process will have `parentProcessInstanceId` corresponding to parent Process (not subProcess), and `processInstanceId` corresponding to CallActivity  process
- Corresponding basic tests are added.

**Comment by erdemedeiros** [comment]
@CTI777 thanks for the detailed explanation. @salaboy to summarize, no process instance will be created to represent embedded subprocess: elements declared inside the embedded subprocess will reuse the "parent" process instance.

**Comment by salaboy** [comment]
@CTI777 @erdemedeiros cool.. that is what I was expecting.. so for this case there is no subprocess itself.. (the element is called embedded subprocess but there is no sub process instance to be specific).
This means, that we need a way to "Demarcate that we are inside a sub process (logical one), and I think that we can do that by just having the right "extra" events"

How much do we need?

**Comment by CTI777** [comment]
@salaboy @erdemedeiros We may create extra events to know that subProcess is started, ended... But how we may use this for identifying that task is inside a subProcess? Internally, this is not supported, so we will need to create something special...
