### ISSUE TITLE
[Core] Process definition version not set for integration request

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#2736]
Process definition version is not set (in the header and inside IntegrationContext object) when the connector is not the first step of the process.

How to reproduce:
1. Create a process: UserTask -> ServiceTask -> UserTask
2. Start the process and execute the user task
3. Inside the connector check the header `processDefinitionVersion` (it's missing) and integrationRequest.getIntegrationContext().getProcessDefinitionVersion (It's null).

**Comment by igdianov** [comment]
![image](https://user-images.githubusercontent.com/20428629/57495400-c8b30080-7282-11e9-8e01-c22cf82ed30c.png)

**Comment by igdianov** [comment]
We also need to add acceptance scenarios for this use case.

**Comment by salaboy** [comment]
@igdianov is there any acc tests addition to test the PRs in the examples?

**Comment by igdianov** [comment]
@salaboy I have added https://github.com/Activiti/activiti-cloud-acceptance-scenarios/pull/367

**Comment by salaboy** [comment]
done and all merged with acc tests
