### ISSUE TITLE
NeverFailAutoDeploymentStrategy is not showing the resource name with problems

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#2747]
Logs from `NeverFailAutoDeploymentStrategy` are not showing the name of the resource with problems. I.e:
```
2019-05-15 11:54:38,743 [main|org.activiti.spring.autodeployment.NeverFailAutoDeploymentStrategy] ERROR The following resource wasn't included in the deployment since it is invalid: 
```

**How to reproduce:**
- add a process with a validation error in the path to be auto-deployed. For instance, [ParsingError.bpmn](https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-starter-runtime-bundle/src/test/resources/processes/ParsingError.bpmn).

**Note:** the same problem is probably present in `FailOnNoProcessAutoDeploymentStrategy`. Please, take the opportunity to remove the duplication of the following code:
- https://github.com/Activiti/Activiti/blob/develop/activiti-spring/src/main/java/org/activiti/spring/autodeployment/NeverFailAutoDeploymentStrategy.java#L25-L36 **duplicated with** https://github.com/Activiti/Activiti/blob/develop/activiti-spring/src/main/java/org/activiti/spring/autodeployment/FailOnNoProcessAutoDeploymentStrategy.java#L26-L37

**Comment by salaboy** [comment]
merged
