### ISSUE TITLE
[Modeler]Add DNS constraint validation for connector names

### ISSUE THREAD

**Issue by constantin-ciobotaru** [Activiti/Activiti#2748]
As the connector names are used to create pods on kubernetes, these names need to be validates (accordingly to https://docs.oracle.com/cd/E52668_01/E88884/html/kubectl-basics.html) against DNS-1123 conventions.

The regex used in the kubernetes UI itself is "[a-z0-9]([-a-z0-9]*[a-z0-9])?" (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go)

**Comment by erdemedeiros** [comment]
For release notes: mention new restrictions on connector name.
