### ISSUE TITLE
[Core] Let's generate process diagram in Query service via Rest Api

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2750]
We need to provide Rest Api in Query service to generate SVG image diagram for any running or completed process instance showing completed and active activities.

There is an existing diagram render api in Activiti Core that uses BPMN model to render SVG images with provided list of historical activities. The Rb uses diagram render  to generate the diagram via Rest endpoints with the following limitations:

1. It works for only running processes. After the process has completed it gets deleted from runtime database.
2. The diagram only shows active activities because history is disabled. 
3. The diagram renderer has hard dependency on Windows fonts and requires adding Windows fonts package to build Docker image.

We need to move diagram Rest Api from Rb into Query service. The Query service will need to aggregate events emitted by Rb to store the list of completed and active activities for the process instance. 

The Diagram Rest Api in Query service will use query database to retrieve current list of historical activities and generate diagram SVG image for any historical process instance. 

We will also need to remove the dependency on Windows fonts in Activiti Core or should be able to customize the font used by diagram render in Query service.

Also, we will need to allow clients to customize colors used to highlight past and current activities.

**Comment by salaboy** [comment]
@igdianov my suggestion is not to generate the SVG in the backend.. we just need to have the right data for the BPMN.io widget to render the state.. query shouldn't generate images in the backend. This was already checked with some other contributors that raised some problems with backend generation. Query should have the right data, enough for a widget to consume and render an SVG or a more dynamic JS widget.

**Comment by igdianov** [comment]
@salaboy I think it makes sense to support both server and client rendering of the BPMN diagram to accommodate different use cases, i.e. if someone wants to simply embed SVG image in their app via , it is a simple Rest GET call without bringing any BPMN.io dependencies on the client.

**Comment by igdianov** [comment]
@salaboy @magemello I have completed the first cut of the ProcessInstanceDiagramController Rest Api. See ITs in the PR https://github.com/Activiti/activiti-cloud-query-service/pull/238. 

In the next step, I will add acceptance scenarios to be able to release the preview.

I also need some guidance on the access permissions policies for the process diagram generator Api.

**Comment by igdianov** [comment]
We will also need admin endpoint as well.

**Comment by salaboy** [comment]
@igdianov can you report progress on this? are the acc tests ready?

**Comment by salaboy** [comment]
waiting for acc tests

**Comment by igdianov** [comment]
We will also need Swagger documentation as well.

**Comment by igdianov** [comment]
@salaboy I have added admin endpoint and canRead security polices check in the PR build: 7.1.0-SNAPSHOT-PR-238-15

**Comment by igdianov** [comment]
@salaboy All PRs are created. It is ready for review.
