### ISSUE TITLE
Missing processInstanceId on Task returned by TaskRuntime.complete(...)

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#2756]
The field `processInstanceId` is not set for the `Task` returned by `TaskRuntime.complete(...)`.

**How to reproduce:**
- complete a task that belongs to a process (not stand alone task)
- check the content of `processInstanceId` field on that task

**Problem:**
[Returned data](https://github.com/Activiti/Activiti/blob/develop/activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskRuntimeImpl.java#L162-L164) is only setting `id`, `name` and `status`.

**How to fix it:**
- create a new constructor to [TaskImpl](https://github.com/Activiti/activiti-api/blob/develop/activiti-api-task-model-impl/src/main/java/org/activiti/api/task/model/impl/TaskImpl.java) that takes the interface `Task` as a parameter. This constructor should set all the available fields from the `Task` passed as parameter (not only the three mentioned above).
- override the status to `completed` using `TaskImpl.setStatus(...)` method.

**Comment by salaboy** [comment]
merged
