### ISSUE TITLE
[Modeling] BPMN Embedded subprocess support

### ISSUE THREAD

**Issue by salaboy** [Activiti/Activiti#2761]
Modeling side of : https://github.com/Activiti/Activiti/issues/2735

**Comment by erdemedeiros** [comment]
The only property to be set for an embedded subprocess is the name. In addition, inside the embedded subprocess box, the only start event type allowed for now is the none start event.

**Comment by salaboy** [comment]
@popovicsandras can you please let us know if this was scheduled in an AMA sprint?

**Comment by salaboy** [comment]
This was notified to be done.. but requires validation by the core team to be closed.

**Comment by popovicsandras** [comment]
This was added to v0.0.90, 4 days ago, but agree, haven't been validated yet.
