### ISSUE TITLE
[BPMN] Add ITs covering events emitted by Parallel gateway

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#2762]
Create `ParallelGatewayAuditProducerIT` checking events sent by the runtime bundle when a parallel gateway is executed. 
Expecting: 
- `ACTIVITY_STARTED` with activityType `parallelGateway`
- `ACITIVITY_COMPLETED` with actvityType `parallelGateway`

**Comment by salaboy** [comment]
done
