### ISSUE TITLE
[BPMN] Add ITs covering events emitted by exclusive gateway

### ISSUE THREAD

**Issue by erdemedeiros** [Activiti/Activiti#2763]
Create `ExclusiveGatewayAuditProducerIT` checking events sent by the runtime bundle when an exclusive gateway is executed. 
Expecting: 
- `ACTIVITY_STARTED` with activityType `exclusiveGateway`
- `ACITIVITY_COMPLETED` with actvityType `exclusiveGateway`

**Comment by salaboy** [comment]
merged
