### ISSUE TITLE
Redundant Keycloak Realm Api call to resolve user groups in Rb, Query and Audit 

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2765]
Query service uses Keycloak realm to resolve user groups via Rest for every task list request using https://github.com/Activiti/activiti-cloud-service-common/blob/448c871049dcececd7df279c4613e32966f3f22f/activiti-cloud-services-common-identity-keycloak/src/main/java/org/activiti/cloud/services/identity/keycloak/KeycloakUserGroupManager.java#L87 . 

Because JWT access token does not contain the list of effective user groups:
```
{
  "jti": "bcd08573-d4d5-4ad8-8c65-8913e9388ec5",
  "exp": 1558536769,
  "nbf": 0,
  "iat": 1558536469,
  "iss": "http://activiti-cloud-gateway.staging.35.223.143.26.nip.io/auth/realms/activiti",
  "aud": "activiti",
  "sub": "784ca026-cfaa-422c-88e8-b7565515ff71",
  "typ": "Bearer",
  "azp": "activiti",
  "auth_time": 0,
  "session_state": "2fd790dd-c27e-46fb-a7de-d99f2e152ad5",
  "acr": "1",
  "allowed-origins": [
    "*"
  ],
  "realm_access": {
    "roles": [
      "offline_access",
      "ACTIVITI_USER",
      "uma_authorization"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "email profile",
  "email_verified": false,
  "name": "h r",
  "preferred_username": "hruser",
  "given_name": "h",
  "family_name": "r",
  "email": "hr@test.com"
}
```

It is not optimal to do that for every request, because it is slow and impacts overall response time when calling Rest Apis.

Another problem is that Keycloak Admin client is instantiating RestEasy Http Client with default connection pool of maximum 10 connections: 

https://github.com/keycloak/keycloak/blob/da85cff53b239250fa880e086b2721ba41a9a1e8/integration/admin-client/src/main/java/org/keycloak/admin/client/Keycloak.java#L72

This configuration creates ThreadPoolExecutor with limited number threads in the pool which will cause blocking with more than 10 concurrent requests:;

![image](https://user-images.githubusercontent.com/20428629/62307500-8f7ccd80-b438-11e9-987b-36c2df2d3d8e.png)

This is likely the reason of a connection timeout when Task Controller tries to connect to Keycloak to extract realm data to get user roles. 

To solve this problem we can use Keycloak User Groups mapper to inject the list of user groups into extra claims inside JWT token below.

**Comment by igdianov** [comment]
After investigating this further, it appears that we will need to configure Keycloak to include group membership in access token:

![image](https://user-images.githubusercontent.com/20428629/58303207-fbd9b180-7da3-11e9-908c-b05867afce47.png)

After that, JWT token will contain a list of groups:

```
{
  "jti": "c3182e7a-a4e9-46f1-a1f6-cd5c35c192b0",
  "exp": 1558673232,
  "nbf": 0,
  "iat": 1558672932,
  "iss": "http://activiti-cloud-gateway.staging.X.X.X.X.nip.io/auth/realms/activiti",
  "aud": "activiti",
  "sub": "784ca026-cfaa-422c-88e8-b7565515ff71",
  "typ": "Bearer",
  "azp": "activiti",
  "auth_time": 0,
  "session_state": "4542eb12-1c89-4c0e-810a-8124adb9ca75",
  "acr": "1",
  "allowed-origins": [
    "*"
  ],
  "realm_access": {
    "roles": [
      "offline_access",
      "ACTIVITI_USER",
      "uma_authorization"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "email profile",
  "email_verified": false,
  "name": "h r",
  "groups": [
    "hr"
  ],
  "preferred_username": "hruser",
  "given_name": "h",
  "family_name": "r",
  "email": "hr@test.com"
}
```

Then, we will need to configure KeycloakAuthenticationProvider to map groups into Spring Security GrantedAuthority in order to seamlessly extract groups using Spring Security Authentication object

**Comment by igdianov** [comment]
After further thought and experiment, it is not a good idea to map user groups from custom `groups` claim into Spring GrantedAuthority. The best place to implement group extraction from Keycloak claim is inside KeycloakSecurityManagerImpl by introducing `List<String> getAuthenticatedUserGroups()` interface method and extract groups list using `IDToken.getOtherClaims`, i.e.


```
          Optional.ofNullable(SecurityContextHolder.getContext())
                        .map(SecurityContext::getAuthentication)
                        .map(Authentication::getCredentials)
                        .filter(KeycloakSecurityContext.class::isInstance)
                        .map(KeycloakSecurityContext.class::cast)
                        .map(KeycloakSecurityContext::getIdToken);
                        .map(IDToken::getOtherClaims)
                       .map(it -> it.get("groups"))
                       .filter(Collection.class::isInstance)
                       .map(Collection.class::cast)
                       .map(it -> new ArrayList<String>(it))
                       .orElseGet(Collections.emptyList());
```

**Comment by igdianov** [comment]
This is the Activiti client protocolMapper configuration:

```
, {
      "id": "5f5272d0-dd32-49ba-b1ab-ac2e6a66d4aa",
      "name": "groups",
      "protocol": "openid-connect",
      "protocolMapper": "oidc-group-membership-mapper",
      "consentRequired": false,
      "config": {
        "full.path": "false",
        "id.token.claim": "true",
        "access.token.claim": "true",
        "claim.name": "groups",
        "userinfo.token.claim": "true"
      }
    }
```

**Comment by igdianov** [comment]
Increasing the size of the pool is not going to solve the problem. It does not make sense to add more threads because Rb pod has limited CPU resources and the number of concurrent connections in the pool will always be a bottleneck causing thread starvation under load.

Adding the list of groups in JWT will slightly increase the size of the token, but requires Keycloak realm reconfiguration.

**Comment by rgauss** [comment]
Apologies, I've only seen this particular issue today.

We're looking to standardize on the realm being used and we'd prefer to not require that the groups be included in the Alfresco Identity Management Service JWT for a number of reasons including:
* Size of the JWT (which you mentioned above) since users could easily be a member of 100s of groups (we have some cases where that is in the 1000s)
* Security implications of potentially sensitive group names
* Diverging component behavior where some services require and use group information in JWTs while others obtain group information through other means (like LDAP sync)

In digging through this a bit it looks like the code that was previously being called was actually making 2 REST calls to Keycloak:
1) [search users](https://github.com/Activiti/activiti-cloud-service-common/blob/develop/activiti-cloud-services-common-identity-keycloak/src/main/java/org/activiti/cloud/services/identity/keycloak/KeycloakUserGroupManager.java#L91) to get the Keycloak user UUID from the username
2) [get user by id](https://github.com/Activiti/activiti-cloud-service-common/blob/develop/activiti-cloud-services-common-identity-keycloak/src/main/java/org/activiti/cloud/services/identity/keycloak/KeycloakUserGroupManager.java#L87) to retrieve the user details including group information

That first call is probably much more expensive and likely a huge contributor to the performance issues.

It looks like part of these changes would enable the Keycloak user UUID to be more easily obtained from the access token, eliminating the need for that first REST call above, then using something like a `KeycloakServerPrincipalGroupsProvider` to make the second REST call above?

Before committing to including the groups in the JWT as the default, could we test the performance of such an implementation, or perhaps this was already investigated?

**Comment by igdianov** [comment]
@rgauss The UserGroupManager implementation makes 2 REST calls to Keycloak because it does not have subject UUID associated with the preferred user name used in Activiti. There is no easy way around it, so that SecurityManager implementation had been redesigned to use a chain of user group providers that can try to resolve groups from different sources, i.e. JWT token or fall back to Keycloak REST Client to resolve user group by subject UUID.

I did the performance benchmarks of the old and new implementations using Stagemonitor monitoring agent to instrument Keycloak instance and all Activiti Cloud applications to collect request metrics with trace spans and send them to ELK for analysis. The test results demonstrated ~10-40x gain in response times for all operations, i.e.

Before, in Rb, the worst performer Claim Task operation had 1340ms response time with 1300ms (99%) used to resolve user groups by calling Keycloak REST Api via UserGroupManager, because the business logic of the Claim Task needed to resolve user groups 4 times, with each Keycloak transaction taking ~300ms. 

![image](https://user-images.githubusercontent.com/20428629/68810081-26554a80-0622-11ea-80a6-565fe5202187.png)

After refactoring was made to extract user groups from JWT token, the Claim Task response time has become ~30ms  => 40x better than before.

![image](https://user-images.githubusercontent.com/20428629/68810532-315caa80-0623-11ea-8149-a5377991a758.png)

It also resolved similar problems in Query and Audit services:

**Query**
![image](https://user-images.githubusercontent.com/20428629/68810760-daa3a080-0623-11ea-9094-6e63185f6b2f.png)

**Audit**
![image](https://user-images.githubusercontent.com/20428629/68810774-e0998180-0623-11ea-8d90-72b169d6e6d5.png)

In addition, the Keycloak Rest Client uses a thread pool with limited number of connections. which will always be a bottleneck in scalability as soon the number of client connections exceed the pool size. The network latencies will add up for each operation and impact the response times of all requests. 

Also having business operations dependent on Keycloak Rest Api defeats the purpose of using stateless authorization and breaks low coupling between micro services. The Keycloak will become a bottleneck if there are many applications using it for synchronous group membership requests.

**Comment by igdianov** [comment]
In summary, the refactoring of SecurityManager to resolve user groups is not opinionated. The first provider in the chain will try to resolve groups from JWT token. If the groups claim is not present, the fallback provider will use Keycloak client to make REST call using subject UUID. It is up to the user to configure the client in the realm to provide custom groups claim based on the preference for token size or performance considerations.

**Comment by rgauss** [comment]
> The UserGroupManager implementation makes 2 REST calls to Keycloak because it does not have subject UUID associated with the preferred user name used in Activiti. There is no easy way around it

Right, it did not previously have the UUID. It could (perhaps should) have had access to it in addition to or even instead of the username via the security manager, but my point is that with your refactoring it is now much easier to get that UUID from the access token instead of a separate REST call.

I don't doubt there's significant improvement when packing the groups into the JWT vs the previous code, but I'd be interested to see the performance gains when eliminating the first search REST call.

> In addition, the Keycloak Rest Client uses a thread pool with limited number of connections. which will always be a bottleneck in scalability as soon the number of client connections exceed the pool size.

Potentially, but there are other ways around that limitation and the RB should be doing more work than simple request for a user by ID at Keycloak.  The same bottlenecks could apply to many other components of the system, like DB, and the entire system should be able to respond to back-pressure from components under load.

> Also having business operations dependent on Keycloak Rest Api defeats the purpose of using stateless authorization and breaks low coupling between micro services.

Stateless authorization isn't always a good idea.  Implicit flow access tokens last 15 minutes by default.  That's a long time to be able to perform malicious acts after one has been removed from a group.

> The Keycloak will become a bottleneck if there are many applications using it for synchronous group membership requests.

Again, we can mitigate that through other means.

> If the groups claim is not present, the fallback provider will use Keycloak client to make REST call using subject UUID

Yes, I saw the chaining mechanism, but on my brief look at the code I did not see a `PrincipalGroupsProvider` that was using the Keycloak client.  Could you point me to that?

> It is up to the user to configure the client in the realm to provide custom groups claim based on the preference for token size, scalability and performance considerations.

Yes, I was under the impression this was proposing that groups in the JWT become the new default.

**Comment by igdianov** [comment]
> > The Keycloak will become a bottleneck if there are many applications using it for synchronous group membership requests.
> 
> Again, we can mitigate that through other means.

What are these means? The simplest solution is usually the most effective because there are less moving pieces that could break, IMO. 

It is the best practice to limit TTL of the access token to under 60 seconds to mitigate any security risk. The TTL should be fine tuned to allow to perform complex business operation by calling several Rest Apis, i.e. Send command to Rb, and then request to Query or Audit, 

Here is the implementation of fallback KeycloakClientPrincipalDetailsProvider: 

https://github.com/Activiti/activiti-cloud-service-common/blob/afa3e954ffaaed0177b2275b467deaa39a5332c0/activiti-cloud-services-common-identity-keycloak/src/main/java/org/activiti/cloud/services/identity/keycloak/KeycloakClientPrincipalDetailsProvider.java#L31

It is configured with lowest precedence to any other provider available in the chain:

https://github.com/Activiti/activiti-cloud-service-common/blob/afa3e954ffaaed0177b2275b467deaa39a5332c0/activiti-cloud-services-common-identity-keycloak/src/main/java/org/activiti/cloud/services/identity/keycloak/config/ActivitiKeycloakAutoConfiguration.java#L34

I can run and provide performance results between embedded and non-embedded groups, in a few days.

**Comment by igdianov** [comment]
To add more food for thought, we should consider removing Keycloak Admin Client wrapper from Rb at some point, because it represents security backdoor into Keycloak Realm via Rest Api using admin user credentials in the Rb configuration. 

Using access token to provide authenticated user groups and roles is much more secure and does not require leaking Keycloak admin user credentials via configuration. 

Also, JWS could be used to encrypt the JWT if there is need to protect sensitive information.

**Comment by rgauss** [comment]
> It is the best practice to limit TTL of the access token to under 60 seconds to mitigate any security risk.

We've discussed that as well and may change the default lifespan in the future, and ADF based apps will actually check for an active Keycloak session every 30 seconds to ensure no logout has occurred, but we may encounter use cases where even 1 min is too long.

> Here is the implementation of fallback KeycloakClientPrincipalDetailsProvider

Looks great, thanks.

> I can run tests and provide performance results comparison between embedded and non-embedded group claim, in a few days.

That would be very helpful, thanks.

> we should consider removing Keycloak Admin Client wrapper from Rb at some point, because it represents security backdoor into Keycloak Realm via Rest Api using admin user credentials provided in the Rb configuration properties.

We definitely don't want to expose 'super' admin credentials, though we will likely need a form of client credentials (hopefully rotating) for other reasons (one of which may be user impersonation) and can enable use the client service account to read the user / group information.

And again, we still need to accomodate the use case of a user being a member of 100s or 1000s of groups and I don't think we want to pack that into a JWT so we'll need a fallback at a minimum.

> Also, JWS could be used to encrypt the JWT if there is need to protect sensitive information.

You're probably referring to JWE, and we considered that as well, but are more likely to use obfuscated public tokens with a public-private token exchange at the API gateway in the future.

**Comment by igdianov** [comment]
> And again, we still need to accomodate the use case of a user being a member of 100s or 1000s of groups and I don't think we want to pack that into a JWT so we'll need a fallback at a minimum.

The custom group claim can be applied for realm's client configuration as needed, so it is possible to accommodate clients with large number of groups where token size is going to be an issue.

**Comment by rgauss** [comment]
Yes, that comment was in response to 'removing Keycloak Admin Client wrapper from Rb at some point'.

**Comment by mteodori** [comment]
@igdianov @rgauss let's try to have some results of embedded vs. non embedded groups performance first, I will organise a meeting for monday so we can take a decision on this thanks

**Comment by igdianov** [comment]
> @igdianov @rgauss let's try to have some results of embedded vs. non embedded groups performance first, I will organise a meeting for monday so we can take a decision on this thanks

Sounds good. I will have the results in ELK for Monday.

**Comment by igdianov** [comment]
For the record, here is the captured response time metrics for access token without groups (left) and with groups (right) claim in milliseconds: 

**Complete Task**
![image](https://user-images.githubusercontent.com/20428629/69097621-c38df580-0a0b-11ea-8432-084522a0af87.png)

**Claim Task**
![image](https://user-images.githubusercontent.com/20428629/69098702-f20cd000-0a0d-11ea-804e-e151c29e5498.png)

**Get Tasks**
![image](https://user-images.githubusercontent.com/20428629/69098754-11a3f880-0a0e-11ea-9997-71f23fb7a836.png)

The summary of different task requests for access token without group claim:

![image](https://user-images.githubusercontent.com/20428629/69097860-4d3dc300-0a0c-11ea-815c-1af65dbb4104.png)

And with embedded groups claim:

![image](https://user-images.githubusercontent.com/20428629/69097953-7bbb9e00-0a0c-11ea-8a25-6e1f48e8da46.png)

The test results show that access token without embedded groups is 8-10x slower vs access token with embedded groups.

**Comment by rgauss** [comment]
Excellent work!

Do you happen to have the numbers for the previous code which included the additional REST call to Keycloak to search by username?  I think on the call you said on the claim task was previously taking 1400 - 2000 ms?

**Comment by igdianov** [comment]
Yes, here is the capture of the Claim Task operation that made additional Search by user name Rest Api call to resolve subject UUID:

![image](https://user-images.githubusercontent.com/20428629/69162795-08fd0200-0aa2-11ea-9773-933c99a2c06f.png)
