### ISSUE TITLE
[Question] Claims of Activiti 6 vs Camunda

### ISSUE THREAD

**Issue by Marco-Sulla** [Activiti/Activiti#2825]
Hello all. I'm testing both Activiti and Camunda for the possible future use in substituition of our actual workflow engine.

I read this [claims](https://blog.camunda.com/post/2016/10/camunda-engine-since-activiti-fork/) about Camunda pros over Activiti 6. 

The parts that most interest me are full BPMN compliance and deadlock prevention. The author claims Activiti 6 is not full BPMN compliant. Furthermore, they claims that Activiti 5 had deadlock problems that Camunda fixed with a new persistence layer. It claims also that Activiti 6 has renewed the persistence layer, but had not resolved the deadlock issues.

What about Activiti 7? It fixes these problems? Can I use Sprig Boot with Activiti 7 with the processes created by the Activiti 6 app (I find the Activiti 7 Cloud editor very limitative)?

**Comment by Marco-Sulla** [comment]
(ಠ_ಠ)

**Comment by Marco-Sulla** [comment]
Well, since you not commented anything, I choose Camunda in the end.
You are yet in time to try to change my opinion.

**Comment by ggrnd0** [comment]
Good choice! 
But

Activiti use optimistic locking by default (only?). 
That means what with non-concurrent access activiti has minimal locking overhead.
But with concurrent access only one transaction will be committed. All other will fail.

Is it issue for you?  We use com.google.common.util.concurrent.Striped for lock on rootProcessId in single app instance.
In multi server deployments that can be solved with load balancing based on rootProcId/procDefKey/tenantId/etc...


About link and activiti6:
1 problem - not sure, they just have different design. 
https://github.com/camunda/camunda-bpm-platform/blob/master/engine/src/main/java/org/camunda/bpm/engine/impl/bpmn/behavior/FlowNodeActivityBehavior.java#L52

Logic inside ExecutionEntity? Thanks, NEVCER=)

**Comment by Marco-Sulla** [comment]
> with concurrent access only one transaction will be committed. All other will fail in case update/delete same entity.

Well, this seems to me a big problem and I don't understand why. You said you use a lock, so why discard the other transactions?

And what about BPMN compliance? It seems to me that Activiti 7 adopted the bpmn.io editor, the same Camunda uses. This means that Activiti 7 now is fully BPMN compliant?

Anyway I tried both Activiti 6 and 7. Camunda seems much simpler to use than Activity 6, and has the same power. Activity 7... well... I didn't understand it. I hope it's a work in progress, since it seems very bare to me.

**Comment by ggrnd0** [comment]
> Well, this seems to me a big problem and I don't understand why. You said you use a lock, so why discard the other transactions?

discard only without lock. With lock all fine...

> And what about BPMN compliance? It seems to me that Activiti 7 adopted the bpmn.io editor, the same Camunda uses. This means that Activiti 7 now is fully BPMN compliant?

Are u sure camunda 100.0000% BPMN2 compliant? 
bpmn.io demo do not have pools and lanes... and camunda do not execute them in scenario if they exists... activiti have same...

**Comment by mteodori** [comment]
Activiti 6.x is not actively maintained, please use 7.x core or cloud
