### ISSUE TITLE
How to disable security in Activiti 7

### ISSUE THREAD

**Issue by tlzjff** [Activiti/Activiti#2845]
We have another authentication system. So i want to disable activiti security, I tried something but it didn't work. For example,  I want to use the following code
@SpringBootApplication(exclude ={SecurityAutoConfiguration.class, org.activiti.spring.boot.SecurityAutoConfiguration.class} )
But the org.activiti.spring.boot.SecurityAutoConfiguration.class not exists in the activiti 7.
So is there another way?

**Comment by rock007** [comment]
me to

**Comment by LuomingXu** [comment]
me too

**Comment by rockjl** [comment]
me too

**Comment by ggrnd0** [comment]
Whick packages you use?
we plan to update 6->7 someday...

**Comment by rockjl** [comment]
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.activiti.dependencies</groupId>
                <artifactId>activiti-dependencies</artifactId>
                <version>7.1.0.M3.1</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>
<dependency>
            <groupId>org.activiti</groupId>
            <artifactId>activiti-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.activiti</groupId>
            <artifactId>activiti-image-generator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.activiti</groupId>
            <artifactId>activiti-json-converter</artifactId>
        </dependency>

**Comment by rockjl** [comment]
`<dependency>
            <groupId>org.activiti</groupId>
            <artifactId>activiti-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.activiti</groupId>
            <artifactId>activiti-image-generator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.activiti</groupId>
            <artifactId>activiti-json-converter</artifactId>
        </dependency>`

**Comment by rockjl** [comment]
`
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.activiti.dependencies</groupId>
                <artifactId>activiti-dependencies</artifactId>
                <version>7.1.0.M3.1</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>
<dependency>
            <groupId>org.activiti</groupId>
            <artifactId>activiti-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.activiti</groupId>
            <artifactId>activiti-image-generator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.activiti</groupId>
            <artifactId>activiti-json-converter</artifactId>
        </dependency>`

**Comment by rockjl** [comment]
springboot 2.1.7 RELEASE

**Comment by nichuanfang** [comment]
you can config '@SpringbootApplication(exclusion={SecurityAutoConfiguration.class})' upon your main class.

**Comment by gitouyoung** [comment]
Same problem, and `exclude = SecurityAutoConfiguration.class` does not work.
Any suggestion is appreciated.

**Comment by nandhagit** [comment]
Still I am not able to disable the activiti default security. Kindly help

**Comment by hoteye** [comment]
@SpringBootApplication(exclude = { 
		//SecurityAutoConfiguration.class 
		org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration.class,
        org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration.class 
		})

**Comment by hoteye** [comment]
The above method effective

**Comment by xiaomahu2021** [comment]
> @SpringBootApplication(exclude = { //SecurityAutoConfiguration.class org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration.class, org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration.class })


tk, but still show some security logs.
2022-05-01 11:07:06.457  WARN 16424 --- [           main] .s.s.UserDetailsServiceAutoConfiguration : 

Using generated security password: 9107d17e-dc6c-4a1d-b218-ab178cf468c0

This generated password is for development use only. Your security configuration must be updated before running your application in production.
