### ISSUE TITLE
Travis CI build takes a long time

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2849]
Looks like it takes a long time for each Travis build to download Maven artifacts from Spring, Maven Central and Alfresco Nexus repositories. I think we can try to improve Travis build time by configuring cache for $HOME/.m2 directory: https://docs.travis-ci.com/user/caching/

```
cache:
  directories:
  - $HOME/.m2
```

I have tested Travis build duration with .m2 cache. The improvement for subsequent Travis build for the same branch is 55%

![image](https://user-images.githubusercontent.com/20428629/62597382-b739be80-b89a-11e9-9425-29f516db147b.png)

**Comment by miguelruizdev** [comment]
this is how the ADF guys set cache directories in Travis:
https://github.com/Alfresco/alfresco-ng2-components/blob/development/.travis.yml#L89
We can just replicate it

**Comment by igdianov** [comment]
Yep, it makes sense to split the build into stages, so the cache stage warm up and update artifacts for running IT tests.

**Comment by robfrank** [comment]
I approved your pr, closing
