### ISSUE TITLE
Sources as maven artifacts 

### ISSUE THREAD

**Issue by campa** [Activiti/Activiti#2855]
Hi guys,
I'm using activiti libs as maven dependencies, i'd like to navigate activiti sources during my development, but they are not published along with maven activiti artifacts. 

I'm wrong or they are not available on maven repos ? 
If it is the situation, why they are not there, it seems there is a built-in way with maven...

It is really useful for developer, as me, having inline sources in the IDE. 
Can you suggest me an easy solution ?

Thanks
Stefano

**Comment by igdianov** [comment]
@campa Yes, the intermediate versions of Activiti sources are not published in Alfresco Nexus repository. We will discuss how to make it available for users and ourselves.

**Comment by campa** [comment]
If can help I have done it by myself and published that in our local maven repo, it is easy, it works out of box  only put this [plugin declaration](https://maven.apache.org/plugins/maven-source-plugin/usage.html)  in your parent pom  as below:

 ```
 <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <version>3.1.0</version>
        <executions>
          <execution>
            <id>attach-sources</id>
            <phase>verify</phase>
            <goals>
              <goal>jar-no-fork</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```
Invoking maven install it puts your sources along with bytecode jars.

Bye

**Comment by erdemedeiros** [comment]
Setting `performRealease` property (`-DperformRelease -Dgpg.skip`) when we are deploying the artifacts (https://github.com/Activiti/Activiti/blob/develop/Jenkinsfile#L51) should be enough. This will publish both sources and Javadoc jars.

**Comment by almerico** [comment]
For what repos we want to do this?

**Comment by igdianov** [comment]
I think we can set these properties globally in Jenkins via `MAVEN_OPTS` environment configuration. 

@almerico Can you give it a spin?

**Comment by igdianov** [comment]
> For what repos we want to do this?

Let try Activiti Core first

**Comment by almerico** [comment]
Ok will do

**Comment by almerico** [comment]
have to check if all propagated and sources uploaded
