### ISSUE TITLE
IdentityLinkEntity NullPointerException

### ISSUE THREAD

**Issue by dengcq2** [Activiti/Activiti#2856]
springmvc response List<ProcessDefinition>  invoke getIdentityLinks ，this getCommandContext()

is null , so  org.springframework.http.converter.HttpMessageNotWritableException: Could not write 
JSON: (was java.lang.NullPointerException); nested exception is 
com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference

**Comment by gebilaoman** [comment]
me too

**Comment by balsarori** [comment]
see https://github.com/Activiti/Activiti/issues/3646#issuecomment-1025532531
