### ISSUE TITLE
startProcessInstanceByMessage does not assign businessKey for process instance

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#2859]
I am using Activiti 7.0.0.SR1, and when I use startProcessInstanceByMessage it seems that the businessKey is doesn't stored in ACT_RU_EXECUTION table, as when i use startProcessInstanceByKey.

**Comment by igdianov** [comment]
The businessKey is not propagated because of a bug in RuntimeService.startProcessInstanceByMessage implementation.

**Comment by dimipapadeas** [comment]
@igdianov 
Thanks for informing me!

Until now I have found that in org.activiti.engine.impl.cmd.StartProcessInstanceByMessageCmd,  despite the fact that businessKey is a constructor argument and a global variable, it isn't used in method call:

```
 ProcessInstance processInstance = processInstanceHelper.createAndStartProcessInstanceByMessage(processDefinition, messageName, processVariables, transientVariables);
```
I think that may help in bugfixing.
