### ISSUE TITLE
Activiti-app (UI) customization

### ISSUE THREAD

**Issue by sinanasiriamirbande** [Activiti/Activiti#2874]
Hello,
I hope all is going well.

We have an integrated angular js and spring boot project. Our purpose is customizing the UI of Activiti-app in our project. Our customization in detail is some localization and Make project Rtl and call rest API to our spring boot back end(XML file). due to getting this goal we have copied web-app of Activiti-app to our project but we got some errors as you can find them at the following in the first step.

Event.observe is not a function in ORYX.
Cannot read property 'Command' of undefined in StencilController
translateFilterProvider <- translateFilter

**Comment by mteodori** [comment]
actviti-app is the old UI example in 6.x we do not maintain anymore as it relies on dated technologies like Oryx, I suggest you build your own UI in AngularJS using the ADF Activiti Cloud components:
* https://github.com/Alfresco/alfresco-ng2-components
* https://www.alfresco.com/abn/adf/docs/process-services-cloud/
