### ISSUE TITLE
Activiti engine mysql script not in sync 

### ISSUE THREAD

**Issue by mohghin** [Activiti/Activiti#2929]
starting from version 7.1.0.M3, there is a bug introduced when using mysql as db.
I think  activiti.mysql.create.engine.sql is not updated to reflect the last changes in data model.

> java.sql.SQLException: Unknown column 'VERSION_' in 'field list'
Query is: insert into ACT_RE_DEPLOYMENT(ID_, NAME_, CATEGORY_, KEY_, TENANT_ID_, DEPLOY_TIME_, ENGINE_VERSION_, VERSION_, PROJECT_RELEASE_VERSION_)
    values(?, ?, ?, ?, ?, ?, ?, ?, ?), parameters ['5bf8c11b-e4f5-11e9-83d7-00090faa0001','SpringAutoDeployment',<null>,<null>,'','2019-10-02 11:16:47.264',<null>,1,<null>]

**Comment by miguelruizdev** [comment]
Issue tracked in Jira: https://issues.alfresco.com/jira/browse/AAE-531

**Comment by hfye** [comment]
Is there any support for mariadb as well?

**Comment by miguelruizdev** [comment]
No, currently there is no support for MariaDB.
We support MySQL though, so maybe you can work around this if we don't hit any incompatibilities between the two: https://mariadb.com/kb/en/library/mariadb-vs-mysql-compatibility/

**Comment by 123lwq** [comment]
请问一下activiti7版本的数据库多数据源怎么设置？

**Comment by miguelruizdev** [comment]
Ni ne provizas tiun funkcion el la skatolo, rigardu ĉi tiun gvidilon pri kiel arkitekturi ĉi tiun solvon: https://www.javadevjournal.com/spring-boot/multiple-data-sources-with-spring-boot/

**Comment by alex1517** [comment]
Hi,
Is this fix included in the 7.1.0.M5 release from Nov 25? I am having the same issue using activiti-engine 7.1.0.M5 and mysql 8.0.17.
I cannot find the _VERSION_ column in the _ACT_RE_DEPLOYMENT_ table definition from activiti-engine-7.1.0.M5.jar!\org\activiti\db\create\activiti.mysql.create.engine.

**Comment by erdemedeiros** [comment]
Hi @alex1517, 
You're right, the fix is missing on 7.1.0.M5. It will come with M6.

Can you give it a try with the latest internal release (`7.1.142`)?

**Comment by alex1517** [comment]
Hi @erdemedeiros ,

I tried 7.1.141 version and it works. I cannot find 7.1.142 version in the activiti maven repository. 

Thank you

**Comment by yupanchen** [comment]
When use mysql or mariadb，You can add nullCatalogMeansCurrent=true in the spring.datasource.url

**Comment by klonhj2015** [comment]
When will 7.1.0.M6 be released.

**Comment by endypark** [comment]
so big defect, should kick the ass of the developer & tester.
3 month gone, this is still not fixed ? I did not find M6.

**Comment by endypark** [comment]
backwards the version to 7.1.0.M4 will be all right.
It should be a developer changed the INSERT code, but does not upgrade the CREATE code.

**Comment by mteodori** [comment]
thanks guys can you please open a PR with the fix so we can review?

**Comment by Find-wei** [comment]
when you changes the version   ,you should drop the  databases or tables when they are already existed.right?
otherwise , insert into questions still in there, Because the table structure has not changed;

**Comment by Find-wei** [comment]
demo is unfriendly  .I want  to learn something about activiti ,they suggest learn the latest version.ok let`s go;but can you give me a detailed description; I have to serarch for 6.document.I'm a rookie.When a newcomer wants to learn Activiti, can he get used to it quickly? Can he provide different documentation for different development methods?

**Comment by erdemedeiros** [comment]
Hi @Find-wei, what exactly are you trying to achieve? you can find some information about Activiti 7 here https://activiti.gitbook.io/activiti-7-developers-guide/. You're not supposed to drop the database in order to go to one version to another. You are trying to go from which version to which version?

**Comment by Find-wei** [comment]
I apologize for my earlier remarks，Maybe I was&nbsp; eager. I should calm down to&nbsp; &nbsp;study instead of complaining about anything.&nbsp;


---Original---
