### ISSUE TITLE
404 path":"/modeling-service/modeling-service/v1/projects"

### ISSUE THREAD

**Issue by bikabdel** [Activiti/Activiti#2944]
![toto](https://user-images.githubusercontent.com/38707032/66644847-da297b80-ec19-11e9-98bc-1250c819edfb.png)

**Comment by qin** [comment]
change to use version "7.1.M3" for now

**Comment by bikabdel** [comment]
@qin thank you so much, but i can't find the installer for it

**Comment by bikabdel** [comment]
Thank you @qin

**Comment by nicholasKC** [comment]
I also have this problem. I solve it. 
1. find nginx.conf file
cd <your path>/activiti/activiti-cloud-examples/docker-compose
2. open nginx.conf and find the configuration of modeling-service
change 'proxy_pass         http://$upstream/modeling-service/$1?$args;'
to 'proxy_pass         http://$upstream/$1?$args;'
3. make down
4. make modeler
access modeler again, there are no mistakes
