### ISSUE TITLE
ProcessDefinitionUtil.getProcess NullPointerException

### ISSUE THREAD

**Issue by anryHan** [Activiti/Activiti#2983]
version ： activiti-engine-7.1.0.M3.1
ProcessDefinitionUtil.java Line 54,
![image](https://user-images.githubusercontent.com/13831076/68926993-b5e52f80-07c1-11ea-81b9-447c1a88fd6d.png)

**Comment by ggrnd0** [comment]
You must not call any *Utils in any way.

try `reposituryService.getBpmnModel(...).getProcessById(...) // or getMainProcess()`

**Comment by balsarori** [comment]
ProcessDefinitionUtil can be only called in an active context. You try what @ggrnd0 suggested.
