### ISSUE TITLE
ORA-00904: "PROJECT_RELEASE_VERSION_": invalid identifier

### ISSUE THREAD

**Issue by pitesta** [Activiti/Activiti#3011]
Error using Activiti Engine 7.1.0.M5 version

**Comment by pitesta** [comment]
The field **PROJECT_RELEASE_VERSION_**is defined only in the create script of activiti.h2.create.engine.sql and not in others database script!

**Comment by zoltanpalfi** [comment]
Thanks for raising it! It was fixed as part of this PR: https://github.com/Activiti/Activiti/pull/3014
