### ISSUE TITLE
INSERT TABLE ACT_RE_DEPLOYMENT ERROR

### ISSUE THREAD

**Issue by 957398123** [Activiti/Activiti#3017]
SQL: insert into ACT_RE_DEPLOYMENT(ID_, NAME_, CATEGORY_, KEY_, TENANT_ID_, DEPLOY_TIME_, ENGINE_VERSION_, VERSION_, PROJECT_RELEASE_VERSION_) values(?, ?, ?, ?, ?, ?, ?, ?, ?)

**Comment by 957398123** [comment]
<dependency>
			<groupId>org.activiti</groupId>
			<artifactId>activiti-spring-boot-starter</artifactId>
			<version>7.1.0.M4</version>
		</dependency>

**Comment by 957398123** [comment]
this is h2 sql:
create table ACT_RE_DEPLOYMENT (
    ID_ varchar(64),
    NAME_ varchar(255),
    CATEGORY_ varchar(255),
    KEY_ varchar(255),
    TENANT_ID_ varchar(255) default '',
    DEPLOY_TIME_ timestamp,
    ENGINE_VERSION_ varchar(255),
    VERSION_ integer,
    PROJECT_RELEASE_VERSION_ varchar(255),
    primary key (ID_)
);

**Comment by 957398123** [comment]
this is mysql:
create table ACT_RE_DEPLOYMENT (
    ID_ nvarchar(64),
    NAME_ nvarchar(255),
    CATEGORY_ nvarchar(255),
    KEY_ nvarchar(255),
    TENANT_ID_ nvarchar(255) default '',
    DEPLOY_TIME_ datetime,
    ENGINE_VERSION_ nvarchar(255),
    primary key (ID_)
);

**Comment by 957398123** [comment]
Why does this happen?I'm confused.

**Comment by 957398123** [comment]
I am a rookie,Hope to get the right solution

**Comment by 957398123** [comment]
thanks

**Comment by ScathonLin** [comment]
I found the same problem .  I think this is a bug of 7.x , 
<img width="540" alt="image" src="https://user-images.githubusercontent.com/40821407/71269925-5d3e1f00-238b-11ea-8593-0b39d137bfaf.png">
there is no "VERSION_" defined in the activiti.mysql.create.engine.sql ,but ..we can found the VERSION in the deployment .xml 
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/40821407/71270106-b908a800-238b-11ea-9011-61f7e56044f1.png">

**Comment by boot-vue** [comment]
the bug  still not fixed

**Comment by boot-vue** [comment]
https://github.com/Activiti/Activiti/issues/2929#issuecomment-563989830

it will  fixed  in M6.
