### ISSUE TITLE
Configuring Environment: DOCKER_IP issues

### ISSUE THREAD

**Issue by blacng** [Activiti/Activiti#3046]
When I enter:

`make modeler`

I get this error:

> /bin/bash: -c: line 0: syntax error near unexpected token `('
> /bin/bash: -c: line 0: `echo Keycloak path  Your IP is here(not localhost)/auth'
> make: *** [infra] Error 2

I tried to edit the environmental variables: `touch .profile` and I entered: **export $DOCKER_IP = "<my_ip_address>"**

Please, how do I resolve this issue?

**Comment by dhrn** [comment]
replace `<my_ip_address>` with your actual IP address.

**Comment by blacng** [comment]
@dhrn: Thank you.

**Comment by aksh1618** [comment]
To clarify for any future confused users: `.env` file is located in the root of `docker-compose` directory of the repo
