### ISSUE TITLE
'MaxPermSize' param is replaced to 'MaxMetaspaceSize'

### ISSUE THREAD

**Issue by silverskyvicto** [Activiti/Activiti#3052]
Hi

Since MaxPermSize has been changed to MaxMetaspaceSize since Java 8, how about changing this argument?

https://github.com/Activiti/Activiti/blob/369777a8a215a4c17e487556d4842e67132132ac/pom.xml#L433

### Reference:
- [Java Platform, Standard Edition Tools Reference](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html)
- [Java SE 11 Tools Reference](https://docs.oracle.com/en/java/javase/11/tools/java.html#GUID-3B1CE181-CD30-4178-9602-230B800D4FAE)

**Comment by zoltanpalfi** [comment]
Hi!

Thanks for your contribution! PR opened with the change.
