### ISSUE TITLE
ProcessInstance was updated by another transaction concurrently

### ISSUE THREAD

**Issue by JulianHang** [Activiti/Activiti#3054]
Using a parallel gateway, two threads are used to perform two tasks, and a concurrent transaction exception occurs. Details can be coded.

```java
List<Task> tasks1 = taskService.createTaskQuery().processInstanceId(processInstance.getProcessInstanceId()).list();
    	
    	ExecutorService executors = Executors.newFixedThreadPool(2);
    	
    	executors.execute(new Runnable() {

			@Override
			public void run() {
		    	       taskService.complete(tasks1.get(0).getId(), null);
			}
    	});
    	
    	executors.execute(new Runnable() {

			@Override
			public void run() {
		    	     taskService.complete(tasks1.get(1).getId(), null);
			}
    	});
```
------------------------------------------------------------------------------------------------
```java
<process id="onboarding" name="onboarding" isExecutable="true">
    <extensionElements>
      <activiti:eventListener class="tech.zlia.activiti.MyEventListener"></activiti:eventListener>
    </extensionElements>
    <startEvent id="startOnboarding" name="Start" activiti:initiator="initiator">
      <extensionElements>
        <activiti:formProperty id="test" name="Test" type="string"></activiti:formProperty>
      </extensionElements>
    </startEvent>
    <userTask id="enterOnboardingData" name="Enter Data" activiti:assignee="${initiator}" activiti:candidateGroups="managers">
      <extensionElements>
        <activiti:formProperty id="fullName" name="Full Name" type="string"></activiti:formProperty>
        <activiti:formProperty id="yearsOfExperience" name="yearsOfExperience" type="long" required="true"></activiti:formProperty>
      </extensionElements>
    </userTask>
    <sequenceFlow id="flow1" sourceRef="startOnboarding" targetRef="enterOnboardingData"></sequenceFlow>
    <endEvent id="endevent1" name="End"></endEvent>
    <userTask id="asyncTask" name="Async Task"></userTask>
    <userTask id="waitTask" name="Wait Task"></userTask>
    <parallelGateway id="parallelgateway1" name="Parallel Gateway"></parallelGateway>
    <sequenceFlow id="flow5" sourceRef="enterOnboardingData" targetRef="parallelgateway1"></sequenceFlow>
    <sequenceFlow id="flow6" sourceRef="parallelgateway1" targetRef="asyncTask"></sequenceFlow>
    <sequenceFlow id="flow7" sourceRef="parallelgateway1" targetRef="waitTask"></sequenceFlow>
    <parallelGateway id="parallelgateway2" name="Parallel Gateway"></parallelGateway>
    <sequenceFlow id="flow8" sourceRef="asyncTask" targetRef="parallelgateway2"></sequenceFlow>
    <sequenceFlow id="flow9" sourceRef="waitTask" targetRef="parallelgateway2"></sequenceFlow>
    <sequenceFlow id="flow10" sourceRef="parallelgateway2" targetRef="endevent1"></sequenceFlow>
  </process>
```
--------------------------------------------------------------------------------------------------
@salaboy thanks

**Comment by salaboy** [comment]
@JulianHang hi there.. I do not fully understand your question. If a concurrent exception occur, it only means that you need to retry to the failing operation. This will happen every time that two threads execute an operation that changes the state of a single process instance at the same time, as in your code.

**Comment by JulianHang** [comment]
> @JulianHang hi there.. I do not fully understand your question. If a concurrent exception occur, it only means that you need to retry to the failing operation. This will happen every time that two threads execute an operation that changes the state of a single process instance at the same time, as in your code.

@salaboy I use a parallel gateway and want to perform multiple tasks in parallel. I do n’t know if you understand?

**Comment by salaboy** [comment]
@JulianHang yes, I do understand, but that there is no way around that exception than retrying.. You can of course do multiple things in parallel as soon as they don't change the same process instance at the same time, while one transaction is being committed, the other will be rejected. As both touches the same rows in the Database. 

By the way, I don't work for the project anymore.. I would recommend to look for alternatives.

**Comment by JulianHang** [comment]
Thank you very much for your confusion, I really feel！

**Comment by JulianHang** [comment]
@salaboy I get, thank you very much!
