### ISSUE TITLE
Cannot find FormService in activiti 7 verison

### ISSUE THREAD

**Issue by oualidbouh** [Activiti/Activiti#3059]
Hello,

I am trying to upgrade activiti 6 to activiti 7 (because I am upgrading my spring boot app to 2.1.5 version). It seems that the FormService class got removed in activiti 7. are there any workarounds for this problem ?

Thank you in advance.

**Comment by ggrnd0** [comment]
TaskService

**Comment by mteodori** [comment]
it's been removed, just update user task properties
