### ISSUE TITLE
CommandContextCloseListener.closed called inside transaction

### ISSUE THREAD

**Issue by ggrnd0** [Activiti/Activiti#3076]
https://github.com/Activiti/Activiti/blob/8c3db4b575581aa79296a8d7f027e8b2085bb23e/activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cfg/ProcessEngineConfigurationImpl.java#L965-L983
Now CommandContextInterceptor and CommandContextCloseListener.closed run inside TransactionInterceptor (SpringTransactionInterceptor in my case)

Is it correct to run AsyncJobAddedNotification.closed() inside transaction?

**Comment by ggrnd0** [comment]
Ok, chain order is good. Transaction must be open while context closing...

But AsyncJobAddedNotification.closed() really must not be executed inside transaction...

**Comment by erdemedeiros** [comment]
@ggrnd0, I was looking at this issue and [AsyncJobAddedNotification](https://github.com/Activiti/Activiti/blob/develop/activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/jobexecutor/AsyncJobAddedNotification.java#L48) is using `TransactionPropagation.REQUIRES_NEW` which means that it should be using a new transaction to execute its unit of work. Could you, please, let us know which is the misbehaviour that you're noticing?

**Comment by ghost** [comment]
@erdemedeiros, in cases when *current* transaction is not commit-ish enough concurrent transaction will fail

**Comment by erdemedeiros** [comment]
@ggrnd0, do you have a reproducer? I guess that if you opened this issue it's because you faced an issue in one of your use cases. With a reproducer, it would easier to investigate and prove that the problem has been solved.

**Comment by ghost** [comment]
no. but we have about 5 issues with stucked tasks per year.
they  successfully unstuck after lock expired

**Comment by erdemedeiros** [comment]
@ggrnd0, this PR should fix the issue for `AsyncJobAddedNotification`:  https://github.com/Activiti/Activiti/pull/3367. Thank you for pointing it out!
