### ISSUE TITLE
Remove Snyk

### ISSUE THREAD

**Issue by mteodori** [Activiti/Activiti#3085]
doesn't seem to play well with multi module maven projects multiplying the vulnerabilities found per each subproject and the jobs on PRs

**Comment by almerico** [comment]
can you advice are there some configs or how you do it ?

**Comment by mteodori** [comment]
unfortunately you have to go one pom after the other in the web UI

**Comment by mteodori** [comment]
I deleted the account should have done everyting, we still have to remove the badges

**Comment by mteodori** [comment]
remove badge from non archived repositories only https://github.com/search?q=org%3AActiviti+snyk&type=Code
