### ISSUE TITLE
Refactor activiti-cloud-dependencies Makefile version resolution

### ISSUE THREAD

**Issue by igdianov** [Activiti/Activiti#3110]
in order to reduce time it takes to resolve artifact versions from pom.xml which runs `mvn` commands every time make is called. It will be much faster to use `grep`, i.e.

**Replace**
```bash
ACTIVITI_CLOUD_CONNECTORS_VERSION := $(shell mvn help:evaluate -Dexpression=example-cloud-connector.version -q -DforceStdout -f dependencies-tests/pom.xml)
```
**with**
```bash
ACTIVITI_CLOUD_CONNECTORS_VERSION := $(shell grep -oPm1 "(?<=<example-cloud-connector.version>)[^<]+" "dependencies-tests/pom.xml") 
```

It will improve pipeline time ~x2!

**Comment by mteodori** [comment]
the less maven the better

**Comment by almerico** [comment]
https://github.com/Activiti/activiti-cloud-dependencies/pull/606

**Comment by igdianov** [comment]
Closed via https://github.com/Activiti/activiti-cloud-dependencies/pull/606
