### ISSUE TITLE
Spike activiti-cloud monorepo

### ISSUE THREAD

**Issue by mteodori** [Activiti/Activiti#3112]
Create an activiti-cloud repository using git submodules to verify the feasibility of bringing all the activiti-cloud-starter projects together in one repo and check CI build time

1. https://github.com/Activiti/activiti-cloud-build
2. https://github.com/Activiti/activiti-cloud-api
3. https://github.com/Activiti/activiti-cloud-service-common
4. https://github.com/Activiti/activiti-cloud-runtime-bundle-service
5. https://github.com/Activiti/activiti-cloud-messages-service
6. https://github.com/Activiti/activiti-cloud-query-service
7. https://github.com/Activiti/activiti-cloud-audit-service
8. https://github.com/Activiti/activiti-cloud-modeling-service
9. https://github.com/Activiti/activiti-cloud-notifications-graphql-service
10. https://github.com/Activiti/activiti-cloud-acceptance-tests

**Comment by robfrank** [comment]
after creating the new mono-repo  we need to update 
https://github.com/Activiti/Activiti/blob/develop/.updatebotyml

**Comment by robfrank** [comment]
I think we need to include :
https://github.com/Activiti/activiti-cloud-connectors
https://github.com/Activiti/activiti-cloud-dependencies
