### ISSUE TITLE
Drop Java 8 support

### ISSUE THREAD

**Issue by mteodori** [Activiti/Activiti#3148]
As Java 11 is the current LTS version, it makes sense to drop Java 8:

- [x] remove java 8 from CI build matrix
- [x] update java.version and java.release in pom.xml
- [x] configure tools like LGTM that default to 8 so that they work with java 11

References:
- https://www.oracle.com/technetwork/java/java-se-support-roadmap.html
- https://blogs.oracle.com/java-platform-group/end-of-public-updates-is-a-process%2c-not-an-event
- https://en.wikipedia.org/wiki/Java_version_history
- https://adoptopenjdk.net/support.html
- https://www.azul.com/products/azul-support-roadmap/

**Comment by ScathonLin** [comment]
So, Activiti with version 7.0.0-SR1 can't build with maven with java8?

**Comment by mteodori** [comment]
@ScathonLin SR1 is released, if you mean for 7.1 final yes for the reasons mentioned in the issue
