### ISSUE TITLE
build source code with maven failed..java version is 8

### ISSUE THREAD

**Issue by ScathonLin** [Activiti/Activiti#3164]
I download the activiti source code with version 7.0.0.SR1 ,I want to build the sourcecode with maven manually, but failed,,,,My jdk version is 8, the error info is below:
![image](https://user-images.githubusercontent.com/40821407/75500337-94722180-5a07-11ea-8b86-ce65fae8c9fc.png)

help~~~
Is that the activiti with latest version has dropped java8 support??

**Comment by mteodori** [comment]
7.0.0.SR1 has that issue which was fixed in the 7.1 milestones but java 8 will be dropped soon in #3148 where you can find the reasons for the choice
