### ISSUE TITLE
app version  is  null

### ISSUE THREAD

**Issue by boot-vue** [Activiti/Activiti#3171]
Will this bug be fixed in activiti-spring-boot-starter 7.1.0.M7?

` private void checkProcessDefinitionBelongsToLatestDeployment(org.activiti.engine.repository.ProcessDefinition processDefinition) {
        if (!this.selectLatestDeployment().getVersion().equals(processDefinition.getAppVersion())) {
            throw new UnprocessableEntityException("Process definition with the given id:'" + processDefinition.getId() + "' belongs to a different application version.");
        }
    }`

**Comment by chithiencandy** [comment]
:))) 
i call {{gateway}}/v1/process-definitions/{process-id}/model. i taken message "Process definition with the given id: {id} belongs to a different application version.". it's not appeared in version 7.1.0.M5.  please guide me how to fix it?

**Comment by HBobertz** [comment]
I am having the same issue. They supposedly fixed this in 7.1.0.m6 by including a workaround. However even after updating to 7.1.0.m6 and verifying the workaround was included, I am still getting the error

**Comment by shiqingfu** [comment]
Starting the Process instance in activti-spring-oot-starter 7.1.0-m6 will throw "Process definition with the given id:'" + processdefinite.getid () + "' belongs to a different application version." exception,Is there a bug in the following code

![image](https://user-images.githubusercontent.com/30172201/82861594-c7b54580-9f4f-11ea-8fe7-0e89e78dd3a5.png)

    private void checkProcessDefinitionBelongsToLatestDeployment(org.activiti.engine.repository.ProcessDefinition processDefinition) {
        if (!this.selectLatestDeployment().getVersion().equals(processDefinition.getAppVersion())) {
            throw new UnprocessableEntityException("Process definition with the given id:'" + processDefinition.getId() + "' belongs to a different application version.");
        }
    }

**Comment by zoltanpalfi** [comment]
Yes, see this issue: https://github.com/Activiti/Activiti/issues/3165

As @CTI777 wrote there, probably it is because of missing either the version from the `default-project.json` manifest file, or missing the manifest file entirely from the resources.

**Comment by vegetarianinvestor** [comment]
Adding the `default-project.json` resolved the issue. What is the significance of this file and what does it contain?

Thanks
