### ISSUE TITLE
On the free jump of process nodes

### ISSUE THREAD

**Issue by 2738671** [Activiti/Activiti#3207]
Hi team, my project uses activiti7, how can I implement the node being approved to jump to the specified approved node. Although this is an illegal operation, but my business scenario encountered this situation, what are the good suggestions?

**Comment by CalvinY058** [comment]
**need to jump with command.**

        //find root
        ExecutionEntity executionEntity = executionEntityManager.findById(rootProcessInstanceId);
        //del
        executionEntityManager.deleteChildExecutions(executionEntity, this.reason);
        //create Child
        ExecutionEntity childExecution = null;
        if (executionEntity.isScope()) {
            childExecution = executionEntityManager.createChildExecution(executionEntity);
        } else {
            childExecution = executionEntity;
        }

        childExecution.setCurrentFlowElement(targetFlowElement);
        childExecution.setDeleteReason(this.reason);
        childExecution.setVariables(this.vars);
        
        commandContext.getAgenda().planContinueProcessInCompensation(childExecution);
