### ISSUE TITLE
Why is the comment interface marked expired

### ISSUE THREAD

**Issue by DemoCap** [Activiti/Activiti#3235]
Why [org.activiti.engine.task.Comment](https://github.com/Activiti/Activiti/blob/522163af2218dae9afe781b715e1eb5a6350925a/activiti-core/activiti-engine/src/main/java/org/activiti/engine/task/Comment.java) interface is marked expired, but there is no new prompt

**Comment by mteodori** [comment]
I guess you mean deprecated, some features have been marked as such and are scheduled for removal in future version as not belonging to the engine main functionality:

This is in the javadoc comment:
https://github.com/Activiti/Activiti/blob/develop/activiti-core/activiti-engine/src/main/java/org/activiti/engine/task/Comment.java#L26-L27
