### ISSUE TITLE
QTaskEntity

### ISSUE THREAD

**Issue by xfl0927** [Activiti/Activiti#3280]
where is the entity QTaskEntity？I can not find it!
import org.activiti.cloud.services.query.model.QTaskEntity;

**Comment by erdemedeiros** [comment]
@xfl0927, `org.activiti.cloud.services.query.model.QTaskEntity` is a generated class. You need to build [activiti-cloud-query-service](https://github.com/Activiti/activiti-cloud/tree/develop/activiti-cloud-query-service) and it will be generated under `activiti-cloud-services-query/activiti-cloud-services-query-model/target/generated-sources`.

**Comment by xfl0927** [comment]
Thanks
