### ISSUE TITLE
Wrong docker images used in activiti-cloud-application tags

### ISSUE THREAD

**Issue by mteodori** [Activiti/Activiti#3290]
For instance, https://github.com/Activiti/activiti-cloud-application/commit/252105daef3da73bd0a8fec1bf3afed3c992b63f references `runtime-bundle` and `activiti-cloud-connector` instead of `example-runtime-bundle` and `example-cloud-connector`.

**Comment by almerico** [comment]
https://github.com/Activiti/activiti-cloud-application/pull/80
