### ISSUE TITLE
Activiti Cloud table "process_definition" and "act_re_procdef"  is not sync

### ISSUE THREAD

**Issue by aresa7796** [Activiti/Activiti#3311]
Hi, guys!

I use Activiti Cloud 7.1.0-m7, I create a new deployment.

steps:

1. Start activiti-cloud-query service.
2. Start example-runtime-bundle service.
3. Run create a new deployment  unit Test.

Unit Test :

```java
@SpringBootTest(classes = RuntimeBundleApplication.class)
public class RuntimeBundleApplicationIT {

    private static final Logger logger = LoggerFactory.getLogger(RuntimeBundleApplicationIT.class);

    @Autowired
    private RepositoryService repositoryService;
    @Autowired
    private ProcessRuntime processRuntime;

    @Test
    public void contextLoads() throws Exception {
        repositoryService.createDeployment()
            .addClasspathResource("processes1/test01.bpmn20.xml")
            .deploy();
    }

}
```
Table "act_re_procdef" data:

id | _name | ...
-- | -- | --
test01:1:07346274-a494-11ea-9eb5-6a171befa292 | test01 |  
test01:2:33d3b98c-a494-11ea-8358-6a171befa292 | test01 |  
  |   |  

Table "process_definition" data:

id | _name |  
-- | -- | --
test01:1:07346274-a494-11ea-9eb5-6a171befa292 | Test01 |  
  |   |  
  |   |  

I try run again:

Table "act_re_procdef" data:

id | _name | ...
-- | -- | --
test01:1:07346274-a494-11ea-9eb5-6a171befa292 | test01 |  
test01:2:33d3b98c-a494-11ea-8358-6a171befa292 | test01 |  
test01:3:f5906fab-a494-11ea-82e3-6a171befa292 | test01 |  

Table "process_definition" data:

id | _name |  
-- | -- | --
test01:1:07346274-a494-11ea-9eb5-6a171befa292 | Test01 |  
test01:2:33d3b98c-a494-11ea-8358-6a171befa292 | test01 |  
  |   |

**Comment by aresa7796** [comment]
@almerico help me,please

**Comment by almerico** [comment]
@erdemedeiros @jesty guys do you know something about this ?

**Comment by erdemedeiros** [comment]
@aresa7796, Activiti Cloud was designed to work with automatic deployment for process definitions (meaning that your processes should be placed in a specific location. The default one is `src/main/processes`). You can add your process there and it will get automatically deployed. No need to call `repositoryService`. In this case, `process_definition` and `act_re_procdef` will be in sync.

**Comment by aresa7796** [comment]
@erdemedeiros Can I specific location is machine path? 
example: ~/processes 
Rather than springboot resources.

**Comment by erdemedeiros** [comment]
yes, you can specify a folder in your machine. It's using Spring `ResourcePatternResolver` to find the resources, so you can use whatever `ResourcePatternResolver` supports. You need to set the property `spring.activiti.process-definition-location-prefix` or the environment variable `SPRING_ACTIVITI_PROCESSDEFINITIONLOCATIONPREFIX`. For instance:

`spring.activiti.process-definition-location-prefix=file:/Users/username/processes/`

**Comment by aresa7796** [comment]
I understand, thanks~

**Comment by aresa7796** [comment]
Hi, @erdemedeiros 
I try to do this.
Steps:
1. update application.properties;

> spring.activiti.process-definition-location-prefix=file:/Users/xxx/processes/

2. start example-runtime-bundle service.
3. move *.bpmn20.xml to /Users/xxx/processes/ .

Result:
1. process not deployed.

I want don't stop service, and deployment process. How to do ?

**Comment by erdemedeiros** [comment]
Hi @aresa7796, yes, Activiti Cloud assumes that your set of process definitions is known beforehand (see https://github.com/Activiti/Activiti/issues/2475). For now, if you want such behaviour you need to implement it. You could try to use your previous code (`repositoryService`), then inject [ProcessDeployedEventProducer](https://github.com/Activiti/Activiti/blob/develop/activiti-core/activiti-spring-boot-starter/src/main/java/org/activiti/spring/ProcessDeployedEventProducer.java) and call `processDeployedEventProducer.doStart()` to get query service and runtime bundle in sync.

**Comment by aresa7796** [comment]
I understand, I try do it. thanks~
