### ISSUE TITLE
Upgrade keycloak client to 10.0.2

### ISSUE THREAD

**Issue by miguelruizdev** [Activiti/Activiti#3369]
Important notes:
There's a bug with this version, already fixed, but only available for `11.0.0`, as reflected in this ticket: https://issues.redhat.com/browse/KEYCLOAK-14520

For `10.0.2` we need to apply a workaround, creating a custom `KeycloakSpringBootConfigResolver`

**Comment by mteodori** [comment]
see #3358

**Comment by miguelruizdev** [comment]
Closed as duplicated of: #3358
