### ISSUE TITLE
how to get task in ActivitiEventListener (activiti6)

### ISSUE THREAD

**Issue by billpu** [Activiti/Activiti#3397]
hello . I'm newbie of Activiti and java.I'm using activiti6 as flow engine.(spring boot 1.2.6)

my target: when a task is created ,system will assign a backup candidate (dynamically) for this task automatically. I'm using ActivitiEventListener to monitor "task created" event.("TASK_CREATED")

But it's strange. I did get event's executionId,but when I tried to get taskinfo by this executionId,it throwed exception (null).I checkd the "activiti-admin",the process have not been created indeed.

then,if I continue the program,at last, the task (the same executionId I caught before) will be created in "activiti-admin" (and database)

if I used "TASK_CREATED" incorrectly ?How can I get task in listener?
my understanding: "TASK_CREATED" event was created in memory not in database.am I correctly?

BTW: the first task in this process is a multi-instace(serial),I use "startProcessInstanceByKey(ProcessKey, variables)" to start the process.

any idea will be appreciated.
thanks

```
@Component
public class ComActivitiEventListener implements ActivitiEventListener, Serializable {
    protected TaskService taskService;

@Override
public void onEvent(ActivitiEvent event) {
    System.out.println(event.getType());
    if ("TASK_CREATED".equals(event.getType().toString()))
    {
        //SpringContextUtils
        taskService = SpringContextUtils.getBean(TaskService.class);
        //here I can get excutionId
        String executionId = event.getExecutionId();
        // I can not get task here, it's null
        Task task = taskService.createTaskQuery().executionId(executionId).singleResult();
        String taskId=task.getId();
        taskService.addCandidateUser(taskId, "backupuser");
    }
}
```

**Comment by sagarhebra** [comment]
Hi @billpu - obtaining a reference to TaskEntity object

       `if (!(event instanceof ActivitiEntityEventImpl)) {
            return;
        }

        ActivitiEntityEventImpl activitiEntityEventImpl = (ActivitiEntityEventImpl) event;
        Object entity = activitiEntityEventImpl.getEntity();

        if (!(entity instanceof TaskEntity)) {
            return;
        }

        TaskEntity taskEntity = (TaskEntity) entity;`

**Comment by billpu** [comment]
Hi @sagarhebra 
it works ,thanks for your help
