### ISSUE TITLE
Exception getting ProcessDefinitions when there are more than 1 versions in 7.1.0-M9

### ISSUE THREAD

**Issue by shkhadijah** [Activiti/Activiti#3425]
When getting list of process definitions and there are more than 1 version of a process definition deployed, I will get an exception. The exception is similar to this: "Query return 2 results instead of max 1".

We use the process runtime as embedded library, we exposed an API to list the active process definitions which calls the method ProcessRuntime.processDefinitions(Pageable pageable). 
From here, the exception is thrown by DeploymentQuery.executeSingleResult(CommandContext commandContext) as can be seen in the image below. 

I have also attached the full stack trace. 

![image](https://user-images.githubusercontent.com/70693797/92099915-afd24500-ee0d-11ea-8063-cb22bc0fd15f.png)
[activiti7.log](https://github.com/Activiti/Activiti/files/5167686/activiti7.log)

**Comment by wangjian1984** [comment]
I also have this problem

**Comment by temiotu** [comment]
should this query be modified to get the latest deployment when starting a new process.
I'm not sure what the use case would be for getting older deployments when starting a new process.

**Comment by erdemedeiros** [comment]
Hi @shkhadijah and @wangjian1984, are you using auto-deployment for the process definitions, or are you deploying them programmatically?

**Comment by erdemedeiros** [comment]
Also, if you guys can share the current entries for the deployment table that would be great!

**Comment by shkhadijah** [comment]
> Hi @shkhadijah and @wangjian1984, are you using auto-deployment for the process definitions, or are you deploying them programmatically?

@erdemedeiros I am using auto-deployment.

**Comment by erdemedeiros** [comment]
@shkhadijah and @wangjian1984, we were not able to reproduce the issue. However, [this PR](https://github.com/Activiti/Activiti/issues/3425) is bringing some improvements in that area.
