### ISSUE TITLE
hello can add “MariaDB ” to  DefaultDatabaseTypeMappings because MariaDB and mysql have almost the same syntax

### ISSUE THREAD

**Issue by cnlpj** [Activiti/Activiti#3485]

**Comment by balsarori** [comment]
Agree. Adding the following line here will do the trick --> https://github.com/Activiti/Activiti/blob/develop/activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cfg/ProcessEngineConfigurationImpl.java#L1131

`databaseTypeMappings.setProperty("MariaDB", DATABASE_TYPE_MYSQL);`

**Comment by balsarori** [comment]
Feel free to create a PR with this change

**Comment by cnlpj** [comment]
> Agree. Adding the following line here will do the trick --> https://github.com/Activiti/Activiti/blob/develop/activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cfg/ProcessEngineConfigurationImpl.java#L1131
> 
> `databaseTypeMappings.setProperty("MariaDB", DATABASE_TYPE_MYSQL);`

Ok thanks for your guidance！

**Comment by balsarori** [comment]
@cnlpj you can contribute back with your changes by creating a PR :)
