### ISSUE TITLE
Process diagram in the Modeling Application disappears in Chromium

### ISSUE THREAD

**Issue by chstrick** [Activiti/Activiti#3486]
I have installed Activiti on my local machine as described here https://activiti.gitbook.io/activiti-7-developers-guide/getting-started/getting-started-activiti-cloud/getting-started-docker-compose.
I also updated the Activiti version in the .env file to 7.1.0-M10.
The Docker containers are starting properly and I can login to the modeler application. 
In Chromium (version 86.0.4240.75) when adding a pool or further swim lanes nearly the whole process diagram disappears like on the picture below.
![Bildschirmfoto von 2020-11-18 10-55-19](https://user-images.githubusercontent.com/33372709/99676767-34317d00-2a79-11eb-9280-477ee257a715.png)
In Firefox (version 82.0.2) it is working well.

**Comment by erdemedeiros** [comment]
This should fix the issue https://github.com/Activiti/activiti-modeling-app/commit/b7fa2558cff7913fdb519f56b0eb83f7b3415127.
