### ISSUE TITLE
Can not successfully log in to modeling application

### ISSUE THREAD

**Issue by Mjasnik** [Activiti/Activiti#3490]
I have followed a [guide](https://activiti.gitbook.io/activiti-7-developers-guide/getting-started/getting-started-activiti-cloud/getting-started-docker-compose) and got everything set up.

After I log into modeling application, I immediately got this:
![image](https://user-images.githubusercontent.com/32698211/100259837-5895c980-2f51-11eb-9f70-23b74f974578.png)

I have tried default 7.1.0.M5 version as well as 7.1.0-M10 in .env file, the issue remains.

OS: CentOS 8.2 (updated)
Docker: lastest from docker-ce repo

Log attached.

**Comment by Mjasnik** [comment]
[activiti.log](https://github.com/Activiti/Activiti/files/5598410/activiti.log)

**Comment by mteodori** [comment]
you should be logging in with a user that has the ACTIVITI_MODELER role, I see you are logging as admin which doesn't have such a role

if you check the users in the keycloak realm https://github.com/Activiti/activiti-cloud-examples/blob/develop/docker-compose/activiti-realm.json only the modeler user has such a role and with default password
