### ISSUE TITLE
How to disable security in Activiti 7

### ISSUE THREAD

**Issue by songfs** [Activiti/Activiti#3504]
I am using activiti 7, I want to disable activiti security.   Our application is for Internal purpose and we dont need to add any security layer for this。
I tried to override WebSecurityConfigurerAdapter config method, but it is not working

```java
@Configuration
@EnableWebSecurity
public class SecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity security) throws Exception
    {
        security.httpBasic().disable(); // or security.csrf().disable();
    }
}
```

**Comment by mteodori** [comment]
Activiti is deeply integrated with the keycloak adapter as it requires users to assign tasks to, so this is not possible at the moment.

**Comment by SkyBadBoy** [comment]
This is a serious problem
