### ISSUE TITLE
Modeling-Service Schemas GET Problem

### ISSUE THREAD

**Issue by unibravoc** [Activiti/Activiti#3516]
GET http://192.168.1.29/modeling-service/v1/schemas/CONNECTOR 
GET http://192.168.1.29/modeling-service/v1/schemas/PROCESS-EXTENSION

**Docker Installation Steps:**
**for v.7.1.M11**

git clone https://github.com/Activiti/activiti-cloud-examples
cd activiti-cloud-examples/docker-compose
nano .env
DOCKER_IP=192.168.1.29 (MYLOCALMACHINEIP)

**Run Activity Cloud**
**make modeler**
http://192.168.1.29/modeling

and after:
**make application**

**Comment by unibravo** [comment]
Schemas not found? Why?

GET http://192.168.1.33/modeling-service/v1/schemas/UI 404
GET http://192.168.1.33/modeling-service/v1/schemas/FILE 404
GET http://192.168.1.33/modeling-service/v1/schemas/FORM 404
GET http://192.168.1.33/modeling-service/v1/schemas/SCRIPT 404
GET http://192.168.1.33/modeling-service/v1/schemas/TRIGGER 404
GET http://192.168.1.33/modeling-service/v1/schemas/CONNECTOR 404
GET http://192.168.1.33/modeling-service/v1/schemas/PROCESS-EXTENSION 404
GET http://192.168.1.33/modeling-service/v1/schemas/CUSTOM-FORM-WIDGET 404

**Comment by dhrn** [comment]
related https://github.com/Activiti/activiti-cloud-examples/issues/107
