### ISSUE TITLE
How to integrate the Activiti 7 Cloud with Alfresco 6.2?

### ISSUE THREAD

**Issue by unibravoc** [Activiti/Activiti#3517]
How to integrate the Activiti 7 Cloud with Alfresco 6.2 for Community Edition?

I have installed it over and over for 2 months. But the result is bad.
Is there anyone who can help me or give me an idea? Thank you from now.

Installed:
Alfresco 6.2 CE.
Activiti Cloud Modeling 7.1.M11 CE.
(with make modeler, make application)
ADF Workspace for Content and Process + Cloud

**Comment by mteodori** [comment]
Alfresco integration is part of Enterprise, please refer to your Alfresco account for any information
