### ISSUE TITLE
Can't Migrate Activiti 5 to Activiti 7

### ISSUE THREAD

**Issue by Raluca-Plugariu** [Activiti/Activiti#3518]
When upgrading from activiti engine 5.x to activiti engine 7, the schema is not being updated. 
**activiti.mysql.upgradestep.7100.to.710M6.engine.sql**  is not executed and in consequence some tables are missing APP_VERSION column. When you try to add new data in the database the logs are:
**Error updating database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'APP_VERSION_' in 'field list_'.**

The issue is because it looks for a different name of the step :
 Upgrade needed: 7100 -> 710-M6. Looking for schema update resource for component ‘engine’
-- no schema resource org/activiti/db/upgrade/activiti.mysql.upgradestep.7100.to.**710-M6**.engine.sql for upgrade

So the step's file name should be renamed from activiti.mysql.upgradestep.7100.to.710M6.engine.sql to activiti.mysql.upgradestep.7100.to.710-M6.engine.sql

**Comment by balsarori** [comment]
Fixed in #3519
