### ISSUE TITLE
How to access activiti7 with rest api

### ISSUE THREAD

**Issue by yijianguanzhu** [Activiti/Activiti#3555]
I don't seem to see the rest api module of activiti7

**Comment by mteodori** [comment]
REST API are available in Activiti Cloud, Activiti Core focuses on the engine, you can check the documentation

Here you see how you can use Postman: on https://activiti.gitbook.io/activiti-7-developers-guide/getting-started/getting-started-activiti-cloud#step-4-use-the-deployed-services
