### ISSUE TITLE
please deploy 7.1.0.M7-M11 to maven central.

### ISSUE THREAD

**Issue by XenoAmess** [Activiti/Activiti#3587]
latest version in maven central seems M6.
https://mvnrepository.com/artifact/org.activiti/activiti-engine

**Comment by mteodori** [comment]
thanks, please check release notes in documentation here:
https://activiti.gitbook.io/activiti-7-developers-guide/releases/7.1.0-m7

since M7 milestones are deployed to Alfresco Nexus

**Comment by XenoAmess** [comment]
> thanks, please check release notes in documentation here: https://activiti.gitbook.io/activiti-7-developers-guide/releases/7.1.0-m7
> 
> since M7 milestones are deployed to Alfresco Nexus

I know, but the internal network in my company allows getting dependencies from oss only
