### ISSUE TITLE
M12 version run program prompting circular reference problem

### ISSUE THREAD

**Issue by LiuXuyang04** [Activiti/Activiti#3650]
**Hello, I have a problem with the latest version, I hope to solve it.**

### Project run environment
Java Version: 11
SpringBoot Version:  2.4.1
Activiti Version: 7.1.0-M12

Pom file:

<dependency>
      <groupId>org.activiti</groupId>
      <artifactId>activiti-spring-boot-starter</artifactId>
      <version>7.1.0-M12</version>
 </dependency>

###  Problem Description

1. The project did not prompt any dependency conflict issues
2. The code compiles without any problems

I added activiti and springboot-start-web to the project, and an error message appeared when I started the project. I tried to solve it, and finally I found that if I remove springboot-start-web or remove the Autowired of converters in the ProcessModelAutoConfiguration file, the problem can be solved and the program can run, but I don't know what happened and the cause of the problem.
Hope to get help and learn more.

Error Log:
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'requestMappingHandlerAdapter' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Unsatisfied dependency expressed through method 'requestMappingHandlerAdapter' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mvcConversionService' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.format.support.FormattingConversionService]: Factory method 'mvcConversionService' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.activiti.api.runtime.conf.impl.ProcessModelAutoConfiguration': Unsatisfied dependency expressed through field 'converters'; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'stringToMapConverter': Requested bean is currently in creation: Is there an unresolvable circular reference?

**Comment by erdemedeiros** [comment]
It should be fixed by https://github.com/Activiti/Activiti/pull/3633. Please, give it a try with version 7.1.0-M13.
