### ISSUE TITLE
Hello, about Activiti6 integrated Spring Boot2.0, ActivitiEventListener problem

### ISSUE THREAD

**Issue by binnetwork** [Activiti/Activiti#3665]
When I use Actiti6.0, I try to trigger the Timer_Fired event for the timed boundary event, but it doesn't happen every time. Sometimes it does, sometimes it doesn't, but act_ru_timer_job does remove the associated timer

**Comment by mteodori** [comment]
Activiti 6.x is not actively maintained, please use 7.x core or cloud
