### ISSUE TITLE
流程完成报错

### ISSUE THREAD

**Issue by yaopeng921111** [Activiti/Activiti#3693]
完成最后一个任务后，报错如下。 是有一个变量未删除

### Cause: java.sql.SQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`qfy_crm`.`act_ru_variable`, CONSTRAINT `ACT_FK_VAR_EXE` FOREIGN KEY (`EXECUTION_ID_`) REFERENCES `act_ru_execution` (`ID_`))
org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.sql.SQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`qfy_crm`.`act_ru_variable`, CONSTRAINT `ACT_FK_VAR_EXE` FOREIGN KEY (`EXECUTION_ID_`) REFERENCES `act_ru_execution` (`ID_`))

**Comment by yaopeng921111** [comment]
最后一个任务的complete监听器中，设置流程参数 会造成此问题
delegateTask.setTransientVariable(varName, user);

**Comment by mteodori** [comment]
please file issues in english thank you
