### ISSUE TITLE
Activiti 6.0.0 : Why asyncExecutorThreadPoolQueueSize is 100 by default?

### ISSUE THREAD

**Issue by skystrix** [Activiti/Activiti#3728]
We are using Activiti 6.0.0

Since asyncExecutorCorePoolSize is 2 and asyncExecutorMaxPoolSize is 10 by default, and we want any job to be picked up as soon as it is in the queue, should not we keep the keep the queue size close to or same as core pool size?

Goal: We want our requests to get processed as soon as they get into the queue, even if new threads are need to be spawned to execute them. High concurrency.

**Comment by mteodori** [comment]
Activiti 6.x is not supported, please use 7.x Core or Cloud
