### ISSUE TITLE
7.1.0.M17 Problem with Gateway Expression Evaluation for Success and Failure Flow

### ISSUE THREAD

**Issue by saraarif** [Activiti/Activiti#3829]
Hi,

 In my project I am facing problem in evaluating gateway expression variables on runtime bundle application. I am using latest activiti Runtime bundle and activiti Connector Version. I have given WorkFlow Diagram, BPMN Expression and Connector Code below :

BPMN Workflow Diagram:

![5837f02c-cded-42ca-96ae-94e4dcf59263](https://user-images.githubusercontent.com/7188621/154305496-2d613bd9-d0e8-46d9-920e-1d893fdeb150.jpg)

**My BPMN expression** is ${ input == 'false'}in Bpmn File

**Connector Code:**
In Gateway Parent process service task simply takes inboundVariables and returns them as outboundVariables inlcuding gateway variable.

results.put("input ", "false");
Message<IntegrationResult> message = IntegrationResultBuilder.resultFor(event, connectorProperties)
        .withOutboundVariables(results)
        .buildMessage();
integrationResultSender.send(message);

**Problem:**
Variable evaluation on exclusive gateway not working fine. Please guide me method, how to send process variables from connector 
for a gateway? How should I configure processes in flow diagram and how to code in connector to pass gateway variables in process definition

@salaboy

**Comment by nloke** [comment]
This issue is very similar to https://github.com/Activiti/Activiti/issues/3773

@salaboy

**Comment by saraarif** [comment]
activiti latest version resolve this problem.
