### ISSUE TITLE
Sequence of flowElementList

### ISSUE THREAD

**Issue by ChrisGray0626** [Activiti/Activiti#3883]
When I used `bpmnModel.getMainProcess().getFlowElements()` to get the flowElementList, I found the sequence of this list isn't the same as the sequence of the process definition, and then, I guessed that it depends on bpmn, because they have the same seq. However, after I altered the sequence of `<bpmndi:BPMNShape>` in bpmn, the seq of this list didn't change still.

**Comment by balsarori** [comment]
Flow elements are not ordered. The sequence is determined by following the outgoing flows of each element (```getOutgoingFlows```).

**Comment by balsarori** [comment]
You can start from ```bpmnModel.getMainProcess().getInitialFlowElement()```

**Comment by ChrisGray0626** [comment]
> Flow elements are not ordered. The sequence is determined by following the outgoing flows of each element (`getOutgoingFlows`).

But I could not affirm the order of this return:

1. sid-42d47dca-0ce6-4622-9650-eb27f3732c64(startEvent)
2. sid-e222354a-d5ee-48f6-89fa-a02550203556(2rd userTask)
3. sid-9c1db114-b852-4aab-a146-18fd5f612359(sequenceFlow between 2rd userTask and endEvent)
4. sid-1568ba8f-6630-4f42-b41f-2e914b1ed525(1st userTask)
5. sid-dc667f30-e36d-47b5-b0b7-25658b1fe8ae(sequenceFlow between 1st userTask and 2rd userTask)
6. sid-43277ba0-f153-41eb-b2a0-9ecf9d254193(endEvent)
7. sid-1ed7484a-7d55-49a8-8660-df3424170c7b(sequenceFlow between startEvent and 1st userTask)

And this is my bmpn:

```xml
<startEvent id="sid-42d47dca-0ce6-4622-9650-eb27f3732c64"/>
<sequenceFlow id="sid-1ed7484a-7d55-49a8-8660-df3424170c7b" sourceRef="sid-42d47dca-0ce6-4622-9650-eb27f3732c64"
              targetRef="sid-1568ba8f-6630-4f42-b41f-2e914b1ed525"/>
<userTask id="sid-1568ba8f-6630-4f42-b41f-2e914b1ed525" name="填报"/>
<sequenceFlow id="sid-dc667f30-e36d-47b5-b0b7-25658b1fe8ae" sourceRef="sid-1568ba8f-6630-4f42-b41f-2e914b1ed525"
              targetRef="sid-e222354a-d5ee-48f6-89fa-a02550203556"/>
<userTask id="sid-e222354a-d5ee-48f6-89fa-a02550203556" name="审核"/>
<sequenceFlow id="sid-9c1db114-b852-4aab-a146-18fd5f612359" sourceRef="sid-e222354a-d5ee-48f6-89fa-a02550203556"
              targetRef="sid-43277ba0-f153-41eb-b2a0-9ecf9d254193"/>
<endEvent id="sid-43277ba0-f153-41eb-b2a0-9ecf9d254193"/>
```

**Comment by ChrisGray0626** [comment]
> You can start from `bpmnModel.getMainProcess().getInitialFlowElement()`

thx, it's a really convenient function!

I reckon it does not seem to appear in any doc?

**Comment by balsarori** [comment]
Unfortunately, that part (BPMN models representation API) isn't well documented. But you can always check the code :)

I'll close this issue for now.
