### ISSUE TITLE
can not find 7.2.0 and  7.3.0 in https://repo1.maven.org/maven2/org/activiti/activiti-core-dependencies/

### ISSUE THREAD

**Issue by looyo** [Activiti/Activiti#3931]
can not find 7.2.0 and  7.3.0 in https://repo1.maven.org/maven2/org/activiti/activiti-core-dependencies/

**Comment by erdemedeiros** [comment]
Hi,

As stated in the [release notes](https://activiti.gitbook.io/activiti-7-developers-guide/releases/7.3.0) the artifacts are so far available on [Alfresco Nexus](https://artifacts.alfresco.com/nexus/content/repositories/activiti-releases/org/activiti/activiti-core-dependencies/7.3.0/).

**Comment by looyo** [comment]
> Hi,
> 
> As stated in the [release notes](https://activiti.gitbook.io/activiti-7-developers-guide/releases/7.3.0) the artifacts are so far available on [Alfresco Nexus](https://artifacts.alfresco.com/nexus/content/repositories/activiti-releases/org/activiti/activiti-core-dependencies/7.3.0/).

Which is the next GA version.
