### ISSUE TITLE
Validate display and displayName variables

### ISSUE THREAD

**Issue by jesty** [Activiti/Activiti#3933]
It is possible defining if a variable must be visible in deployed applications using the display flag and a human-readable display name, e.g.:

"Process_jEKhhV0rp": {
      "constants": {},
      "mappings": {},
      "properties": {
        "47b3a61f-02c5-4e7e-bafb-f95e1a71d23d": {
          "id": "47b3a61f-02c5-4e7e-bafb-f95e1a71d23d",
          "name": "test",
          "type": "string",
          "required": false,
          "model": {
            "$ref": "#/$defs/primitive/string"
          },
          "display": true,
          "displayName": "My name"
        }
      }

Please validate those two new properties in the backend side

**Comment by oliveralfresco2018** [comment]
@jesty Hi, Can you confirm if this needs adding to the release notes?
If so can you add a bit more of an explanation please?
Cheers
