### ISSUE TITLE
Fix call urls from swagger-ui on community applications

### ISSUE THREAD

**Issue by jsokolowskii** [Activiti/Activiti#3941]
The apis call are not working on community, with the change from Springfox to Springdoc we need set the server path as well. For instance, this is an env created by a PR [Swagger UI](https://gateway-pr-622-rabbit-n-d.activiti-test.envalfresco.com/rb/swagger-ui/index.html#/task-controller-impl/getTasks)
the curl  command is missing the rb :
curl -X 'GET' \
  'https://gateway-pr-622-rabbit-n-d.activiti-test.envalfresco.com/v1/tasks' \
  -H 'accept: application/hal+json' \
  -H 'Authorization: Bearer ...'

**Comment by oliveralfresco2018** [comment]
@jsokolowskii Does this need adding to the release notes ?

**Comment by jsokolowskii** [comment]
Hi, @oliveralfresco2018, it was a bugfix for swagger-ui of the community edition applications. It doesn't seem very relevant, but can be mentioned. Basically the swager-ui wasn't referencing the right backend paths.
