### ISSUE TITLE
Get user roles from Keycloak

### ISSUE THREAD

**Issue by Giovanni007** [Activiti/Activiti#3942]
We need an API to retrieve all the roles of a user. 
The API should work as a proxy and call a HxP or A keycloack API to get the roles and return them to the caller.

The response should be:

```
{
  "globalAccess": {
    "roles": [
      "ACTIVITI_USER",
      "ACTIVITI_DEVOPS"
    ]
  },
  "applicationAccess": 
    [
      {
        "name": "simpleapp",
        "roles": [
          "ACTIVITI_USER"
        ]
      },
      {
        "name": "myapp",
        "roles": [
          "ACTIVITI_USER"
        ]
      }
    ]
}
```

**Comment by oliveralfresco2018** [comment]
Hello @Giovanni007 
Does this need adding to the release notes?
If so what is the name of the API ?
Cheers

**Comment by Giovanni007** [comment]
@oliveralfresco2018 The API is `GET /v1/identity/roles`
