### ISSUE TITLE
Filter users by application (Keycloak)

### ISSUE THREAD

**Issue by Giovanni007** [Activiti/Activiti#3943]
Right now, in the people component, we have some logic that use KeyKloak APIs to retrieve only the users that have access to an application. 
Implement the same behaviour when using /indentity/users?search= adding the possibility to filter users by application.

**Comment by oliveralfresco2018** [comment]
@Giovanni007 Does this need adding to the release notes?
If so can we have a chat about what this actually means?
thanks.

**Comment by Giovanni007** [comment]
@oliveralfresco2018 Looking at the past release notes, I don't think we need to add this.
This part of the work we did and are doing to allow the use of other IAM services instead of Keycloak. (see https://github.com/Activiti/Activiti/issues/3916 from milestone 7.3 and past release notes https://activiti.gitbook.io/activiti-7-developers-guide/releases/7.3.0#api-changes)

With this issue, I'm only adding the ability to filter the /users by the "application" they are part of.
I guess this makes sense mostly in the enterprise version.

Feel free to contact me for further information.
Thank you.

**Comment by oliveralfresco2018** [comment]
Thanks @Giovanni007
