### ISSUE TITLE
make identity endpoints available to all the users

### ISSUE THREAD

**Issue by Giovanni007** [Activiti/Activiti#3951]
Right now, Identity endpoints in modeling-service are available only to users with role Modeler.
Make the endpoints available to all the authenticated uses

**Comment by oliveralfresco2018** [comment]
@Giovanni007 Does this need adding to the release notes?
If so can we have a chat about what this actually means?
thanks.

**Comment by Giovanni007** [comment]
No, this should not be added to the release notes
