### ISSUE TITLE
Process validation error in modeling app when using mapping type

### ISSUE THREAD

**Issue by pmartinezga** [Activiti/Activiti#3963]
When validating a project that contains a process with a mapping using the mapping type, we see errors like this in the log:

```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize Map key of type `org.activiti.cloud.modeling.api.process.ServiceTaskActionType` from String "mappingType": not a valid representation, problem: (java.lang.IllegalArgumentException) No enum constant org.activiti.cloud.modeling.api.process.ServiceTaskActionType.MAPPINGTYPE
```

I think there is a problem here because the `mappingType` can’t be converted to the enumerated class ServiceTaskActionType The enumeration only contains the values (https://github.com/Activiti/activiti-cloud/blob/070c1d31aa41551f65d0269e2101b9a5212d8beb/activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-api/src/main/java/org/activiti/cloud/modeling/api/process/ServiceTaskActionType.java#L27-L28 ):

- INPUT
- OUTPUT

This means that the mapping works correctly when we use the implicit mapping for a task because in that case, the mapping in the extensions looks like this:

```
"mappings": {
            "Task_0hkm1bw": {
                "inputs": {
                    "restUrl": {
                        "type": "variable",
                        "value": "str"
                    }
                }
            }
        }
```

But we can set the other types of implicit mappings like Map all inputs and outputs, map all inputs or map all outputs, that are placed in the `mappingType` attribute:

For example, for the option Map all inputs and outputs then the mapping looks like:

```
"mappings": {
            "Task_0hkm1bw": {
                "mappingType": "MAP_ALL"
            }
        }
```

For example, for the option Map all inputs variables then the mapping looks like:

```
"mappings": {
            "Task_0hkm1bw": {
                "mappingType": "MAP_ALL_INPUTS"
            }
        }
```

For example, for the option Map all outputs variables then the mapping looks like:

```
"mappings": {
            "Task_0hkm1bw": {
                "mappingType": "MAP_ALL_OUTPUTS"
            }
        }
```

As you can see, the mapping is not following the expected structure here https://github.com/Activiti/activiti-cloud/blob/070c1d31aa41551f65d0269e2101b9a5212d8beb/activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-api/src/main/java/org/activiti/cloud/modeling/api/process/Extensions.java#L39  so it is not possible to convert the received JSON into a valid Extensions object

**Comment by oliveralfresco2018** [comment]
Hello @pmartinezga Does this need to go into the release notes?
If so can we have a chat about what is going on here and what is an appropriate way of me explaining it. Cheers

**Comment by pmartinezga** [comment]
> Hello @pmartinezga Does this need to go into the release notes?
> If so can we have a chat about what is going on here and what is an appropriate way of me explaining it. Cheers

I don't think this is worth to be mentioned in the release notes as a new feature is a bugfix
