### ISSUE TITLE
how to use activiti7 in springboot3

### ISSUE THREAD

**Issue by karluto** [Activiti/Activiti#4217]
how to use activiti7 in springboot3

**Comment by solidarity-forever** [comment]
activiti use the `spring.factories` file to execute auto-configure. but in spingboot3, it is not supported. you can try to configure it manually.
and hope that the development team will provide support for springboot3 as soon as possible

**Comment by balsarori** [comment]
Springboot 3 support was added recently https://github.com/Activiti/Activiti/commit/f795c17fda6363b5b1b6b4ee3b49f60a6f1bfcdc

**Comment by WangLiNaruto** [comment]
@balsarori  hi,how to use activiti7 in springboot3，I tried to integrate Activiti7 in Springboot3, but it failed every time

**Comment by balsarori** [comment]
SB3 is supported in Activiti 8. No plans to add SB3 in Activiti 7
