### ISSUE TITLE
activiti-spring-boot-starter doesn't support Jakarta EE

### ISSUE THREAD

**Issue by coderhuang** [Activiti/Activiti#4324]
# **activiti-spring-boot-starter doesn't support Jakarta EE**

Hey there,my project based on spring boot 3.X and jpa.
I use the latest version of **activiti-spring-boot-starter**.
I don't find classfier for jakarta ee.
with JPA config need JPA EntityManageris that is Jakarta EE package API

Does anyone can resolve this issue?
thanks

**Comment by balsarori** [comment]
Hey, there is an on going effort to upgrade to spring boot 3. See --> https://github.com/Activiti/Activiti/pull/4313
You can help by providing feedback :)

**Comment by coderhuang** [comment]
great to hear that message.
appreciate your work.
keep it up,thanks
