### ISSUE TITLE
Did you abandon version 7. x and upgrade to version 8?

### ISSUE THREAD

**Issue by wangjian1984** [Activiti/Activiti#4446]
I see that version 8 and 0 have already been launched, does it mean that version 7 has been abandoned?

**Comment by erdemedeiros** [comment]
Hi, the version `8.0.0` was released mainly to leverage `JDK 17` and `Spring Boot 3`. No major changes related to Activiti itself. The version `7.x is` not abandoned, but it will be less actively maintained.

**Comment by CHkingshin** [comment]
Ok, my understanding is that if I just upgraded the java and springboot versions to java21 and springboot3.x, then I should use the 8.x series, because the difference between 7.x and 8.x is the difference between springboot and java versions？

**Comment by erdemedeiros** [comment]
Yes, that's correct @CHkingshin
