### ISSUE TITLE
Creating the ACT_HI_IDENTITYLINK table fails

### ISSUE THREAD

**Issue by doveylovey** [Activiti/Activiti#4491]
Environment: Windows, Activi-8.1.0, MySQL-8.0.30

Table creation error when using activiti version 8.1.0.
![image](https://github.com/Activiti/Activiti/assets/28882195/95b19e4a-2c3e-4cd1-98c7-6d4a135d048f)

**Comment by ankurgogate** [comment]
In MySQL there's no such a const `MAX` which defines the maximum column length.

The equivalent to varbinary(max) would LONGBLOB in MySQL:

http://dev.mysql.com/doc/refman/5.5/en/blob.html

**Comment by swaroopar** [comment]
Hi All, is there a solution or a workaround for this problem?
@igdianov Could you please help here? Change was with this commit - https://github.com/Activiti/Activiti/commit/68e3afe801d60c5f467d6be7d1d77628c9ebe6f7

**Comment by weiwangda2014** [comment]
How to solve this problem?

**Comment by balsarori** [comment]
Fixed.
