### ISSUE TITLE
Cannot access public URLs using POST method

### ISSUE THREAD

**Issue by tom-dal** [Activiti/Activiti#4515]
Due to CSRF enabling, it's not possible to access public URLs using an http verb different than GET.

**Comment by climber-shy** [comment]
可以使用CSRF令牌：在您的应用程序中实现CSRF令牌机制，以允许通过其他HTTP动词对公共URL进行访问。您可以在您的表单或API请求中包含带有有效期的CSRF令牌，并在服务器端验证令牌的有效性。

排除公共URL：将公共URL排除在CSRF保护机制之外，不要要求CSRF令牌。但请注意，这可能会使您的应用程序面临CSRF攻击的风险，请确保您已经实施了其他适当的安全措施来保护您的应用程序。
