### ISSUE TITLE
create table ACT_HI_IDENTITYLINK not work in version 8.2.0

### ISSUE THREAD

**Issue by weiwangda2014** [Activiti/Activiti#4567]
create table ACT_HI_IDENTITYLINK ( 
ID_ varchar(64), 
GROUP_ID_ varchar(255), 
TYPE_ varchar(255), 
USER_ID_ varchar(255), 
TASK_ID_ varchar(64), 
PROC_INST_ID_ varchar(64), 
DETAILS_ varbinary(max), 
primary key (ID_) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin

mysql can not support varbinary(max).

**Comment by balsarori** [comment]
it was fixed here --> https://github.com/Activiti/Activiti/pull/4557
