### ISSUE TITLE
BoundaryCancelEventActivityBehavior BUG

### ISSUE THREAD

**Issue by zy5651768** [Activiti/Activiti#4621]
activiti 8.3.0版本
![1711526315001](https://github.com/Activiti/Activiti/assets/16420091/e1401025-e56b-48c4-aede-a6ac585d2cc2)
当我发送消息已接收事件，触发取消结束事件。就报错了 
![1711526551456](https://github.com/Activiti/Activiti/assets/16420091/dff644ce-e3a6-471f-bbea-7e1cb5fae1d1)

throw new ActivitiException("No execution found for sub process of boundary cancel event " + boundaryEvent.getId());
subProcessExecution 是null
我debug发现 findChildExecutionsByProcessInstanceId获取的 processInstanceExecutions 只有1条数据，没有包含边界的子流程。可能已经被被删除了。

这个是activiti的程序代码的问题 还是我流程图画错了

**Comment by zy5651768** [comment]
流程图画错 补偿人任务不能是 task

**Comment by rizalalfarizi123** [comment]
is compensation event supported in v8.3.0 @zy5651768 ?
