### ISSUE TITLE
Patch fix(AAE-2166) to Activiti 6

### ISSUE THREAD

**Issue by 188888888** [Activiti/Activiti#4631]
Hi, we face this [issue 2666](https://github.com/Activiti/Activiti/issues/2666) on Activiti 6, I saw you have fixed it on [3367](https://github.com/Activiti/Activiti/pull/3367), so the question is has this fix been patched to Activiti 6? Or are you going to patch it to Activiti 6? If both of these answers are NO, please tell us how to fix it on project side, is there any workaround?

**Comment by balsarori** [comment]
Hi, no there is no plan to do any changes on 6.x. You can apply the fix in https://github.com/Activiti/Activiti/blob/6.x/modules/activiti-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/DefaultJobManager.java#L406
