### ISSUE TITLE
Activit web ui

### ISSUE THREAD

**Issue by zawarkhan1** [Activiti/Activiti#4757]
Hello I am new to activiti i want to understand do we have any web app where i can model and then execute the process.
Alfresco is one but it is not free and has poor support

**Comment by balsarori** [comment]
There is no UI in Activiti. Last UI provided was in 6.x but it's no longer supported.

**Comment by zawarkhan1** [comment]
what is the difference between alfresco and activiti.
So activiti is totally code based then ?
i was of idea that it would be similar to jbpm where i can model my flow then deploy it to some server and then depending on user tasks i can view it and do action accordingly
@balsarori

**Comment by balsarori** [comment]
Afresco (now part of Hyland) has a product built on Activiti open source called APS (Alfresco Process Services).  
For now, yes there is no UI in Activiti. Previously, there was this modeling app https://github.com/Activiti/activiti-modeling-app (now discontinued) and in 6.x (no longer supported) there is webapp https://github.com/Activiti/Activiti/tree/6.x/modules/activiti-ui/activiti-app

A web based UI is available in APS which is an enterprise software.

**Comment by zawarkhan1** [comment]
@balsarori for end user mentioned here: https://activiti.gitbook.io/activiti-7-developers-guide/overview/personas

How will they interact with activiti, till now my understanding is use eclipse/ activiti modeler app to get a flow diagram in bpmn.
then include that diagram in resources folder and write some code related to it in spring or your beans of runtime engine will take care of it.
However how do human tasks get fulfilled ?
for example hr has to approve some application so if there is no ui how will they see the request make some action for it and then approve it 

Any guidline on it would be helpful

**Comment by zawarkhan1** [comment]
> Activiti Cloud will first target Activiti Developers & Activiti DevOps which are in charge of setting up the infrastructure and making sure that Activiti Applications can be deployed to a cloud provider.

Does this mean that end user and stake holder will come in later but for now only developer bit is released by activiti ?
