### ISSUE TITLE
boundaryEvent does not support custom attributes?

### ISSUE THREAD

**Issue by molleafauss** [Activiti/Activiti#480]
I am generating a bpmn and needed to add custom attributes to some user tasks and boundaryEvents. Those extra attributes are needed by an UI so we could drive some rendering and actions available to a monitoring system based on such attributes.
It seems that ExtensionAttributes works fine on userTask elements, but don't show up in the XML when set on the boundaryEvents.

Can't say if this is on purpose or a bug.

Have a test case:
https://gist.github.com/molleafauss/5ea6ff35acee7538d2d8#file-customattributebug-java
this would be the java code which create a process with some custom attributes. In timerBoundary() we add such attribute to a boundaryEvent. We also add them on the UserTask

This is the resulting bpmn
https://gist.github.com/molleafauss/5ea6ff35acee7538d2d8#file-output-bpmn
as you see no pfx:customAttribute is present on the boundaryEvent.

I checked a bit the code and noticed that the call to 
BpmnXMLUtil.addCustomAttributes
which adds such attributes seems present only in UserTaskXMLConverter.convertXMLToElement()

Let me know if this is a bug or not.

**Comment by molleafauss** [comment]
Sorry had little time to look after this during the holiday period.
Just looked at it again, but have a little clarification. You said "extensionElements". I have issues with "extension**Attributes**".

This currently works:
```xml
    <boundaryEvent id="boundaryevent5" name="Timer" attachedToRef="usertask4" cancelActivity="false">
      <extensionElements>
        <pfx:extension>CustomValue</pfx:extension>
      </extensionElements>
      <timerEventDefinition>
        <timeDate>PT10M</timeDate>
      </timerEventDefinition>
    </boundaryEvent>
```
This doesn't
```xml
    <boundaryEvent id="boundaryevent5" name="Timer" attachedToRef="usertask4" 
         cancelActivity="false" pfx:extension="CustomValue">
      <timerEventDefinition>
        <timeDate>PT10M</timeDate>
      </timerEventDefinition>
    </boundaryEvent>
```

Are BPMN extensionAttributes supported on mostly all BPMN constructs or this holds only for extensionElements?

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
