### ISSUE TITLE
Process instance name is never persisted in table ACT_HI_PROCINST(for HistoricProcessInstance)

### ISSUE THREAD

**Issue by mengqhai** [Activiti/Activiti#499]
Start the process instance by using the ProcessInstanceBuilder and provide an instance name:
ProcessInstanceBuilder builder = ruService.createProcessInstanceBuilder();
builder.processDefinitionId(processDefinitionId);
builder.processInstanceName("Some process instance name");
ProcessInstance p = builder.start();

Then check the db table ACT_RU_EXECUTION and ACT_HI_PROCINST, you'll find the name column for ACT_RU_EXECUTION is filled with "Some process instance name", but name column of  ACT_HI_PROCINST is still null.
After the process instance is finished and archived, query the HistoricProcessInstance, you'll find the name field is null.  So now, you'll never know what the name of that process instance was.

**Comment by mengqhai** [comment]
You can also see the problem from the constructor of HistoricProcessInstanceEntity:
public HistoricProcessInstanceEntity(ExecutionEntity processInstance) {
    id = processInstance.getId();
    processInstanceId = processInstance.getId();
    businessKey = processInstance.getBusinessKey();
    processDefinitionId = processInstance.getProcessDefinitionId();
    startTime = Context.getProcessEngineConfiguration().getClock().getCurrentTime();
    startUserId = Authentication.getAuthenticatedUserId();
    startActivityId = processInstance.getActivityId();
    superProcessInstanceId = processInstance.getSuperExecution() != null ? processInstance.getSuperExecution().getProcessInstanceId() : null;
    
    // Inherit tenant id (if applicable)
    if (processInstance.getTenantId() != null) {
    	tenantId = processInstance.getTenantId();
    }
  }

The name field is totally ignored.

**Comment by mengqhai** [comment]
This issue can be easily reproduced by adding a test method in org.activiti.engine.test.history.HistoricProcessInstanceTest:

  @Deployment(resources = {"org/activiti/engine/test/history/oneTaskProcess.bpmn20.xml"})
  public void testHistoricProcessInstanceName() {
	  String piName = "Customized Process Instance Name";
	  ProcessInstanceBuilder builder = runtimeService.createProcessInstanceBuilder();
	  builder.processDefinitionKey("oneTaskProcess");
	  builder.processInstanceName(piName);
	  ProcessInstance processInstance1 = builder.start();
	  
	  HistoricProcessInstance historicProcessInstance = historyService.createHistoricProcessInstanceQuery().processInstanceId(processInstance1.getProcessInstanceId()).singleResult();
	  assertEquals(piName, historicProcessInstance.getName());
	  assertEquals(1, historyService.createHistoricProcessInstanceQuery().processInstanceName(piName).list().size());
  }

**Comment by jbarrez** [comment]
Indeed, test was failing. Fixed in the commit referenced.

**Comment by EduFrazao** [comment]
Folks, this fix was released?

**Comment by jbarrez** [comment]
No. On master currently, not yet released.

**Comment by EduFrazao** [comment]
I understand. There any expected date to release 5.17.1 release?

**Comment by jbarrez** [comment]
We're mostly stabilizing now. I would expect a new version in a few weeks rather than months.

**Comment by EduFrazao** [comment]
Very good. Thanks by your fast response and your effort.
