### ISSUE TITLE
TaskService.saveTask() always dispatches task TASK_ASSIGNED ActivitiEvent

### ISSUE THREAD

**Issue by mengqhai** [Activiti/Activiti#500]
I implemented an ActivitiEventListener and added it to the RuntimeService by RuntimeService.addEventListener(myListener, ActivitiEventType.TASK_ASSIGNED).  But I found 
TaskService.saveTask() always dispatches task TASK_ASSIGNED ActivitiEvent even though I was just updating the task description.
The root cause is in TaskEntity.update() and TaskEntity.setAssignee().

public void update() {
    // Needed to make history work: the setter will also update the historic task
    setOwner(this.getOwner());
    setAssignee(this.getAssignee(), true, false);  <--- Here hard coded second parameter dispatchAssignmentEvent to true
.......
}

public void setAssignee(String assignee, boolean dispatchAssignmentEvent, boolean dispatchUpdateEvent) {
......
      if(!StringUtils.equals(initialAssignee, assignee)) {
        fireEvent(TaskListener.EVENTNAME_ASSIGNMENT);
        initialAssignee = assignee;
      }

```
  if(commandContext.getProcessEngineConfiguration().getEventDispatcher().isEnabled()) {
    if(dispatchAssignmentEvent) { <-- Here doesn't care whether initialAssignee == assignee
        commandContext.getProcessEngineConfiguration().getEventDispatcher().dispatchEvent(
                ActivitiEventBuilder.createEntityEvent(ActivitiEventType.TASK_ASSIGNED, this));
    }
    ......
  }
```

}

**Comment by mengqhai** [comment]
Current I have to work around(with the dirty and ugly approach) by accessing the protected field assignee and initialAssignee using reflection and decide whether to ignore the TASK_ASSIGNED event in my ActivitiEventListener.
Something like this:
```java
	public boolean ignoreForWorkaroundBug500(Task task) {
		// workaround the Activiti bug #500:
		// https://github.com/Activiti/Activiti/issues/500
		try {
			Field assigneeField = ReflectionUtils.findField(TaskEntity.class,
					"assignee");
			Field initialAssigneeField = ReflectionUtils.findField(
					TaskEntity.class, "initialAssignee");
			assigneeField.setAccessible(true);
			initialAssigneeField.setAccessible(true);
			String assignee = (String) assigneeField.get(task);
			String initialAssignee = (String) initialAssigneeField.get(task);
			return StringUtils.equals(assignee, initialAssignee);
		} catch (Exception e) {
			logger.error("Failed to work around bug 500", e);
			return false;
		}
	}
```

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
