### ISSUE TITLE
Uploading activity to sonatype snapshots?

### ISSUE THREAD

**Issue by victornoel** [Activiti/Activiti#504]
Hi,

I was wondering why the current development version of Activiti is not uploaded on the sonatype snapshots mirror as it was in the past?

(I'm using https://oss.sonatype.org/content/repositories/snapshots/, is it correct?)

Thanks,

Victor

**Comment by jbarrez** [comment]
We don't upload snapshot versions in the past, that particular version was actually used for the Spring Boot demo work we did and such that people had a chance to play around with it before the actual release.

Is there anything in the current master you're looking for that you need the current snapshot?

**Comment by victornoel** [comment]
Hi,

I understand better.

Someone in our team (Petals ESB) is using the development version of
Activiti and waiting for fixes, and our continuous integration system uses
relies on the SNAPSHOT to be available for compiling and testing our
software.
But if it's not possible, it's ok, we will work around that in a way or
another :)

Thank you!

2015-01-26 15:59 GMT+01:00 Joram Barrez <notifications@github.com>:

**Comment by victornoel** [comment]
Hi,

Have you considered the possibility to do it then?

We contributed pull requests to Activiti (for example #570) and when it will be integrated we will need to continue development by relaying on the SNAPSHOT version, it would be better than compiling it ourselves to be sure we always have the latest version of Activiti in order to be able to release our code as soon as the first stable version of Activit including our needs is available.

Thank you for your time,

**Comment by jbarrez** [comment]
Every day is not what we're planning on the short term, but once we merged the pull request you mention we'll manually push a snapshot.

**Comment by victornoel** [comment]
Thanks, that's great. We will remind you about it by citing you in the PR
once it's merged then, and if that's OK, in other PR from us if we need it
:)

**Comment by jbarrez** [comment]
Yes, perfect :-)
