### ISSUE TITLE
.net needs this

### ISSUE THREAD

**Issue by mowan808** [Activiti/Activiti#515]
.net is not workflow for linux Depend on mono .can you help write  it for linux Depend on mono?

**Comment by tijsrademakers** [comment]
You can run Activiti on any system, Windows, Linux, Mac if there's a JRE installed. Rewriting Activiti in Mono is a huge exercise, are you willing and able to invest that much time?

**Comment by dmitryvk** [comment]
I'd like to point out that it's possible to run Activiti via IKVM/IKVMC. It works, but you'll have to write some adapters (e.g., to proxy JDBC calls to ADO.NET).
