### ISSUE TITLE
TaskService.complete  not have "outcome" arguments?

### ISSUE THREAD

**Issue by xinggg22** [Activiti/Activiti#516]
TaskService.complete  not have "outcome" arguments?
When the task have two or three outcome , how can I specify one outcome  that I want?

**Comment by jbarrez** [comment]
What use case is this: API? Explorer? Something else ... ?

**Comment by xinggg22** [comment]
I use Activiti API.

This is so trouble, because I have to add a ConditionExpression to my prodess definitation when the UserTask have two OutgoingFlows! 

And then,  I have to use the follow code to complete the task:
   variables.put("outcome", nextTransitionId);
   taskService.complete(taskId, variables);

This will destroy the program‘s consistence.
So, I think if the TaskService.complete method have a  "outcome" arguments is the best solution for this case..

**Comment by xinggg22** [comment]
I use Activiti API.

This is so trouble, because I have to add a ConditionExpression to my prodess definitation when the UserTask have two OutgoingFlows! 

And then,  I have to use the follow code to complete the task:
   variables.put("outcome", nextTransitionId);
   taskService.complete(taskId, variables);

This will destroy the program‘s consistence.
So, I think if the TaskService.complete method have a  "outcome" arguments is the best solution for this case..

Thanks for your commented..

**Comment by cheshenglin** [comment]
I think you should use an exclusive gateway after the user task and using TaskListener to set the "outcome" variable at the end of the user task. It is strange for a user task with more than one outgoing flows.

**Comment by xinggg22** [comment]
But use exclusive gateway I don't think is a good idea.
First of all, in my process, I have so many UserTask that have over 2 OutgoingFlows.(You konw that this is over 2, it mean some UserTask many have 3 or 4 OutgoingFlows) . If I use  exclusive gateway ,I will add to mnch exclusive gateway  to my process. 
And then, if  will make the process looks so complex.

Thanks for your commented.

**Comment by tijsrademakers** [comment]
the ActivityBehavior interface allows you to choose one of the outgoing sequence flows directly from the user task itself. You would have to implement your own version of the UserTaskActivityBehavior class and then implement the logic to choose the sequence flow you want to take next. Then you won't need any exclusive gateways in your process definition.

**Comment by xinggg22** [comment]
Thanks  tijsrademakers!

I found  UserTaskActivityBehavior the leave method..Finally, it run BpmnActivityBehavior.performOutgoingBehavior. So every outgoing will be "take"...


I think I can do this:

Add a method to TaskEntity.complete(taskId, variables,outcome); 
Add a method TaskEntity.complete(Map variablesMap, boolean localScope,String outcome);
Change the code  execution.signal(null, null); to  execution.signal(null, outcome);
At the UserTaskActivityBehavior add leave(ActivityExecution execution,,String outcome) When the signl use execution.signal(null, outcome);
At last add bpmnActivityBehavior.performDefaultOutgoingBehavior(execution,outcome);method..

And then  execution.take(transitionsToTake);that "transitionsToTake" is the outcome specified.

Can I fork  Activiti and then add the code  push it to the Activiti's master?

**Comment by jbarrez** [comment]
No, this is not something we want in the core. It goes against the BPMN 2.0 spec.
