### ISSUE TITLE
RuntimeService.getProcessInstanceEvents returns no events

### ISSUE THREAD

**Issue by dmitryvk** [Activiti/Activiti#523]
I have a process definition which uses event subprocess with message start event.
I start a process instance for this definition.
I call ProcessEngine.getRuntimeService().getProcessInstanceEvents(processInstanceId) (where processInstanceId contains the identifier of started process). It returns 0 events.

Table ACT_RU_EVENT_SUBSCR has a record that correspons to the process instance. In SQL queries log I see that Activiti executes SQL of the form "select * from ACT_HI_COMMENT where PROC_INST_ID = ? order by TIME_ desc" which is odd because it should query ACT_RU_EVENT_SUBSCR.

GetProcessInstanceEventsCmd.execute seems to the wrong query. The code for GetProcessInstanceEventsCmd.execute calls "commandContext.getCommentEntityManager().findEventsByProcessInstanceId(..)". I think that it should call "commandContext.getEventSubscriptionEntityManager().findSignalEventSubscriptionsByExecution(..)"

**Comment by jbarrez** [comment]
If you check the Event class being returned, you see that this is not matching the BPMN 2.0 events, but rather the events in the event stream as they appear in Explorer.
