### ISSUE TITLE
update logback logger classes

### ISSUE THREAD

**Issue by n0mer** [Activiti/Activiti#539]
* org.activiti.management.jmx.MBeanInfoAssembler uses 
```java
private static final Logger LOG = LoggerFactory.getLogger(DefaultManagementAgent.class);
```

* org.activiti.management.jmx.DefaultManagementMBeanAssembler
```java
private static final Logger LOG = LoggerFactory.getLogger(DefaultManagementAgent.class);
```

if this is not intentional - please update to relevant log classes

**Comment by n0mer** [comment]
and another (probably) copy-paste issue: org.activiti.management.jmx.mbeans.JobExecutorMBean
```java
@ManagedResource(description = "Process definition MBean")
```

should be smth. other, not "Process definition MBean"

**Comment by jbarrez** [comment]
cc @smirzai

**Comment by smirzai** [comment]
Thank you @n0mer @jbarrez  
Fixed in https://github.com/Activiti/Activiti/pull/540

**Comment by tijsrademakers** [comment]
Fixed
