### ISSUE TITLE
why 5.17.0 version   delete code for resolver flow label display problem

### ISSUE THREAD

**Issue by llk2256** [Activiti/Activiti#544]
BpmnJsonConverter.java

```
   // if sequence has a name, just add a label graphic info
  String flowName = JsonConverterUtil.getPropertyValueAsString("name", edgeNode);
  if (StringUtils.isNotEmpty(flowName)) {
    bpmnModel.addLabelGraphicInfo(edgeId, createGraphicInfo(0D, 0D));
  }
```

**Comment by jbarrez** [comment]
Not sure I'm following here .. what's the question/issue?

**Comment by xinggg22** [comment]
Is this : http://jira.codehaus.org/browse/ACT-1745  ?

**Comment by jbarrez** [comment]
Ok, you mean the zeroes there, right?
No idea if that would fix it (maybe the real values are set later on?). Would be good if you could try it out first and update here.

**Comment by xinggg22** [comment]
with pleasure...

**Comment by xinggg22** [comment]
In the class org.activiti.bpmn.converter.BaseBpmnXMLConverter
the method  change like this:
 
 

public void convertToBpmnModel(XMLStreamReader xtr, BpmnModel model,
			Process activeProcess, List<SubProcess> activeSubProcessList)
			throws Exception {
      ................

         if (parsedElement instanceof FlowElement) {

			FlowElement currentFlowElement = (FlowElement) parsedElement;
			currentFlowElement.setId(elementId);
			currentFlowElement.setName(elementName);

			if (currentFlowElement instanceof Activity) {

				Activity activity = (Activity) currentFlowElement;
				activity.setAsynchronous(async);
				activity.setNotExclusive(notExclusive);
				activity.setForCompensation(isForCompensation);
				if (StringUtils.isNotEmpty(defaultFlow)) {
					activity.setDefaultFlow(defaultFlow);
				}
			}
                       if (currentFlowElement instanceof SequenceFlow) {
				SequenceFlow sf = (SequenceFlow) currentFlowElement;
				GraphicInfo graphicInfo = new GraphicInfo();
				graphicInfo.setElement(sf);
				model.addLabelGraphicInfo(sf.getId(), graphicInfo);
			}

  ..............................
}

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding
