### ISSUE TITLE
activiti rest save comment utf-8 ?? #urgent #blocker 

### ISSUE THREAD

**Issue by savicprvoslav** [Activiti/Activiti#549]
Saving comment  using rest application where message value is on  Russian language saves only ???????. 

This is a HUGE blocker for us as our Russian clients are unable to use activiti and our app that depends on Activiti.

url: 
activiti-rest/service/runtime/tasks/2579670/comments

json:
{
    "message":"ру́сский язы́к"
}

version is : 5.17 

Thank you.

**Comment by jbarrez** [comment]
Please check if your Tomcat (or whatever server you are using) is running in the correct character encoding.

FYI: Adding 'urgent', 'blocker' or multiple question marks won't help answering an issue sooner. On the contrary.

**Comment by savicprvoslav** [comment]
Multiple question marks is what application saves into the database and returns back after get comments rest is called. Sorry if I was missundestood but " then it saves ????? " means this is 
how comment is saved Into the database :).

When we use explorer app it all works nice So we do not think it is mysql related.


We are using tomcat and filter is set in web.xml I will check to make sure and write back.

**Comment by savicprvoslav** [comment]
It turned our that we added filter  in web.xml ( both in activiti-rest and conf/web.xml) 
```
<filter>
        <filter-name>setCharacterEncodingFilter</filter-name>
        <filter-class>org.apache.catalina.filters.SetCharacterEncodingFilter</filter-class>
        <init-param>
            <param-name>encoding</param-name>
            <param-value>UTF-8</param-value>
        </init-param>
        <async-supported>true</async-supported>
    </filter>

     <filter-mapping>
        <filter-name>setCharacterEncodingFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>
```
also we added utf-8 in server.xml
```
  <Connector port="7753" protocol="HTTP/1.1"
               connectionTimeout="20000"  URIEncoding="UTF-8"
               redirectPort="8443" />

```

Also we noticed that Russian is working for tasks and properties related to task but on comments it is not :), any help is appreciated .

**Comment by savicprvoslav** [comment]
We have it fixed. 
 What was missing is:
JAVA_OPTS="$JAVA_OPTS -Djavax.servlet.request.encoding=UTF-8 -Dfile.encoding=UTF-8"
