### ISSUE TITLE
Cannot build Activiti

### ISSUE THREAD

**Issue by wepo** [Activiti/Activiti#583]
I've changed into directory distro and executed the command "ant clean distro" and the following error occured: "BUILD FAILED
/home/lukas/Development/GitRepos/Activiti/distro/build.xml:134: Warning: Could not find file /home/lukas/Development/GitRepos/Activiti/distro/target/zip/activiti-5.17.1-SNAPSHOT/wars/activiti-webapp-explorer2-5.17.1-SNAPSHOT.war to copy.".

I've seen, that there is the Version 5.18.0 in the modules and in the ant build.xml still there is 5.17.1. But if I change it to 5.18.0 another error occurs. So do you have some help for me?

**Comment by jbarrez** [comment]
Thanks, it was indeed failing. This commit https://github.com/Activiti/Activiti/commit/35738825a2364666676076d352e2aad6bec864a4 should fix it.
