### ISSUE TITLE
Http 'Content-type':'application/json' header cause CORS issue in a POST request

### ISSUE THREAD

**Issue by jotamorais** [Activiti/Activiti#587]
I'm using AngularJS to consume Activit REST resources. All GET operations works as expected but, when I try to POST to /runtime/process-instances with Content-Type:application/json, it fails on the preflight. As you can see, there's no 'Access-Control-Allow-Origin' in the response header.

![2015-05-08 17_29_07-activiti rest caller net](https://cloud.githubusercontent.com/assets/5201388/7544957/2dc08936-f5a8-11e4-8a9a-094d6fcd7205.png)

When I change the Content-Type to application/x-www-form-urlencoded;charset=utf-8, for example, the 'Access-Control-Allow-Origin' comes in the response header but as we know, my POST won't work as API expects it to have a content-type:application/json

![2015-05-08 17_39_01-activiti rest caller net](https://cloud.githubusercontent.com/assets/5201388/7545095/5d9daaca-f5a9-11e4-8e34-753e24c0d449.png)

How can I get around the issue?

Appreciate any input!

**Comment by jbarrez** [comment]
Is the Acces-Control-Allow-Origin something you configured on your webserver? I'm not sure if the Activiti REST api is responsible for that.

**Comment by jotamorais** [comment]
I'm facing the issue since the beginning (with a fresh and default Tomcat and Activiti installation). 
So, I thought it would then, be required to add CORS filter to Tomcat web.xml. And now, it looks like this:

```
  <!-- ==================== Built In Filter Mappings ====================== -->
    
	<!-- Add CORS Support for Tomcat -->
<filter>
    <filter-name>CorsFilter</filter-name>
    <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
    <init-param>
        <param-name>cors.allowed.origins</param-name>
        <param-value>*</param-value>
    </init-param>
    <init-param>
        <param-name>cors.allowed.methods</param-name>
        <param-value>GET,POST,HEAD,PUT</param-value>
    </init-param>
    <init-param>
        <param-name>cors.allowed.headers</param-name>
        <param-value>Content-Type,X-Requested-With,accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers</param-value>
    </init-param>
    <init-param>
       <param-name>cors.exposed.headers</param-name>
       <param-value>Access-Control-Allow-Origin,Access-Control-Allow-Credentials</param-value>
    </init-param>
    <init-param>
        <param-name>cors.support.credentials</param-name>
        <param-value>true</param-value>
    </init-param>
    <init-param>
        <param-name>cors.preflight.maxage</param-name>
        <param-value>10</param-value>
    </init-param>
</filter>
<filter-mapping>
    <filter-name>CorsFilter</filter-name>
    <url-pattern>/*</url-pattern>
</filter-mapping>
```

Even though (as I reported), it doesn't work for POST action.

**Comment by jbarrez** [comment]
If you run on the same domain, you shouldn't need to worry about CORS.
Or (as I do), run a local apache proxy in front. 

Is there a way I can try to reproduce this on a *vanilla* activiti rest war?

**Comment by jotamorais** [comment]
Yes, I agree and it would work running on the same domain but, the purpose of using a REST API is to be able to call from anywhere (out of boundaries).
To reproduce it, you can install Activiti on Tomcat 7.0.61, create a short process with couple of tasks and then, using a JS client (in my case, I'm using AngularJS) try to call the GET  /runtime/process-instances and later, try to POST to the same URL to start a process. When you try to POST, using the Content-Type: application/json, then you should get the same error I got.

You may argument that using REST Client browser extensions (like PostMan), it works - but that's because browser extension works differently (browser disable security checks for extensions).

**Comment by jbarrez** [comment]
> the purpose of using a REST API is to be able to call from anywhere (out of boundaries).

Not for javascript within the browser. Read up on http://en.wikipedia.org/wiki/Same-origin_policy

**Comment by jotamorais** [comment]
???

I think you didn't get it right. Same origin policy is meant to allow a script consume data only if both have the same origin (the script and the data it's trying to reach). That's where CORS come in handy - **to allow script reach data from different origin.**

For your reference: https://en.wikipedia.org/wiki/Same-origin_policy#Cross-Origin_Resource_Sharing

**Comment by jbarrez** [comment]
Do not worry, I do know what CORS is.

In any of the above, i cannot find where your javascript is running: on the same domain on or not. 
If you are running on the same domain, then you shouldn't be seeing the exceptions you see and something is wrong. Hence my first comment about using a proxy such that both reside on the same domain which is for example what we are using for https://activiti.alfresco.com (which is also an Angular application calling the REST api). 
Now, if you are not running on the same domain then you need to configure your web server to use CORS and there is very little the Activiti REST API can do about that in that case.

**Comment by ManusoftarHIBA** [comment]
Actually is Actititi REST API the one which should implement a ContainerResponseFilter to return the needed headers to allow CORS, specially if you are running it from GlassFish which doesn't have an out of the box CORS configuration support...

**Comment by skbelalmd** [comment]
@jotamorais,
Can you help me with how to pass the authentication header data (user name and password) with the get request.

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
