### ISSUE TITLE
5.17 + PG9.4 deployment PSQLException (order by  order by RES.ID_ asc )

### ISSUE THREAD

**Issue by dongcb678** [Activiti/Activiti#597]
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: syntax error at or near "order"
  位置：113
### Cause: org.postgresql.util.PSQLException: ERROR: syntax error at or near "order"

**Comment by dongcb678** [comment]
order by  order by RES.ID_ asc

**Comment by jbarrez** [comment]
How to reproduce? Which java query are you executing.

I'm assuming this is Postgres 9.4?

**Comment by dongcb678** [comment]
RepositoryService repositoryService = (RepositoryService) applicationContext.getBean("repositoryService"); 

Deployment deployment = repositoryService.createDeployment().addClasspathResource("little/ant/pingtai/activiti/QingJia.bpmn").deploy();
		
String deploymentId = deployment.getId();
		
long count = repositoryService.createProcessDefinitionQuery().deploymentId(deploymentId).count();
System.out.println(count);

-------------------------------------------
deployment  ProcessDefinition error  order by order by RES.ID_ asc
-------------------------------------------

**Comment by watano** [comment]
I find a same bug.

### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order by RES.KEY_ asc  
    LIMIT 30 OFFSET 0' at line 11
### The error may exist in org/activiti/db/mapping/entity/ProcessDefinition.xml
### The error may involve org.activiti.engine.impl.persistence.entity.ProcessDefinitionEntity.selectProcessDefinitionsByQueryCriteria_mysql-Inline
### The error occurred while setting parameters
### SQL: select distinct RES.*              from ACT_RE_PROCDEF RES            WHERE  RES.VERSION_ = (select max(VERSION_) from ACT_RE_PROCDEF where KEY_ = RES.KEY_                                              )           order by  order by RES.KEY_ asc       LIMIT ? OFFSET ?
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order by RES.KEY_ asc  
    LIMIT 30 OFFSET 0' at line 11
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order by RES.KEY_ asc  
    LIMIT 30 OFFSET 0' at line 11
### The error may exist in org/activiti/db/mapping/entity/ProcessDefinition.xml
### The error may involve org.activiti.engine.impl.persistence.entity.ProcessDefinitionEntity.selectProcessDefinitionsByQueryCriteria_mysql-Inline
### The error occurred while setting parameters
### SQL: select distinct RES.*              from ACT_RE_PROCDEF RES            WHERE  RES.VERSION_ = (select max(VERSION_) from ACT_RE_PROCDEF where KEY_ = RES.KEY_                                              )           order by  order by RES.KEY_ asc       LIMIT ? OFFSET ?
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order by RES.KEY_ asc  
    LIMIT 30 OFFSET 0' at line 11
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:122)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:113)
	at org.activiti.engine.impl.db.DbSqlSession.selectListWithRawParameter(DbSqlSession.java:426)
	at org.activiti.engine.impl.db.DbSqlSession.selectList(DbSqlSession.java:417)
	at org.activiti.engine.impl.db.DbSqlSession.selectList(DbSqlSession.java:407)
	at org.activiti.engine.impl.persistence.entity.ProcessDefinitionEntityManager.findProcessDefinitionsByQueryCriteria(ProcessDefinitionEntityManager.java:57)
	at org.activiti.engine.impl.ProcessDefinitionQueryImpl.executeList(ProcessDefinitionQueryImpl.java:288)
	at org.activiti.engine.impl.AbstractQuery.execute(AbstractQuery.java:162)
	at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:24)
	at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:57)
	at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
	at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:31)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:40)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:35)
	at org.activiti.engine.impl.AbstractQuery.listPage(AbstractQuery.java:143)
	at com.thinkgem.jeesite.modules.act.service.ActProcessService.processList(ActProcessService.java:71)

**Comment by tijsrademakers** [comment]
Which version of MySQL are you using that throws this error?

**Comment by winix** [comment]
Use mybatis 3.3.0 will throws this error.
Test with mysql 5.5.43 and h2 database.

**Comment by jbarrez** [comment]
But Activiti 5.17 uses mybatis 3.2.5. That might explain the problem.

**Comment by winix** [comment]
I checked Deployment.xml
```
    select distinct RES.* ${limitBetween}
    <include refid="selectDeploymentsByQueryCriteriaSql"/>
    ${orderBy}
    ${limitAfter}
```
I think problem caused by invalid orderBy parameter value

**Comment by jbarrez** [comment]
Why would that be invalid? 
Can you post a query on a vanilla 5.17 that leads to this error?

**Comment by winix** [comment]
I clone activiti master source and upgrade mybatis to new version 3.3.0, run mvn test on modules/activiti-engine, many tests failed.
```
Tests run: 1572, Failures: 110, Errors: 1299, Skipped: 0
```

**Comment by tijsrademakers** [comment]
Ok thanks for sharing this. Is there any specific reason why you would like to upgrade to MyBatis 3.3.0? Is Activiti not working ok for you with the MyBatis version we ship?

**Comment by winix** [comment]
I test mybatis new version and found this problem.
So we continue to use old mybatis version(3.2.8) now.

**Comment by tijsrademakers** [comment]
MyBatis 3.3.x is not yet supported

**Comment by hakamairi** [comment]
Why would you close the issue then?

**Comment by jbarrez** [comment]
Because Activiti currently does not work with MyBatis 3.3.x.

When we upgrade the MyBatis dependency of Activiti, we will make sure it works.  Until then, changing the MyBatis dependency version for Activiti is not possible.

**Comment by WenTao-Love** [comment]
I am also encountered such a problem!
I use mybatis3.3 + activiti5.18.0
OH my god

**Comment by jbarrez** [comment]
As said above, activiti does not support 3.3 yet. It will, in the future.
Let's also keep gods out of this.

**Comment by hakamairi** [comment]
@jbarrez Could you please create a feature request or an improvement ticket and link it to this one?

**Comment by tijsrademakers** [comment]
@hakamairi You can create an issue in our JIRA system (https://activiti.atlassian.net) and add a link to this github issue. We prefer if community members create the JIRA tickets.

**Comment by hakamairi** [comment]
@tijsrademakers Thanks for the pointer, I thought that github was the place to post issues.

Created an improvement ticket: https://activiti.atlassian.net/browse/ACT-4081
