### ISSUE TITLE
ACT-4021: Asynchronous tasks on model created via the AngularJS modeler are handled as synchronous ones

### ISSUE THREAD

**Issue by pmesmeur** [Activiti/Activiti#619]
On models designed with the AngularJS modeler, asynchronous tasks are handled by the engine as being synchronous

The problem comes from the conversion from JSON to XML. The value of boolean fields are processed by the function JsonConverterUtil.getPropertyValueAsBoolean(). This function works with values "Yes" or "No" but the JSON model has "True" or "False".
As JsonConverterUtil.getPropertyValueAsBoolean() cannot find "Yes" is considers that the boolean value is false.

The issue is corrected in the Activiti6 branch by revision 8ef406fa7405b5d64e8422a56c5dad7b1e6ec4e6:
Author: Tijs Rademakers <tijs.rademakers@gmail.com>
Date:   Wed Feb 25 10:26:07 2015 +0100

    Fix for signal and message boundary event cancel activity + Fix model save + Fix job executor issue in demo data configuration

**Comment by pmesmeur** [comment]
If the 5.17 version is supposed to continue to leave in parallel of the version 6, I would appreciate if this bug could be corrected

**Comment by jbarrez** [comment]
The commit you reference is actually on master, not on the 6 branch. So it's fixed.
