### ISSUE TITLE
mule fails to build

### ISSUE THREAD

**Issue by lukaswerner** [Activiti/Activiti#625]
Hey I've tried to build Activiti from source code for two hours now and I still get errors, so maybe you can help me. The following error is the current one:
```
[exec] [ERROR] Failed to execute goal on project activiti-mule: Could not resolve dependencies for project org.activiti:activiti-mule:jar:5.18.0-SNAPSHOT: The following artifacts could not be resolved: net.java.dev.stax-utils:stax-utils:jar:20080702, com.yourkit:yjp-controller-api-redist:jar:9.0.8: Failure to find net.java.dev.stax-utils:stax-utils:jar:20080702 in http://repository.mulesoft.org/releases/ was cached in the local repository, resolution will not be reattempted until the update interval of mulesoft-releases has elapsed or updates are forced -> [Help 1]
```

What should I do?

**Comment by jbarrez** [comment]
Not sure what to do ... the jar seems to be still up on repo's (eg https://repository-master.mulesoft.org/nexus/content/groups/public/net/java/dev/stax-utils/stax-utils/20080702/).

You're sure you don't have any corporate firewalls or whatever intervening?

**Comment by lukaswerner** [comment]
No I don't. I've tested in on a clean linux installation. The steps I have to do for compiling the stuff are simply change into directory "distro" and run there `ant clean distro`, right?

**Comment by jbarrez** [comment]
I tried it here with an empty maven repo, and indeed:

[ERROR] Failed to execute goal on project activiti-mule: Could not resolve dependencies for project org.activiti:activiti-mule:jar:5.18.0-SNAPSHOT: Failed to collect dependencies at org.mule.transports:mule-transport-vm:jar:3.5.0 -> org.mule.modules:mule-module-xml:jar:3.5.0 -> net.java.dev.stax-utils:stax-utils:jar:20080702: Failed to read artifact descriptor for net.java.dev.stax-utils:stax-utils:jar:20080702: Could not transfer artifact net.java.dev.stax-utils:stax-utils:pom:20080702 from/to codehaus (http://repository.codehaus.org): Failed to transfer file: http://repository.codehaus.org/net/java/dev/stax-utils/stax-utils/20080702/stax-utils-20080702.pom. Return code is: 410 , ReasonPhrase:Gone. -> [Help 1]


We'll look into it.

The best thing you probably can do for now is remove activiti-mule from the <modules> in the pom.xml

**Comment by lukaswerner** [comment]
Ok thanks for helping me! What is it exactly, do I need that for Activiti to work properly?

**Comment by jbarrez** [comment]
No, it is an optional module, for if you want to integrate Activiti with Mule

**Comment by ibakayoko** [comment]
I remember fixing it by updating the url to mule repository in the activiti-mule module.

The value i have in my pom.xml
```
 <repositories>
      <repository>
        <id>codehaus-mule-repo</id>
        <name>codehaus-mule-repo</name>
        <url>https://repository-master.mulesoft.org/nexus/content/groups/public/</url>
        <layout>default</layout>
      </repository>
  </repositories>
```
Below is the current value shipped in activiti

```
<repositories>
      <repository>
          <id>mulesoft-releases</id>
          <name>MuleSoft Releases Repository</name>
          <url>http://repository.mulesoft.org/releases/</url>
          <layout>default</layout>
      </repository>
  </repositories>
```

If you browse the two urls you will see that the contents are not the same:

http://repository.mulesoft.org/releases/ 
vs
https://repository-master.mulesoft.org/nexus/content/groups/public/

hope this will help you.

**Comment by lukaswerner** [comment]
Very cool, now it's running with the mule module in it :) Thanks a lot!

**Comment by vikpr** [comment]
It seems that this issue has came back, I was trying to build the 5.19.0.1 version and it fails with the same message. If you check the repo https://repository-master.mulesoft.org/nexus/content/groups/public/net/java/dev/stax-utils/stax-utils/ you'll see that the version 20080702 isn't there anymore.

**Comment by aarmijo** [comment]
It seems that it works using this in the pom.xml
`  <repositories>
      <repository>
          <id>mulesoft-releases</id>
          <name>MuleSoft Releases Repository</name>
          <url>https://repository.mulesoft.org/nexus/content/groups/public/</url>
          <layout>default</layout>
      </repository>
  </repositories>`

**Comment by shturec** [comment]
The Activiti 5.20 release still fails to build with profile distro.
That should be an easy fix - all you need to do is to change the current mule repo url in the activiti-mule pom witth the correct one: 

```
<repositories>
      <repository>
          <id>mulesoft-releases</id>
          <name>MuleSoft Releases Repository</name>
          <url>https://repository.mulesoft.org/nexus/content/groups/public/</url>
          <layout>default</layout>
      </repository>
  </repositories>
```

Details on how to reproduce:

mvn -Pdistro clean install
...
[INFO] Activiti - Mule .................................... FAILURE
...
[ERROR] Failed to execute goal on project activiti-mule: Could not resolve dependencies for project org.activiti:activiti-mule:jar:5.20.0: Failed to collect dependencies at org.mule.transports:mule-transport-vm:jar:3.5.0 -> org.mule.modules:mule-module-xml:jar:3.5.0 -> net.java.dev.stax-utils:stax-utils:jar:20080702: Failed to read artifact descriptor for net.java.dev.stax-utils:stax-utils:jar:20080702: Could not transfer artifact net.java.dev.stax-utils:stax-utils:pom:20080702 from/to codehaus (http://repository.codehaus.org): repository.codehaus.org: Unknown host repository.codehaus.org -> [Help 1]
