### ISSUE TITLE
<activiti:formProperty /> should supports dynamicAttributes

### ISSUE THREAD

**Issue by quaff** [Activiti/Activiti#628]
```xml
<activiti:formProperty id="reason" type="custom" required="true" key1="value1" key2="value2">
```
I want to customize formProperty with type="custom" and some extra information. currently It's not possible to define other attributes that not predefined by activiti.
you can refer to jsp tag 2.0 or freemarker macro or html5 dataset.

**Comment by kotslon** [comment]
Is not that what you want?
http://forums.activiti.org/content/custom-form-type
https://github.com/mateuszwenus/activiti-custom-form-types
https://www.google.com/#newwindow=1&q=activiti+custom+form+type

**Comment by quaff** [comment]
@kotslon ,thanks for response, I know how to custom form type, I need custom form type with extra information.

**Comment by kotslon** [comment]
I use 

```xml
<ns8:extensionElements>
    <ns6:formProperty id="input" name="choiceField" 
               required="true" type="enum" variable="input" writable="true">
        <ns6:value id="1" name="Again"/>
        <ns6:value id="2" name="Enough"/>
        <ns6:value id="_bp_newPerTask" name="false"/>
    </ns6:formProperty>
</ns8:extensionElements>
```

... and in my form renderer I treat all values with IDs starting with "_" as "extra information" and modify the renderer's behaviour according to them instead of showing them to my users.

**Comment by kotslon** [comment]
By the way, old Modeller by Signavio had a special field for every property of the form - "Type extension value". The new angular-based editor in 5.17 does not have it :( .

**Comment by quaff** [comment]
@kotslon , thanks for your advice, It is doable but not graceful. I'm still expecting dynamic attributes.

**Comment by tijsrademakers** [comment]
Feature requests should be created in our JIRA system
