### ISSUE TITLE
loopCounter is null in the first iteration

### ISSUE THREAD

**Issue by amitport** [Activiti/Activiti#636]
using activiti 5.17 and a collection based sequential multi-instance

**Comment by jbarrez** [comment]
Do you have an example process + unit test that demonstrates this problem?

**Comment by amitport** [comment]
the task process just has simple 

`<multiInstanceLoopCharacteristics isSequential="true" activiti:collection="${arr}" activiti:elementVariable="elm"/>`

additionally, this [issue](http://forums.activiti.org/content/multiinstance-loop-variable-execution-listener) seems related and has an example project
