### ISSUE TITLE
ORACLE: new bulk insert queries result in 'ORA-00911: invalid character'

### ISSUE THREAD

**Issue by reva** [Activiti/Activiti#642]
The new bulk insert queries added for oracle (using 'insert all' and 'select * from dual') result in 'ORA-00911: invalid character' with Oracle 11.2. It seems to be the trailing semicolon. Hard to reproduce in a test, I guess.

**Comment by reva** [comment]
Pul request: https://github.com/Activiti/Activiti/pull/643

**Comment by jbarrez** [comment]
You are correct. Actually, I still needed to port that commit to the v6 branch : https://github.com/Activiti/Activiti/commit/bba9f2eff73a1b0d806b714502154c4295359d16

But good validation either way!

**Comment by tijsrademakers** [comment]
Fixed
