### ISSUE TITLE
Process definition suspensionState does not have effect on process instance creation sometimes,when Activiti is used in clusters

### ISSUE THREAD

**Issue by Gonster** [Activiti/Activiti#649]
Sorry for my English, it's not my mother tongue.

I met an inconsistency problem when using Activiti engine 5.15.1 in clusters. Assume that there are two java web apps, `App1` and `App2`, and each of them has an activiti instance running inside. `App1` and `App2` share the same database. 

Here we go. `App1` deploys a process definition (PB1) into the database, then `App2` starts `PB1`. `PB1` starts successfully. After that, `App1` suspends `PB1` and I check the suspensionState of `PB1` in the database, it has been set to 2. Nothing goes wrong until `App2` starts the suspended process definition `PB1`. It can be started by `App2` after `App1` suspended it.

But after restarting `App2`, `PB1` can't be started by Activiti engine. So I guess there is some kind of cache mechanism inside the engine that doesn't update the suspendState of process definition in this condition. After looking into the source code of the project (activiti-engine), I find that in the class [RuntimeServiceImpl.java](https://github.com/Activiti/Activiti/blob/master/modules/activiti-engine/src/main/java/org/activiti/engine/impl/RuntimeServiceImpl.java) the method `startProcessInstanceByKey` or other methods which start a process will eventually invoke the method `execute` in [StartProcessInstanceCmd.java#L66](https://github.com/Activiti/Activiti/blob/master/modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/StartProcessInstanceCmd.java#L66). If the process is start by key, then `deploymentCache.findDeployedLatestProcessDefinitionByKey` will be called. [DeploymentManager.java#L117](https://github.com/Activiti/Activiti/blob/master/modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/deploy/DeploymentManager.java#L117), there are many similar methods reside in it. First it fetch the process definition data from database, then [resolveProcessDefinition](https://github.com/Activiti/Activiti/blob/master/modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/deploy/DeploymentManager.java#L154) is called. The method retrieves the definition directly from the cache according to the definition id. So if `PD1` is stored in the cache in `App2`, it seems that the definition retrieved will not be affected by the suspension operation performed in `App1`. 

So I change the source code:

``` java
  public ProcessDefinitionEntity resolveProcessDefinition(ProcessDefinitionEntity processDefinition) {
    String processDefinitionId = processDefinition.getId();
    String deploymentId = processDefinition.getDeploymentId();
    int suspensionState = processDefinition.getSuspensionState();
    processDefinition = processDefinitionCache.get(processDefinitionId);
    if (processDefinition==null) {
      DeploymentEntity deployment = Context
        .getCommandContext()
        .getDeploymentEntityManager()
        .findDeploymentById(deploymentId);
      deployment.setNew(false);
      deploy(deployment, null);
      processDefinition = processDefinitionCache.get(processDefinitionId);

      if (processDefinition==null) {
        throw new ActivitiException("deployment '"+deploymentId+"' didn't put process definition '"+processDefinitionId+"' in the cache");
      }
    }
    else {
        if (processDefinition.getSuspensionState() == suspensionState
                || (suspensionState != SuspensionState.ACTIVE.getStateCode()
                && suspensionState != SuspensionState.SUSPENDED.getStateCode())) {
            return processDefinition;
        }
        processDefinition.setSuspensionState(suspensionState);
    }
    return processDefinition;
  }
```

Althought I have run the code above, and it has solved my problem. But I'm still not sure about this. Do I have some misunderstanding about the source code, or if there are some better solutions to make the suspenstionState affect every app in the cluster? I'm still wondering if there are some other issues might have made it malfunctioning when I use activiti in clusters.

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding
