### ISSUE TITLE
access to activiti-spring-boot 5.18.0 via maven

### ISSUE THREAD

**Issue by maku** [Activiti/Activiti#650]
Is there a possibility to access activiti-spring-boot via maven in version 5.18.0?
I do not find such a version in the public maven repos....

**Comment by yvoswillens** [comment]
Hi Maku,

You should use this dependency;

```
<dependency>
	<groupId>org.activiti</groupId>
	<artifactId>activiti-spring-boot-starter-basic</artifactId>
	<version>${activiti.version}</version>
</dependency>
```

(as described here; http://activiti.org/userguide/index.html#springSpringBoot )

**Comment by yvoswillens** [comment]
I see the the dependencies are missing in the maven repo. 
I will investigate why they aren't there.

**Comment by maku** [comment]
Same problem with spring-boot-starter-rest-api, spring-boot-starter-actuator, spring-boot-starter-jpa. There is NO 5.18.0 in the public maven repos!!!

**Comment by maku** [comment]
O.k. saw that all mentioned dependencies are available ("aktiviti" prefix). 
Thank you

**Comment by jbarrez** [comment]
Spring Boot artifacts are available in the maven repository: http://mvnrepository.com/artifact/org.activiti/activiti-spring-boot-starter-rest-api/5.18.0

They are renamed vs the 5.17 version, as requested by the Spring Boot team (3th party libs should not start with 'spring-boot'). The 'activiti-' prefix was added.
