### ISSUE TITLE
In activiti spring boot, load process definitions whose names end with **.bpmn along with **.bpmn20.xml

### ISSUE THREAD

**Issue by vickysirwani** [Activiti/Activiti#655]
In ActivitiProperties.java, processDefinitionLocationSuffix is **.bpmn20.xml. Can we also add **.bpmn files?

**Comment by donovanmuller** [comment]
This has been implemented. See this commit: https://github.com/Activiti/Activiti/commit/fa50cb5b2939bfd6b66cd34b7a5ced84d5c1f887

**Comment by vickysirwani** [comment]
Thank you!
