### ISSUE TITLE
Bug in user select popup widget: Unable to add user to a group

### ISSUE THREAD

**Issue by bobonaut** [Activiti/Activiti#672]
There is a bug in activiti-webapp-explorer2 (activiti-5.18.0).
Whenever you want to add a user to a group i.e. fozzie to the admin group you can not select this user. This is also the case with all other places like: selecting a user for a task.

examples:
![image](https://cloud.githubusercontent.com/assets/4076121/9814162/1dfb6ad8-588c-11e5-99bd-46eddc3a25d8.png)
![image](https://cloud.githubusercontent.com/assets/4076121/9814172/2e81870c-588c-11e5-844e-4eb71269637b.png)

I've tried to find the issue but it seems the bug is located in the CustomWidgetset somewhere and these files are minified, which makes it quite impossible to find it.

**Comment by jbarrez** [comment]
If I recall correctly, the search is case sensitive. Have you tried searching with a uppercases G ?

**Comment by bobonaut** [comment]
Nope I didn't my fault. You are right I can find the users if Isearch with uppercase G.

This is not a bug then. Is it possible that the decompressed version of the code is committed? Could have found this myself. (Although should have thought of case sensitivity).

**Comment by jbarrez** [comment]
The compressed widget is a custom Vaadin widget, but that's actually not the code that is responsible for this. All the code for explorer is open and can be found here: https://github.com/Activiti/Activiti/tree/master/modules/activiti-explorer/src/main/java/org/activiti/explorer

**Comment by bobonaut** [comment]
Ok thank you for a quick reply and the help!
