### ISSUE TITLE
org.activiti.engine.ActivitiException: Entity does not exist

### ISSUE THREAD

**Issue by flybyray** [Activiti/Activiti#675]
The HistoricDetailQueryImpl::executeList method can be called from many places:
[public List<HistoricDetail> executeList(CommandContext commandContext, Page page)](https://github.com/Activiti/Activiti/blob/master/modules/activiti-engine/src/main/java/org/activiti/engine/impl/HistoricDetailQueryImpl.java#L108)

Here one possibility by DeleteDeploymentCmd:

```
        at org.activiti.engine.impl.variable.JPAEntityVariableType.getValue(JPAEntityVariableType.java:79)
        at org.activiti.engine.impl.persistence.entity.HistoricDetailVariableInstanceUpdateEntity.getValue(HistoricDetailVariableInstanceUpdateEntity.java:76)
        at org.activiti.engine.impl.HistoricDetailQueryImpl.executeList(HistoricDetailQueryImpl.java:129)
        at org.activiti.engine.impl.AbstractQuery.list(AbstractQuery.java:140)
        at org.activiti.engine.impl.persistence.entity.HistoricDetailEntityManager.deleteHistoricDetailsByProcessInstanceId(HistoricDetailEntityManager.java:34)
        at org.activiti.engine.impl.persistence.entity.HistoricProcessInstanceEntityManager.deleteHistoricProcessInstanceById(HistoricProcessInstanceEntityManager.java:58)
        at org.activiti.engine.impl.persistence.entity.HistoricProcessInstanceEntityManager.deleteHistoricProcessInstanceByProcessDefinitionId(HistoricProcessInstanceEntityManager.java:47)
        at org.activiti.engine.impl.persistence.entity.ExecutionEntityManager.deleteProcessInstancesByProcessDefinition(ExecutionEntityManager.java:51)
        at org.activiti.engine.impl.persistence.entity.DeploymentEntityManager.deleteDeployment(DeploymentEntityManager.java:76)
        at org.activiti.engine.impl.persistence.deploy.DeploymentManager.removeDeployment(DeploymentManager.java:200)
        at org.activiti.engine.impl.cmd.DeleteDeploymentCmd.execute(DeleteDeploymentCmd.java:41)
        at org.activiti.engine.impl.cmd.DeleteDeploymentCmd.execute(DeleteDeploymentCmd.java:24)
```

But for a delete deployment command it is not recommended to get all the values

https://github.com/Activiti/Activiti/blob/master/modules/activiti-engine/src/main/java/org/activiti/engine/impl/HistoricDetailQueryImpl.java#L129

it may result in an exception

```
org.activiti.engine.ActivitiException: Entity does not exist
```

**Comment by jbarrez** [comment]
I'm not yet following fully. Do you have a failing example/unit test?

**Comment by flybyray** [comment]
Maybe you can see the activiti mistake in a possible patch.
```
diff --git a/modules/activiti-engine/src/main/java/org/activiti/engine/impl/HistoricDetailQueryImpl.java b/modules/activiti-engine/src/main/java/org/activiti/engine/impl/HistoricDetailQueryImpl.java
index 47a40a6..7bbe8dc 100644
--- a/modules/activiti-engine/src/main/java/org/activiti/engine/impl/HistoricDetailQueryImpl.java
+++ b/modules/activiti-engine/src/main/java/org/activiti/engine/impl/HistoricDetailQueryImpl.java
@@ -17,6 +17,7 @@ import java.util.List;
 
 import org.activiti.engine.history.HistoricDetail;
 import org.activiti.engine.history.HistoricDetailQuery;
+import org.activiti.engine.impl.cmd.DeleteDeploymentCmd;
 import org.activiti.engine.impl.interceptor.CommandContext;
 import org.activiti.engine.impl.interceptor.CommandExecutor;
 import org.activiti.engine.impl.persistence.entity.HistoricDetailVariableInstanceUpdateEntity;
@@ -126,7 +127,9 @@ public class HistoricDetailQueryImpl extends AbstractQuery<HistoricDetailQuery,
           if (varUpdate.getVariableType() instanceof JPAEntityVariableType) {
             // Use HistoricJPAEntityVariableType to force caching of value to return from query
             varUpdate.setVariableType(HistoricJPAEntityVariableType.getSharedInstance());
-            varUpdate.getValue();
+            if (!(commandContext.getCommand() instanceof DeleteDeploymentCmd)) {
+              varUpdate.getValue();
+            }
           } else if (varUpdate.getVariableType() instanceof JPAEntityListVariableType) {
             // Use HistoricJPAEntityListVariableType to force caching of list to return from query
             varUpdate.setVariableType(HistoricJPAEntityListVariableType.getSharedInstance());
```

The point is you dont have to execute getValue() if you want to run a DeleteDeploymentCmd !!! At least getValue should not throw an exception in that case! Because no one is intrested in finding a JPAEntity Value at this point of execution!

**Comment by jbarrez** [comment]
The .getValue() was introduced here: https://github.com/Activiti/Activiti/commit/a3ebcbbd407676d4c558c2dbd8b4e7633981a0d2, and I'm assuming it was added for a valid reason back then.

I agree that the getValue is strange to have there. Try-catching it should be sufficient, no?

**Comment by flybyray** [comment]
Where do you want to do the try-catching?
- In my application code it is too late. I really want to delete the deployment! But activiti 
- In DeleteDeploymentCmd execution? is too late to

Maybe we should design a test case for it.
But I dont get it how activiti should work correctly. I found those methods in test cases:
```
org.activiti.engine.test.api.runtime.RuntimeServiceTest.checkHistoricVariableUpdateEntity(String, String)
org.activiti.engine.test.api.task.TaskServiceTest.checkHistoricVariableUpdateEntity(String, String)
```
There is conditional check 'historicVariableUpdate.getValue() == null' 
If historicVariableUpdate would hold a variableType [JPAEntityListVariableType] and has a not cached value it would go down to findEntity this way:
```
      org.activiti.engine.impl.persistence.entity.HistoricDetailVariableInstanceUpdateEntity.getValue()
    org.activiti.engine.impl.variable.JPAEntityVariableType.getValue(ValueFields)
  org.activiti.engine.impl.variable.JPAEntityMappings.getJPAEntity(String, String)
org.activiti.engine.impl.variable.JPAEntityMappings.findEntity(Class<?>, Object)
```
Maybe the problem is 'org.activiti.engine.impl.variable.JPAEntityMappings.findEntity(Class<?>, Object)'
```
    Object entity = em.find(entityClass, primaryKey);
    if(entity == null) {
      throw new ActivitiException("Entity does not exist: " + entityClass.getName() + " - " + primaryKey);
    }
```
Why entity may not be null? What about the testcases which call 'checkHistoricVariableUpdateEntity'?

In our application the deployments have old values in JPAEntityVariables which do not exist anymore. It is possible that em.find can return null.

**Comment by jbarrez** [comment]
I want to do the try catching at the getValue() in the HistoricDetailQueryImpl. 

It seems it is there to force the loading of a value. If the entity does not exist, then try catching it will catch that, and the exception won't bubble up. For entities that do exist, it just works as before.

We can't change the throwing of an exception in case of null to not throwing an exception: that would break backwards compatibility with many existing installations.

You could argue the fetching of the variables is not needed for deleteDeployment, which is true, from a performance perspective. Then again, deleting a deployment is an infrequent operation.

**Comment by flybyray** [comment]
thank you.
I can live with the try-catch on the getValue().
