### ISSUE TITLE
Start message events not active

### ISSUE THREAD

**Issue by agentnico** [Activiti/Activiti#677]
Hi,

I have encountered an issue while using start message events. They usually work fine but I ended up in a situation where they stop working. It seems that the engine doesn't re-create the subscription after removing a workflow version.

Here are some instructions in order to reproduce:
- Create and deploy a workflow with a start message event and an end event (message id is 'test')
- Trigger the 'test' event, the workflow runs fine
- Update the workflow by simply changing the message id to 'test2'
- Deploy the workflow, this is a new version of the previous one
- Trigger the 'test2' event, the workflow version 2 runs fine
- Now, remove the version 2, I expect the engine to enable the version 1
- Trigger the 'test' event, nothing happens and we get the following error:

{
  "message": "Bad request",
  "exception": "Cannot start process instance by message: no subscription to message with name 'test' found."
}

I checked the DB and event subscriptions are correctly updated when deploying a new version but not when removing one.

This issue reproduces on Activiti 5.17, 5.18 and 6beta. I used activiti-rest to do my test.

Here is an example of the XML I use:

``` xml
<?xml version='1.0' encoding='UTF-8'?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:activiti="http://activiti.org/bpmn" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" typeLanguage="http://www.w3.org/2001/XMLSchema" expressionLanguage="http://www.w3.org/1999/XPath" targetNamespace="StartEvent">
  <message id="test" name="test"/>
  <process id="uid-25daa6ec-ba96-43a9-af4d-0d2976b88a01" name="StartEvent" isExecutable="true">
    <endEvent id="uid-b2fe2f77-0073-4d1d-a516-e17ab6b4f63a" name="End event"/>
    <startEvent id="uid-68139f1f-2730-40b1-9c85-37f5031fe34c" name="Start Event">
      <messageEventDefinition messageRef="test"/>
    </startEvent>
    <sequenceFlow id="uid-80ad6c01-9936-4c86-b423-24226a09feb7" sourceRef="uid-68139f1f-2730-40b1-9c85-37f5031fe34c" targetRef="uid-b2fe2f77-0073-4d1d-a516-e17ab6b4f63a"/>
  </process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_uid-25daa6ec-ba96-43a9-af4d-0d2976b88a01">
    <bpmndi:BPMNPlane bpmnElement="uid-25daa6ec-ba96-43a9-af4d-0d2976b88a01" id="BPMNPlane_uid-25daa6ec-ba96-43a9-af4d-0d2976b88a01">
      <bpmndi:BPMNShape bpmnElement="uid-b2fe2f77-0073-4d1d-a516-e17ab6b4f63a" id="BPMNShape_uid-b2fe2f77-0073-4d1d-a516-e17ab6b4f63a">
        <omgdc:Bounds height="60.30000000000001" width="62.0" x="494.0" y="0.0"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape bpmnElement="uid-68139f1f-2730-40b1-9c85-37f5031fe34c" id="BPMNShape_uid-68139f1f-2730-40b1-9c85-37f5031fe34c">
        <omgdc:Bounds height="79.10000000000002" width="53.0" x="0.0" y="68.25"/>
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge bpmnElement="uid-80ad6c01-9936-4c86-b423-24226a09feb7" id="BPMNEdge_uid-80ad6c01-9936-4c86-b423-24226a09feb7">
        <omgdi:waypoint x="52.684243779160326" y="103.72135099407863"/>
        <omgdi:waypoint x="494.36937520173694" y="34.921249780511786"/>
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>
```

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding
