### ISSUE TITLE
Update javax.mail version to 1.5.3

### ISSUE THREAD

**Issue by rafaelso** [Activiti/Activiti#678]
Hi,

I have faced a problem while deploying Activiti on Wildfly-9.0.1 because the javax.mail implementation provided by the application server is at version 1.5.3 and Activiti uses 1.4.1. For what I could find there is an API clash between this versions [https://developer.jboss.org/thread/261565] .

Assuming more folks may be facing the same problem it would be good to update javax.mail.

**Comment by PascalSchumacher** [comment]
Activiti 5.19+ uses javax.mail 1.5.2, I guess that is close enough and this issue can be closed?

**Comment by rafaelso** [comment]
Sure.
