### ISSUE TITLE
Create activiti tables in another schema than public with PostgreSQL

### ISSUE THREAD

**Issue by jkeruzec** [Activiti/Activiti#680]
Hello,

I'm experiencing an issue with activiti 5.18.0. I'm trying to create activiti tables in a "work" schema in PostgreSQL.

The problem is that the creation of tables are always in "public" schema whereas I put all required parameters of schema on my datasource or activiti configuration. See below.

```java
springProcessEngineConfiguration.setDatabaseSchemaUpdate("true");
        springProcessEngineConfiguration.setDatabaseSchema("work");
        springProcessEngineConfiguration.setDatabaseCatalog("work");
        springProcessEngineConfiguration.setTablePrefixIsSchema(true);
        springProcessEngineConfiguration.setDatabaseTablePrefix("work.");
```

However, the select queries seems to be good, for instance :
```sql
select * from work.ACT_RE_DEPLOYMENT D where NAME_=? order by D.DEPLOY_TIME_ desc
```

Is there a method to create all table into a particular schema with activiti ?

I saw this in code :
 /**
   * In some situations you want to set the schema to use for table checks / generation if the database metadata
   * doesn't return that correctly, see https://activiti.atlassian.net/browse/ACT-1220,
   * https://activiti.atlassian.net/browse/ACT-1062
   */
  protected String databaseSchema = null;

Thanks,

**Comment by jbarrez** [comment]
Looking at the code, it seems the _databaseSchema_ setting is only used for verifying the tables, not when creating the tables. I'll see if I can fix the code to take it in account too when creating/droppings tables.

So currently, you'll have to apply the DDL yourself before first boot. The config settings above are correct in that case, as they are used when checking the tables to be present.

**Comment by jkeruzec** [comment]
Ok thank you ! hope we will have the fix soon.

As workaround, I used the search_path option of PostgreSQL to look into my default schema but it's just a workaround and not a proper way.

**Comment by jbarrez** [comment]
@jkeruzec : doing some digging into this issue, found that recent jdbc drivers allow to set the schema via the jdbc url (see https://jdbc.postgresql.org/documentation/94/connect.html#connection-parameters) like this : 

jdbc:postgresql://localhost:5432/mydatabase?currentSchema=myschema

Any reason why using the jdbc url is not a good choice for this case?

**Comment by jbarrez** [comment]
Closing this for now. Tested with a simple test application that uses the jdbcUrl above and the data ends up in the custom schema.

**Comment by brunojcm** [comment]
It doesn't seem a proper fix, but indeed it works.

**Comment by shalugin** [comment]
> Any reason why using the jdbc url is not a good choice for this case?

It's not a good choice. Because it's set default schema for all connections. If other part of application has different default schema it wouldn't work.

**Comment by codecracker2014** [comment]
@jbarrez  currently i'm using activiti 5.21.0 and i'm facing this DDL issue with prefix. Is there any fix available to to this issue?
