### ISSUE TITLE
Multi instance parallel task fails with empty collection

### ISSUE THREAD

**Issue by romainguay** [Activiti/Activiti#694]
A multi instance parallel task fails systematically with a PvmException("already taking a transition") when the collection is empty. However it works fine when when set as sequential.

I have created a unit test project to demonstrate, but I am not able to attach it to this post. Can you tell me how to share it?

**Comment by jbarrez** [comment]
That's odd, Github just boasted that they now allowed any type.
Alternative is putting it online on a github repo we can access.

**Comment by SergioLog10** [comment]
You can find the Unit test here https://github.com/Log10Solutions/empty-collection-test

**Comment by romainguay** [comment]
Hi Joram,

Here is the repo on git-hub:
https://github.com/Log10Solutions/empty-collection-test

Thank you!
Romain

**Comment by jbarrez** [comment]
@erikwinlof verified this test against the latest master. 
This has been fixed in the past by this commit https://github.com/Activiti/Activiti/commit/2767caef878dad48bcbd06102d0736556ce4ecb5
