### ISSUE TITLE
Delete the tasks that are running, causing the process instance to be unable to end？

### ISSUE THREAD

**Issue by tanyo520** [Activiti/Activiti#700]
for (TaskEntity tk : taskList){
				 //tk.setExecution(null);
				// tk.setExecutionId(null);
				 //tk.getExecution().end();
				 //tk.getExecution().remove()
				 tk.getExecution().deleteCascade("删除当前");
				 tk.getExecution().remove();
				 executionEntity.removeTask(tk);
				 commandContext.getTaskEntityManager().deleteTask(tk, rejectOrgin, true);
				 commandContext.getHistoricTaskInstanceEntityManager().deleteHistoricTaskInstanceById(tk.getId());
			 }
Delete the tasks that are running, causing the process instance to be unable to end?
Table [ACT_HI_PROCINST]  END_TIME_ is null

**Comment by jbarrez** [comment]
I don't understand what the question is here. What are you trying to do? What is failing? 

Closing for now. Please reopen with detailed instructions.
