### ISSUE TITLE
BpmnJsonConverter doesn't add execution listeners of StartEvent/EndEvent

### ISSUE THREAD

**Issue by ojkey** [Activiti/Activiti#714]
Simple example: 
1. Create new model in activiti-explorer.
2. Add execution listener to start event in activiti-modeler and save changes.
3. Export model and open it.
So StartEvent should look like this:
```xml
<startEvent id="Start">
    <extensionElements>
        <activiti:executionListener event="start" delegateExpression="#{testDelegate}">
        </activiti:executionListener>
    </extensionElements>
</startEvent>
```
But StartEvent hasn't any execution listeners:   
```xml
<startEvent id="Start"/>
```
Same bug was described [here](https://forums.activiti.org/content/executionlistener-startend-event-removedignored).
I found out that the problem is in module "Activiti - JSON Converter". I have changed if-else logic in class BpmnJsonConverterUtil and committed to github [bfa2511221e24507ab8cff73ce7c5539b0b973d7](https://github.com/ojkey/Activiti/commit/bfa2511221e24507ab8cff73ce7c5539b0b973d7)

Now it generates correct bpmn-xml.

**Comment by balsarori** [comment]
Tested on version 5.19.02 and it's working as expected. What version did you try?

**Comment by ojkey** [comment]
Thank you, I will check the new version next week. And this ticket was opened, when I tried version 5.18.0.
