### ISSUE TITLE
org.activiti.editor.language.json.converter.BaseBpmnJsonConverter.java#L422 no put enum.id to enumValues 

### ISSUE THREAD

**Issue by kfypmqqw** [Activiti/Activiti#743]
org.activiti.editor.language.json.converter.BaseBpmnJsonConverter.java#L422 no put enum.id to enumValues.after saved by process-editor, the value of enum.id changed to value of enum.name.

**Comment by kotslon** [comment]
See #703 and [topic on the forum](https://forums.activiti.org/content/loss-id-when-converting-bpmntojson).

**Comment by tijsrademakers** [comment]
Fixed
