### ISSUE TITLE
Forum not work

### ISSUE THREAD

**Issue by Fabryprog** [Activiti/Activiti#745]
Hello,

i cannot put new message into "Activiti-engine" forum. See the screenshot

![cattura](https://cloud.githubusercontent.com/assets/8210189/11391771/5a204192-9355-11e5-9a74-fe90c9dfa81e.PNG)

**Comment by paulhh** [comment]
Hi,

We'll look into it.  Many thanks for letting us know.

Paul.

**Comment by paulhh** [comment]
Is it working now?
