### ISSUE TITLE
Activiti license confusion

### ISSUE THREAD

**Issue by Belogron** [Activiti/Activiti#778]
I have a question concerning the licensing of the Activiti Engine, specifically of the [activiti-ui](https://github.com/Activiti/Activiti/tree/activiti6/modules/activiti-ui) module on the activiti6 branch:

The folder includes an [lgpl.txt](https://github.com/Activiti/Activiti/blob/activiti6/modules/activiti-ui/lgpl.txt) that contains both the LGPL and this text:
```
    Copyright 2005-2015 Alfresco Software, Ltd. All rights reserved.
    License rights for this program may be obtained from Alfresco Software, Ltd.
    pursuant to a written agreement and any use of this program without such an
    agreement is prohibited.
```

This copyright notice is neither compliant with the Apache license of the main Activiti project nor with the LGPL License found in the activiti-ui folder.
This notice occurs in at least 5 more files:
```
$ egrep -lir "agreement is prohibited" .
./modules/activiti-ui/activiti-app/src/main/webapp/editor/editor-app/editor/css/editor.css
./modules/activiti-ui/activiti-app/src/main/webapp/editor/editor-app/editor/oryx.debug.js
./modules/activiti-ui/activiti-app/src/main/webapp/idm/styles/style-idm.css
./modules/activiti-ui/activiti-app/src/main/webapp/scripts/app-cfg.js
./modules/activiti-ui/activiti-app/src/main/webapp/workflow/styles/style-workflow.css
./modules/activiti-ui/lgpl.txt
```
Many files have an LGPL notice inside, e.g.: [clazz.js](https://github.com/Activiti/Activiti/blob/activiti6/modules/activiti-ui/activiti-app/oryx-editor-code/scripts/clazz.js), [ActivitiEngineConfiguration.java](https://github.com/Activiti/Activiti/blob/activiti6/modules/activiti-ui/activiti-app/src/main/java/com/activiti/conf/ActivitiEngineConfiguration.java) and so on...

Does the LGPL license apply to every file inside the activiti-ui module? Is the other notice just a leftover from the Activiti Enterprise code, or am I not allowed to modify the code (in compliance with LGPL license) or even use the Activiti UI without a license from Alfresco?

With kind regards,

Belogron

**Comment by tijsrademakers** [comment]
Hi Belogron, All code in the activiti-ui module is LGPL, so the Alfresco copyright headers you've found should be replaced with the LGPL license header.
