### ISSUE TITLE
[HistoryService] wrong sort when using the parameter "includeProcessVariables"

### ISSUE THREAD

**Issue by charnet3d** [Activiti/Activiti#780]
Hi,

Using version **5.19.0**

I have a service that does the same as the historyService in the REST API, and uses the same sort and pagination calls:

> DataResponse dataResponse = new HistoricTaskInstancePaginateList(restResponseFactory, "")
>       .paginateList(allRequestParams, query, "taskInstanceId", historicSortProperties);

I find out that when I use the "includeProcessVariables" parameter I get a wrong sorting result, but without it the sorting works.

My query uses the following parameters: **finished=false**&**includeProcessVariables=true**&**sort=start**

Here's an example of the 'startDate' values of the tasks I get, for both cases (The one affected element is in bold) :
- With 'includeProcessVariables'

> Mon Jan 18 09:15:06 CET 2016
> Mon Jan 18 09:15:26 CET 2016
> Mon Jan 18 13:19:41 CET 2016
> Mon Jan 18 14:42:59 CET 2016
> **Tue Jan 19 11:15:35 CET 2016**
> Mon Jan 18 15:07:55 CET 2016
> Mon Jan 18 15:10:09 CET 2016
> Mon Jan 18 15:21:53 CET 2016
> Mon Jan 18 15:53:58 CET 2016
> Mon Jan 18 15:57:49 CET 2016
> Mon Jan 18 15:57:59 CET 2016
> Mon Jan 18 16:43:53 CET 2016
> Mon Jan 18 18:00:08 CET 2016
> Mon Jan 18 18:11:47 CET 2016
> Mon Jan 18 18:11:48 CET 2016
> Mon Jan 18 18:11:50 CET 2016
> Mon Jan 18 19:59:34 CET 2016
> Tue Jan 19 09:27:31 CET 2016
> Tue Jan 19 09:29:57 CET 2016
> Tue Jan 19 09:31:20 CET 2016
> Tue Jan 19 10:44:01 CET 2016
> Tue Jan 19 10:45:48 CET 2016
> Tue Jan 19 11:16:51 CET 2016
> Tue Jan 19 11:38:54 CET 2016
> Tue Jan 19 11:45:41 CET 2016
> Tue Jan 19 11:46:09 CET 2016
> Tue Jan 19 15:18:52 CET 2016
> Tue Jan 19 15:19:08 CET 2016
> Tue Jan 19 15:26:49 CET 2016
> Tue Jan 19 15:37:39 CET 2016
> Tue Jan 19 15:56:19 CET 2016
> Tue Jan 19 16:07:04 CET 2016
> Tue Jan 19 16:32:34 CET 2016
- Without 'includeProcessVariables'

> Mon Jan 18 09:15:06 CET 2016
> Mon Jan 18 09:15:26 CET 2016
> Mon Jan 18 13:19:41 CET 2016
> Mon Jan 18 14:42:59 CET 2016
> Mon Jan 18 15:07:55 CET 2016
> Mon Jan 18 15:10:09 CET 2016
> Mon Jan 18 15:21:53 CET 2016
> Mon Jan 18 15:53:58 CET 2016
> Mon Jan 18 15:57:49 CET 2016
> Mon Jan 18 15:57:59 CET 2016
> Mon Jan 18 16:43:53 CET 2016
> Mon Jan 18 18:00:08 CET 2016
> Mon Jan 18 18:11:47 CET 2016
> Mon Jan 18 18:11:48 CET 2016
> Mon Jan 18 18:11:50 CET 2016
> Mon Jan 18 19:59:34 CET 2016
> Tue Jan 19 09:27:31 CET 2016
> Tue Jan 19 09:29:57 CET 2016
> Tue Jan 19 09:31:20 CET 2016
> Tue Jan 19 10:44:01 CET 2016
> Tue Jan 19 10:45:48 CET 2016
> **Tue Jan 19 11:15:35 CET 2016**
> Tue Jan 19 11:16:51 CET 2016
> Tue Jan 19 11:38:54 CET 2016
> Tue Jan 19 11:45:41 CET 2016
> Tue Jan 19 11:46:09 CET 2016
> Tue Jan 19 15:18:52 CET 2016
> Tue Jan 19 15:19:08 CET 2016
> Tue Jan 19 15:26:49 CET 2016
> Tue Jan 19 15:37:39 CET 2016
> Tue Jan 19 15:56:19 CET 2016
> Tue Jan 19 16:07:04 CET 2016
> Tue Jan 19 16:32:34 CET 2016

While browsing the [forums](https://forums.activiti.org/comment/24720#comment-24720) I find out that without the variables the query uses database sorting (the one that works normally), however with the variables included you had to use in memory sorting because of some issues with variables. My guess is that there's an issue with this kind of in memory sorting...

Can you check if this can be solved ?

Thank you.

Charaf

**Comment by polouis** [comment]
I'm experiencing something kind of similar : when getting tasks matching a certain "taskDefinitionKey" and with sort parameters "start" and "size" set to a certain value everything works fine. If I add "includeProcessVariables=true" in my request the size parameter is ignored and the set of tasks I get is always limited to the first 90 ones...
Hello, did someone find a solution for this?

**Comment by Salaboy** [comment]
Your issue is being closed now due to inactivity for a long period.  We want to keep the project repository healthy and for that reason, we will close inactive issues. If you are interested in reviewing this issue with us so we can find a way to close it we will appreciate you opening a new issue pointing out the correct branch where the issue is present. 
We appreciate your support and understanding.
