### ISSUE TITLE
Process instance not ended after End Terminate Event with terminateAll 

### ISSUE THREAD

**Issue by zanottifio** [Activiti/Activiti#791]
Ending the process with terminateAll doesn't update act_hi_procinst row.

As END_TIME_ , DURATION_ , END_ACT_ID_ , are null the process is reported not ended.

**Comment by eugeneroz** [comment]
Also occured

**Comment by jbarrez** [comment]
Jira case: https://activiti.atlassian.net/browse/ACT-4137

**Comment by jbarrez** [comment]
Indeed, thanks for reporting! Added tests and fixed.
