### ISSUE TITLE
activiti-5.19.0.2 database create scripts insert 5.20.0.1 as version

### ISSUE THREAD

**Issue by PascalSchumacher** [Activiti/Activiti#793]
e.g. `activiti.oracle.create.engine.sql`:

```
insert into ACT_GE_PROPERTY
values ('schema.version', '5.20.0.1', 1);

insert into ACT_GE_PROPERTY
values ('schema.history', 'create(5.20.0.1)', 1);
```

Just wanted to let you know.

BTW Thanks for providing activiti!

**Comment by tijsrademakers** [comment]
Thanks Pascal, we are aware of this ;-)
The db scripts were already created for the next 5.20.0 version, but we had to do an intermediate 5.19.0.2 release, so that's why the db scripts have this versioning.

**Comment by omasseau** [comment]
This sucks and adds a lot of confusion...
I just lost several hours of problems investigation because of this.
