### ISSUE TITLE
Return format for Activiti REST API for getting Process Instance Variables

### ISSUE THREAD

**Issue by thanneru** [Activiti/Activiti#797]
When we try to query the process instance variables using the [Activiti REST API](http://activiti.org/userguide/index.html#_list_of_variables_for_a_process_instance), we get serialized Java objects instead of JSON. The whole idea of using the Activiti REST API instead of the Activiti Java API is so that any programming language (for e.g. client side JavaScript making the REST API call) can consume the output from the REST API call. We had to change the activiti-rest module codebase to return JSON (using Jackson/Gson to convert the Java object to JSON before returning) so that we can consume the REST API. I am wondering if this issue/discrepancy has already been fixed or do you plan to fix with 6.0 because this is an issue that anyone who is trying to use the REST API will run in to. If not, can we submit a pull request for this change?

**Comment by tijsrademakers** [comment]
This from the Activiti user guide:

It’s possible to support additional variable-types with a custom JSON representation (either simple value or complex/nested JSON object). By extending the initializeVariableConverters() method on org.activiti.rest.service.api.RestResponseFactory, you can add additional org.activiti.rest.service.api.engine.variable.RestVariableConverter classes to support converting your POJO’s to a format suitable for transferring through REST and converting the REST-value back to your POJO. The actual transformation to JSON is done by Jackson.

So it's already possible to return JSON objects, but you need to inject a variable converter.

**Comment by thanneru** [comment]
I am aware of that and that's how I have done. My question is why would you want the REST API to return a Java object? What's the issue with just converting it to JSON and return the JSON?

**Comment by tijsrademakers** [comment]
I agree, that it doesn't make much sense. But not every Java object can be translated into JSON, to it's done this way to deal with any variable type there could be. And it's easy to register your own variable converter anyway.

**Comment by thanneru** [comment]
The problem is now everyone using the Activiti REST API has to write this same code, and also, re-apply and re-test the changes everytime we upgrade to a newer version of Activiti. It's not completely pluggable where we don't have to touch the core Activiti code (it it was, then it would have been ok to deal with it). Can you look in to the option of having this as a setting (may be in one of the properties files), and then give the option of returning variables as Java objects or JSON? Projects can choose based on their needs without making the same code changes that we talked about above. It's one thing to make changes to core Activiti code so that it suits our specific requirements (that other projects/users don't need or want), but this seems like something basic that almost everyone who is using the REST API will benefit from, and can avoid making the same changes.

**Comment by tijsrademakers** [comment]
Yes having a property that determines if objects are returned as Java or as JSON would be a good solution. Can you work on a PR to implement this functionality?

**Comment by thanneru** [comment]
I need to go through a lot of process (many presentations, reviews, legal, security scan of the code, etc.) to submit a PR. At this point, I am not sure if it's worth my time going through the corporate process to get this, but I will see.

**Comment by thanneru** [comment]
I got a working solution to get any POJO variable as JSON when calling the REST API. However, now the issue is that all the activiti-rest unit tests are expecting a POJO in the response, and are breaking because now they get JSON (instead of a POJO).

**Comment by petzstef** [comment]
Instead of using an activiti property I would like Activiti to respect the HTTP Accept header of the request. If it is application/json then JSON should be returned. This would be compatible and probably not break existing tests.
