### ISSUE TITLE
Activiti6: Invalid reference in 'bpmnElement' attribute, sequenceFlow ... not found

### ISSUE THREAD

**Issue by wayerr** [Activiti/Activiti#801]
In Activiti6 i got follow error: `Invalid reference in 'bpmnElement' attribute, sequenceFlow ... not found`

Investigation of SequenceFlowParseHandler in master and activiti6 branches show that in new version the https://github.com/Activiti/Activiti/blob/master/modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/parser/handler/SequenceFlowParseHandler.java#L55 line was removed, this cause above error.

Trivial fix: 
`+ bpmnParse.getSequenceFlows().put(sequenceFlow.getId(), sequenceFlow);`

in https://github.com/Activiti/Activiti/blob/activiti6/modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/parser/handler/SequenceFlowParseHandler.java#L34

**Comment by balsarori** [comment]
@wayerr Thanks for reporting the issue and fix. 
Can you share a process definition that produces the error so that we can add a JUnit test for this issue?

**Comment by yvoswillens** [comment]
@wayerr I've checked the unit tests covering this behavior and it seems fine. 
If you still think something is wrong please reopen the issue and provide the process definition causing the issue.
