### ISSUE TITLE
HistoricTaskInstanceEntity(Impl) does not copy the formKey from the parent task.

### ISSUE THREAD

**Issue by caleblevine-google** [Activiti/Activiti#814]
It copies other fields in the constructor, but formKey is omitted. I'm guessing this was just an oversight in the original formKey commit.

https://github.com/Activiti/Activiti/commit/eb9acf7bd29f9a22eee0b1e9dc4d0ed5443c63e8

**Comment by tijsrademakers** [comment]
Hi, thanks for reporting the issue. It has been fixed in the referenced commit.
