### ISSUE TITLE
using Maven repo for activiti-spring-boot-starter-basic result in an exception

### ISSUE THREAD

**Issue by yalmuhaidib** [Activiti/Activiti#855]
when I use spring boot activiti maven repo `5.19.0.2` and run the application I get `org.activiti.engine.ActivitiException: Can't find scripting engine for 'groovy'`

the below dependency is added to my project
```
<dependency>
	<groupId>org.activiti</groupId>
	<artifactId>activiti-spring-boot-starter-basic</artifactId>
	<version>5.19.0.2</version>
</dependency>
```

**Comment by jbarrez** [comment]
Can you attach your whole app zip here so we can have a look?

**Comment by yalmuhaidib** [comment]
[activiti-demo.zip](https://github.com/Activiti/Activiti/files/189689/activiti-demo.zip)
attached

**Comment by jbarrez** [comment]
The error is because you are using a scripting task: 
`<scriptTask id="service1" scriptFormat="groovy">
            <script>
               println 'customerId=' + customerId
            </script>
        </scriptTask>`

That needs groovy on the classpath (which Activiti does not include by default as not everyone use Groovy or script tasks).

**Comment by yalmuhaidib** [comment]
I copied from the `spring-boot-sample-basic`.. which is using `5.20.0-SNAPSHOT` and there groovy is added as a dependancy
