### ISSUE TITLE
split 'activiti-spring-boot-starter-basic' into 'starter' and 'autoconfigure'

### ISSUE THREAD

**Issue by amitport** [Activiti/Activiti#872]
[spring.factories](https://github.com/Activiti/Activiti/blob/769b3372fce3ec7d233b122510f83e57405c5426/modules/activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter-basic/src/main/resources/META-INF/spring.factories) includes auto-configuration classes that are not always wanted.

Would it be possible to split this lib into 'starter' and 'autoconfigure' in order to enable users to create a more selective starter (without needing to explicitly exclude many classes)?

See http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-auto-configuration.html#boot-features-custom-starter

**Comment by jbarrez** [comment]
The basic starter already contains the minimal needed for getting going with Spring Boot + Activiti.
The spring.factories files mentions those optional extra auto configs that are enabled when on the classpath, but they don't need to be.

So, I'm not sure what you're looking for? What is now too much in the basic starter?

**Comment by amitport** [comment]
For example, if you want to expose only specific rest endpoint at specific paths/security configuration, you may not want RestApiAutoConfiguration even if activiti-rest is on the classpath. We can still manually exclude those configuration classes, so to is not a critical issue -but- IMHO, splitting to starter and autoconfigure projects gives you more flexibility without any real cost.

**Comment by jbarrez** [comment]
Okay, I see that use case. But the cost is in the complexity of modules / documentation to maintain (see https://github.com/Activiti/Activiti/tree/master/modules/activiti-spring-boot/spring-boot-starters, it would mean that it would at least double in number of modules). Also, wouldn't that make the basic and default use cases more complex as it would require more than one module to depend on?

cc @joshlong for input.

**Comment by amitport** [comment]
it is enough to split only the activiti-basic-starter project, and add a single activiti-autoconfigure proejct.

activiti-basic-starter can depend on activiti-autoconfigure and include in `spring.factories` only
```
org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
    org.activiti.spring.boot.DataSourceProcessEngineAutoConfiguration,\
    org.activiti.spring.boot.JpaProcessEngineAutoConfiguration
```

activiti-actuator-starter can depend on activiti-basic-starter and include in `spring.factories` only
```
org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
    org.activiti.spring.boot.EndpointAutoConfiguration
```
and activiti-rest-starter can depend on activiti-basic-starter and include in `spring.factories` only
```
org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
   org.activiti.spring.boot.RestApiAutoConfiguration,
    org.activiti.spring.boot.SecurityAutoConfiguration
```

**Comment by Salaboy** [comment]
we did some work around this for activiti-cloud, feel free to reopen if you find issues with our new spring boot 2 starters.
