### ISSUE TITLE
5.20.0 Please add Neo4j support

### ISSUE THREAD

**Issue by nhalase** [Activiti/Activiti#878]
With Neo4j supporting JDBC connections, please add Neo4j database support to Activiti.

Requesting per ["Subsequent database compatibility will be driven by demand."](http://activiti.org/faq.html)

I like the effort made by @jbarrez over at [https://github.com/jbarrez/activiti-neo4j](https://github.com/jbarrez/activiti-neo4j), but that work is a bit dated and not ready for production use. What all needs to be done to drive support for this request? Thanks!

**Comment by jbarrez** [comment]
@nhalase : are you referring to the jdbc driver for neo4j (https://github.com/neo4j-contrib/neo4j-jdbc)?
If so, I don't see how this would be compatible with Activiti, as that is a bridge layer, but the queries would all still be cypher-based (which would mean an implementation of the persistence layer using cyper).

**Comment by nhalase** [comment]
Maybe I'm misunderstanding something, but what about ProcessEngineConfiguration?
```
processEngine = configuration
			.setJdbcUrl("jdbc:neo4j:mem:testgraphdb")
			.setJdbcDriver("org.neo4j.jdbc.Driver")
			.buildProcessEngine();
```
Sorry if I'm being dense.

**Comment by jbarrez** [comment]
See https://github.com/neo4j-contrib/neo4j-jdbc : that would allow to connect to neo4j using a jdbc url, but queries still are written in cyper format, see the example there:

ResultSet rs = stmt.executeQuery("MATCH (n:User) RETURN n.name");

So it's using the jdbc classes, but the actual queries are in not in sql. 
As all the Activiti logic is written in SQL, this is incompatible.

**Comment by nhalase** [comment]
That helps. Thanks!
