### ISSUE TITLE
ActivitiEvent.getProcessDefinitionId() is null for type VARIABLE_DELETED

### ISSUE THREAD

**Issue by wblancqu** [Activiti/Activiti#880]
As the title says, this returns null when subscribing a listener to event type VARIABLE_DELETED.
Activiti 6.0.0.Beta2

**Comment by jbarrez** [comment]
Correct, this seemed to be a piece of code that was not ported to the new v6 way of firing events (i.e. _not_ in the DbSqlSession). Fixed. Thanks @wblancqu for reporting.

**Comment by wblancqu** [comment]
Any chance this gets ported to the 5.x branch? I still see it in the 5.21.0. Or will the 6 be out any time soon ;-)?
