### ISSUE TITLE
Boundary message event subscriptions removed when deploying new version

### ISSUE THREAD

**Issue by wblancqu** [Activiti/Activiti#881]
[https://forums.activiti.org/content/boundary-message-event-subscriptions-removed-when-deploying-new-version](https://forums.activiti.org/content/boundary-message-event-subscriptions-removed-when-deploying-new-version)

Activiti 6.0.0.Beta2
1. Create new workflow with boundary message event on specific user task.
2. Create process instance, and activate above task (so subscription to message event comes in)
3. Re-deploy new version of the workflow.
4. Send message event.

=> This results in the event subscription not being triggered due to following code being executed when re-deploying:
org.activiti.engine.impl.bpmn.deployer.BpmnDeploymentHelper

public void updateTimersAndEvents(ProcessDefinitionEntity processDefinition, 
ProcessDefinitionEntity previousProcessDefinition, ParsedDeployment parsedDeployment) {
...
eventSubscriptionManager.removeObsoleteMessageEventSubscriptions(previousProcessDefinition);
...
}

I understand that this is normal behavior for start message events. However I'm not sure about boundary message events. In our use case it shouldn't. I was hesitating to file this as a bug report since I'm not sure if this is expected.

**Comment by daisuke-yoshimoto** [comment]
@wblancqu

I think you can solve the problem by building from the newest activiti6 branch.
https://github.com/Activiti/Activiti/tree/activiti6

This bug already fixed as issue ACT-4112 in master branch.
[Issue] https://activiti.atlassian.net/browse/ACT-4112
[Commit log] https://github.com/Activiti/Activiti/commit/5ffac043e8d25a5940593038f2da2bcad0cf6592

This fix already merged to activiti6 branch by following commit log.
[Commit log] https://github.com/Activiti/Activiti/commit/29dea0d115fe3832127b67550e7d5df1aa4f6cab

**Comment by wblancqu** [comment]
OK thank you. Any idea when a new (beta or final) 6 release will be made?

**Comment by daisuke-yoshimoto** [comment]
@wblancqu

I don't know when next activiti6 will be released, sine I'm not a commiter of Activiti.

But,considering the past release, I think that next activiti6 will be released after about two months.
https://github.com/Activiti/Activiti/releases

**Comment by daisuke-yoshimoto** [comment]
Activiti 6 official is already released. So this issue will be closed.
https://community.alfresco.com/community/bpm/blog/2017/06/01/activiti-6-is-here
