### ISSUE TITLE
ConcurrentModificationException when listener removes itself (Activiti 5.19.0.2)

### ISSUE THREAD

**Issue by jesperdj** [Activiti/Activiti#886]
I register an `ActivitiEventListener` with the `RuntimeService`, for event types that indicate that a process ends. The event listener removes itself by calling `RuntimeService.removeEventListener(this);` in the `onEvent(...)` method:

    ActivitiEventListener eventListener = new ActivitiEventListener() {
        @Override
        public void onEvent(ActivitiEvent event) {
            // ...
            runtimeService.removeEventListener(this);
        }

        @Override
        public boolean isFailOnException() {
            return false;
        }
    };

    runtimeService.addEventListener(eventListener,
            ActivitiEventType.PROCESS_CANCELLED,
            ActivitiEventType.PROCESS_COMPLETED,
            ActivitiEventType.PROCESS_COMPLETED_WITH_ERROR_END_EVENT);

The call `runtimeService.removeEventListener(this);` causes a `ConcurrentModificationException` in `ActivitiEventSupport.dispatchEvent(...)`. That method contains two loops over lists of event listeners; the exception happens because the call to remove the listener modifies one of those two lists while it is being iterated over.

A possible fix would be for `ActivitiEventSupport.dispatchEvent(...)` to make a copy of the lists before looping over them and calling listeners.

**Comment by faizal-manan** [comment]
I would suggest to change return type for 'onEvent(ActivitiEvent event)' to boolean. 'ActivitiEventSupport.dispatchEvent` will remove the listener at the end of the loop for 'dispatchEvent(event, listener) == true'

**Comment by jesperdj** [comment]
The best solution would be for class `ActivitiEventSupport` to use `java.util.concurrent.CopyOnWriteArrayList` instead of the regular `java.util.ArrayList` for `eventListeners` and the values in `typedListeners`.

**Comment by tijsrademakers** [comment]
Merged your PR, thanks
