### ISSUE TITLE
use activiti with drools

### ISSUE THREAD

**Issue by gummike** [Activiti/Activiti#892]
can i set a glabal parameter in activiti,  and set it into the drools' drl file

**Comment by gummike** [comment]
activiti  only have three parameters .first is  rules ,second is valueinput ,thrid is  resultdata.  how can i set a glabol java instance ,so i can  use it in drools

**Comment by huksley** [comment]
Currently Activiti does not provide ApplicationContext to Drools Engine, so 
your options resort to extends Activiti to do what you want.

WARNING: All options involving overriding or extending implementation side of Activiti can be broken in next release!

You have two options:
- Extend BusinessRuleTaskActivityBehavior and DefaultActivityBehaviorFactory and create your instance of BusinessRuleTaskActivityBehavior  in DefaultActivityBehaviorFactory .createBusinessRuleTaskActivityBehavior(BusinessRuleTask businessRuleTask);
- Extend BusinessRuleParseHandler  to provide your own ActivityImply.setActivityBehavior()

Both solutions will require you to look into Activiti source code.
Also you will need to declare your instance in activity.cfg.xml:
```
<!-- to override BusinessRuleTaskActivityBehavior -->
<property name="activityBehaviorFactory">
<bean class="package.CustomActivityBehaviorFactory"/>
</property>
<!-- to override BusinessRuleParseHandler   -->
<property name="customDefaultBpmnParseHandlers">
<list>
<bean class="ru.gpb.bpm.activiti.CustomBusinessRuleParseHandler"/>
</list>
</property>
```

**Comment by Salaboy** [comment]
there are a lot of new things coming around this in activiti cloud, I'm closing this issue now, but feel free to reach us in our gitter channel to discuss this further.
