### ISSUE TITLE
Activiti Designer lets me create tasks with the same ID

### ISSUE THREAD

**Issue by jesperdj** [Activiti/Activiti#894]
Try this in Activiti Designer: Create a simple process with a start event, two service tasks and an end event. Create connections: start -> service task 1 -> service task 2 -> end.

Now, edit the ID of the two service tasks. Give them the same ID.

Save the process definition and close the file. Then re-open the file. You'll see only one service task instead of two.

ID's are supposed to be unique, but the designer doesn't check this; it lets you save an invalid BPMN, and you won't notice it until you close / re-open the process definition.

The designer should prevent you from creating invalid process definitions.

**Comment by Salaboy** [comment]
Totally agree on this one, I'm closing this issue because the designer is not longer part of this repository.
