### ISSUE TITLE
@Deployment with parameters in test method signature

### ISSUE THREAD

**Issue by MKorsch** [Activiti/Activiti#899]
Hi,

as I'm using JMockit in my unit tests, sometimes I need to add some @Mocked Parameters to my test method. When I'm executing the tests, the @Deployment annotation does not seem to be processed propperly. I have four processes set as resources in this annotation. But one of them is always missing. (no process deployed with key ...). When using no parameters in test method everything goes fine.

Can you help me with that?

**Comment by Salaboy** [comment]
Is this still a problem? We are reviewing the testing mechanism that was created based on JUnit3 and does a lot of internal JUnit manipulation. We are moving to a more standard way of doing testing with more modern versions of Junit.

**Comment by mkorsch-nli** [comment]
Currently no time to review if that's still a problem. But anyway, as you plan to refactor the testing mechanisms I'll give a more recent version a try if I encounter the problem again.

**Comment by Salaboy** [comment]
@MKorsch thanks a lot, we will really appreciate that.
