### ISSUE TITLE
I can't find any documentation about activiti business calendar

### ISSUE THREAD

**Issue by Hdebbech** [Activiti/Activiti#901]
Hi,

I can't find any documentations about the business calendar component. It would be very helpful to know when it comes into action (in user tasks only ?) and how to implement a custom calendar.

Thank you
Best Regards.

**Comment by Salaboy** [comment]
@Hdebbech I totally agree. We are refactoring these services for Activiti 7 and Activiti Cloud. If you are implementing something around Calendars we will appreciate your involvement as a community contributor for the new versions.
