### ISSUE TITLE
historic tasks deleted on execution deletion

### ISSUE THREAD

**Issue by amitport** [Activiti/Activiti#905]
When we delete a process definition it seems that related historic tasks are also being deleted.

Shouldn't historic tasks be kept for future audit no matter what happens to the original process definition?

**Comment by jbarrez** [comment]
There is no api to delete a process definition, so I'm assuming your talking about deleting a deployment?

If so, the delete deployment method takes a boolean to indicate if you want to cascade (to history) or not:

  void deleteDeployment(String deploymentId, boolean cascade);

**Comment by amitport** [comment]
I do use cascade, it is required in order to also delete the executing process instances.

I would still expect it to only delete those and not affect the historic tasks.

**Comment by jbarrez** [comment]
That's not possible with one API call. You'd need to delete the process instances via the runtimeService.deleteProcessInstance before deleting the deployment without cascade.

**Comment by amitport** [comment]
Doing it manually will add an ongoing, not completed tasks to the history. This doesn't make sense in my opinion, I do want everything running to be destroyed (and not send to history) when deleting, but I don't see the use case for deleting rows that are already in history table.

Additionally, note that there seems that there is an inconsistency. Using cascade does not delete historic activities and historic process instances, while deleting historic tasks.

**Comment by jbarrez** [comment]
> This doesn't make sense in my opinion

I understand your use case, I'm just saying that the current API's don't do that. That would be a new option that needs to be added to the deleteDeployment.

> Using cascade does not delete historic activities and historic process instances, while deleting historic tasks.

That shouldn't be the case. Do you have a unit test demonstrating that?

**Comment by amitport** [comment]
OK 

It's hard to extract a test case from our code, but at the end it's just deploys process and later deletes them. We're using 5.17.

**Comment by Salaboy** [comment]
feel free to reopen if this is still an issue.
