### ISSUE TITLE
activiti-mule is missing dependency stax-utils

### ISSUE THREAD

**Issue by shturec** [Activiti/Activiti#915]
[Activiti 5.20.0](https://github.com/Activiti/Activiti/tree/5.20.0) release still fails to build with profile _distro_ for the same reasons outlined in issue https://github.com/Activiti/Activiti/issues/625. The failing module is again [activiti-mule](https://github.com/Activiti/Activiti/tree/master/modules/activiti-mule).
That should be an easy fix - all you need to do is to change the current mule repo url in the activiti-mule [pom](https://github.com/Activiti/Activiti/blob/5.20.0/modules/activiti-mule/pom.xml) with the one that contains the [required dependency](https://repository.mulesoft.org/nexus/content/groups/public/net/java/dev/stax-utils/stax-utils/20080702/) (hence the missing _-master_ in the URL):

```
<repositories>
      <repository>
          <id>mulesoft-releases</id>
          <name>MuleSoft Releases Repository</name>
          <url>https://repository.mulesoft.org/nexus/content/groups/public/</url>
          <layout>default</layout>
      </repository>
  </repositories>
```

Details on how to reproduce:

mvn -Pdistro clean install
...
[INFO] Activiti - Mule .................................... FAILURE
...
[ERROR] Failed to execute goal on project activiti-mule: Could not resolve dependencies for project org.activiti:activiti-mule:jar:5.20.0: Failed to collect dependencies at org.mule.transports:mule-transport-vm:jar:3.5.0 -> org.mule.modules:mule-module-xml:jar:3.5.0 -> net.java.dev.stax-utils:stax-utils:jar:20080702: Failed to read artifact descriptor for net.java.dev.stax-utils:stax-utils:jar:20080702: Could not transfer artifact net.java.dev.stax-utils:stax-utils:pom:20080702 from/to codehaus (http://repository.codehaus.org): repository.codehaus.org: Unknown host repository.codehaus.org -> [Help 1]

**Comment by Salaboy** [comment]
I'm closing this issue due to inactiviti. On a side note Codehaus closed long time ago so the dependency that you are referencing might be in a different repo. Probably maven central.
