### ISSUE TITLE
Add option to execute persisted jobs and timers first-in-frist-out?

### ISSUE THREAD

**Issue by PascalSchumacher** [Activiti/Activiti#920]
Currently Activiti does not guaranty any order when executing persistent jobs and timers (if my understanding is correct).

I would like to have the option to execute these first-in-frist-out. To make this possible I think it would be necessary to add a column like CREATE_TIME to the ACT_RU_JOB table.

Would you consider adding this feature if create a pull request for it?

**Comment by PascalSchumacher** [comment]
Looks like this is solved by the new jms-async-executor added with: https://github.com/Activiti/Activiti/commit/d08a247570336c872bb17ce513c1fb95b3ba47a2

**Comment by jbarrez** [comment]
@PascalSchumacher : correct. It also opens up a way to implement 'priority queues'.
I'm hoping to have a blog about the jms async executor online tomorow.
