### ISSUE TITLE
Can I check commits between 5.20.0 and 5.21.0 ?

### ISSUE THREAD

**Issue by daisuke-yoshimoto** [Activiti/Activiti#923]
@jbarrez 

Thank you for your release(Activiti 5.21.0).
https://github.com/Activiti/Activiti/releases/tag/activiti-5.21.0

Can I check commits between 5.20.0 and 5.21.0 like the following link page.
https://github.com/Activiti/Activiti/compare/5.20.0...master

In the following link page, there is only one commit.
https://github.com/Activiti/Activiti/compare/activiti-5.21.0...master

**Comment by jbarrez** [comment]
https://github.com/Activiti/Activiti/compare/5.20.0...master is the right URL, yes, to see the difference between 5.20 and 5.21.

There is but one commit difference between 5.21 and current master (which is moving to 5.22.0-SNAPSHOT)

**Comment by daisuke-yoshimoto** [comment]
@jbarrez 

Thank you for reply.
But your comment is mistake.

https://github.com/Activiti/Activiti/compare/5.20.0...master is  the difference between 5.19 and 5.20.

https://github.com/Activiti/Activiti/compare/activiti-5.21.0...master is the difference between 5.20 and 5.21.
And, the page have only one commit.

**Comment by jbarrez** [comment]
Look at the url of it ... it is the difference between 5.21.0 (released this morning) and the current state of master ... only one commit happened since then.

**Comment by jbarrez** [comment]
And the right url for 5.20 vs 5.21 is this: https://github.com/Activiti/Activiti/compare/5.20.0...activiti-5.21.0

**Comment by daisuke-yoshimoto** [comment]
@jbarrez 

Thank you for the following link.
https://github.com/Activiti/Activiti/compare/5.20.0...activiti-5.21.0
