### ISSUE TITLE
resourceName confusion during deployment

### ISSUE THREAD

**Issue by sachintyagi22** [Activiti/Activiti#925]
While creating deployment object --  for a ResourceEntity, the "resourceName" field is actually expected to be a file name with a proper extension: i.e. "bpmn20.xml" and "bpmn"  for Bpmn deployment and ".drl" for Rules deployment **. This works fine when the resource is a classpath resource and the file name or file path of the resource is used as the resource name. 

But while adding input stream to the deployment, it is not evident that the resourceName should end with .bpmn or .drl. This causes a perfectly valid bpmn file to be ignored during deployement -- and nothing gets shown in the logs. For a new user, this is confusing. 

*\* In BpmnDeployer the deployment proceeds only "if (isBpmnResource(resourceName))" check passes. Similarly, in RulesDeployer there is 'resourceName.endsWith(".drl")' check.

IMHO, the resourceName should be decoupled from what kind of deployment it is. Or there should be explicit documentation about the contraints on the resourceName. Please share your thoughts.

**Comment by Salaboy** [comment]
@sachintyagi22 totally agree. you can contribute with the change that you mention for branch 6.x. We are moving forward to deployments to containers (docker) and Kubernetes for version 7 and activiti cloud. I will close this issue, but feel free to reopen if you can provide a contribution.
