### ISSUE TITLE
Feature request: VARIABLE_DELETED events should contain old value

### ISSUE THREAD

**Issue by blancqua** [Activiti/Activiti#927]
For now, these events give null as value. Conceptually this is correct in the sense that it's no longer there. However there is no easy way of finding out what the value was just before. Would it make sense to enrich this event with that information?

**Comment by Salaboy** [comment]
@wblancqu this sounds like a great community contribution. It should be easy enough to add and to test the new behaviour. Are you interested in contributing this back to Activiti 7 and Activiti Cloud? Cheers

**Comment by CTI777** [comment]
@salaboy 
I think we may close this?
