### ISSUE TITLE
Missing column definition in the ACT_RU_DEADLETTER_JOB table for H2

### ISSUE THREAD

**Issue by dbmalkovsky** [Activiti/Activiti#934]
In the latest merge of the 'activiti6-job-refactor' branch into V6 and the subsequent modifications to the SQL table definitions there is a missing column in the ACT_RU_DEADLETTER_JOB table for H2.

Specifically the RETRIES_ column is missing; it should be located after PROC_DEF_ID_ and before EXCEPTION_STACK_ID_. 

I will see about submitting a pull request tomorrow if it doesn't get fixed before that.

**Comment by tijsrademakers** [comment]
That's correct, we should remove the RETRIES column from every db table definition for ACT_RU_DEADLETTER_JOB, because the retries are not important for a deadletter job. There are no more retries left.
