### ISSUE TITLE
activiti-bpmn-layout fails to build

### ISSUE THREAD

**Issue by guofengxu** [Activiti/Activiti#940]
Failed to execute goal on project activiti-bpmn-layout: Could not resolve dependencies for project org.activiti:activiti-bpmn-layout:jar:5.21.0-SNAPSHOT: Failed to collect dependencies at org.activiti:activiti-bpmn-model:jar:5.21.0-SNAPSHOT: Failed to read artifact descriptor for org.activiti:activiti-bpmn-model:jar:5.21.0-SNAPSHOT: Failure to find org.activiti:activiti-root:pom:5.20.0-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]

**Comment by guofengxu** [comment]
i build activiti-bpmn-model success!
but i build activiti-bpmn-layout  failed!
why?

**Comment by tijsrademakers** [comment]
I see a mixture of 5.21.0-SNAPSHOT and 5.20.0-SNAPSHOT, how is that possible?

**Comment by guofengxu** [comment]
ok,you are right!
thank you
