### ISSUE TITLE
MyClass extends ReceiveTaskActivityBehavior

### ISSUE THREAD

**Issue by guofengxu** [Activiti/Activiti#949]
if  MyClass  receive signal ,then activiti continue work!
how deal with MyClass  ?

**Comment by tijsrademakers** [comment]
It's very difficult to answer your very short question. Can you please elaborate?

**Comment by guofengxu** [comment]
MyClass  function is internal trigger!

**Comment by guofengxu** [comment]
beacause  A receive task is a wait state that waits for the receival of some message.the only message that is supported is the external trigger!
but i want to support internal trigger!

**Comment by guofengxu** [comment]
ReceiveTaskActivityBehavior is a wait state that waits for the receival of some message.the only message that is supported is the external trigger!
but i want to make MyClass  support internal trigger!
