### ISSUE TITLE
How do MyClass extends ReceiveTask?

### ISSUE THREAD

**Issue by guofengxu** [Activiti/Activiti#955]
A receive task is a wait state that waits for the receival of some message,and this only  is supported the external trigger. but i want to make MyClass  that when it waits for the receival of some message, and it is  supported the internal trigger!

**Comment by guofengxu** [comment]
When MyClass  waits for the receival of some message,and it auto trigger activiti instance!

**Comment by tijsrademakers** [comment]
With an internal trigger, you mean a message event in the process definition? Or something else? Would an intermediate signal catch event not do what you are looking for?

**Comment by guofengxu** [comment]
i mean a message event in the process definition function.
you mean i make MyClass  is internal trigger,i should extends intermediate signal catch event?

**Comment by guofengxu** [comment]
i need a message event in the process definition function.
you mean i make MyClass is internal trigger,i should extends intermediate signal catch event?

**Comment by tijsrademakers** [comment]
ok, what kind of logic are you implementing in your "MyClass"?

**Comment by guofengxu** [comment]
first.
when activiti instance enter "MyClass" ,it will create ActiveMQClient ,then it waits for some message.
second.
when ActiveMQClient  receive some message ,it make "MyClass" internal trigger!

**Comment by tijsrademakers** [comment]
You can implement this pattern with a service task that sends the message to ActiveMQ, then add after the service task a receive task. Implement a message listener that will signal the receive task when a response comes back from ActiveMQ.

**Comment by guofengxu** [comment]
you tell this just,how to use activiti,but i need modify activiti.
so i want make "MyClass" extends ReceiveTask!

**Comment by tijsrademakers** [comment]
Why do you need to extend the ReceiveTask if it also works by default like I'm describing?

**Comment by guofengxu** [comment]
our team want make activiti without extenal class that mean no message listener or others , it can works just be configuration!

**Comment by jbarrez** [comment]
I'm really not sure if I'm understanding your requirements correctly ... are you looking for something to replace the default behaviour of the Activiti classes? If so, look into the 'parse handler' pluggability: http://activiti.org/userguide/index.html#_hooking_into_process_parsing

Closing this issue, as it's not an issue with Activiti, rather a question on how to do something.
