### ISSUE TITLE
can we make ajax request in script task.

### ISSUE THREAD

**Issue by skbelalmd** [Activiti/Activiti#956]
As per the the activiti documentation for script task, it should support all javascript functionalities.
But does it support ajax requests.

**Comment by jbarrez** [comment]
Activiti supports all functionality that the javascript engine in the JDK supports, not _all_ javascript functionality. Depending on your JDK the scripting engine can be Rhino or Nashorn.

But I don't believe 'ajax' is supported, as this is a browser specific thing. You can do the same thing even with using the URLConnection in a script (or use any other, simpler to use, library from within the script.
