### ISSUE TITLE
java.lang.ClassNotFoundException: org.activiti.rest.editor.application.ModelerRestApplication

### ISSUE THREAD

**Issue by leglory** [Activiti/Activiti#960]
use activiti 5.16.1 create ModelRestApplication for modeler，update 5.21.0 how to made a servlet for ModelRestServlet and RestletServlet？ please give me a example ，think you

**Comment by tijsrademakers** [comment]
You can find the example in the activiti-webapp-explorer2 module. We switched from Restlet to Spring MVC, so that's why you need some changes.

**Comment by leglory** [comment]
A small mistake error 404
editor-app/app-cfg.js 'contextRoot' : '/activiti-webapp-explorer2/service',
change "activiti-explorer" to "activiti-webapp-explorer2"
get the json data success
