### ISSUE TITLE
Activiti 6 Cancel Boundary Event Issues

### ISSUE THREAD

**Issue by jayhf** [Activiti/Activiti#962]
I've been trying to get a really simple cancel boundary event example working on Activiti 6 (both beta 2 and the current snapshot), but it fails with an ActivitiException with the message "No execution found for sub process of boundary cancel event boundaryCancelEvent". This problem didn't occur in Activiti 5 and changing the cancel events to error events allows the process to complete. Is there something wrong with the bpmn file or is this a bug in the engine?
Thank you!

<img width="494" alt="sample_diagram" src="https://cloud.githubusercontent.com/assets/828594/17064244/a8405850-5009-11e6-8d6a-e8126c5b9720.png">
[sample.txt](https://github.com/Activiti/Activiti/files/378700/sample.txt)

**Comment by jayhf** [comment]
Moved to Jira: https://activiti.atlassian.net/browse/ACT-4198

**Comment by erre-k-erre** [comment]
Hi,

I can't access to Jira. Is there any update about this issue?
We're finding a similar error.

Thx.

**Comment by lucianoprea** [comment]
@erre-k-erre you need to sign up for an account and access the issue. There is a resolution for your problem there.

**Comment by shreejitray** [comment]
@lucianoprea I am facing the same issue in activiti 6. I tried to login to view jira but it is not allowing me to signup. The error is 
_Your email address shreejitray@gmail.com doesn't have access because activiti.atlassian.net has reached its license limit.
You can request access from your site admin._

Can you please let me know the solution to the problem?

**Comment by lucianoprea** [comment]
@shreejitray you should have access to the issue now thanks to @balsarori who made it public 👍

**Comment by yizhongwei** [comment]
What if you don't want to trigger a compensation event?

**Comment by lastboy1228** [comment]
A compensation job must be associated to one task in the subprocess, and the compensation job can not be async.
