### ISSUE TITLE
Historic process instance queries with 'or query variables' need optimization

### ISSUE THREAD

**Issue by m4ng0** [Activiti/Activiti#988]
When using multiple or conditions for process variables in a historic process instance query, Activiti generates a new left outer join for every variable value condition. This leads to very complex queries so that it is impossible to execute a query with more than a couple of or conditions on variable values.
I provided a pull request (#989) that uses a single join. I don't know if I'm missing something, however all existing tests pass and I've added some test cases (which were problematic before this patch).

**Comment by paulhh** [comment]
Many thanks.  You've hit vacation season, so it may take a bit of time to for the PR to get reviewed.

Cheers
Paul.

**Comment by m4ng0** [comment]
Paul, thank you for the update. I will wait for the pull request to be carefully reviewed.

**Comment by m4ng0** [comment]
Now that #989 has been merged, I think this issue could be closed.
Thank you.
