### ISSUE TITLE
Support for OpenEdge RDBMS

### ISSUE THREAD

**Issue by kullmanp** [Activiti/Activiti#992]
We would like to integrate activiti into our product. For this we would need to have support for OpenEdge databases. We would also contribute the database integration code back to activiti. I'm not sure where to start, though. Is it possible to extend activiti with a custom database layer? Or shall I have to fork activiti and build my own version? Which parts do I have to touch in order to add another database?

Thanks,
Peter

**Comment by paulhh** [comment]
Best to look at the version 6 that's in beta, as there's a data abstraction layer.  It's much more work to do on version 5.

Cheers
Paul.

**Comment by Salaboy** [comment]
feel free to re-open or open a new one if you want to collaborate with the integration
