### ISSUE TITLE
The number of retry count should be configurable globally

### ISSUE THREAD

**Issue by luengnat** [Activiti/Activiti#998]
It would be nice if the number of retries can be configured globally rather than defaulting to 3 and has to be configured from BPMN in each place.

**Comment by matt-rich** [comment]
Agreed, this is causing us problems with multi-instance processing with our retry count (and frequency) not being configurable causing our flow to block.

**Comment by Salaboy** [comment]
@luengnat totally agree. We are currently working in Activiti 7 & Activiti Cloud and this is a configuration parameter that will be configured in our infrastructure.
